# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionAttributes',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('cgac_code', models.CharField(blank=True, max_length=3, null=True)),
                ('submitting_agency', models.CharField(blank=True, max_length=150, null=True)),
                ('submitter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('submission_modification', models.NullBooleanField()),
                ('version_number', models.IntegerField(blank=True, null=True)),
                ('reporting_period_start', models.DateField(blank=True, null=True)),
                ('reporting_period_end', models.DateField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('create_user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('update_user_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'submission_attributes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubmissionProcess',
            fields=[
                ('submission_process_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('file_a_submission', models.NullBooleanField()),
                ('file_b_submission', models.NullBooleanField()),
                ('file_c_submission', models.NullBooleanField()),
                ('file_d1_submission', models.NullBooleanField()),
                ('file_d2_submission', models.NullBooleanField()),
                ('file_e_submission', models.NullBooleanField()),
                ('file_f_submission', models.NullBooleanField()),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('create_user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='submissions.SubmissionAttributes')),
            ],
            options={
                'db_table': 'submission_process',
                'managed': True,
            },
        ),
    ]
