# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionattributes',
            name='frec_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
