# Generated by Django 2.2.9 on 2020-01-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20191016_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionattributes',
            name='reporting_agency_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
