# Generated by Django 2.2.12 on 2020-05-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20200429_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionattributes',
            name='previous_submission',
        ),
    ]
