# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20161027_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionprocess',
            name='submission',
        ),
        migrations.AddField(
            model_name='submissionattributes',
            name='db_submission_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submissionattributes',
            name='usaspending_flag',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='SubmissionProcess',
        ),
    ]
