# Generated by Django 2.2.12 on 2020-06-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_remove_submissionattributes_previous_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionattributes',
            name='broker_submission_id',
        ),
    ]
