# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_auto_20161130_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissionattributes',
            old_name='db_submission_id',
            new_name='broker_submission_id',
        ),
        migrations.RenameField(
            model_name='submissionattributes',
            old_name='submission_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='submissionattributes',
            name='usaspending_flag',
        ),
        migrations.AddField(
            model_name='submissionattributes',
            name='usaspending_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
