# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-31 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_remove_submissionattributes_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionattributes',
            name='certified_date',
        ),
        migrations.RemoveField(
            model_name='submissionattributes',
            name='last_modified_date',
        ),
        migrations.RemoveField(
            model_name='submissionattributes',
            name='submission_modification',
        ),
        migrations.RemoveField(
            model_name='submissionattributes',
            name='submitter_name',
        ),
        migrations.RemoveField(
            model_name='submissionattributes',
            name='submitting_agency',
        ),
        migrations.RemoveField(
            model_name='submissionattributes',
            name='version_number',
        ),
        migrations.AddField(
            model_name='submissionattributes',
            name='quarter_format_flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='submissionattributes',
            name='reporting_fiscal_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionattributes',
            name='reporting_fiscal_quarter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionattributes',
            name='reporting_fiscal_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissionattributes',
            name='cgac_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
