# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-31 02:34
from __future__ import unicode_literals

from django.db import migrations

from usaspending_api.etl.helpers import get_fiscal_quarter


def get_fiscal_year_period(calendar_date):
    """Convert calendar date to a federal fiscal year and period."""
    if calendar_date.month in [10, 11, 12]:
        return calendar_date.year + 1, calendar_date.month - 9
    else:
        return calendar_date.year, calendar_date.month + 3


def update_broker_submissions(apps, schema_editor):
    """Update new columns of existing broker submissions."""
    subs = apps.get_model("submissions", "SubmissionAttributes")

    # get all submissions that came from the broker
    broker_subs = subs.objects.filter(
        broker_submission_id__isnull=False)
    # fill in new data for each submission, using the reporting period
    # start date to calculate fiscal year, fiscal period, and fiscal quarter
    for s in broker_subs:
        fiscal_year, fiscal_period = get_fiscal_year_period(s.reporting_period_start)
        s.reporting_fiscal_year = fiscal_year
        s.reporting_fiscal_period = fiscal_period
        s.reporting_fiscal_quarter = get_fiscal_quarter(fiscal_period)
        s.quarter_format_flag = True # not used in USAspending code right now
        s.save()


def clear_new_submission_columns(apps, schema_editor):
    """Set new columns back to null."""
    subs = apps.get_model("submissions", "SubmissionAttributes")
    broker_subs = subs.objects.filter(
        broker_submission_id__isnull=False)

    for s in broker_subs:
        s.reporting_fiscal_year = None
        s.reporting_fiscal_period = None
        s.reporting_fiscal_quarter = None
        s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_auto_20170331_0209'),
    ]

    operations = [
        migrations.RunPython(update_broker_submissions, clear_new_submission_columns),
    ]
