# Generated by Django 2.2.12 on 2020-06-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_auto_20200608_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionattributes',
            name='submission_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        # There's a bug probably in Django whereby when we change a field from AutoField
        # to IntegerField, its sequence isn't dropped in the database.  This rectifies this
        # for submission_attributes.
        migrations.RunSQL(sql=[
            "alter table submission_attributes alter column submission_id drop default",
            "drop sequence if exists submission_attributes_submission_id_seq"
        ]),
    ]
