# Generated by Django 2.2.13 on 2020-07-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0010_auto_20200623_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionQueue',
            fields=[
                ('submission_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.TextField(choices=[('NEW', 'NEW'), ('IN PROGRESS', 'IN PROGRESS'), ('FAILED', 'FAILED')], default='NEW')),
                ('force_reload', models.BooleanField(default=False)),
                ('processor_id', models.TextField(default=None, null=True)),
                ('processing_started', models.DateTimeField(null=True)),
                ('heartbeat', models.DateTimeField(null=True)),
                ('processing_failed', models.DateTimeField(null=True)),
                ('exception', models.TextField(default=None, null=True)),
            ],
            options={
                'db_table': 'submission_queue',
            },
        ),
    ]
