# Generated by Django 2.2.14 on 2020-08-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_dabsloaderqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionattributes',
            name='is_final_balances_for_fy',
            field=models.BooleanField(default=False),
        ),
    ]
