# Generated by Django 2.2.17 on 2020-12-03 16:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0014_auto_20200901_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionattributes',
            name='history',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
