# Generated by Django 2.2.17 on 2020-12-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0014_auto_20200901_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionattributes',
            name='history',
            field=models.JSONField(null=True),
        ),
    ]
