# Generated by Django 5.0.4 on 2024-04-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0015_submissionattributes_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dabssubmissionwindowschedule",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
