# Generated by Django 4.2.17 on 2024-12-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0015_submissionattributes_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dabssubmissionwindowschedule",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
