# Generated by Django 4.2.19 on 2025-04-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0016_alter_dabssubmissionwindowschedule_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionattributes",
            name="reporting_fiscal_period",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="submissionattributes",
            name="reporting_fiscal_quarter",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="submissionattributes",
            name="reporting_fiscal_year",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
