name: Initialize Python Environment

inputs:
  python-version:
    description: Version of Python to use in the environment and install dependencies with
    default: "3.12.11"
  working-directory:
    description: Directory where the requirements can be found; used when multiple repos are checked out
    default: ""

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v10.2.0
      with:
        python-version: ${{ inputs.python-version }}
        enable-cache: true

    - name: Install dev dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: uv sync --extra dev

    - name: Add venv to PATH
      shell: bash
      run: echo "${{ inputs.working-directory }}.venv/bin" >> "$GITHUB_PATH"
