from duckdb.experimental.spark.sql import SparkSession as DuckDBSparkSession
from duckdb.experimental.spark.sql.column import Column as DuckDBSparkColumn
from duckdb.experimental.spark.sql.dataframe import DataFrame as DuckDBSparkDataFrame
from pyspark.sql import Column, DataFrame, SparkSession

from usaspending_api.download.delta_downloads.abstract_downloads.monthly_download import (
    AbstractMonthlyDownload,
    Category,
    MonthlyType,
)
from usaspending_api.download.delta_downloads.abstract_factories.monthly_download_factory import (
    AbstractMonthlyDownloadFactory,
    MonthlyDownload,
)
from usaspending_api.download.delta_downloads.filters.monthly_download_filters import (
    MonthlyDownloadFilters,
)


class ContractMixin:
    spark: SparkSession

    download_table: DataFrame
    dynamic_filters: Column | DuckDBSparkColumn
    filters: MonthlyDownloadFilters

    select_cols: list[Column | DuckDBSparkColumn]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if isinstance(self.spark, DuckDBSparkSession):
            from duckdb.experimental.spark.sql import functions
        else:
            from pyspark.sql import functions

        self.sf = functions

    @property
    def category(self) -> Category:
        return Category.CONTRACT

    @property
    def select_cols(self) -> list[Column | DuckDBSparkColumn]:
        return [
            self.sf.col("transaction_unique_key").alias("contract_transaction_unique_key"),
            self.sf.col("generated_unique_award_id").alias("contract_award_unique_key"),
            self.sf.col("piid").alias("award_id_piid"),
            self.sf.col("modification_number"),
            self.sf.col("transaction_number"),
            self.sf.col("referenced_idv_agency_iden").alias("parent_award_agency_id"),
            self.sf.col("referenced_idv_agency_desc").alias("parent_award_agency_name"),
            self.sf.col("parent_award_id").alias("parent_award_id_piid"),
            self.sf.col("referenced_idv_modificatio").alias("parent_award_modification_number"),
            self.sf.col("federal_action_obligation"),
            self.sf.col("total_obligation").alias("total_dollars_obligated"),
            self.sf.col("total_outlayed_amount_for_overall_award"),
            self.sf.col("base_exercised_options_val").alias("base_and_exercised_options_value"),
            self.sf.col("current_total_value_award").alias("current_total_value_of_award"),
            self.sf.col("base_and_all_options_value"),
            self.sf.col("potential_total_value_awar").alias("potential_total_value_of_award"),
            self.sf.col("defc_for_overall_award").alias("disaster_emergency_fund_codes_for_overall_award"),
            self.sf.col("covid_19_outlayed_amount").alias(
                "outlayed_amount_from_COVID-19_supplementals_for_overall_award"
            ),
            self.sf.col("covid_19_obligated_amount").alias(
                "obligated_amount_from_COVID-19_supplementals_for_overall_award"
            ),
            self.sf.col("iija_outlayed_amount").alias("outlayed_amount_from_IIJA_supplemental_for_overall_award"),
            self.sf.col("iija_obligated_amount").alias("obligated_amount_from_IIJA_supplemental_for_overall_award"),
            self.sf.col("action_date"),
            self.sf.col("action_date_fiscal_year"),
            self.sf.col("period_of_performance_start_date"),
            self.sf.col("period_of_performance_current_end_date"),
            self.sf.col("period_of_perf_potential_e").alias("period_of_performance_potential_end_date"),
            self.sf.col("ordering_period_end_date"),
            self.sf.col("solicitation_date"),
            self.sf.col("awarding_agency_code"),
            self.sf.col("awarding_toptier_agency_name_raw").alias("awarding_agency_name"),
            self.sf.col("awarding_sub_tier_agency_c").alias("awarding_sub_agency_code"),
            self.sf.col("awarding_subtier_agency_name_raw").alias("awarding_sub_agency_name"),
            self.sf.col("awarding_office_code"),
            self.sf.col("awarding_office_name"),
            self.sf.col("funding_agency_code"),
            self.sf.col("funding_toptier_agency_name_raw").alias("funding_agency_name"),
            self.sf.col("funding_sub_tier_agency_co").alias("funding_sub_agency_code"),
            self.sf.col("funding_subtier_agency_name_raw").alias("funding_sub_agency_name"),
            self.sf.col("funding_office_code"),
            self.sf.col("funding_office_name"),
            self.sf.col("treasury_accounts_funding_this_award"),
            self.sf.col("federal_accounts_funding_this_award"),
            self.sf.col("object_classes_funding_this_award"),
            self.sf.col("program_activities_funding_this_award"),
            self.sf.col("foreign_funding"),
            self.sf.col("foreign_funding_desc").alias("foreign_funding_description"),
            self.sf.col("sam_exception"),
            self.sf.col("sam_exception_description"),
            self.sf.col("recipient_uei"),
            self.sf.col("recipient_unique_id").alias("recipient_duns"),
            self.sf.col("recipient_name"),
            self.sf.col("recipient_name_raw"),
            self.sf.col("vendor_doing_as_business_n").alias("recipient_doing_business_as_name"),
            self.sf.col("cage_code"),
            self.sf.col("parent_uei").alias("recipient_parent_uei"),
            self.sf.col("parent_recipient_unique_id").alias("recipient_parent_duns"),
            self.sf.col("parent_recipient_name").alias("recipient_parent_name"),
            self.sf.col("parent_recipient_name_raw").alias("recipient_parent_name_raw"),
            self.sf.col("recipient_location_country_code").alias("recipient_country_code"),
            self.sf.col("recipient_location_country_name").alias("recipient_country_name"),
            self.sf.col("legal_entity_address_line1").alias("recipient_address_line_1"),
            self.sf.col("legal_entity_address_line2").alias("recipient_address_line_2"),
            self.sf.col("recipient_location_city_name").alias("recipient_city_name"),
            self.sf.col("recipient_location_county_fips").alias("prime_award_transaction_recipient_county_fips_code"),
            self.sf.col("recipient_location_county_name").alias("recipient_county_name"),
            self.sf.col("recipient_location_state_fips").alias("prime_award_transaction_recipient_state_fips_code"),
            self.sf.col("recipient_location_state_code").alias("recipient_state_code"),
            self.sf.col("recipient_location_state_name").alias("recipient_state_name"),
            self.sf.col("legal_entity_zip_last4").alias("recipient_zip_4_code"),
            self.sf.col("recipient_location_cd_original").alias("prime_award_transaction_recipient_cd_original"),
            self.sf.col("recipient_location_cd_current").alias("prime_award_transaction_recipient_cd_current"),
            self.sf.col("vendor_phone_number").alias("recipient_phone_number"),
            self.sf.col("vendor_fax_number").alias("recipient_fax_number"),
            self.sf.col("pop_country_code").alias("primary_place_of_performance_country_code"),
            self.sf.col("pop_country_name").alias("primary_place_of_performance_country_name"),
            self.sf.col("pop_city_name").alias("primary_place_of_performance_city_name"),
            self.sf.col("pop_county_fips").alias("prime_award_transaction_place_of_performance_county_fips_code"),
            self.sf.col("pop_county_name").alias("primary_place_of_performance_county_name"),
            self.sf.col("pop_state_fips").alias("prime_award_transaction_place_of_performance_state_fips_code"),
            self.sf.col("pop_state_code").alias("primary_place_of_performance_state_code"),
            self.sf.col("pop_state_name").alias("primary_place_of_performance_state_name"),
            self.sf.col("place_of_performance_zip4a").alias("primary_place_of_performance_zip_4"),
            self.sf.col("pop_cd_original").alias("prime_award_transaction_place_of_performance_cd_original"),
            self.sf.col("pop_cd_current").alias("prime_award_transaction_place_of_performance_cd_current"),
            self.sf.col("pulled_from").alias("award_or_idv_flag"),
            self.sf.col("contract_award_type").alias("award_type_code"),
            self.sf.col("contract_award_type_desc").alias("award_type"),
            self.sf.col("idv_type").alias("idv_type_code"),
            self.sf.col("idv_type_description").alias("idv_type"),
            self.sf.col("multiple_or_single_award_i").alias("multiple_or_single_award_idv_code"),
            self.sf.col("multiple_or_single_aw_desc").alias("multiple_or_single_award_idv"),
            self.sf.col("type_of_idc").alias("type_of_idc_code"),
            self.sf.col("type_of_idc_description").alias("type_of_idc"),
            self.sf.col("type_of_contract_pricing").alias("type_of_contract_pricing_code"),
            self.sf.col("type_of_contract_pric_desc").alias("type_of_contract_pricing"),
            self.sf.col("transaction_description").alias("transaction_description"),
            self.sf.col("award_description").alias("prime_award_base_transaction_description"),
            self.sf.col("action_type").alias("action_type_code"),
            self.sf.col("action_type_description").alias("action_type"),
            self.sf.col("solicitation_identifier"),
            self.sf.col("number_of_actions"),
            self.sf.col("inherently_government_func").alias("inherently_governmental_functions"),
            self.sf.col("inherently_government_desc").alias("inherently_governmental_functions_description"),
            self.sf.col("product_or_service_code"),
            self.sf.col("product_or_service_description").alias("product_or_service_code_description"),
            self.sf.col("contract_bundling").alias("contract_bundling_code"),
            self.sf.col("contract_bundling_descrip").alias("contract_bundling"),
            self.sf.col("dod_claimant_program_code"),
            self.sf.col("dod_claimant_prog_cod_desc").alias("dod_claimant_program_description"),
            self.sf.col("naics_code"),
            self.sf.col("naics_description"),
            self.sf.col("recovered_materials_sustai").alias("recovered_materials_sustainability_code"),
            self.sf.col("recovered_materials_s_desc").alias("recovered_materials_sustainability"),
            self.sf.col("domestic_or_foreign_entity").alias("domestic_or_foreign_entity_code"),
            self.sf.col("domestic_or_foreign_e_desc").alias("domestic_or_foreign_entity"),
            self.sf.col("program_system_or_equipmen").alias("dod_acquisition_program_code"),
            self.sf.col("program_system_or_equ_desc").alias("dod_acquisition_program_description"),
            self.sf.col("information_technology_com").alias("information_technology_commercial_item_category_code"),
            self.sf.col("information_technolog_desc").alias("information_technology_commercial_item_category"),
            self.sf.col("epa_designated_product").alias("epa_designated_product_code"),
            self.sf.col("epa_designated_produc_desc").alias("epa_designated_product"),
            self.sf.col("country_of_product_or_serv").alias("country_of_product_or_service_origin_code"),
            self.sf.col("country_of_product_or_desc").alias("country_of_product_or_service_origin"),
            self.sf.col("place_of_manufacture").alias("place_of_manufacture_code"),
            self.sf.col("place_of_manufacture_desc").alias("place_of_manufacture"),
            self.sf.col("subcontracting_plan").alias("subcontracting_plan_code"),
            self.sf.col("subcontracting_plan_desc").alias("subcontracting_plan"),
            self.sf.col("extent_competed").alias("extent_competed_code"),
            self.sf.col("extent_compete_description").alias("extent_competed"),
            self.sf.col("solicitation_procedures").alias("solicitation_procedures_code"),
            self.sf.col("solicitation_procedur_desc").alias("solicitation_procedures"),
            self.sf.col("type_set_aside").alias("type_of_set_aside_code"),
            self.sf.col("type_set_aside_description").alias("type_of_set_aside"),
            self.sf.col("evaluated_preference").alias("evaluated_preference_code"),
            self.sf.col("evaluated_preference_desc").alias("evaluated_preference"),
            self.sf.col("research").alias("research_code"),
            self.sf.col("research_description").alias("research"),
            self.sf.col("fair_opportunity_limited_s").alias("fair_opportunity_limited_sources_code"),
            self.sf.col("fair_opportunity_limi_desc").alias("fair_opportunity_limited_sources"),
            self.sf.col("other_than_full_and_open_c").alias("other_than_full_and_open_competition_code"),
            self.sf.col("other_than_full_and_o_desc").alias("other_than_full_and_open_competition"),
            self.sf.col("number_of_offers_received"),
            self.sf.col("commercial_item_acquisitio").alias("commercial_item_acquisition_procedures_code"),
            self.sf.col("commercial_item_acqui_desc").alias("commercial_item_acquisition_procedures"),
            self.sf.col("small_business_competitive").alias("small_business_competitiveness_demonstration_program"),
            self.sf.col("commercial_item_test_progr").alias("simplified_procedures_for_certain_commercial_items_code"),
            self.sf.col("commercial_item_test_desc").alias("simplified_procedures_for_certain_commercial_items"),
            self.sf.col("a_76_fair_act_action").alias("a76_fair_act_action_code"),
            self.sf.col("a_76_fair_act_action_desc").alias("a76_fair_act_action"),
            self.sf.col("fed_biz_opps").alias("fed_biz_opps_code"),
            self.sf.col("fed_biz_opps_description").alias("fed_biz_opps"),
            self.sf.col("local_area_set_aside").alias("local_area_set_aside_code"),
            self.sf.col("local_area_set_aside_desc").alias("local_area_set_aside"),
            self.sf.col("price_evaluation_adjustmen").alias(
                "price_evaluation_adjustment_preference_percent_difference"
            ),
            self.sf.col("clinger_cohen_act_planning").alias("clinger_cohen_act_planning_code"),
            self.sf.col("clinger_cohen_act_pla_desc").alias("clinger_cohen_act_planning"),
            self.sf.col("materials_supplies_article").alias("materials_supplies_articles_equipment_code"),
            self.sf.col("materials_supplies_descrip").alias("materials_supplies_articles_equipment"),
            self.sf.col("labor_standards").alias("labor_standards_code"),
            self.sf.col("labor_standards_descrip").alias("labor_standards"),
            self.sf.col("construction_wage_rate_req").alias("construction_wage_rate_requirements_code"),
            self.sf.col("construction_wage_rat_desc").alias("construction_wage_rate_requirements"),
            self.sf.col("interagency_contracting_au").alias("interagency_contracting_authority_code"),
            self.sf.col("interagency_contract_desc").alias("interagency_contracting_authority"),
            self.sf.col("other_statutory_authority"),
            self.sf.col("program_acronym"),
            self.sf.col("referenced_idv_type").alias("parent_award_type_code"),
            self.sf.col("referenced_idv_type_desc").alias("parent_award_type"),
            self.sf.col("referenced_mult_or_single").alias("parent_award_single_or_multiple_code"),
            self.sf.col("referenced_mult_or_si_desc").alias("parent_award_single_or_multiple"),
            self.sf.col("major_program"),
            self.sf.col("national_interest_action").alias("national_interest_action_code"),
            self.sf.col("national_interest_desc").alias("national_interest_action"),
            self.sf.col("cost_or_pricing_data").alias("cost_or_pricing_data_code"),
            self.sf.col("cost_or_pricing_data_desc").alias("cost_or_pricing_data"),
            self.sf.col("cost_accounting_standards").alias("cost_accounting_standards_clause_code"),
            self.sf.col("cost_accounting_stand_desc").alias("cost_accounting_standards_clause"),
            self.sf.col("government_furnished_prope").alias("government_furnished_property_code"),
            self.sf.col("government_furnished_desc").alias("government_furnished_property"),
            self.sf.col("sea_transportation").alias("sea_transportation_code"),
            self.sf.col("sea_transportation_desc").alias("sea_transportation"),
            self.sf.col("undefinitized_action").alias("undefinitized_action_code"),
            self.sf.col("undefinitized_action_desc").alias("undefinitized_action"),
            self.sf.col("consolidated_contract").alias("consolidated_contract_code"),
            self.sf.col("consolidated_contract_desc").alias("consolidated_contract"),
            self.sf.col("performance_based_service").alias("performance_based_service_acquisition_code"),
            self.sf.col("performance_based_se_desc").alias("performance_based_service_acquisition"),
            self.sf.col("multi_year_contract").alias("multi_year_contract_code"),
            self.sf.col("multi_year_contract_desc").alias("multi_year_contract"),
            self.sf.col("contract_financing").alias("contract_financing_code"),
            self.sf.col("contract_financing_descrip").alias("contract_financing"),
            self.sf.col("purchase_card_as_payment_m").alias("purchase_card_as_payment_method_code"),
            self.sf.col("purchase_card_as_paym_desc").alias("purchase_card_as_payment_method"),
            self.sf.col("contingency_humanitarian_o").alias("contingency_humanitarian_or_peacekeeping_operation_code"),
            self.sf.col("contingency_humanitar_desc").alias("contingency_humanitarian_or_peacekeeping_operation"),
            self.sf.col("alaskan_native_owned_corpo").alias("alaskan_native_corporation_owned_firm"),
            self.sf.col("american_indian_owned_busi").alias("american_indian_owned_business"),
            self.sf.col("indian_tribe_federally_rec").alias("indian_tribe_federally_recognized"),
            self.sf.col("native_hawaiian_owned_busi").alias("native_hawaiian_organization_owned_firm"),
            self.sf.col("tribally_owned_business").alias("tribally_owned_firm"),
            self.sf.col("veteran_owned_business"),
            self.sf.col("service_disabled_veteran_o").alias("service_disabled_veteran_owned_business"),
            self.sf.col("woman_owned_business"),
            self.sf.col("women_owned_small_business"),
            self.sf.col("economically_disadvantaged").alias("economically_disadvantaged_women_owned_small_business"),
            self.sf.col("joint_venture_women_owned").alias("joint_venture_women_owned_small_business"),
            self.sf.col("joint_venture_economically").alias(
                "joint_venture_economic_disadvantaged_women_owned_small_bus"
            ),
            self.sf.col("minority_owned_business"),
            self.sf.col("subcontinent_asian_asian_i").alias("subcontinent_asian_asian_indian_american_owned_business"),
            self.sf.col("asian_pacific_american_own").alias("asian_pacific_american_owned_business"),
            self.sf.col("black_american_owned_busin").alias("black_american_owned_business"),
            self.sf.col("hispanic_american_owned_bu").alias("hispanic_american_owned_business"),
            self.sf.col("native_american_owned_busi").alias("native_american_owned_business"),
            self.sf.col("other_minority_owned_busin").alias("other_minority_owned_business"),
            self.sf.col("contracting_officers_desc").alias("contracting_officers_determination_of_business_size"),
            self.sf.col("contracting_officers_deter").alias("contracting_officers_determination_of_business_size_code"),
            self.sf.col("emerging_small_business"),
            self.sf.col("community_developed_corpor").alias("community_developed_corporation_owned_firm"),
            self.sf.col("labor_surplus_area_firm"),
            self.sf.col("us_federal_government"),
            self.sf.col("federally_funded_research").alias("federally_funded_research_and_development_corp"),
            self.sf.col("federal_agency"),
            self.sf.col("us_state_government"),
            self.sf.col("us_local_government"),
            self.sf.col("city_local_government"),
            self.sf.col("county_local_government"),
            self.sf.col("inter_municipal_local_gove").alias("inter_municipal_local_government"),
            self.sf.col("local_government_owned"),
            self.sf.col("municipality_local_governm").alias("municipality_local_government"),
            self.sf.col("school_district_local_gove").alias("school_district_local_government"),
            self.sf.col("township_local_government"),
            self.sf.col("us_tribal_government"),
            self.sf.col("foreign_government"),
            self.sf.col("organizational_type"),
            self.sf.col("corporate_entity_not_tax_e").alias("corporate_entity_not_tax_exempt"),
            self.sf.col("corporate_entity_tax_exemp").alias("corporate_entity_tax_exempt"),
            self.sf.col("partnership_or_limited_lia").alias("partnership_or_limited_liability_partnership"),
            self.sf.col("sole_proprietorship"),
            self.sf.col("small_agricultural_coopera").alias("small_agricultural_cooperative"),
            self.sf.col("international_organization"),
            self.sf.col("us_government_entity"),
            self.sf.col("community_development_corp").alias("community_development_corporation"),
            self.sf.col("domestic_shelter"),
            self.sf.col("educational_institution"),
            self.sf.col("foundation"),
            self.sf.col("hospital_flag"),
            self.sf.col("manufacturer_of_goods"),
            self.sf.col("veterinary_hospital"),
            self.sf.col("hispanic_servicing_institu").alias("hispanic_servicing_institution"),
            self.sf.col("contracts").alias("receives_contracts"),
            self.sf.col("grants").alias("receives_financial_assistance"),
            self.sf.col("receives_contracts_and_gra").alias("receives_contracts_and_financial_assistance"),
            self.sf.col("airport_authority"),
            self.sf.col("council_of_governments"),
            self.sf.col("housing_authorities_public").alias("housing_authorities_public_tribal"),
            self.sf.col("interstate_entity"),
            self.sf.col("planning_commission"),
            self.sf.col("port_authority"),
            self.sf.col("transit_authority"),
            self.sf.col("subchapter_s_corporation").alias("subchapter_scorporation"),
            self.sf.col("limited_liability_corporat").alias("limited_liability_corporation"),
            self.sf.col("foreign_owned_and_located").alias("foreign_owned"),
            self.sf.col("for_profit_organization"),
            self.sf.col("nonprofit_organization"),
            self.sf.col("other_not_for_profit_organ").alias("other_not_for_profit_organization"),
            self.sf.col("the_ability_one_program"),
            self.sf.col("private_university_or_coll").alias("private_university_or_college"),
            self.sf.col("state_controlled_instituti").alias("state_controlled_institution_of_higher_learning"),
            self.sf.col("c1862_land_grant_college").alias("1862_land_grant_college"),
            self.sf.col("c1890_land_grant_college").alias("1890_land_grant_college"),
            self.sf.col("c1994_land_grant_college").alias("1994_land_grant_college"),
            self.sf.col("minority_institution"),
            self.sf.col("historically_black_college"),
            self.sf.col("tribal_college"),
            self.sf.col("alaskan_native_servicing_i").alias("alaskan_native_servicing_institution"),
            self.sf.col("native_hawaiian_servicing").alias("native_hawaiian_servicing_institution"),
            self.sf.col("school_of_forestry"),
            self.sf.col("veterinary_college"),
            self.sf.col("dot_certified_disadvantage"),
            self.sf.col("self_certified_small_disad").alias("self_certified_small_disadvantaged_business"),
            self.sf.col("small_disadvantaged_busine").alias("small_disadvantaged_business"),
            self.sf.col("c8a_program_participant"),
            self.sf.col("historically_underutilized").alias("historically_underutilized_business_zone_hubzone_firm"),
            self.sf.col("sba_certified_8_a_joint_ve").alias("sba_certified_8a_joint_venture"),
            self.sf.col("officer_1_name").alias("highly_compensated_officer_1_name"),
            self.sf.col("officer_1_amount").alias("highly_compensated_officer_1_amount"),
            self.sf.col("officer_2_name").alias("highly_compensated_officer_2_name"),
            self.sf.col("officer_2_amount").alias("highly_compensated_officer_2_amount"),
            self.sf.col("officer_3_name").alias("highly_compensated_officer_3_name"),
            self.sf.col("officer_3_amount").alias("highly_compensated_officer_3_amount"),
            self.sf.col("officer_4_name").alias("highly_compensated_officer_4_name"),
            self.sf.col("officer_4_amount").alias("highly_compensated_officer_4_amount"),
            self.sf.col("officer_5_name").alias("highly_compensated_officer_5_name"),
            self.sf.col("officer_5_amount").alias("highly_compensated_officer_5_amount"),
            self.sf.col("usaspending_permalink"),
            self.sf.col("initial_report_date"),
            self.sf.col("last_modified_date"),
        ]

    def _build_dataframes(self) -> list[DataFrame | DuckDBSparkDataFrame]:
        return [self.download_table.filter(self.dynamic_filters).select(*self.select_cols)]


class ContractDeltaMonthlyDownload(ContractMixin, AbstractMonthlyDownload):
    @property
    def monthly_type(self) -> MonthlyType:
        return MonthlyType.DELTA


class ContractFullMonthlyDownload(ContractMixin, AbstractMonthlyDownload):
    @property
    def monthly_type(self) -> MonthlyType:
        return MonthlyType.FULL


class TransactionContractMonthlyDownloadFactory(AbstractMonthlyDownloadFactory):
    def _create_delta_download(self) -> MonthlyDownload:
        return ContractDeltaMonthlyDownload(self.spark, self.filters, self.dynamic_filters)

    def _create_full_download(self) -> MonthlyDownload:
        return ContractFullMonthlyDownload(self.spark, self.filters, self.dynamic_filters)
