# Generated by Django 2.2.14 on 2021-01-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210104_2314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniversalTransactionView',
        ),
    ]
