# Generated by Django 2.2.24 on 2021-07-06 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210629_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsearch',
            name='award',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='awards.Award'),
        ),
    ]
