# Generated by Django 2.2.17 on 2021-08-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210629_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsearch',
            name='award_date_signed',
            field=models.DateTimeField(null=True),
        ),
    ]
