# Generated by Django 2.2.17 on 2022-01-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_transactionsearch_award_date_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsearch',
            name='recipient_uei',
            field=models.TextField(null=True),
        ),
    ]
