# Generated by Django 2.2.23 on 2022-01-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_transactionsearch_recipient_uei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsearch',
            name='award_date_signed',
            field=models.DateField(null=True),
        ),
    ]
