# Generated by Django 2.2.17 on 2022-03-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20220113_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsearch',
            name='parent_uei',
            field=models.TextField(null=True),
        ),
    ]
