# Generated by Django 3.2.13 on 2022-07-13 21:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_awardsearch_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AwardSearchView',
        ),
        migrations.DeleteModel(
            name='ContractAwardSearchMatview',
        ),
        migrations.DeleteModel(
            name='DirectPaymentAwardSearchMatview',
        ),
        migrations.DeleteModel(
            name='GrantAwardSearchMatview',
        ),
        migrations.DeleteModel(
            name='IDVAwardSearchMatview',
        ),
        migrations.DeleteModel(
            name='LoanAwardSearchMatview',
        ),
        migrations.DeleteModel(
            name='OtherAwardSearchMatview',
        ),
        migrations.DeleteModel(
            name='Pre2008AwardSearchMatview',
        ),
    ]
