# Generated by Django 3.2.13 on 2022-08-26 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_awardsearch_view_drop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summarystateview',
            options={'managed': True},
        ),
    ]
