# Generated by Django 3.2.13 on 2022-08-26 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0096_removing_subaward_models'),
        ('references', '0058_bureautitlelookup'),
        ('search', '0010_subaward_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubawardView',
        ),
    ]
