# Generated by Django 3.2.13 on 2022-11-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_auto_20221110_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsearch',
            name='awarding_subtier_agency_name_raw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transactionsearch',
            name='awarding_toptier_agency_name_raw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transactionsearch',
            name='funding_subtier_agency_name_raw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transactionsearch',
            name='funding_toptier_agency_name_raw',
            field=models.TextField(null=True),
        ),
    ]
