# Generated by Django 3.2.15 on 2022-11-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_additional_transaction_search_fields'),
        ('search', '0018_transaction_search_cols_agency'),
    ]

    operations = [
    ]
