# Generated by Django 3.2.13 on 2022-10-20 18:29

from django.db import migrations, models
import usaspending_api.common.custom_django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0018_transaction_search_cols_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsearch',
            name='detached_award_procurement_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionsearch',
            name='indirect_federal_sharing',
            field=usaspending_api.common.custom_django_fields.NumericField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionsearch',
            name='published_fabs_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionsearch',
            name='funding_opportunity_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionsearch',
            name='funding_opportunity_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
