# Generated by Django 3.2.15 on 2022-11-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0019_merge_20221115_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardsearch',
            name='data_source',
            field=models.TextField(null=True),
        ),
    ]
