
# Generated by Django 3.2.16 on 2023-02-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0020_auto_20221215_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardsearch',
            name='iija_spending_by_defc',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='awardsearch',
            name='total_iija_obligation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='awardsearch',
            name='total_iija_outlay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),
    ]
