# Generated by Django 3.2.15 on 2022-12-08 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0020_awardsearch_data_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subawardsearch',
            name='award',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subawardsearch', to='search.awardsearch'),
        ),
        migrations.AlterField(
            model_name='transactionsearch',
            name='award',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='search.awardsearch'),
        ),
    ]
