# Generated by Django 3.2.15 on 2022-12-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0021_auto_20221208_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardsearch',
            name='certified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='awardsearch',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='awardsearch',
            name='last_modified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='awardsearch',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RemoveField(
            model_name='awardsearch',
            name='award',
        ),
        migrations.AddField(
            model_name='awardsearch',
            name='award_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
