# Generated by Django 3.2.15 on 2023-02-25 22:40

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0024_partition_transaction_search_pt4_swap_in_partitioned_table'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='awardsearch',
            index=models.Index(django.db.models.functions.text.Upper('piid'), name='as_idx_piid_upper'),
        ),
        migrations.AddIndex(
            model_name='awardsearch',
            index=models.Index(django.db.models.functions.text.Upper('parent_award_piid'), name='as_idx_parent_award_piid_upper'),
        ),
        migrations.AddIndex(
            model_name='awardsearch',
            index=models.Index(django.db.models.functions.text.Upper('fain'), name='as_idx_fain_upper'),
        ),
        migrations.AddIndex(
            model_name='awardsearch',
            index=models.Index(django.db.models.functions.text.Upper('uri'), name='as_idx_uri_upper'),
        ),
    ]
