# Generated by Django 3.2.15 on 2023-02-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0025_award_keys_upper_indexes'),
    ]

    operations = [
        # Make column not null and unique through an index, but leave off the unique constraint
        # i.e. do the parts we want via SQL and tell Django through state_operations what those parts cover
        migrations.RunSQL(
            sql="""
                ALTER TABLE rpt.award_search ALTER COLUMN generated_unique_award_id SET NOT NULL;
                CREATE UNIQUE INDEX as_idx_generated_unique_award_id_uq ON rpt.award_search(generated_unique_award_id);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS rpt.as_idx_generated_unique_award_id_uq;
                ALTER TABLE rpt.award_search ALTER COLUMN generated_unique_award_id SET NULL;
            """,
            state_operations=[
                migrations.AlterField(
                    model_name='awardsearch',
                    name='generated_unique_award_id',
                    field=models.TextField(unique=True),
                ),
            ]
        ),
    ]
