# Generated by Django 3.2.15 on 2023-02-25 22:40

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0025_award_keys_upper_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transactionsearch',
            name='ts_idx_award_key_pre2008',
        ),
        migrations.AddIndex(
            model_name='awardsearch',
            index=models.Index(fields=['generated_unique_award_id'], name='as_idx_award_key'),
        ),
        migrations.AddIndex(
            model_name='transactionsearch',
            index=models.Index(fields=['generated_unique_award_id'], name='ts_idx_award_key'),
        ),
    ]
