# Generated by Django 3.2.13 on 2023-03-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0030_force_as_linkage_to_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardsearch',
            name='pop_congressional_code_current',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='awardsearch',
            name='recipient_location_congressional_code_current',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transactionsearch',
            name='pop_congressional_code_current',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transactionsearch',
            name='recipient_location_congressional_code_current',
            field=models.TextField(null=True),
        ),
    ]
