# Generated by Django 3.2.13 on 2023-03-16 18:16

from django.db import migrations, models
from usaspending_api.awards.models.transaction_fabs import vw_transaction_fabs_sql
from usaspending_api.awards.models.transaction_normalized import vw_transaction_normalized_sql

class Migration(migrations.Migration):

    dependencies = [
        ('search', '0031_add_iija_spending_fields'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP VIEW IF EXISTS rpt.vw_transaction_fabs",
            reverse_sql=vw_transaction_fabs_sql
        ),
        migrations.RunSQL(
            sql="DROP VIEW IF EXISTS rpt.vw_transaction_normalized",
            reverse_sql=vw_transaction_normalized_sql
        ),
        migrations.AlterField(
            model_name='transactionsearch',
            name='indirect_federal_sharing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),
        migrations.RunSQL(
            sql=vw_transaction_fabs_sql,
            reverse_sql="DROP VIEW IF EXISTS rpt.vw_transaction_fabs"
        ),
        migrations.RunSQL(
            sql=vw_transaction_normalized_sql,
            reverse_sql="DROP VIEW IF EXISTS rpt.vw_transaction_normalized"
        )
    ]
