# Generated by Django 3.2.19 on 2023-05-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0034_subaward_search_current_cds"),
    ]

    operations = [
        migrations.AddField(
            model_name="awardsearch",
            name="pop_county_fips",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="awardsearch",
            name="recipient_location_county_fips",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="transactionsearch",
            name="pop_county_fips",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="transactionsearch",
            name="recipient_location_county_fips",
            field=models.TextField(null=True),
        ),
    ]
