# Generated by Django 3.2.13 on 2023-09-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0036_add_state_county_fips_to_subaward_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='subawardsearch',
            name='legal_entity_county_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subawardsearch',
            name='legal_entity_county_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subawardsearch',
            name='place_of_perform_county_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subawardsearch',
            name='place_of_perform_county_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
