# Generated by Django 3.2.23 on 2023-12-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0037_auto_20230921_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsearch',
            name='initial_report_date',
            field=models.TextField(null=True),
        ),
    ]
