# Generated by Django 3.2.23 on 2023-12-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0037_auto_20230921_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardsearch',
            name='type_description_raw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='awardsearch',
            name='type_raw',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionsearch',
            name='type_description_raw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transactionsearch',
            name='type_raw',
            field=models.TextField(null=True),
        ),
    ]
