# Generated by Django 3.2.23 on 2023-12-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0038_add_type_raw_type_description_raw_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsearch',
            name='initial_report_date',
            field=models.DateField(null=True),
        ),
    ]
