# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-07 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0039_transactionsearch_initial_report_date'),
    ]

    # You may notice that the unmanaged models here have no fields.  This is an intentional
    # attempt to cut back a bit on unnecessary migration code.  Unmanaged models do not require
    # fields unless they are referenced by another model so this should cause no harm.
    operations = [
        migrations.CreateModel(
            name='AgencyAutocompleteMatview',
            fields=[],
            options={
                'db_table': 'mv_agency_autocomplete',
                'managed': False,
            },
        ),
    ]
