# Generated by Django 3.2.25 on 2024-07-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0040_initial_mv_agency_office_autocomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardsearch',
            name='parent_recipient_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
