# Generated by Django 5.0.3 on 2024-03-27 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0104_alter_transactiondelta_transaction"),
        ("search", "0040_initial_mv_agency_office_autocomplete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awardsearch",
            name="award",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                primary_key=True,
                related_name="%(class)s",
                serialize=False,
                to="awards.award",
            ),
        ),
        migrations.AlterField(
            model_name="summarystateview",
            name="duh",
            field=models.UUIDField(help_text="Deterministic Unique Hash", primary_key=True, serialize=False),
        ),
    ]
