# Generated by Django 3.2.25 on 2024-08-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0041_add_parent_recipient_name'),
    ]

    operations = [
        migrations.RunSQL(
            sql="",
            reverse_sql="",
            state_operations=[
                migrations.AddField(
                    model_name='SummaryStateView',
                    name='total_outlays',
                    field=models.DecimalField(decimal_places=2, max_digits=23, null=True),
                ),
            ],
        )
    ]
