# Generated by Django 3.2.25 on 2024-08-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0041_add_parent_recipient_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="summarystateview",
            name="testing_field",
            field=models.TextField(blank=True, null=True),
        ),
    ]
