# Generated by Django 3.2.25 on 2024-08-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0041_add_parent_recipient_name'),
    ]

    operations = [
        migrations.RunSQL(
            sql=f"""
                DROP TABLE IF EXISTS rpt.summary_state_view;
                CREATE TABLE rpt.summary_state_view (
                    duh uuid NULL,
                    action_date date NULL,
                    fiscal_year int4 NULL,
                    "type" text NULL,
                    distinct_awards text NULL,
                    pop_country_code text NULL,
                    pop_state_code text NULL,
                    generated_pragmatic_obligation numeric(23, 2) NULL,
                    federal_action_obligation numeric(23, 2) NULL,
                    original_loan_subsidy_cost numeric(23, 2) NULL,
                    face_value_loan_guarantee numeric(23, 2) NULL,
                    counts int8 NULL
                )
                WITH (
                    autovacuum_enabled=false
                );

                CREATE INDEX "idx_51ceb7ee$918_compound_geo_pop" ON rpt.summary_state_view 
                    USING btree (pop_country_code, pop_state_code, action_date) 
                    WITH (fillfactor='97');
                CREATE UNIQUE INDEX "idx_51ceb7ee$918_deterministic_unique_hash" ON rpt.summary_state_view 
                    USING btree (duh) 
                    WITH (fillfactor='97');
                CREATE INDEX "idx_51ceb7ee$918_ordered_action_date" ON rpt.summary_state_view 
                    USING btree (action_date DESC NULLS LAST) 
                    WITH (fillfactor='97');
                CREATE INDEX "idx_51ceb7ee$918_pop_country_code" ON rpt.summary_state_view 
                    USING btree (pop_country_code) 
                    WITH (fillfactor='97');
                CREATE INDEX "idx_51ceb7ee$918_pop_state_code" ON rpt.summary_state_view 
                    USING btree (pop_state_code) 
                    WITH (fillfactor='97') 
                    WHERE (pop_state_code IS NOT NULL);
                CREATE INDEX "idx_51ceb7ee$918_type" ON rpt.summary_state_view 
                    USING btree ("type") 
                    WITH (fillfactor='97') 
                    WHERE ("type" IS NOT NULL);
            """,
            reverse_sql=f"DROP TABLE IF EXISTS rpt.summary_state_view;"
        ),
    ]
