# Generated by Django 3.2.25 on 2024-08-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0042_create_summary_state_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='SummaryStateView',
            name='total_outlays',
            field=models.DecimalField(decimal_places=2, max_digits=23, null=True),
        ),
    ]
