# Generated by Django 3.2.25 on 2024-09-19 14:45

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0044_remove_summarystateview_action_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='awardsearch',
            index=models.Index(django.db.models.expressions.OrderBy(django.db.models.expressions.F('update_date'), descending=True, nulls_last=True), name='as_idx_update_date_desc'),
        ),
    ]
