# Generated by Django 3.2.25 on 2024-09-24 15:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0046_add_program_activities_award_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsearch',
            name='program_activity_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='transactionsearch',
            name='program_activity_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, null=True, size=None),
        ),
    ]
