# Generated by Django 4.2.17 on 2024-12-10 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0107_alter_financialaccountsbyawards_pa_reporting_key_and_more"),
        ("search", "0047_add_program_activity_to_search"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awardsearch",
            name="award",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                primary_key=True,
                related_name="%(class)s",
                serialize=False,
                to="awards.award",
            ),
        ),
        migrations.AlterField(
            model_name="summarystateview",
            name="duh",
            field=models.UUIDField(help_text="Deterministic Unique Hash", primary_key=True, serialize=False),
        ),
    ]
