# Generated by Django 3.2.25 on 2024-12-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0049_awardsearch_federal_accounts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="awardsearch",
            name="program_activity_codes",
        ),
        migrations.RemoveField(
            model_name="awardsearch",
            name="program_activity_names",
        ),
        migrations.RemoveField(
            model_name="subawardsearch",
            name="program_activity_codes",
        ),
        migrations.RemoveField(
            model_name="subawardsearch",
            name="program_activity_names",
        ),
        migrations.RemoveField(
            model_name="transactionsearch",
            name="program_activity_codes",
        ),
        migrations.RemoveField(
            model_name="transactionsearch",
            name="program_activity_names",
        ),
        migrations.AddField(
            model_name="awardsearch",
            name="program_activities",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="subawardsearch",
            name="program_activities",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="transactionsearch",
            name="program_activities",
            field=models.JSONField(null=True),
        ),
    ]
