# Generated by Django 4.2.17 on 2025-02-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0050_replace_pac_pan_columns_with_program_activities"),
    ]

    operations = [
        migrations.AddField(
            model_name="subawardsearch",
            name="prime_award_recipient_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
