# Generated by Django 4.2.19 on 2025-03-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0051_add_prime_award_recipient_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subawardsearch",
            name="subaward_report_month",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subawardsearch",
            name="subaward_report_year",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
