# Generated by Django 4.2.17 on 2025-02-14 18:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0051_add_prime_award_recipient_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="subawardsearch",
            name="tas_components",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="subawardsearch",
            name="tas_paths",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=list, null=True, size=None
            ),
        ),
    ]
