# Generated by Django 4.2.20 on 2025-03-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0052_alter_subawardsearch_subaward_report_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="awardsearch",
            name="pop_zip4",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="awardsearch",
            name="recipient_location_address_line1",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="awardsearch",
            name="recipient_location_address_line2",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="awardsearch",
            name="recipient_location_address_line3",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="awardsearch",
            name="recipient_location_foreign_postal_code",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="awardsearch",
            name="recipient_location_foreign_province",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="awardsearch",
            name="recipient_location_zip4",
            field=models.TextField(null=True),
        ),
    ]
