# Generated by Django 4.2.19 on 2025-03-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0053_awardsearch_pop_zip4_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subawardsearch",
            name="subaward_recipient_hash",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subawardsearch",
            name="subaward_recipient_level",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subawardsearch",
            name="awarding_toptier_agency_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subawardsearch",
            name="funding_toptier_agency_code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
