# Generated by Django 4.2.19 on 2025-04-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0053_awardsearch_pop_zip4_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awardsearch",
            name="recipient_name",
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="awardsearch",
            index=models.Index(
                condition=models.Q(("action_date__gte", "2007-10-01")),
                fields=["recipient_name"],
                name="as_idx_recipient_name",
            ),
        ),
    ]
