# Generated by Django 4.2.20 on 2025-04-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0053_add_columns_for_es_agg_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="subawardsearch",
            name="awarding_toptier_agency_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subawardsearch",
            name="funding_toptier_agency_code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
