# Generated by Django 4.2.20 on 2025-04-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0053_awardsearch_pop_zip4_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subawardsearch",
            name="sub_award_recipient_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
