# Generated by Django 4.2.20 on 2025-05-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0055_awardsearch_generated_unique_award_id_legacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="awardsearch",
            name="spending_by_defc",
            field=models.JSONField(null=True),
        ),
    ]
