# Generated by Django 4.2.20 on 2025-05-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0056_awardsearch_spending_by_defc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="awardsearch",
            name="covid_spending_by_defc",
        ),
        migrations.RemoveField(
            model_name="awardsearch",
            name="iija_spending_by_defc",
        ),
    ]
