# Generated by Django 4.2.23 on 2025-08-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0057_remove_awardsearch_covid_spending_by_defc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="awardsearch",
            name="transaction_count",
            field=models.IntegerField(null=True),
        ),
    ]
