# Generated by Django 4.2.23 on 2026-02-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0058_add_transaction_count_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="awardsearch",
            name="last_modified_date_new",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subawardsearch",
            name="last_modified_date_new",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transactionsearch",
            name="initial_report_date_new",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="transactionsearch",
            name="last_modified_date_new",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddIndex(
            model_name='subawardsearch',
            index=models.Index(
                models.OrderBy(models.F('last_modified_date_new'), descending=True, nulls_last=True),
                name='ss_idx_last_modified_date_new'),
        ),
        migrations.AddIndex(
            model_name="transactionsearch",
            index=models.Index(
                fields=["-last_modified_date_new"], name="ts_idx_last_modified_date_new"
            ),
        ),
        migrations.RunSQL(
            sql="""
                -- Renaming the auto-named indexes on the partitioned tables
                ALTER INDEX rpt.transaction_search_fabs_last_modified_date_new_idx
                    RENAME TO ts_idx_last_modified_date_new_fabs;
                ALTER INDEX rpt.transaction_search_fpds_last_modified_date_new_idx
                    RENAME TO ts_idx_last_modified_date_new_fpds;
            """,
            reverse_sql="""
                ALTER INDEX rpt.ts_idx_last_modified_date_new_fabs
                    RENAME TO transaction_search_fabs_last_modified_date_new_idx;
                ALTER INDEX rpt.ts_idx_last_modified_date_new_fpds
                    RENAME TO transaction_search_fpds_last_modified_date_new_idx;
            """
        )
    ]
