# Generated by Django 4.2.23 on 2026-01-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0058_add_transaction_count_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionsearch",
            name="initial_report_datetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="transactionsearch",
            name="last_modified_datetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="awardsearch",
            name="last_modified_datetime",
            field=models.DateTimeField(null=True),
        ),
    ]
