# Generated by Django 4.2.23 on 2026-01-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("search", "0058_add_transaction_count_field"),
    ]

    operations = [
        # Without dropping these tables, it caused the error cannot alter type of a column used by a view or rule
        migrations.RunSQL(
            sql="""
                DROP VIEW IF EXISTS
                vw_awards,
                vw_transaction_fabs,
                vw_transaction_normalized,
                vw_transaction_fpds,
                transaction_delta_view
                CASCADE;
                """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
