# Generated by Django 4.2.23 on 2026-01-02 16:42

from django.db import migrations, models

from usaspending_api.awards.models.award import vw_awards_sql
from usaspending_api.awards.models.transaction_fabs import vw_transaction_fabs_sql
from usaspending_api.awards.models.transaction_fpds import vw_transaction_fpds_sql
from usaspending_api.awards.models.transaction_normalized import (
    vw_transaction_normalized_sql,
)

transaction_delta_view_file = (
    "usaspending_api/database_scripts/etl/transaction_delta_view.sql"
)
with open(transaction_delta_view_file, "r") as f:
    transaction_delta_view = f.read()


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("search", "0059_alter_transactionsearch_initial_report_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionsearch",
            name="initial_report_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="transactionsearch",
            name="last_modified_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="awardsearch",
            name="last_modified_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunSQL(
            sql=f"""
                {vw_awards_sql}
                {vw_transaction_normalized_sql}
                {vw_transaction_fpds_sql}
                {vw_transaction_fabs_sql}
                {transaction_delta_view}
            """,
            reverse_sql="""DROP VIEW IF EXISTS
                vw_awards,
                vw_transaction_fabs,
                vw_transaction_normalized,
                vw_transaction_fpds,
                transaction_delta_view
                """,
        ),
    ]
