# Generated by Django 5.2.14 on 2026-08-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0061_awardsearch_object_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsearch',
            name='award_amount_basis_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionsearch',
            name='award_amount_basis_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionsearch',
            name='award_recipient_basis_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionsearch',
            name='award_recipient_basis_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
