# Generated by Django 5.2.14 on 2026-10-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0116_create_transaction_fabs_view'),
        ('search', '0062_new_award_amount_award_recipient_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transactionsearch',
            index=models.Index(fields=['awarding_agency_code'], name='ts_idx_awarding_agency_code'),
        ),
        migrations.AddIndex(
            model_name='transactionsearch',
            index=models.Index(fields=['funding_agency_code'], name='ts_idx_funding_agency_code'),
        ),
    ]
