languages:
  Python: true

engines:
  pep8:
    enabled: true
    checks:
      # Disable line length (> 79) check
      E501:
        enabled: false
  radon:
    enabled: true

ratings:
  paths:
  - "**.py"

exclude_paths:
  - "*/site-packages/*"
  - "usaspending_api/*/migrations/*"
