version: "2"

languages:
  Python: true
  Javascript: true

checks:
  argument-count:
    enabled: true
    config:
      threshold: 6
  complex-logic:
    enabled: true
    config:
      threshold: 8
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 15
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 45
  nested-control-flow:
    enabled: true
    config:
      threshold: 5
  return-statements:
    enabled: true
    config:
      threshold: 3
  similar-code:
    enabled: false

engines:
  pep8:
    enabled: true
    checks:
      # Disable line length (> 79) check
      E501:
        enabled: false
      # Disable Line break occurred before a binary operator
      W503:
        enabled: false
      # Disable Whitespace before ':'
      E203:
        enabled: false
  radon:
    enabled: true
    channel: beta
    config:
      python_version: 3
      threshold: "D"

ratings:
  paths:
  - "**.py"

exclude_paths:
  - "*/site-packages/*"
  - "usaspending_api/api_contracts/*"
  - "usaspending_api/api_docs/*"
  - "usaspending_api/*/migrations/*"
  - "usaspending_api/*/tests/*"
  - "usaspending_api/static_doc_files/js/*"
