ARG usaspending_api_tag=latest
FROM usaspending-api:${usaspending_api_tag}
RUN yum install -y \
    git \
    gcc-c++ \
    postgresql-devel \
    pcre \
    pcre-devel \
    mlocate \
    wget \
    unzip \
    bzip2-devel
COPY requirements/requirements-server.txt requirements/requirements-server.txt
RUN python3 -m pip install -r requirements/requirements-server.txt ansible==2.9.15 awscli
