# Dockerfile for usaspending-test image

# If any changes are made to the usaspending-backend image (Dockerfile) then this image needs to be rebuilt to stay in sync.

# If you do not already have the `usaspending-backend` image locally you can build it by running:
#       docker compose --profile usaspending build
# in the parent usaspending-api directory.

FROM usaspending-backend:latest

WORKDIR /usaspending-api

# Install Java for PySpark
RUN apt update && \
    apt -y install make openjdk-11-jdk
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

RUN python3 -m pip install -r requirements/requirements-dev.txt
