award_contracts_mapping = {
    'Award ID': 'piid',
    'Recipient Name': 'recipient_name',
    'Start Date': 'period_of_performance_start_date',
    'End Date': 'period_of_performance_current_end_date',
    'Award Amount': 'total_obligation',
    'Funding Agency': 'funding_toptier_agency_name',
    'Funding Sub Agency': 'funding_subtier_agency_name',
    'Contract Award Type': 'type_description',
    'Contract Description': 'description',
    'Signed Date': 'date_signed',
    'Potential Award Amount': 'base_and_all_options_value',
    'Awarding Agency': 'awarding_toptier_agency_name',
    'Awarding Sub Agency': 'awarding_subtier_agency_name',
    'Awarding Office': 'awarding_agency_office_name',
    'Funding Office': 'funding_agency_office_name',
    'Recipient Address Line 1': 'recipient_location_address_line1',
    'Recipient Address Line 2': 'recipient_location_address_line2',
    'Recipient Address Line 3': 'recipient_location_address_line3',
    'Recipient Country': 'recipient_location_country_name',
    'Recipient State': 'recipient_location_state_code',
    'Recipient Province': 'recipient_location_foreign_province',
    'Recipient County': 'recipient_location_county_name',
    'Recipient City': 'recipient_location_city_name',
    'Recipient Zip Code': 'recipient_location_zip5',
    'Place of Performance City': 'pop_city_name',
    'Place of Performance Zip Code': 'pop_zip5',
    'Place of Performance Country': 'pop_country_name',
    'Place of Performance State': 'pop_state_name',
    'Place of Performance Province': 'pop_foreign_province',
    'Recipient DUNS Number': 'recipient_unique_id',
    'Recipient Ultimate DUNS Number': 'parent_recipient_unique_id',
    'Contract Pricing Type': 'type_of_contract_pricing',
    'Recipient Congressional District': 'recipient_location_congressional_code',
    'Recipient Phone Number': 'vendor_phone_number',
    'Recipient Fax Number': 'vendor_fax_number',
    'Place of Performance Congressional District': 'pop_congressional_code',
    'Place of Performance County': 'pop_county_name',
    'Parent Award ID': 'parent_award_id',
    'IDV Type': 'idv_type',
    'IDC Type': 'type_of_idc',
    'IDV Agency Identifier': 'referenced_idv_agency_iden',
    'Multiple or Single Award IDV': 'multiple_or_single_award_i',
    'Solicitation ID': 'solicitation_identifier',
    'Solicitation Procedures': 'solicitation_procedures',
    'Number of Offers Received': 'number_of_offers_received',
    'Extent Competed': 'extent_compete_description',
    'Set-Aside Type': 'type_set_aside_description',
    'Commercial Item Acquisition Procedures': 'commercial_item_acqui_desc',
    'Commercial Item Test Program': 'commercial_item_test_progr',
    'Evaluated Preference': 'evaluated_preference_desc',
    'FedBizOpps': 'fed_biz_opps_description',
    'Small Business Competitiveness Demonstration Program': 'small_business_competitive',
    'PSC Code': 'product_or_service_code',
    'NAICS Code': 'naics',
    'NAICS Description': 'naics_description',
    'DoD Claimant Program Code': 'dod_claimant_program_code',
    'Program, System, or Equipment Code': 'program_system_or_equipmen',
    'Information Technology Commercial Item Category': 'information_technolog_desc',
    'Sea Transportation': 'sea_transportation_desc',
    'Clinger-Cohen Act Compliant': 'clinger_cohen_act_planning',
    'Subject To Davis Bacon Act': 'davis_bacon_act_descrip',
    'Subject To Service Contract Act': 'service_contract_act_desc',
    'Subject To Walsh Healey Act': 'walsh_healey_act',
    'Consolidated Contract': 'consolidated_contract',
    'Cost or Pricing Data': 'cost_or_pricing_data_desc',
    'Fair Opportunity Limited Sources': 'fair_opportunity_limi_desc',
    'Foreign Funding': 'foreign_funding_desc',
    'Interagency Contracting Authority': 'interagency_contract_desc',
    'Major program': 'major_program',
    'Multi Year Contract': 'multi_year_contract',
    'Price Evaluation Adjustment Preference Percent Difference': 'price_evaluation_adjustmen',
    'Program Acronym': 'program_acronym',
    'Purchase Card as Payment Method': 'purchase_card_as_payment_m',
    'Subcontracting Plan': 'subcontracting_plan_desc'
}

grant_award_mapping = {
    'Award ID': 'fain',
    'Recipient Name': 'recipient_name',
    'Start Date': 'period_of_performance_start_date',
    'End Date': 'period_of_performance_current_end_date',
    'Award Amount': 'total_obligation',
    'Awarding Agency': 'awarding_toptier_agency_name',
    'Awarding Sub Agency': 'awarding_subtier_agency_name',
    'Award Type': 'type',
    'Funding Agency': 'funding_toptier_agency_name',
    'Funding Sub Agency': 'funding_subtier_agency_name'
}

loan_award_mapping = {
    'Award ID': 'fain',
    'Recipient Name': 'recipient_name',
    'Issued Date': 'issued_date',
    'Loan Value': 'face_value_loan_guarantee',
    'Subsidy Cost': 'original_loan_subsidy_cost',
    'Awarding Agency': 'awarding_toptier_agency_name',
    'Awarding Sub Agency': 'awarding_subtier_agency_name',
    'Funding Agency': 'funding_toptier_agency_name',
    'Funding Sub Agency': 'funding_subtier_agency_name'
}

direct_payment_award_mapping = {
    'Award ID': 'fain',
    'Recipient Name': 'recipient_name',
    'Start Date': 'period_of_performance_start_date',
    'End Date': 'period_of_performance_current_end_date',
    'Award Amount': 'total_obligation',
    'Awarding Agency': 'awarding_toptier_agency_name',
    'Awarding Sub Agency': 'awarding_subtier_agency_name',
    'Award Type': 'type',
    'Funding Agency': 'funding_toptier_agency_name',
    'Funding Sub Agency': 'funding_subtier_agency_name'
}

other_award_mapping = {
    'Award ID': 'fain',
    'Recipient Name': 'recipient_name',
    'Start Date': 'period_of_performance_start_date',
    'End Date': 'period_of_performance_current_end_date',
    'Award Amount': 'total_obligation',
    'Awarding Agency': 'awarding_toptier_agency_name',
    'Awarding Sub Agency': 'awarding_subtier_agency_name',
    'Award Type': 'type',
    'Funding Agency': 'funding_toptier_agency_name',
    'Funding Sub Agency': 'funding_subtier_agency_name'
}

award_assistance_mapping = {**grant_award_mapping, **loan_award_mapping, **direct_payment_award_mapping,
                            **other_award_mapping}
non_loan_assistance_award_mapping = assistance_award_mapping = {**grant_award_mapping, **direct_payment_award_mapping,
                                                                **other_award_mapping}
