CREATE UNIQUE INDEX idx_47293de1$f21_subaward_id_temp ON subaward_view_temp USING BTREE(subaward_id) WITH (fillfactor = 97);
CREATE INDEX idx_47293de1$f21_award_id_temp ON subaward_view_temp USING BTREE(award_id) WITH (fillfactor = 97);
CREATE INDEX idx_47293de1$f21_generated_unique_award_id_temp ON subaward_view_temp USING BTREE(generated_unique_award_id) WITH (fillfactor = 97);
CREATE UNIQUE INDEX idx_47293de1$f21_broker_subaward_id_temp ON subaward_view_temp USING BTREE(broker_subaward_id) WITH (fillfactor = 97);
CREATE INDEX idx_47293de1$f21_award_type_temp ON subaward_view_temp USING BTREE(award_type) WITH (fillfactor = 97) WHERE award_type IS NOT NULL;
CREATE INDEX idx_47293de1$f21_ordered_subaward_number_temp ON subaward_view_temp USING BTREE(subaward_number DESC NULLS LAST) WITH (fillfactor = 97);
CREATE INDEX idx_47293de1$f21_ordered_award_type_temp ON subaward_view_temp USING BTREE(award_type DESC NULLS LAST) WITH (fillfactor = 97);
CREATE INDEX idx_47293de1$f21_ordered_fain_temp ON subaward_view_temp USING BTREE(UPPER(fain) DESC NULLS LAST) WITH (fillfactor = 97) WHERE fain IS NOT NULL;
CREATE INDEX idx_47293de1$f21_ordered_piid_temp ON subaward_view_temp USING BTREE(UPPER(piid) DESC NULLS LAST) WITH (fillfactor = 97) WHERE piid IS NOT NULL;
CREATE INDEX idx_47293de1$f21_amount_temp ON subaward_view_temp USING BTREE(amount) WITH (fillfactor = 97) WHERE amount IS NOT NULL;
DO $$ BEGIN RAISE NOTICE '10 indexes created, 42 remaining'; END $$;
CREATE INDEX idx_47293de1$f21_ordered_amount_temp ON subaward_view_temp USING BTREE(amount DESC NULLS LAST) WITH (fillfactor = 97);
CREATE INDEX idx_47293de1$f21_total_obl_bin_temp ON subaward_view_temp USING BTREE(total_obl_bin) WITH (fillfactor = 97);
CREATE INDEX idx_47293de1$f21_gin_recipient_name_temp ON subaward_view_temp USING GIN(recipient_name gin_trgm_ops);
CREATE INDEX idx_47293de1$f21_recipient_name_temp ON subaward_view_temp USING BTREE(recipient_name) WITH (fillfactor = 97) WHERE recipient_name IS NOT NULL;
CREATE INDEX idx_47293de1$f21_recipient_unique_id_temp ON subaward_view_temp USING BTREE(recipient_unique_id) WITH (fillfactor = 97) WHERE recipient_unique_id IS NOT NULL;
CREATE INDEX idx_47293de1$f21_parent_recipient_unique_id_temp ON subaward_view_temp USING BTREE(parent_recipient_unique_id) WITH (fillfactor = 97) WHERE parent_recipient_unique_id IS NOT NULL;
CREATE INDEX idx_47293de1$f21_action_date_temp ON subaward_view_temp USING BTREE(action_date DESC NULLS LAST) WITH (fillfactor = 97);
CREATE INDEX idx_47293de1$f21_last_modified_date_temp ON subaward_view_temp USING BTREE(last_modified_date DESC NULLS LAST) WITH (fillfactor = 97);
CREATE INDEX idx_47293de1$f21_fiscal_year_temp ON subaward_view_temp USING BTREE(fiscal_year DESC NULLS LAST) WITH (fillfactor = 97);
CREATE INDEX idx_47293de1$f21_awarding_agency_id_temp ON subaward_view_temp USING BTREE(awarding_agency_id ASC NULLS LAST) WITH (fillfactor = 97) WHERE awarding_agency_id IS NOT NULL;
DO $$ BEGIN RAISE NOTICE '20 indexes created, 32 remaining'; END $$;
CREATE INDEX idx_47293de1$f21_funding_agency_id_temp ON subaward_view_temp USING BTREE(funding_agency_id ASC NULLS LAST) WITH (fillfactor = 97) WHERE funding_agency_id IS NOT NULL;
CREATE INDEX idx_47293de1$f21_ordered_awarding_toptier_agency_name_temp ON subaward_view_temp USING BTREE(awarding_toptier_agency_name DESC NULLS LAST) WITH (fillfactor = 97);
CREATE INDEX idx_47293de1$f21_ordered_awarding_subtier_agency_name_temp ON subaward_view_temp USING BTREE(awarding_subtier_agency_name DESC NULLS LAST) WITH (fillfactor = 97);
CREATE INDEX idx_47293de1$f21_awarding_toptier_agency_name_temp ON subaward_view_temp USING BTREE(awarding_toptier_agency_name) WITH (fillfactor = 97) WHERE awarding_toptier_agency_name IS NOT NULL;
CREATE INDEX idx_47293de1$f21_awarding_subtier_agency_name_temp ON subaward_view_temp USING BTREE(awarding_subtier_agency_name) WITH (fillfactor = 97) WHERE awarding_subtier_agency_name IS NOT NULL;
CREATE INDEX idx_47293de1$f21_funding_toptier_agency_name_temp ON subaward_view_temp USING BTREE(funding_toptier_agency_name) WITH (fillfactor = 97) WHERE funding_toptier_agency_name IS NOT NULL;
CREATE INDEX idx_47293de1$f21_funding_subtier_agency_name_temp ON subaward_view_temp USING BTREE(funding_subtier_agency_name) WITH (fillfactor = 97) WHERE funding_subtier_agency_name IS NOT NULL;
CREATE INDEX idx_47293de1$f21_recipient_location_country_code_temp ON subaward_view_temp USING BTREE(recipient_location_country_code) WITH (fillfactor = 97) WHERE recipient_location_country_code IS NOT NULL;
CREATE INDEX idx_47293de1$f21_recipient_location_state_code_temp ON subaward_view_temp USING BTREE(recipient_location_state_code) WITH (fillfactor = 97) WHERE recipient_location_state_code IS NOT NULL;
CREATE INDEX idx_47293de1$f21_recipient_location_county_code_temp ON subaward_view_temp USING BTREE(recipient_location_county_code) WITH (fillfactor = 97) WHERE recipient_location_county_code IS NOT NULL;
DO $$ BEGIN RAISE NOTICE '30 indexes created, 22 remaining'; END $$;
CREATE INDEX idx_47293de1$f21_recipient_location_zip5_temp ON subaward_view_temp USING BTREE(recipient_location_zip5) WITH (fillfactor = 97) WHERE recipient_location_zip5 IS NOT NULL;
CREATE INDEX idx_47293de1$f21_recipient_location_cong_code_temp ON subaward_view_temp USING BTREE(recipient_location_congressional_code) WITH (fillfactor = 97) WHERE recipient_location_congressional_code IS NOT NULL;
CREATE INDEX idx_47293de1$f21_recipient_location_city_name_temp ON subaward_view_temp USING BTREE(recipient_location_city_name) WITH (fillfactor = 97) WHERE recipient_location_city_name IS NOT NULL;
CREATE INDEX idx_47293de1$f21_pop_country_code_temp ON subaward_view_temp USING BTREE(pop_country_code) WITH (fillfactor = 97) WHERE pop_country_code IS NOT NULL;
CREATE INDEX idx_47293de1$f21_pop_state_code_temp ON subaward_view_temp USING BTREE(pop_state_code) WITH (fillfactor = 97) WHERE pop_state_code IS NOT NULL;
CREATE INDEX idx_47293de1$f21_pop_county_code_temp ON subaward_view_temp USING BTREE(pop_county_code) WITH (fillfactor = 97) WHERE pop_county_code IS NOT NULL;
CREATE INDEX idx_47293de1$f21_pop_zip5_temp ON subaward_view_temp USING BTREE(pop_zip5) WITH (fillfactor = 97) WHERE pop_zip5 IS NOT NULL;
CREATE INDEX idx_47293de1$f21_pop_congressional_code_temp ON subaward_view_temp USING BTREE(pop_congressional_code) WITH (fillfactor = 97) WHERE pop_congressional_code IS NOT NULL;
CREATE INDEX idx_47293de1$f21_pop_city_name_temp ON subaward_view_temp USING BTREE(pop_city_name) WITH (fillfactor = 97) WHERE pop_city_name IS NOT NULL;
CREATE INDEX idx_47293de1$f21_cfda_number_temp ON subaward_view_temp USING BTREE(cfda_number) WITH (fillfactor = 97) WHERE cfda_number IS NOT NULL;
DO $$ BEGIN RAISE NOTICE '40 indexes created, 12 remaining'; END $$;
CREATE INDEX idx_47293de1$f21_type_of_contract_pricing_temp ON subaward_view_temp USING BTREE(type_of_contract_pricing) WITH (fillfactor = 97) WHERE type_of_contract_pricing IS NOT NULL;
CREATE INDEX idx_47293de1$f21_extent_competed_temp ON subaward_view_temp USING BTREE(extent_competed) WITH (fillfactor = 97) WHERE extent_competed IS NOT NULL;
CREATE INDEX idx_47293de1$f21_type_set_aside_temp ON subaward_view_temp USING BTREE(type_set_aside) WITH (fillfactor = 97) WHERE type_set_aside IS NOT NULL;
CREATE INDEX idx_47293de1$f21_product_or_service_code_temp ON subaward_view_temp USING BTREE(product_or_service_code) WITH (fillfactor = 97) WHERE product_or_service_code IS NOT NULL;
CREATE INDEX idx_47293de1$f21_gin_product_or_service_description_temp ON subaward_view_temp USING GIN((product_or_service_description) gin_trgm_ops);
CREATE INDEX idx_47293de1$f21_gin_business_categories_temp ON subaward_view_temp USING GIN(business_categories);
CREATE INDEX idx_47293de1$f21_keyword_ts_vector_temp ON subaward_view_temp USING GIN(keyword_ts_vector);
CREATE INDEX idx_47293de1$f21_award_ts_vector_temp ON subaward_view_temp USING GIN(award_ts_vector);
CREATE INDEX idx_47293de1$f21_recipient_name_ts_vector_temp ON subaward_view_temp USING GIN(recipient_name_ts_vector);
CREATE INDEX idx_47293de1$f21_treasury_account_identifiers_temp ON subaward_view_temp USING GIN(treasury_account_identifiers gin__int_ops);
DO $$ BEGIN RAISE NOTICE '50 indexes created, 2 remaining'; END $$;
CREATE INDEX idx_47293de1$f21_compound_psc_action_date_temp ON subaward_view_temp USING BTREE(product_or_service_code, action_date) WITH (fillfactor = 97);
CREATE INDEX idx_47293de1$f21_compound_cfda_action_date_temp ON subaward_view_temp USING BTREE(cfda_number, action_date) WITH (fillfactor = 97);
