from pyspark.sql.types import (
    BooleanType,
    DateType,
    DecimalType,
    IntegerType,
    LongType,
    StringType,
    StructField,
    StructType,
)

_common_schema = StructType(
    [
        # --- Award ---
        StructField("award_id", LongType(), False),
        StructField("award_unique_key", StringType(), False),
        StructField("award_description", StringType()),
        StructField("total_obligated_amount", DecimalType(23, 2)),
        StructField("usaspending_permalink", StringType(), False),
        # --- File C ---
        StructField("covid_19_obligated_amount", DecimalType(23, 2)),
        StructField("covid_19_outlayed_amount", DecimalType(23, 2)),
        StructField("disaster_emergency_fund_codes_for_overall_award", DecimalType(23, 2)),
        StructField("federal_accounts_funding_this_award", StringType()),
        StructField("iija_obligated_amount", DecimalType(23, 2)),
        StructField("iija_outlayed_amount", DecimalType(23, 2)),
        StructField("object_classes_funding_this_award", StringType()),
        StructField("program_activities_funding_this_award", StringType()),
        StructField("total_outlayed_amount_for_overall_award", DecimalType(23, 2)),
        StructField("treasury_accounts_funding_this_award", StringType()),
        # --- Transaction ---
        StructField("modification_number", StringType()),
        StructField("transaction_id", LongType(), False),
        StructField("transaction_raw_id", LongType(), False),
        StructField("transaction_unique_key", StringType(), False),
        # Agencies
        StructField("awarding_agency_code", StringType()),
        StructField("awarding_agency_name", StringType()),
        StructField("awarding_sub_agency_code", StringType()),
        StructField("awarding_sub_agency_name", StringType()),
        StructField("funding_agency_code", StringType()),
        StructField("funding_agency_name", StringType()),
        StructField("funding_sub_agency_code", StringType()),
        StructField("funding_sub_agency_name", StringType()),
        # Amounts
        StructField("federal_action_obligation", DecimalType(23, 2)),
        StructField("generated_pragmatic_obligations", DecimalType(23, 2)),
        # Dates
        StructField("action_date", DateType()),
        StructField("action_date_fiscal_year", IntegerType()),
        StructField("initial_report_date", DateType()),
        StructField("last_modified_date", DateType()),
        StructField("period_of_performance_current_end_date", DateType()),
        StructField("period_of_performance_start_date", DateType()),
        # Officer Amounts
        StructField("highly_compensated_officer_1_name", StringType()),
        StructField("highly_compensated_officer_1_amount", DecimalType(23, 2)),
        StructField("highly_compensated_officer_2_name", StringType()),
        StructField("highly_compensated_officer_2_amount", DecimalType(23, 2)),
        StructField("highly_compensated_officer_3_name", StringType()),
        StructField("highly_compensated_officer_3_amount", DecimalType(23, 2)),
        StructField("highly_compensated_officer_4_name", StringType()),
        StructField("highly_compensated_officer_4_amount", DecimalType(23, 2)),
        StructField("highly_compensated_officer_5_name", StringType()),
        StructField("highly_compensated_officer_5_amount", DecimalType(23, 2)),
        # Offices
        StructField("awarding_office_code", StringType()),
        StructField("awarding_office_name", StringType()),
        StructField("funding_office_code", StringType()),
        StructField("funding_office_name", StringType()),
        # Place of Performance
        StructField("place_of_performance_cd_current", StringType()),
        StructField("place_of_performance_cd_original", StringType()),
        StructField("place_of_performance_city_name", StringType()),
        StructField("place_of_performance_country_code", StringType()),
        StructField("place_of_performance_country_name", StringType()),
        StructField("place_of_performance_county_fips_code", StringType()),
        StructField("place_of_performance_county_name", StringType()),
        StructField("place_of_performance_state_fips_code", StringType()),
        StructField("place_of_performance_state_code", StringType()),
        StructField("place_of_performance_state_name", StringType()),
        StructField("place_of_performance_zip_4a", StringType()),
        # Recipient
        StructField("recipient_duns", StringType()),
        StructField("recipient_name", StringType()),
        StructField("recipient_name_raw", StringType()),
        StructField("recipient_uei", StringType()),
        StructField("parent_recipient_duns", StringType()),
        StructField("parent_recipient_name", StringType()),
        StructField("parent_recipient_name_raw", StringType()),
        StructField("parent_recipient_uei", StringType()),
        # Recipient Location
        StructField("recipient_location_address_line_1", StringType()),
        StructField("recipient_location_address_line_2", StringType()),
        StructField("recipient_location_cd_current", StringType()),
        StructField("recipient_location_cd_original", StringType()),
        StructField("recipient_location_city_name", StringType()),
        StructField("recipient_location_country_code", StringType()),
        StructField("recipient_location_country_name", StringType()),
        StructField("recipient_location_county_fips_code", StringType()),
        StructField("recipient_location_county_name", StringType()),
        StructField("recipient_location_state_code", StringType()),
        StructField("recipient_location_state_fips_code", StringType()),
        StructField("recipient_location_state_name", StringType()),
        StructField("recipient_location_zip_5", StringType()),
        StructField("recipient_location_zip_last_4", StringType()),
        # Typing
        StructField("action_type_code", StringType()),
        StructField("action_type_description", StringType()),
        StructField("award_type", StringType()),
        StructField("award_type_description", StringType()),
        StructField("is_fpds", BooleanType(), False),
        StructField("transaction_description", StringType()),
    ]
)

_fabs_specific_schema = StructType(
    [
        # --- Award ---
        StructField("total_face_value_of_loan", DecimalType(23, 2)),
        StructField("total_loan_subsidy_cost", DecimalType(23, 2)),
        StructField("total_non_federal_funding_amount", DecimalType(23, 2)),
        # --- Transaction ---
        StructField("fain", StringType()),
        StructField("uri", StringType()),
        # Amounts
        StructField("face_value_of_loan", DecimalType(23, 2)),
        StructField("indirect_cost_federal_share_amount", DecimalType(23, 2)),
        StructField("non_federal_funding_amount", DecimalType(23, 2)),
        StructField("original_loan_subsidy_cost", DecimalType(23, 2)),
        # Place of Performance
        StructField("place_of_performance_code", StringType()),
        StructField("place_of_performance_foreign_location", StringType()),
        StructField("place_of_performance_scope", StringType()),
        # Recipient Location
        StructField("recipient_location_foreign_city_name", StringType()),
        StructField("recipient_location_foreign_postal_code", StringType()),
        StructField("recipient_location_foreign_province_name", StringType()),
        # Additional FABS Fields
        StructField("assistance_type_code", StringType()),
        StructField("assistance_type_description", StringType()),
        StructField("business_funds_indicator_code", StringType()),
        StructField("business_funds_indicator_description", StringType()),
        StructField("business_types_code", StringType()),
        StructField("business_types_description", StringType()),
        StructField("cfda_program_code", StringType()),
        StructField("cfda_program_description", StringType()),
        StructField("correction_delete_indicator_code", StringType()),
        StructField("correction_delete_indicator_description", StringType()),
        StructField("funding_opportunity_code", StringType()),
        StructField("funding_opportunity_description", StringType()),
        StructField("record_type_code", StringType()),
        StructField("record_type_description", StringType()),
        StructField("sai_number", StringType()),
    ]
)

_fpds_specific_schema = StructType(
    [
        # -- Transaction ---
        StructField("piid", StringType()),
        StructField("transaction_number", StringType()),
        # Dates
        StructField("ordering_period_end_date", StringType()),
        StructField("solicitation_date", StringType()),
        # Parent Award (for IDV)
        StructField("parent_award_agency_id", StringType()),
        StructField("parent_award_agency_name", StringType()),
        StructField("parent_award_id_piid", StringType()),
        StructField("parent_award_modification_number", StringType()),
        StructField("parent_award_single_or_multiple_code", StringType()),
        StructField("parent_award_single_or_multiple_description", StringType()),
        StructField("parent_award_type_code", StringType()),
        StructField("parent_award_type_description", StringType()),
        # Recipient
        StructField("recipient_phone_number", StringType()),
        StructField("recipient_fax_number", StringType()),
        StructField("recipient_doing_business_as_name", StringType()),
        # Recipient Location
        StructField("recipient_location_zip_4", StringType()),
        # Additional FPDS Fields
        StructField("1862_land_grant_college", BooleanType()),
        StructField("1890_land_grant_college", BooleanType()),
        StructField("1994_land_grant_college", BooleanType()),
        StructField("a76_fair_act_action_code", StringType()),
        StructField("a76_fair_act_action_description", StringType()),
        StructField("airport_authority", BooleanType()),
        StructField("alaskan_native_corporation_owned_firm", BooleanType()),
        StructField("alaskan_native_servicing_institution", BooleanType()),
        StructField("american_indian_owned_business", BooleanType()),
        StructField("asian_pacific_american_owned_business", BooleanType()),
        StructField("award_or_idv_flag", StringType()),
        StructField("base_and_all_options_value", StringType()),
        StructField("base_and_exercised_options_value", StringType()),
        StructField("black_american_owned_business", BooleanType()),
        StructField("c8a_program_participant", BooleanType()),
        StructField("cage_code", StringType()),
        StructField("city_local_government", BooleanType()),
        StructField("clinger_cohen_act_planning_code", StringType()),
        StructField("clinger_cohen_act_planning_description", StringType()),
        StructField("commercial_item_acquisition_procedures_code", StringType()),
        StructField("commercial_item_acquisition_procedures_description", StringType()),
        StructField("community_developed_corporation_owned_firm", BooleanType()),
        StructField("community_development_corporation", BooleanType()),
        StructField("consolidated_contract_code", StringType()),
        StructField("consolidated_contract_description", StringType()),
        StructField("construction_wage_rate_requirements_code", StringType()),
        StructField("construction_wage_rate_requirements_description", StringType()),
        StructField("contingency_humanitarian_or_peacekeeping_operation_code", StringType()),
        StructField("contingency_humanitarian_or_peacekeeping_operation_description", StringType()),
        StructField("contract_bundling_code", StringType()),
        StructField("contract_bundling_description", StringType()),
        StructField("contract_financing_code", StringType()),
        StructField("contract_financing_description", StringType()),
        StructField("contracting_officers_determination_of_business_size_code", StringType()),
        StructField("contracting_officers_determination_of_business_size_description", StringType()),
        StructField("corporate_entity_not_tax_exempt", BooleanType()),
        StructField("corporate_entity_tax_exempt", BooleanType()),
        StructField("cost_accounting_standards_clause_code", StringType()),
        StructField("cost_accounting_standards_clause_description", StringType()),
        StructField("cost_or_pricing_data_code", StringType()),
        StructField("cost_or_pricing_data_description", StringType()),
        StructField("council_of_governments", BooleanType()),
        StructField("country_of_product_or_service_origin_code", StringType()),
        StructField("country_of_product_or_service_origin_description", StringType()),
        StructField("county_local_government", BooleanType()),
        StructField("current_total_value_of_award", StringType()),
        StructField("dod_acquisition_program_code", StringType()),
        StructField("dod_acquisition_program_description", StringType()),
        StructField("dod_claimant_program_code", StringType()),
        StructField("dod_claimant_program_description", StringType()),
        StructField("domestic_or_foreign_entity_code", StringType()),
        StructField("domestic_or_foreign_entity_description", StringType()),
        StructField("domestic_shelter", BooleanType()),
        StructField("dot_certified_disadvantage", BooleanType()),
        StructField("economically_disadvantaged_women_owned_small_business", BooleanType()),
        StructField("educational_institution", BooleanType()),
        StructField("emerging_small_business", BooleanType()),
        StructField("epa_designated_product_code", StringType()),
        StructField("epa_designated_product_description", StringType()),
        StructField("evaluated_preference_code", StringType()),
        StructField("evaluated_preference_description", StringType()),
        StructField("extent_competed_code", StringType()),
        StructField("extent_competed_description", StringType()),
        StructField("fair_opportunity_limited_sources_code", StringType()),
        StructField("fair_opportunity_limited_sources_description", StringType()),
        StructField("fed_biz_opps_code", StringType()),
        StructField("fed_biz_opps_description", StringType()),
        StructField("federal_agency", BooleanType()),
        StructField("federally_funded_research_and_development_corp", BooleanType()),
        StructField("for_profit_organization", BooleanType()),
        StructField("foreign_funding_code", StringType()),
        StructField("foreign_funding_description", StringType()),
        StructField("foreign_government", BooleanType()),
        StructField("foreign_owned", BooleanType()),
        StructField("foundation", BooleanType()),
        StructField("government_furnished_property_code", StringType()),
        StructField("government_furnished_property_description", StringType()),
        StructField("hispanic_american_owned_business", BooleanType()),
        StructField("hispanic_servicing_institution", BooleanType()),
        StructField("historically_black_college", BooleanType()),
        StructField("historically_underutilized_business_zone_hubzone_firm", BooleanType()),
        StructField("hospital_flag", BooleanType()),
        StructField("housing_authorities_public_tribal", BooleanType()),
        StructField("idv_type_code", StringType()),
        StructField("idv_type_description", StringType()),
        StructField("information_technology_commercial_item_category_code", StringType()),
        StructField("information_technology_commercial_item_category_description", StringType()),
        StructField("indian_tribe_federally_recognized", BooleanType()),
        StructField("inherently_governmental_functions_code", StringType()),
        StructField("inherently_governmental_functions_description", StringType()),
        StructField("inter_municipal_local_government", BooleanType()),
        StructField("interagency_contracting_authority_code", StringType()),
        StructField("interagency_contracting_authority_description", StringType()),
        StructField("international_organization", BooleanType()),
        StructField("interstate_entity", BooleanType()),
        StructField("joint_venture_economic_disadvantaged_women_owned_small_bus", BooleanType()),
        StructField("joint_venture_women_owned_small_business", BooleanType()),
        StructField("labor_standards_code", StringType()),
        StructField("labor_standards_description", StringType()),
        StructField("labor_surplus_area_firm", BooleanType()),
        StructField("limited_liability_corporation", BooleanType()),
        StructField("local_area_set_aside_code", StringType()),
        StructField("local_area_set_aside_description", StringType()),
        StructField("local_government_owned", BooleanType()),
        StructField("major_program", StringType()),
        StructField("manufacturer_of_goods", BooleanType()),
        StructField("materials_supplies_articles_equipment_code", StringType()),
        StructField("materials_supplies_articles_equipment_description", StringType()),
        StructField("minority_institution", BooleanType()),
        StructField("minority_owned_business", BooleanType()),
        StructField("multi_year_contract_code", StringType()),
        StructField("multi_year_contract_description", StringType()),
        StructField("multiple_or_single_award_idv_code", StringType()),
        StructField("multiple_or_single_award_idv_description", StringType()),
        StructField("municipality_local_government", BooleanType()),
        StructField("naics_code", StringType()),
        StructField("naics_description", StringType()),
        StructField("national_interest_action_code", StringType()),
        StructField("national_interest_action_description", StringType()),
        StructField("native_american_owned_business", BooleanType()),
        StructField("native_hawaiian_organization_owned_firm", BooleanType()),
        StructField("native_hawaiian_servicing_institution", BooleanType()),
        StructField("nonprofit_organization", BooleanType()),
        StructField("number_of_actions", StringType()),
        StructField("number_of_offers_received", StringType()),
        StructField("organizational_type", StringType()),
        StructField("other_minority_owned_business", BooleanType()),
        StructField("other_not_for_profit_organization", BooleanType()),
        StructField("other_statutory_authority", StringType()),
        StructField("other_than_full_and_open_competition_code", StringType()),
        StructField("other_than_full_and_open_competition_description", StringType()),
        StructField("partnership_or_limited_liability_partnership", BooleanType()),
        StructField("performance_based_service_acquisition_code", StringType()),
        StructField("performance_based_service_acquisition_description", StringType()),
        StructField("place_of_manufacture_code", StringType()),
        StructField("place_of_manufacture_description", StringType()),
        StructField("planning_commission", BooleanType()),
        StructField("port_authority", BooleanType()),
        StructField("potential_total_value_of_award", StringType()),
        StructField("price_evaluation_adjustment_preference_percent_difference", StringType()),
        StructField("private_university_or_college", BooleanType()),
        StructField("program_acronym", StringType()),
        StructField("product_or_service_code", StringType()),
        StructField("product_or_service_code_description", StringType()),
        StructField("purchase_card_as_payment_method_code", StringType()),
        StructField("purchase_card_as_payment_method_description", StringType()),
        StructField("receives_contracts", BooleanType()),
        StructField("receives_contracts_and_financial_assistance", BooleanType()),
        StructField("receives_financial_assistance", BooleanType()),
        StructField("recovered_materials_sustainability_code", StringType()),
        StructField("recovered_materials_sustainability_description", StringType()),
        StructField("research_code", StringType()),
        StructField("research_description", StringType()),
        StructField("sam_exception_code", StringType()),
        StructField("sam_exception_description", StringType()),
        StructField("sba_certified_8a_joint_venture", BooleanType()),
        StructField("school_district_local_government", BooleanType()),
        StructField("school_of_forestry", BooleanType()),
        StructField("sea_transportation_code", StringType()),
        StructField("sea_transportation_description", StringType()),
        StructField("self_certified_small_disadvantaged_business", BooleanType()),
        StructField("service_disabled_veteran_owned_business", BooleanType()),
        StructField("simplified_procedures_for_certain_commercial_items_code", StringType()),
        StructField("simplified_procedures_for_certain_commercial_items_description", StringType()),
        StructField("small_agricultural_cooperative", BooleanType()),
        StructField("small_business_competitiveness_demonstration_program", BooleanType()),
        StructField("small_disadvantaged_business", BooleanType()),
        StructField("sole_proprietorship", BooleanType()),
        StructField("solicitation_identifier", StringType()),
        StructField("state_controlled_institution_of_higher_learning", BooleanType()),
        StructField("subchapter_s_corporation", BooleanType()),
        StructField("subcontinent_asian_asian_indian_american_owned_business", BooleanType()),
        StructField("subcontracting_plan_code", StringType()),
        StructField("subcontracting_plan_description", StringType()),
        StructField("the_ability_one_program", BooleanType()),
        StructField("township_local_government", BooleanType()),
        StructField("transit_authority", BooleanType()),
        StructField("tribal_college", BooleanType()),
        StructField("tribally_owned_firm", BooleanType()),
        StructField("type_of_contract_pricing_code", StringType()),
        StructField("type_of_contract_pricing_description", StringType()),
        StructField("type_of_idc_code", StringType()),
        StructField("type_of_idc_description", StringType()),
        StructField("type_of_set_aside_code", StringType()),
        StructField("type_of_set_aside_description", StringType()),
        StructField("undefinitized_action_code", StringType()),
        StructField("undefinitized_action_description", StringType()),
        StructField("us_federal_government", BooleanType()),
        StructField("us_government_entity", BooleanType()),
        StructField("us_local_government", BooleanType()),
        StructField("us_state_government", BooleanType()),
        StructField("us_tribal_government", BooleanType()),
        StructField("veteran_owned_business", BooleanType()),
        StructField("veterinary_college", BooleanType()),
        StructField("veterinary_hospital", BooleanType()),
        StructField("woman_owned_business", BooleanType()),
        StructField("women_owned_small_business", BooleanType()),
    ]
)

transaction_download_schema = StructType([*_common_schema, *_fabs_specific_schema, *_fpds_specific_schema])
