from pyspark.sql.types import (
    BooleanType,
    DateType,
    DecimalType,
    IntegerType,
    LongType,
    StringType,
    StructField,
    StructType,
    TimestampType,
)

_common_schema = StructType(
    [
        # --- Award ---
        StructField("award_id", LongType(), False),
        StructField("generated_unique_award_id", StringType(), False),
        StructField("award_description", StringType()),
        StructField("total_obligation", DecimalType(23, 2)),
        StructField("usaspending_permalink", StringType(), False),
        # --- Transaction ---
        StructField("modification_number", StringType()),
        StructField("transaction_id", LongType(), False),
        StructField("transaction_broker_id", IntegerType(), False),
        StructField("transaction_unique_key", StringType(), False),
        # Agencies
        StructField("awarding_agency_code", StringType()),
        StructField("awarding_toptier_agency_name_raw", StringType()),
        StructField("awarding_sub_tier_agency_c", StringType()),
        StructField("awarding_subtier_agency_name_raw", StringType()),
        StructField("funding_agency_code", StringType()),
        StructField("funding_toptier_agency_name_raw", StringType()),
        StructField("funding_sub_tier_agency_co", StringType()),
        StructField("funding_subtier_agency_name_raw", StringType()),
        # Amounts
        StructField("federal_action_obligation", DecimalType(23, 2)),
        StructField("generated_pragmatic_obligation", DecimalType(23, 2)),
        # Dates
        StructField("action_date", DateType()),
        StructField("action_date_fiscal_year", IntegerType()),
        StructField("initial_report_date", TimestampType()),
        StructField("last_modified_date", TimestampType()),
        StructField("period_of_performance_current_end_date", DateType()),
        StructField("period_of_performance_start_date", DateType()),
        # Offices
        StructField("awarding_office_code", StringType()),
        StructField("awarding_office_name", StringType()),
        StructField("funding_office_code", StringType()),
        StructField("funding_office_name", StringType()),
        # Place of Performance
        StructField("pop_cd_current", StringType()),
        StructField("pop_cd_original", StringType()),
        StructField("pop_city_name", StringType()),
        StructField("pop_country_code", StringType()),
        StructField("pop_country_name", StringType()),
        StructField("pop_county_fips", StringType()),
        StructField("pop_county_name", StringType()),
        StructField("pop_state_fips", StringType()),
        StructField("pop_state_code", StringType()),
        StructField("pop_state_name", StringType()),
        StructField("place_of_performance_zip4a", StringType()),
        # Recipient
        StructField("recipient_unique_id", StringType()),
        StructField("recipient_name", StringType()),
        StructField("recipient_name_raw", StringType()),
        StructField("recipient_uei", StringType()),
        StructField("parent_recipient_unique_id", StringType()),
        StructField("parent_recipient_name", StringType()),
        StructField("parent_recipient_name_raw", StringType()),
        StructField("parent_uei", StringType()),
        # Recipient Location
        StructField("legal_entity_address_line1", StringType()),
        StructField("legal_entity_address_line2", StringType()),
        StructField("recipient_location_cd_current", StringType()),
        StructField("recipient_location_cd_original", StringType()),
        StructField("recipient_location_city_name", StringType()),
        StructField("recipient_location_country_code", StringType()),
        StructField("recipient_location_country_name", StringType()),
        StructField("recipient_location_county_fips", StringType()),
        StructField("recipient_location_county_name", StringType()),
        StructField("recipient_location_state_code", StringType()),
        StructField("recipient_location_state_fips", StringType()),
        StructField("recipient_location_state_name", StringType()),
        StructField("recipient_location_zip5", StringType()),
        StructField("legal_entity_zip_last4", StringType()),
        # Typing
        StructField("action_type", StringType()),
        StructField("action_type_description", StringType()),
        StructField("is_fpds", BooleanType(), False),
        StructField("transaction_description", StringType()),
    ]
)

_faba_agg_schema = StructType(
    [
        StructField("covid_19_obligated_amount", DecimalType(23, 2)),
        StructField("covid_19_outlayed_amount", DecimalType(23, 2)),
        StructField("defc_for_overall_award", StringType()),
        StructField("federal_accounts_funding_this_award", StringType()),
        StructField("iija_obligated_amount", DecimalType(23, 2)),
        StructField("iija_outlayed_amount", DecimalType(23, 2)),
        StructField("object_classes_funding_this_award", StringType()),
        StructField("program_activities_funding_this_award", StringType()),
        StructField("total_outlayed_amount_for_overall_award", DecimalType(23, 2)),
        StructField("treasury_accounts_funding_this_award", StringType()),
    ]
)

_fabs_specific_schema = StructType(
    [
        # --- Award ---
        StructField("total_loan_value", DecimalType(23, 2)),
        StructField("total_subsidy_cost", DecimalType(23, 2)),
        StructField("total_non_federal_funding_amount", DecimalType(23, 2)),
        # --- Transaction ---
        StructField("fain", StringType()),
        StructField("uri", StringType()),
        # Amounts
        StructField("face_value_loan_guarantee", DecimalType(23, 2)),
        StructField("indirect_federal_sharing", DecimalType(23, 2)),
        StructField("non_federal_funding_amount", DecimalType(23, 2)),
        StructField("original_loan_subsidy_cost", DecimalType(23, 2)),
        # Place of Performance
        StructField("place_of_performance_code", StringType()),
        StructField("place_of_performance_forei", StringType()),
        StructField("place_of_performance_scope", StringType()),
        # Recipient Location
        StructField("legal_entity_foreign_city", StringType()),
        StructField("legal_entity_foreign_posta", StringType()),
        StructField("legal_entity_foreign_provi", StringType()),
        # Additional FABS Fields
        StructField("business_funds_indicator", StringType()),
        StructField("business_funds_ind_desc", StringType()),
        StructField("business_types", StringType()),
        StructField("business_types_desc", StringType()),
        StructField("cfda_number", StringType()),
        StructField("cfda_title", StringType()),
        StructField("correction_delete_indicatr", StringType()),
        StructField("correction_delete_ind_desc", StringType()),
        StructField("funding_opportunity_number", StringType()),
        StructField("funding_opportunity_goals", StringType()),
        StructField("record_type", IntegerType()),
        StructField("record_type_description", StringType()),
        StructField("sai_number", StringType()),
        StructField("type", StringType()),
        StructField("type_description", StringType()),
    ]
)

_fpds_specific_schema = StructType(
    [
        # -- Transaction ---
        StructField("piid", StringType()),
        StructField("transaction_number", StringType()),
        # Dates
        StructField("ordering_period_end_date", StringType()),
        StructField("solicitation_date", DateType()),
        # Officer Amounts
        StructField("officer_1_name", StringType()),
        StructField("officer_1_amount", DecimalType(23, 2)),
        StructField("officer_2_name", StringType()),
        StructField("officer_2_amount", DecimalType(23, 2)),
        StructField("officer_3_name", StringType()),
        StructField("officer_3_amount", DecimalType(23, 2)),
        StructField("officer_4_name", StringType()),
        StructField("officer_4_amount", DecimalType(23, 2)),
        StructField("officer_5_name", StringType()),
        StructField("officer_5_amount", DecimalType(23, 2)),
        # Parent Award (for IDV)
        StructField("referenced_idv_agency_iden", StringType()),
        StructField("referenced_idv_agency_desc", StringType()),
        StructField("parent_award_id", StringType()),
        StructField("referenced_idv_modificatio", StringType()),
        StructField("referenced_mult_or_single", StringType()),
        StructField("referenced_mult_or_si_desc", StringType()),
        StructField("referenced_idv_type", StringType()),
        StructField("referenced_idv_type_desc", StringType()),
        # Recipient
        StructField("vendor_phone_number", StringType()),
        StructField("vendor_fax_number", StringType()),
        StructField("vendor_doing_as_business_n", StringType()),
        # Recipient Location
        StructField("legal_entity_zip4", StringType()),
        # Additional FPDS Fields
        StructField("a_76_fair_act_action", StringType()),
        StructField("a_76_fair_act_action_desc", StringType()),
        StructField("airport_authority", BooleanType()),
        StructField("alaskan_native_owned_corpo", BooleanType()),
        StructField("alaskan_native_servicing_i", BooleanType()),
        StructField("american_indian_owned_busi", BooleanType()),
        StructField("asian_pacific_american_own", BooleanType()),
        StructField("pulled_from", StringType()),
        StructField("base_and_all_options_value", StringType()),
        StructField("base_exercised_options_val", StringType()),
        StructField("black_american_owned_busin", BooleanType()),
        StructField("c1862_land_grant_college", BooleanType()),
        StructField("c1890_land_grant_college", BooleanType()),
        StructField("c1994_land_grant_college", BooleanType()),
        StructField("c8a_program_participant", BooleanType()),
        StructField("cage_code", StringType()),
        StructField("city_local_government", BooleanType()),
        StructField("clinger_cohen_act_planning", StringType()),
        StructField("clinger_cohen_act_pla_desc", StringType()),
        StructField("commercial_item_acqui_desc", StringType()),
        StructField("commercial_item_acquisitio", StringType()),
        StructField("commercial_item_test_progr", StringType()),
        StructField("commercial_item_test_desc", StringType()),
        StructField("community_developed_corpor", BooleanType()),
        StructField("community_development_corp", BooleanType()),
        StructField("consolidated_contract", StringType()),
        StructField("consolidated_contract_desc", StringType()),
        StructField("construction_wage_rat_desc", StringType()),
        StructField("construction_wage_rate_req", StringType()),
        StructField("contingency_humanitar_desc", StringType()),
        StructField("contingency_humanitarian_o", StringType()),
        StructField("contract_award_type", StringType()),
        StructField("contract_award_type_desc", StringType()),
        StructField("contract_bundling", StringType()),
        StructField("contract_bundling_descrip", StringType()),
        StructField("contract_financing", StringType()),
        StructField("contract_financing_descrip", StringType()),
        StructField("contracting_officers_desc", StringType()),
        StructField("contracting_officers_deter", StringType()),
        StructField("contracts", BooleanType()),
        StructField("corporate_entity_not_tax_e", BooleanType()),
        StructField("corporate_entity_tax_exemp", BooleanType()),
        StructField("cost_accounting_standards", StringType()),
        StructField("cost_accounting_stand_desc", StringType()),
        StructField("cost_or_pricing_data", StringType()),
        StructField("cost_or_pricing_data_desc", StringType()),
        StructField("council_of_governments", BooleanType()),
        StructField("country_of_product_or_serv", StringType()),
        StructField("country_of_product_or_desc", StringType()),
        StructField("county_local_government", BooleanType()),
        StructField("current_total_value_award", StringType()),
        StructField("program_system_or_equipmen", StringType()),
        StructField("program_system_or_equ_desc", StringType()),
        StructField("dod_claimant_program_code", StringType()),
        StructField("dod_claimant_prog_cod_desc", StringType()),
        StructField("domestic_or_foreign_entity", StringType()),
        StructField("domestic_or_foreign_e_desc", StringType()),
        StructField("domestic_shelter", BooleanType()),
        StructField("dot_certified_disadvantage", BooleanType()),
        StructField("economically_disadvantaged", BooleanType()),
        StructField("educational_institution", BooleanType()),
        StructField("emerging_small_business", BooleanType()),
        StructField("epa_designated_product", StringType()),
        StructField("epa_designated_produc_desc", StringType()),
        StructField("evaluated_preference", StringType()),
        StructField("evaluated_preference_desc", StringType()),
        StructField("extent_competed", StringType()),
        StructField("extent_compete_description", StringType()),
        StructField("fair_opportunity_limited_s", StringType()),
        StructField("fair_opportunity_limi_desc", StringType()),
        StructField("fed_biz_opps", StringType()),
        StructField("fed_biz_opps_description", StringType()),
        StructField("federal_agency", BooleanType()),
        StructField("federally_funded_research", BooleanType()),
        StructField("for_profit_organization", BooleanType()),
        StructField("foreign_funding", StringType()),
        StructField("foreign_funding_desc", StringType()),
        StructField("foreign_government", BooleanType()),
        StructField("foreign_owned_and_located", BooleanType()),
        StructField("foundation", BooleanType()),
        StructField("government_furnished_prope", StringType()),
        StructField("government_furnished_desc", StringType()),
        StructField("grants", BooleanType()),
        StructField("hispanic_american_owned_bu", BooleanType()),
        StructField("hispanic_servicing_institu", BooleanType()),
        StructField("historically_black_college", BooleanType()),
        StructField("historically_underutilized", BooleanType()),
        StructField("hospital_flag", BooleanType()),
        StructField("housing_authorities_public", BooleanType()),
        StructField("idv_type", StringType()),
        StructField("idv_type_description", StringType()),
        StructField("information_technology_com", StringType()),
        StructField("information_technolog_desc", StringType()),
        StructField("indian_tribe_federally_rec", BooleanType()),
        StructField("inherently_government_func", StringType()),
        StructField("inherently_government_desc", StringType()),
        StructField("inter_municipal_local_gove", BooleanType()),
        StructField("interagency_contracting_au", StringType()),
        StructField("interagency_contract_desc", StringType()),
        StructField("international_organization", BooleanType()),
        StructField("interstate_entity", BooleanType()),
        StructField("joint_venture_economically", BooleanType()),
        StructField("joint_venture_women_owned", BooleanType()),
        StructField("labor_standards", StringType()),
        StructField("labor_standards_descrip", StringType()),
        StructField("labor_surplus_area_firm", BooleanType()),
        StructField("limited_liability_corporat", BooleanType()),
        StructField("local_area_set_aside", StringType()),
        StructField("local_area_set_aside_desc", StringType()),
        StructField("local_government_owned", BooleanType()),
        StructField("major_program", StringType()),
        StructField("manufacturer_of_goods", BooleanType()),
        StructField("materials_supplies_article", StringType()),
        StructField("materials_supplies_descrip", StringType()),
        StructField("minority_institution", BooleanType()),
        StructField("minority_owned_business", BooleanType()),
        StructField("multi_year_contract", StringType()),
        StructField("multi_year_contract_desc", StringType()),
        StructField("multiple_or_single_award_i", StringType()),
        StructField("multiple_or_single_aw_desc", StringType()),
        StructField("municipality_local_governm", BooleanType()),
        StructField("naics_code", StringType()),
        StructField("naics_description", StringType()),
        StructField("national_interest_action", StringType()),
        StructField("national_interest_desc", StringType()),
        StructField("native_american_owned_busi", BooleanType()),
        StructField("native_hawaiian_owned_busi", BooleanType()),
        StructField("native_hawaiian_servicing", BooleanType()),
        StructField("nonprofit_organization", BooleanType()),
        StructField("number_of_actions", StringType()),
        StructField("number_of_offers_received", StringType()),
        StructField("organizational_type", StringType()),
        StructField("other_minority_owned_busin", BooleanType()),
        StructField("other_not_for_profit_organ", BooleanType()),
        StructField("other_statutory_authority", StringType()),
        StructField("other_than_full_and_open_c", StringType()),
        StructField("other_than_full_and_o_desc", StringType()),
        StructField("partnership_or_limited_lia", BooleanType()),
        StructField("performance_based_service", StringType()),
        StructField("performance_based_se_desc", StringType()),
        StructField("place_of_manufacture", StringType()),
        StructField("place_of_manufacture_desc", StringType()),
        StructField("planning_commission", BooleanType()),
        StructField("port_authority", BooleanType()),
        StructField("potential_total_value_awar", StringType()),
        StructField("price_evaluation_adjustmen", StringType()),
        StructField("private_university_or_coll", BooleanType()),
        StructField("program_acronym", StringType()),
        StructField("product_or_service_code", StringType()),
        StructField("product_or_service_description", StringType()),
        StructField("purchase_card_as_payment_m", StringType()),
        StructField("purchase_card_as_paym_desc", StringType()),
        StructField("recovered_materials_sustai", StringType()),
        StructField("recovered_materials_s_desc", StringType()),
        StructField("research", StringType()),
        StructField("research_description", StringType()),
        StructField("sam_exception", StringType()),
        StructField("sam_exception_description", StringType()),
        StructField("sba_certified_8_a_joint_ve", BooleanType()),
        StructField("school_district_local_gove", BooleanType()),
        StructField("school_of_forestry", BooleanType()),
        StructField("sea_transportation", StringType()),
        StructField("sea_transportation_desc", StringType()),
        StructField("self_certified_small_disad", BooleanType()),
        StructField("service_disabled_veteran_o", BooleanType()),
        StructField("small_agricultural_coopera", BooleanType()),
        StructField("small_business_competitive", BooleanType()),
        StructField("small_disadvantaged_busine", BooleanType()),
        StructField("sole_proprietorship", BooleanType()),
        StructField("solicitation_identifier", StringType()),
        StructField("state_controlled_instituti", BooleanType()),
        StructField("subchapter_s_corporation", BooleanType()),
        StructField("subcontinent_asian_asian_i", BooleanType()),
        StructField("subcontracting_plan", StringType()),
        StructField("subcontracting_plan_desc", StringType()),
        StructField("the_ability_one_program", BooleanType()),
        StructField("township_local_government", BooleanType()),
        StructField("transit_authority", BooleanType()),
        StructField("tribal_college", BooleanType()),
        StructField("tribally_owned_business", BooleanType()),
        StructField("type_of_contract_pricing", StringType()),
        StructField("type_of_contract_pric_desc", StringType()),
        StructField("type_of_idc", StringType()),
        StructField("type_of_idc_description", StringType()),
        StructField("type_set_aside", StringType()),
        StructField("type_set_aside_description", StringType()),
        StructField("undefinitized_action", StringType()),
        StructField("undefinitized_action_desc", StringType()),
        StructField("us_federal_government", BooleanType()),
        StructField("us_government_entity", BooleanType()),
        StructField("us_local_government", BooleanType()),
        StructField("us_state_government", BooleanType()),
        StructField("us_tribal_government", BooleanType()),
        StructField("veteran_owned_business", BooleanType()),
        StructField("veterinary_college", BooleanType()),
        StructField("veterinary_hospital", BooleanType()),
        StructField("woman_owned_business", BooleanType()),
        StructField("women_owned_small_business", BooleanType()),
    ]
)

transaction_download_schema = StructType(
    [
        *_common_schema,
        *_faba_agg_schema,
        *_fabs_specific_schema,
        *_fpds_specific_schema,
        StructField("merge_hash_key", LongType()),
    ]
)
