CREATE INDEX idx_47293de1$f21_generated_unique_award_id_temp ON subaward_view_temp USING BTREE(generated_unique_award_id) WITH (fillfactor = 97);
CREATE INDEX idx_47293de1$f21_ordered_subaward_number_temp ON subaward_view_temp USING BTREE(subaward_number DESC NULLS LAST) WITH (fillfactor = 97);
CREATE INDEX idx_47293de1$f21_ordered_piid_temp ON subaward_view_temp USING BTREE(UPPER(piid) DESC NULLS LAST) WITH (fillfactor = 97) WHERE piid IS NOT NULL;
CREATE INDEX idx_47293de1$f21_total_obl_bin_temp ON subaward_view_temp USING BTREE(total_obl_bin) WITH (fillfactor = 97);
CREATE INDEX idx_47293de1$f21_recipient_unique_id_temp ON subaward_view_temp USING BTREE(recipient_unique_id) WITH (fillfactor = 97) WHERE recipient_unique_id IS NOT NULL;
CREATE INDEX idx_47293de1$f21_last_modified_date_temp ON subaward_view_temp USING BTREE(last_modified_date DESC NULLS LAST) WITH (fillfactor = 97);
CREATE INDEX idx_47293de1$f21_funding_agency_id_temp ON subaward_view_temp USING BTREE(funding_agency_id ASC NULLS LAST) WITH (fillfactor = 97) WHERE funding_agency_id IS NOT NULL;
CREATE INDEX idx_47293de1$f21_awarding_toptier_agency_name_temp ON subaward_view_temp USING BTREE(awarding_toptier_agency_name) WITH (fillfactor = 97) WHERE awarding_toptier_agency_name IS NOT NULL;
CREATE INDEX idx_47293de1$f21_funding_subtier_agency_name_temp ON subaward_view_temp USING BTREE(funding_subtier_agency_name) WITH (fillfactor = 97) WHERE funding_subtier_agency_name IS NOT NULL;
CREATE INDEX idx_47293de1$f21_recipient_location_county_code_temp ON subaward_view_temp USING BTREE(recipient_location_county_code) WITH (fillfactor = 97) WHERE recipient_location_county_code IS NOT NULL;
CREATE INDEX idx_47293de1$f21_recipient_location_city_name_temp ON subaward_view_temp USING BTREE(recipient_location_city_name) WITH (fillfactor = 97) WHERE recipient_location_city_name IS NOT NULL;
CREATE INDEX idx_47293de1$f21_pop_county_code_temp ON subaward_view_temp USING BTREE(pop_county_code) WITH (fillfactor = 97) WHERE pop_county_code IS NOT NULL;
CREATE INDEX idx_47293de1$f21_pop_city_name_temp ON subaward_view_temp USING BTREE(pop_city_name) WITH (fillfactor = 97) WHERE pop_city_name IS NOT NULL;
CREATE INDEX idx_47293de1$f21_extent_competed_temp ON subaward_view_temp USING BTREE(extent_competed) WITH (fillfactor = 97) WHERE extent_competed IS NOT NULL;
CREATE INDEX idx_47293de1$f21_gin_product_or_service_description_temp ON subaward_view_temp USING GIN((product_or_service_description) gin_trgm_ops);
CREATE INDEX idx_47293de1$f21_award_ts_vector_temp ON subaward_view_temp USING GIN(award_ts_vector);
CREATE INDEX idx_47293de1$f21_compound_psc_action_date_temp ON subaward_view_temp USING BTREE(product_or_service_code, action_date) WITH (fillfactor = 97);
