# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-17 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtieragency',
            name='toptier',
        ),
        migrations.DeleteModel(
            name='SubtierAgency',
        ),
        migrations.DeleteModel(
            name='ToptierAgency',
        ),
    ]
