# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-07 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_auto_20190917_1750'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                migrations.CreateModel(
                    name='Agency',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('create_date', models.DateTimeField(auto_now_add=True)),
                        ('update_date', models.DateTimeField(auto_now=True)),
                        ('toptier_flag', models.BooleanField(default=False)),
                        ('user_selectable', models.BooleanField(default=False)),
                    ],
                    options={
                        'db_table': 'agency',
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                migrations.CreateModel(
                    name='SubtierAgency',
                    fields=[
                        ('subtier_agency_id', models.AutoField(primary_key=True, serialize=False)),
                        ('create_date', models.DateTimeField(auto_now_add=True)),
                        ('update_date', models.DateTimeField(auto_now=True)),
                        ('subtier_code', models.TextField(db_index=True, unique=True)),
                        ('abbreviation', models.TextField(blank=True, null=True)),
                        ('name', models.TextField(db_index=True)),
                    ],
                    options={
                        'db_table': 'subtier_agency',
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                migrations.CreateModel(
                    name='ToptierAgency',
                    fields=[
                        ('toptier_agency_id', models.AutoField(primary_key=True, serialize=False)),
                        ('create_date', models.DateTimeField(auto_now_add=True)),
                        ('update_date', models.DateTimeField(auto_now=True)),
                        ('cgac_code', models.TextField(db_index=True, unique=True)),
                        ('abbreviation', models.TextField(blank=True, null=True)),
                        ('name', models.TextField(db_index=True)),
                        ('mission', models.TextField(blank=True, null=True)),
                        ('website', models.URLField(blank=True, null=True)),
                        ('justification', models.URLField(blank=True, null=True)),
                        ('icon_filename', models.TextField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'toptier_agency',
                    },
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                migrations.AddField(
                    model_name='agency',
                    name='subtier_agency',
                    field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='agencies.SubtierAgency'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                migrations.AddField(
                    model_name='agency',
                    name='toptier_agency',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agencies.ToptierAgency'),
                ),
            ],
        ),
    ]
