# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccountsByProgramActivityObjectClass',
            fields=[
                ('financial_accounts_by_program_activity_object_class_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_activity_name', models.CharField(max_length=164)),
                ('by_direct_reimbursable_fun', models.CharField(max_length=1)),
                ('ussgl480100_undelivered_or_fyb', models.DecimalField(decimal_places=0, max_digits=21)),
                ('ussgl480100_undelivered_or_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('ussgl483100_undelivered_or_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('ussgl488100_upward_adjustm_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('ussgl490100_delivered_orde_fyb', models.DecimalField(decimal_places=0, max_digits=21)),
                ('ussgl490100_delivered_orde_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('ussgl493100_delivered_orde_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('ussgl498100_upward_adjustm_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('ussgl480200_undelivered_or_fyb', models.DecimalField(decimal_places=0, max_digits=21)),
                ('ussgl480200_undelivered_or_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('ussgl483200_undelivered_or_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('ussgl488200_upward_adjustm_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('ussgl490200_delivered_orde_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('ussgl490800_authority_outl_fyb', models.DecimalField(decimal_places=0, max_digits=21)),
                ('ussgl490800_authority_outl_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('ussgl498200_upward_adjustm_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('obligations_undelivered_or_fyb', models.DecimalField(decimal_places=0, max_digits=21)),
                ('obligations_undelivered_or_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('obligations_delivered_orde_fyb', models.DecimalField(decimal_places=0, max_digits=21)),
                ('obligations_delivered_orde_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('gross_outlays_undelivered_fyb', models.DecimalField(decimal_places=0, max_digits=21)),
                ('gross_outlays_undelivered_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('gross_outlays_delivered_or_fyb', models.DecimalField(decimal_places=0, max_digits=21)),
                ('gross_outlays_delivered_or_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('gross_outlay_amount_by_pro_fyb', models.DecimalField(decimal_places=0, max_digits=21)),
                ('gross_outlay_amount_by_pro_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('obligations_incurred_by_pr_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('ussgl487100_downward_adjus_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('ussgl497100_downward_adjus_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('ussgl487200_downward_adjus_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('ussgl497200_downward_adjus_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('deobligations_recov_by_pro_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('drv_obli_inc_by_prog_obj_class', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('drv_obligations_undel_ord_unp', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('reporting_period_start', models.DateField(blank=True, null=True)),
                ('reporting_period_end', models.DateField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('create_user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('update_user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('appropriation_account_balances', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.AppropriationAccountBalances')),
                ('object_class', models.ForeignKey(db_column='object_class', on_delete=django.db.models.deletion.DO_NOTHING, to='references.RefObjectClassCode')),
                ('program_activity_code', models.ForeignKey(db_column='program_activity_code', on_delete=django.db.models.deletion.DO_NOTHING, to='references.RefProgramActivity')),
            ],
            options={
                'db_table': 'financial_accounts_by_program_activity_object_class',
                'managed': True,
            },
        ),
    ]
