# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-29 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaccountsbyprogramactivityobjectclass',
            name='reporting_period_start',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
