# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialaccountsbyprogramactivityobjectclass',
            name='create_user_id',
        ),
        migrations.RemoveField(
            model_name='financialaccountsbyprogramactivityobjectclass',
            name='update_user_id',
        ),
        migrations.AlterField(
            model_name='financialaccountsbyprogramactivityobjectclass',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyprogramactivityobjectclass',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
