# Generated by Django 2.2.12 on 2020-05-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_activities', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TasProgramActivityObjectClassQuarterly',
        ),
    ]
