# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_activities', '0002_auto_20160915_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaccountsbyprogramactivityobjectclass',
            name='object_class',
            field=models.ForeignKey(db_column='object_class', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='references.RefObjectClassCode'),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyprogramactivityobjectclass',
            name='program_activity_code',
            field=models.ForeignKey(db_column='program_activity_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='references.RefProgramActivity'),
        ),
    ]
