# Generated by Django 2.2.24 on 2021-08-06 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_activities', '0004_remove_financialaccountsbyprogramactivityobjectclass_final_of_fy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaccountsbyprogramactivityobjectclass',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounts_by_program_activity_object_classes', to='submissions.SubmissionAttributes'),
        ),
    ]
