# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_activities', '0005_auto_20161004_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaccountsbyprogramactivityobjectclass',
            name='object_class',
            field=models.ForeignKey(db_column='object_class', on_delete=django.db.models.deletion.DO_NOTHING, to='references.RefObjectClassCode'),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyprogramactivityobjectclass',
            name='program_activity_code',
            field=models.ForeignKey(db_column='program_activity_code', on_delete=django.db.models.deletion.DO_NOTHING, to='references.RefProgramActivity'),
        ),
    ]
