# Generated by Django 3.2.25 on 2024-09-09 16:14

from django.db import migrations
from django.db import models

class Migration(migrations.Migration):

    dependencies = [
        ('financial_activities', '0008_auto_20211019_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaccountsbyprogramactivityobjectclass',
            name='data_source',
            field=models.TextField(
                choices=[
                    ('USA', 'USAspending'),
                    ('DBR', 'Data Broker')
                ],
                help_text='The source of this entry, either Data Broker (DBR) or USASpending (USA)',
                null=True,
            ),
        ),
    ]