# Generated by Django 3.2.25 on 2024-10-18 15:26
from pathlib import Path

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_activities', '0009_rename_column_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccountsbyprogramactivityobjectclass',
            name='pa_reporting_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialaccountsbyprogramactivityobjectclass',
            name='prior_year_adjustment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialaccountsbyprogramactivityobjectclass',
            name='ussgl480110_reinstated_del_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='financialaccountsbyprogramactivityobjectclass',
            name='ussgl490110_reinstated_del_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),
        # Update the download view to include the new columns
        migrations.RunSQL(
            sql=[f"{Path('usaspending_api/download/sql/vw_financial_accounts_by_program_activity_object_class_download.sql').read_text()}"],
        ),
    ]
