# Generated by Django 4.2.17 on 2024-12-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_activities", "0010_auto_20241018_1526"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialaccountsbyprogramactivityobjectclass",
            name="pa_reporting_key",
            field=models.TextField(blank=True, help_text="A unique identifier for a Program Activity", null=True),
        ),
    ]
