# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20170209_1753'),
        ('financial_activities', '0011_auto_20161129_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccountsbyprogramactivityobjectclass',
            name='treasury_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_balances', to='accounts.TreasuryAppropriationAccount'),
        ),
    ]
