# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_activities', '0012_financialaccountsbyprogramactivityobjectclass_treasury_account'),
    ]

    operations = [
        migrations.RunSQL("UPDATE financial_accounts_by_program_activity_object_class SET treasury_account_id = (SELECT treasury_account_identifier FROM appropriation_account_balances WHERE financial_accounts_by_program_activity_object_class.appropriation_account_balances_id=appropriation_account_balances.appropriation_account_balances_id)"),
    ]
