# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-09 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_activities', '0013_auto_20170209_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialaccountsbyprogramactivityobjectclass',
            name='appropriation_account_balances',
        ),
    ]
