# Generated by Django 4.2.23 on 2025-08-06 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0070_programactivitypark"),
        ("financial_activities", "0013_delete_old_park_columns_fabpaoc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialaccountsbyprogramactivityobjectclass",
            name="program_activity_reporting_key",
            field=models.ForeignKey(
                blank=True,
                db_column="program_activity_reporting_key",
                help_text="A unique identifier for a Program Activity",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="references.programactivitypark",
            ),
        ),
    ]
