# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-17 18:07
from __future__ import unicode_literals

from django.db import migrations
from usaspending_api.financial_activities.sql_model_defs import sql


class Migration(migrations.Migration):

    dependencies = [(
        'financial_activities',
        '0014_remove_financialaccountsbyprogramactivityobjectclass_appropriation_account_balances'
    ), ]

    operations = [migrations.RunSQL(forward, rev) for (rev, forward) in sql]
