# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-20 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_activities', '0014_remove_financialaccountsbyprogramactivityobjectclass_appropriation_account_balances'),
    ]

    operations = [
        # Rename the existing object_class field. Using raw SQL to do this
        # because the RenameField migration operation didn't work (possibly
        # because the model column/FK reference didn't follow typical Django
        # standard naming pattern)
        migrations.RunSQL(
            'ALTER TABLE financial_accounts_by_program_activity_object_class RENAME COLUMN object_class TO object_class_old',
            migrations.RunSQL.noop),
        # create a new object_class column that points to the new object class model
        migrations.AddField(
            model_name='FinancialAccountsByProgramActivityObjectClass',
            name='object_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='references.ObjectClass'),
        ),
        # create a new program_activity column that points to the new object class model
        migrations.AddField(
            model_name='FinancialAccountsByProgramActivityObjectClass',
            name='program_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='references.RefProgramActivity'),
        ),
    ]
