# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-20 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_activities', '0021_auto_20170405_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccountsbyprogramactivityobjectclass',
            name='final_of_fy',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
