state_codes = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Northern Mariana Islands": "MP",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "Puerto Rico": "PR",
    "U.S. Virgin Islands": "VI",
    "American Samoa": "AS",
    "Guam": "GU",
    "U.S. Minor Outlying Islands": "UM",
}


country_codes = [
    {"code": "AFG", "name": "AFGHANISTAN"},
    {"code": "XQZ", "name": "AKROTIRI"},
    {"code": "ALB", "name": "ALBANIA"},
    {"code": "DZA", "name": "ALGERIA"},
    {"code": "AND", "name": "ANDORRA"},
    {"code": "AGO", "name": "ANGOLA"},
    {"code": "AIA", "name": "ANGUILLA"},
    {"code": "ATA", "name": "ANTARCTICA"},
    {"code": "ATG", "name": "ANTIGUA AND BARBUDA"},
    {"code": "ARG", "name": "ARGENTINA"},
    {"code": "ARM", "name": "ARMENIA"},
    {"code": "ABW", "name": "ARUBA"},
    {"code": "XAC", "name": "ASHMORE AND CARTIER ISLANDS"},
    {"code": "AUS", "name": "AUSTRALIA"},
    {"code": "AUT", "name": "AUSTRIA"},
    {"code": "AZE", "name": "AZERBAIJAN"},
    {"code": "BHS", "name": "BAHAMAS, THE"},
    {"code": "BHR", "name": "BAHRAIN"},
    {"code": "XBK", "name": "BAKER ISLAND"},
    {"code": "BGD", "name": "BANGLADESH"},
    {"code": "BRB", "name": "BARBADOS"},
    {"code": "XBI", "name": "BASSAS DA INDIA"},
    {"code": "BLR", "name": "BELARUS"},
    {"code": "BEL", "name": "BELGIUM"},
    {"code": "BLZ", "name": "BELIZE"},
    {"code": "BEN", "name": "BENIN"},
    {"code": "BMU", "name": "BERMUDA"},
    {"code": "BTN", "name": "BHUTAN"},
    {"code": "BOL", "name": "BOLIVIA"},
    {"code": "BES", "name": "BONAIRE, SINT EUSTATIUS, AND SABA"},
    {"code": "BIH", "name": "BOSNIA AND HERZEGOVINA"},
    {"code": "BWA", "name": "BOTSWANA"},
    {"code": "BVT", "name": "BOUVET ISLAND"},
    {"code": "BRA", "name": "BRAZIL"},
    {"code": "IOT", "name": "BRITISH INDIAN OCEAN TERRITORY"},
    {"code": "BRN", "name": "BRUNEI"},
    {"code": "BGR", "name": "BULGARIA"},
    {"code": "BFA", "name": "BURKINA FASO"},
    {"code": "MMR", "name": "BURMA"},
    {"code": "BDI", "name": "BURUNDI"},
    {"code": "CPV", "name": "CABO VERDE"},
    {"code": "KHM", "name": "CAMBODIA"},
    {"code": "CMR", "name": "CAMEROON"},
    {"code": "CAN", "name": "CANADA"},
    {"code": "CYM", "name": "CAYMAN ISLANDS"},
    {"code": "CAF", "name": "CENTRAL AFRICAN REPUBLIC"},
    {"code": "TCD", "name": "CHAD"},
    {"code": "CHL", "name": "CHILE"},
    {"code": "CHN", "name": "CHINA"},
    {"code": "CXR", "name": "CHRISTMAS ISLAND"},
    {"code": "CPT", "name": "CLIPPERTON ISLAND"},
    {"code": "CCK", "name": "COCOS (KEELING) ISLANDS"},
    {"code": "COL", "name": "COLOMBIA"},
    {"code": "COM", "name": "COMOROS"},
    {"code": "COG", "name": "CONGO (BRAZZAVILLE)"},
    {"code": "COD", "name": "CONGO (KINSHASA)"},
    {"code": "COK", "name": "COOK ISLANDS"},
    {"code": "XCS", "name": "CORAL SEA ISLANDS"},
    {"code": "CRI", "name": "COSTA RICA"},
    {"code": "CIV", "name": "CÔTE D’IVOIRE"},
    {"code": "HRV", "name": "CROATIA"},
    {"code": "CUB", "name": "CUBA"},
    {"code": "CUW", "name": "CURAÇAO"},
    {"code": "CYP", "name": "CYPRUS"},
    {"code": "CZE", "name": "CZECH REPUBLIC"},
    {"code": "DNK", "name": "DENMARK"},
    {"code": "XXD", "name": "DHEKELIA"},
    {"code": "DGA", "name": "DIEGO GARCIA"},
    {"code": "DJI", "name": "DJIBOUTI"},
    {"code": "DMA", "name": "DOMINICA"},
    {"code": "DOM", "name": "DOMINICAN REPUBLIC"},
    {"code": "ECU", "name": "ECUADOR"},
    {"code": "EGY", "name": "EGYPT"},
    {"code": "SLV", "name": "EL SALVADOR"},
    {"code": "GNQ", "name": "EQUATORIAL GUINEA"},
    {"code": "ERI", "name": "ERITREA"},
    {"code": "EST", "name": "ESTONIA"},
    {"code": "ETH", "name": "ETHIOPIA"},
    {"code": "XEU", "name": "EUROPA ISLAND"},
    {"code": "FLK", "name": "FALKLAND ISLANDS (ISLAS MALVINAS)"},
    {"code": "FRO", "name": "FAROE ISLANDS"},
    {"code": "FJI", "name": "FIJI"},
    {"code": "FIN", "name": "FINLAND"},
    {"code": "FRA", "name": "FRANCE"},
    {"code": "GUF", "name": "FRENCH GUIANA"},
    {"code": "PYF", "name": "FRENCH POLYNESIA"},
    {"code": "ATF", "name": "FRENCH SOUTHERN AND ANTARCTIC LANDS"},
    {"code": "GAB", "name": "GABON"},
    {"code": "GMB", "name": "GAMBIA, THE"},
    {"code": "XGZ", "name": "GAZA STRIP"},
    {"code": "GEO", "name": "GEORGIA"},
    {"code": "DEU", "name": "GERMANY"},
    {"code": "GHA", "name": "GHANA"},
    {"code": "GIB", "name": "GIBRALTAR"},
    {"code": "XGL", "name": "GLORIOSO ISLANDS"},
    {"code": "GRC", "name": "GREECE"},
    {"code": "GRL", "name": "GREENLAND"},
    {"code": "GRD", "name": "GRENADA"},
    {"code": "GLP", "name": "GUADELOUPE"},
    {"code": "AX2", "name": "GUANTANAMO BAY NAVAL BASE"},
    {"code": "GTM", "name": "GUATEMALA"},
    {"code": "GGY", "name": "GUERNSEY"},
    {"code": "GIN", "name": "GUINEA"},
    {"code": "GNB", "name": "GUINEA-BISSAU"},
    {"code": "GUY", "name": "GUYANA"},
    {"code": "HTI", "name": "HAITI"},
    {"code": "HMD", "name": "HEARD ISLAND AND MCDONALD ISLANDS"},
    {"code": "HND", "name": "HONDURAS"},
    {"code": "HKG", "name": "HONG KONG"},
    {"code": "XHO", "name": "HOWLAND ISLAND"},
    {"code": "HUN", "name": "HUNGARY"},
    {"code": "ISL", "name": "ICELAND"},
    {"code": "IND", "name": "INDIA"},
    {"code": "IDN", "name": "INDONESIA"},
    {"code": "IRN", "name": "IRAN"},
    {"code": "IRQ", "name": "IRAQ"},
    {"code": "IRL", "name": "IRELAND"},
    {"code": "IMN", "name": "ISLE OF MAN"},
    {"code": "ISR", "name": "ISRAEL"},
    {"code": "ITA", "name": "ITALY"},
    {"code": "JAM", "name": "JAMAICA"},
    {"code": "XJM", "name": "JAN MAYEN"},
    {"code": "JPN", "name": "JAPAN"},
    {"code": "XJV", "name": "JARVIS ISLAND"},
    {"code": "JEY", "name": "JERSEY"},
    {"code": "XJA", "name": "JOHNSTON ATOLL"},
    {"code": "JOR", "name": "JORDAN"},
    {"code": "XJN", "name": "JUAN DE NOVA ISLAND"},
    {"code": "KAZ", "name": "KAZAKHSTAN"},
    {"code": "KEN", "name": "KENYA"},
    {"code": "XKR", "name": "KINGMAN REEF"},
    {"code": "KIR", "name": "KIRIBATI"},
    {"code": "PRK", "name": "KOREA, NORTH"},
    {"code": "KOR", "name": "KOREA, SOUTH"},
    {"code": "XKS", "name": "KOSOVO"},
    {"code": "KWT", "name": "KUWAIT"},
    {"code": "KGZ", "name": "KYRGYZSTAN"},
    {"code": "LAO", "name": "LAOS"},
    {"code": "LVA", "name": "LATVIA"},
    {"code": "LBN", "name": "LEBANON"},
    {"code": "LSO", "name": "LESOTHO"},
    {"code": "LBR", "name": "LIBERIA"},
    {"code": "LBY", "name": "LIBYA"},
    {"code": "LIE", "name": "LIECHTENSTEIN"},
    {"code": "LTU", "name": "LITHUANIA"},
    {"code": "LUX", "name": "LUXEMBOURG"},
    {"code": "MAC", "name": "MACAU"},
    {"code": "MKD", "name": "MACEDONIA"},
    {"code": "MDG", "name": "MADAGASCAR"},
    {"code": "MWI", "name": "MALAWI"},
    {"code": "MYS", "name": "MALAYSIA"},
    {"code": "MDV", "name": "MALDIVES"},
    {"code": "MLI", "name": "MALI"},
    {"code": "MLT", "name": "MALTA"},
    {"code": "MTQ", "name": "MARTINIQUE"},
    {"code": "MRT", "name": "MAURITANIA"},
    {"code": "MUS", "name": "MAURITIUS"},
    {"code": "MYT", "name": "MAYOTTE"},
    {"code": "MEX", "name": "MEXICO"},
    {"code": "XMW", "name": "MIDWAY ISLANDS"},
    {"code": "MDA", "name": "MOLDOVA"},
    {"code": "MCO", "name": "MONACO"},
    {"code": "MNG", "name": "MONGOLIA"},
    {"code": "MNE", "name": "MONTENEGRO"},
    {"code": "MSR", "name": "MONTSERRAT"},
    {"code": "MAR", "name": "MOROCCO"},
    {"code": "MOZ", "name": "MOZAMBIQUE"},
    {"code": "NAM", "name": "NAMIBIA"},
    {"code": "NRU", "name": "NAURU"},
    {"code": "XNV", "name": "NAVASSA ISLAND"},
    {"code": "NPL", "name": "NEPAL"},
    {"code": "NLD", "name": "NETHERLANDS"},
    {"code": "NCL", "name": "NEW CALEDONIA"},
    {"code": "NZL", "name": "NEW ZEALAND"},
    {"code": "NIC", "name": "NICARAGUA"},
    {"code": "NER", "name": "NIGER"},
    {"code": "NGA", "name": "NIGERIA"},
    {"code": "NIU", "name": "NIUE"},
    {"code": "NFK", "name": "NORFOLK ISLAND"},
    {"code": "NOR", "name": "NORWAY"},
    {"code": "OMN", "name": "OMAN"},
    {"code": "PAK", "name": "PAKISTAN"},
    {"code": "PSE", "name": "PALESTINE, STATE OF"},
    {"code": "XPL", "name": "PALMYRA ATOLL"},
    {"code": "PAN", "name": "PANAMA"},
    {"code": "PNG", "name": "PAPUA NEW GUINEA"},
    {"code": "XPR", "name": "PARACEL ISLANDS"},
    {"code": "PRY", "name": "PARAGUAY"},
    {"code": "PER", "name": "PERU"},
    {"code": "PHL", "name": "PHILIPPINES"},
    {"code": "PCN", "name": "PITCAIRN ISLANDS"},
    {"code": "POL", "name": "POLAND"},
    {"code": "PRT", "name": "PORTUGAL"},
    {"code": "QAT", "name": "QATAR"},
    {"code": "REU", "name": "REUNION"},
    {"code": "ROU", "name": "ROMANIA"},
    {"code": "RUS", "name": "RUSSIA"},
    {"code": "RWA", "name": "RWANDA"},
    {"code": "BLM", "name": "SAINT BARTHELEMY"},
    {"code": "SHN", "name": "SAINT HELENA, ASCENSION, AND TRISTAN DA CUNHA"},
    {"code": "KNA", "name": "SAINT KITTS AND NEVIS"},
    {"code": "LCA", "name": "SAINT LUCIA"},
    {"code": "MAF", "name": "SAINT MARTIN"},
    {"code": "SPM", "name": "SAINT PIERRE AND MIQUELON"},
    {"code": "VCT", "name": "SAINT VINCENT AND THE GRENADINES"},
    {"code": "WSM", "name": "SAMOA"},
    {"code": "SMR", "name": "SAN MARINO"},
    {"code": "STP", "name": "SAO TOME AND PRINCIPE"},
    {"code": "SAU", "name": "SAUDI ARABIA"},
    {"code": "SEN", "name": "SENEGAL"},
    {"code": "SRB", "name": "SERBIA"},
    {"code": "SYC", "name": "SEYCHELLES"},
    {"code": "SLE", "name": "SIERRA LEONE"},
    {"code": "SGP", "name": "SINGAPORE"},
    {"code": "SXM", "name": "SINT MAARTEN"},
    {"code": "SVK", "name": "SLOVAKIA"},
    {"code": "SVN", "name": "SLOVENIA"},
    {"code": "SLB", "name": "SOLOMON ISLANDS"},
    {"code": "SOM", "name": "SOMALIA"},
    {"code": "ZAF", "name": "SOUTH AFRICA"},
    {"code": "SGS", "name": "SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS"},
    {"code": "SSD", "name": "SOUTH SUDAN"},
    {"code": "ESP", "name": "SPAIN"},
    {"code": "XSP", "name": "SPRATLY ISLANDS"},
    {"code": "LKA", "name": "SRI LANKA"},
    {"code": "SDN", "name": "SUDAN"},
    {"code": "SUR", "name": "SURINAME"},
    {"code": "XSV", "name": "SVALBARD"},
    {"code": "SWZ", "name": "SWAZILAND"},
    {"code": "SWE", "name": "SWEDEN"},
    {"code": "CHE", "name": "SWITZERLAND"},
    {"code": "SYR", "name": "SYRIA"},
    {"code": "TWN", "name": "TAIWAN"},
    {"code": "TJK", "name": "TAJIKISTAN"},
    {"code": "TZA", "name": "TANZANIA"},
    {"code": "THA", "name": "THAILAND"},
    {"code": "TLS", "name": "TIMOR-LESTE"},
    {"code": "TGO", "name": "TOGO"},
    {"code": "TKL", "name": "TOKELAU"},
    {"code": "TON", "name": "TONGA"},
    {"code": "TTO", "name": "TRINIDAD AND TOBAGO"},
    {"code": "XTR", "name": "TROMELIN ISLAND"},
    {"code": "TUN", "name": "TUNISIA"},
    {"code": "TUR", "name": "TURKEY"},
    {"code": "TKM", "name": "TURKMENISTAN"},
    {"code": "TCA", "name": "TURKS AND CAICOS ISLANDS"},
    {"code": "TUV", "name": "TUVALU"},
    {"code": "UGA", "name": "UGANDA"},
    {"code": "UKR", "name": "UKRAINE"},
    {"code": "ARE", "name": "UNITED ARAB EMIRATES"},
    {"code": "GBR", "name": "UNITED KINGDOM"},
    {"code": "AX1", "name": "UNKNOWN"},
    {"code": "URY", "name": "URUGUAY"},
    {"code": "UZB", "name": "UZBEKISTAN"},
    {"code": "VUT", "name": "VANUATU"},
    {"code": "VAT", "name": "VATICAN CITY"},
    {"code": "VEN", "name": "VENEZUELA"},
    {"code": "VNM", "name": "VIETNAM"},
    {"code": "VGB", "name": "VIRGIN ISLANDS, BRITISH"},
    {"code": "XWK", "name": "WAKE ISLAND"},
    {"code": "WLF", "name": "WALLIS AND FUTUNA"},
    {"code": "XWB", "name": "WEST BANK"},
    {"code": "ESH", "name": "WESTERN SAHARA"},
    {"code": "YEM", "name": "YEMEN"},
    {"code": "ZMB", "name": "ZAMBIA"},
    {"code": "ZWE", "name": "ZIMBABWE"},
    {"code": "USA", "name": "UNITED STATES"},
]
