DROP VIEW IF EXISTS subaward_es_view;

CREATE VIEW subaward_es_view AS
SELECT
	broker_subaward_id,
	unique_award_key,
	award_piid_fain,
	parent_award_id,
	award_id,
	award_amount,
	action_date,
	fy,
	awarding_agency_id,
	awarding_agency_name,
	awarding_agency_code,
	awarding_office_name,
	awarding_office_code,
	awarding_subtier_agency_name,
	awarding_subtier_agency_abbreviation,
	awarding_sub_tier_agency_c AS awarding_subtier_agency_code,
	funding_agency_id,
	funding_agency_name,
	funding_agency_code,
	funding_office_name,
	funding_office_code,
	funding_subtier_agency_name,
	funding_subtier_agency_abbreviation,
	funding_sub_tier_agency_co AS funding_subtier_agency_code,
	awardee_or_recipient_uniqu,
	awardee_or_recipient_uei,
	awardee_or_recipient_legal,
	dba_name,
	ultimate_parent_unique_ide,
	ultimate_parent_uei,
	ultimate_parent_legal_enti,
	legal_entity_country_code AS recipient_location_country_code,
	legal_entity_country_name AS recipient_location_country_name,
	legal_entity_state_code AS recipient_location_state_code,
	legal_entity_state_name AS recipient_location_state_name,
	legal_entity_zip AS recipient_location_zip,
	legal_entity_foreign_posta AS recipient_location_foreign_posta,
	legal_entity_city_name AS recipient_location_city_name,
	legal_entity_congressional AS recipient_location_congressional_code,
	legal_entity_congressional_current AS recipient_location_congressional_code_current,
	business_types,
	place_of_perform_country_co AS pop_country_code,
	place_of_perform_country_na AS pop_country_name,
	place_of_perform_state_code AS pop_state_code,
	place_of_perform_state_name AS pop_state_name,
	place_of_performance_zip AS pop_zip,
	place_of_perform_city_name AS pop_city_name,
	place_of_perform_street AS pop_street,
	place_of_perform_congressio AS pop_congressional_code,
	place_of_performance_congressional_current AS pop_congressional_code_current,
	award_description,
	naics,
	naics_description,
	cfda_numbers,
	cfda_titles,
	subaward_type,
	subaward_report_year,
	subaward_report_month,
	subaward_number,
	subaward_amount,
	sub_action_date,
	sub_awardee_or_recipient_uniqu,
	sub_awardee_or_recipient_uei,
	sub_awardee_or_recipient_legal,
	sub_dba_name,
	sub_legal_entity_country_code AS sub_recipient_location_country_code,
	sub_legal_entity_country_name AS sub_recipient_location_country_name,
	sub_legal_entity_state_code AS sub_recipient_location_state_code,
	sub_legal_entity_state_name AS sub_recipient_location_state_name,
	sub_legal_entity_zip AS sub_recipient_location_zip,
	sub_legal_entity_congressional AS sub_recipient_location_congressional_code,
	sub_legal_entity_congressional_current AS sub_recipient_location_congressional_code_current,
	sub_legal_entity_foreign_posta AS sub_recipient_location_foreign_posta,
	sub_legal_entity_city_name AS sub_recipient_location_city_name,
	sub_business_types,
	sub_place_of_perform_country_co AS sub_pop_country_code,
	sub_place_of_perform_country_name AS sub_pop_country_name,
	sub_place_of_perform_state_code AS sub_pop_state_code,
	sub_place_of_perform_state_name AS sub_pop_state_name,
	sub_place_of_performance_zip AS sub_pop_zip,
	sub_place_of_perform_congressio AS sub_pop_congressional_code,
	sub_place_of_performance_congressional_current AS sub_pop_congressional_code_current,
	sub_place_of_perform_city_name AS sub_pop_city_name,
	sub_place_of_perform_street AS sub_pop_street,
	subaward_description,
	prime_award_group,
	prime_award_type,
	latest_transaction_id,
	last_modified_date,
	awarding_toptier_agency_name,
	awarding_toptier_agency_abbreviation,
	funding_toptier_agency_name,
	funding_toptier_agency_abbreviation,
	sub_fiscal_year,
	business_categories,
	type_of_contract_pricing,
	type_set_aside,
	extent_competed,
	product_or_service_code,
	product_or_service_description,
    treasury_account_identifiers
FROM
	rpt.subaward_search
WHERE action_date >= '2007-10-01';