DROP VIEW IF EXISTS subaward_es_view;

CREATE VIEW subaward_es_view AS
SELECT
	s.broker_subaward_id,
	s.unique_award_key,
	s.award_piid_fain,
	s.parent_award_id,
	s.award_id,
    a.display_award_id,
	s.award_amount,
	s.action_date,
	s.fy,
	s.awarding_agency_id,
	s.awarding_agency_name,
	s.awarding_agency_code,
	s.awarding_office_name,
	s.awarding_office_code,
	s.awarding_subtier_agency_name,
	s.awarding_subtier_agency_abbreviation,
	s.awarding_sub_tier_agency_c AS awarding_subtier_agency_code,
	s.funding_agency_id,
	s.funding_agency_name,
	s.funding_agency_code,
	s.funding_office_name,
	s.funding_office_code,
	s.funding_subtier_agency_name,
	s.funding_subtier_agency_abbreviation,
	s.funding_sub_tier_agency_co AS funding_subtier_agency_code,
	s.awardee_or_recipient_uniqu,
	s.awardee_or_recipient_uei,
	s.awardee_or_recipient_legal,
	s.dba_name,
	s.ultimate_parent_unique_ide,
	s.ultimate_parent_uei,
	s.ultimate_parent_legal_enti,
	s.legal_entity_country_code AS recipient_location_country_code,
	s.legal_entity_country_name AS recipient_location_country_name,
	s.legal_entity_state_code AS recipient_location_state_code,
	s.legal_entity_state_name AS recipient_location_state_name,
	s.legal_entity_zip AS recipient_location_zip,
	s.legal_entity_foreign_posta AS recipient_location_foreign_posta,
	s.legal_entity_city_name AS recipient_location_city_name,
	s.legal_entity_congressional AS recipient_location_congressional_code,
	s.legal_entity_congressional_current AS recipient_location_congressional_code_current,
	s.business_types,
	s.place_of_perform_country_co AS pop_country_code,
	s.place_of_perform_country_na AS pop_country_name,
	s.place_of_perform_state_code AS pop_state_code,
	s.place_of_perform_state_name AS pop_state_name,
	s.place_of_performance_zip AS pop_zip,
	s.place_of_perform_city_name AS pop_city_name,
	s.place_of_perform_street AS pop_street,
	s.place_of_perform_congressio AS pop_congressional_code,
	s.place_of_performance_congressional_current AS pop_congressional_code_current,
	s.award_description,
	s.naics,
	s.naics_description,
	s.cfda_numbers as cfda_number,
	s.cfda_titles,
	s.subaward_type,
	s.subaward_report_year,
	s.subaward_report_month,
	s.subaward_number,
	s.subaward_amount,
	s.sub_action_date,
	s.sub_awardee_or_recipient_uniqu,
	s.sub_awardee_or_recipient_uei,
	s.sub_awardee_or_recipient_legal,
	s.sub_dba_name,
	s.sub_legal_entity_country_code AS sub_recipient_location_country_code,
	s.sub_legal_entity_country_name AS sub_recipient_location_country_name,
	s.sub_legal_entity_state_code AS sub_recipient_location_state_code,
	s.sub_legal_entity_state_name AS sub_recipient_location_state_name,
    s.sub_legal_entity_county_code AS sub_recipient_location_county_code,
    s.sub_legal_entity_zip5 AS sub_recipient_location_zip5,
	s.sub_legal_entity_zip AS sub_recipient_location_zip,
	s.sub_legal_entity_congressional AS sub_recipient_location_congressional_code,
	s.sub_legal_entity_congressional_current AS sub_recipient_location_congressional_code_current,
	s.sub_legal_entity_foreign_posta AS sub_recipient_location_foreign_posta,
	s.sub_legal_entity_city_name AS sub_recipient_location_city_name,
	s.sub_legal_entity_county_name AS sub_recipient_location_county_name,
	s.sub_legal_entity_address_line1 AS sub_recipient_location_address_line1,
	s.sub_business_types,
	s.sub_place_of_perform_country_co AS sub_pop_country_code,
	s.sub_place_of_perform_country_name AS sub_pop_country_name,
	s.sub_place_of_perform_state_code AS sub_pop_state_code,
	s.sub_place_of_perform_state_name AS sub_pop_state_name,
    s.sub_place_of_perform_county_code AS sub_pop_county_code,
	s.sub_place_of_performance_zip AS sub_pop_zip,
	s.sub_place_of_perform_congressio AS sub_pop_congressional_code,
	s.sub_place_of_performance_congressional_current AS sub_pop_congressional_code_current,
	s.sub_place_of_perform_city_name AS sub_pop_city_name,
	s.sub_place_of_perform_street AS sub_pop_street,
	s.sub_place_of_perform_county_name AS sub_pop_county_name,
	s.subaward_description,
	-- Keywords have a byte limit in elasticsearch that subaward_description was exceeding when sorting
	LEFT(s.subaward_description, 8190) AS subaward_description_sort,
	s.prime_award_group,
	s.prime_award_type,
	s.latest_transaction_id,
	s.last_modified_date,
	s.awarding_toptier_agency_name,
	s.awarding_toptier_agency_abbreviation,
	s.funding_toptier_agency_name,
	s.funding_toptier_agency_abbreviation,
	s.sub_fiscal_year,
	s.business_categories,
	s.type_of_contract_pricing,
	s.type_set_aside,
	s.extent_competed,
	s.product_or_service_code,
	s.product_or_service_description,
    s.treasury_account_identifiers,
    s.sub_ultimate_parent_unique_ide,
    s.sub_ultimate_parent_uei,
    a.disaster_emergency_fund_codes,
    a.recipient_hash,
    a.parent_uei,
    s.program_activities::JSON,
    s.prime_award_recipient_id,
    a.tas_paths,
    a.tas_components,
    s.subaward_recipient_hash,
    s.subaward_recipient_level,
    s.awarding_toptier_agency_code,
    s.funding_toptier_agency_code
FROM
	rpt.subaward_search s
LEFT JOIN rpt.award_search a
    ON s.award_id = a.award_id
WHERE s.action_date >= '2007-10-01';