from collections import OrderedDict

"""
Sets up mappings from column names used in downloads to the query paths used to get the data from django.

Not in use while we pull CSV data from the non-historical tables. Until we switch to pulling CSV downloads from the
historical tables TransactionFPDS and TransactionFABS, import download_column_lookups.py instead.
"""
"""
Code to generate these from spreadsheets:

tail -n +3 'usaspending_api/data/DAIMS_IDD_Resorted+DRW+KB+GGv7/D2-Award (Financial Assistance)-Table 1.csv' >
d2_columns.csv


def find_column(col_name, model_classes):
    for (model_class, prefix) in model_classes:
        if hasattr(model_class, col_name):
            return '{}{}'.format(prefix, col_name)
    return None

query_paths = {'transaction': {'d1': {}, 'd2': {}}, 'award': {'d1': {}, 'd2': {}}}
human_names = {'transaction': {'d1': [], 'd2': []}, 'award': {'d1': [], 'd2': []}}

models_award_d1 = ((Award, ''), (TransactionNormalized, 'latest_transaction__'),
                    (TransactionFPDS, 'latest_transaction__contract_data__'))
models_transaction_d1 = ((TransactionNormalized, ''), (TransactionFPDS, 'contract_data__'), (Award, 'award__'))
models_award_d2 = ((Award, ''), (TransactionNormalized, 'latest_transaction__'),
                    (TransactionFABS, 'latest_transaction__assistance_data__'))
models_transaction_d2 = ((TransactionNormalized, ''), (TransactionFABS, 'assistance_data__'), (Award, 'award__'))

def set_if_found(dl_name, path, model, file):
    if path:
        if dl_name in ('fain', 'piid', 'uri'):
            dl_name = 'award_id_' + dl_name
        query_paths[model][file][dl_name] = path
        human_names[model][file].append(dl_name)
    else:
        print('Not found: {}: {}: {}'.format(model, file, dl_name))

for row in d1:
    if len(row['Download Name']) <= 1:
        continue
    if len(row['Database Tag']) <= 1:
        continue
    if row['Award Level'] == 'Y':
        path = find_column(row['Database Tag'], models_award_d1)
        set_if_found(row['Download Name'], path, 'award', 'd1')
    if row['Transaction Level'] == 'Y':
        path = find_column(row['Database Tag'], models_transaction_d1)
        set_if_found(row['Download Name'], path, 'transaction', 'd1')

# no database tags supplied for d2
for row in d2:
    if len(row['Download Name']) <= 1:
        continue
    if row['Award Level?'] == 'Y':
        path = find_column(row['Download Name'], models_award_d2)
        if not path:
            # try what it was for D1
            path = query_paths['award']['d1'].get(row['Download Name'])
            if path:
                col_name = path.split('__')[-1]
                path = find_column(col_name, models_award_d2)
        set_if_found(row['Download Name'], path, 'award', 'd2')
    if row['Transaction Level?'] == 'Y':
        path = find_column(row['Download Name'], models_transaction_d2)
        if not path:
            # try what it was for D1
            path = query_paths['transaction']['d1'].get(row['Download Name'])
            if path:
                col_name = path.split('__')[-1]
                path = find_column(col_name, models_transaction_d2)
        set_if_found(row['Download Name'], path, 'transaction', 'd2')
"""

query_paths = {
    'award': {
        'd1': OrderedDict([
            ('award_id_piid', 'award__piid'),
            ('parent_award_agency_id', 'award__latest_transaction__contract_data__referenced_idv_agency_iden'),
            ('parent_award_agency_name', 'award__latest_transaction__contract_data__referenced_idv_agency_desc'),
            ('parent_award_id', 'award__parent_award_piid'),
            ('obligated_amount', 'award__total_obligation'),
            ('period_of_performance_start_date',
             'award__latest_transaction__contract_data__period_of_performance_star'),
            ('period_of_performance_current_end_date',
             'award__latest_transaction__contract_data__period_of_performance_curr'),
            ('period_of_performance_potential_end_date',
             'award__latest_transaction__contract_data__period_of_perf_potential_e'),
            ('ordering_period_end_date', 'award__latest_transaction__contract_data__ordering_period_end_date'),
            ('awarding_agency_code', 'award__latest_transaction__contract_data__awarding_agency_code'),
            ('awarding_agency_name', 'award__latest_transaction__contract_data__awarding_agency_name'),
            ('awarding_sub_agency_code', 'award__latest_transaction__contract_data__awarding_sub_tier_agency_c'),
            ('awarding_sub_agency_name', 'award__latest_transaction__contract_data__awarding_sub_tier_agency_n'),
            ('awarding_office_code', 'award__latest_transaction__contract_data__awarding_office_code'),
            ('awarding_office_name', 'award__latest_transaction__contract_data__awarding_office_name'),
            ('funding_agency_code', 'award__latest_transaction__contract_data__funding_agency_code'),
            ('funding_agency_name', 'award__latest_transaction__contract_data__funding_agency_name'),
            ('funding_sub_agency_code', 'award__latest_transaction__contract_data__funding_sub_tier_agency_co'),
            ('funding_sub_agency_name', 'award__latest_transaction__contract_data__funding_sub_tier_agency_na'),
            ('funding_office_code', 'award__latest_transaction__contract_data__funding_office_code'),
            ('funding_office_name', 'award__latest_transaction__contract_data__funding_office_name'),
            ('foreign_funding', 'award__latest_transaction__contract_data__foreign_funding'),
            ('sam_exception', 'award__latest_transaction__contract_data__sam_exception'),
            ('recipient_duns', 'award__latest_transaction__contract_data__awardee_or_recipient_uniqu'),
            ('recipient_name', 'award__latest_transaction__contract_data__awardee_or_recipient_legal'),
            ('recipient_doing_business_as_name',
             'award__latest_transaction__contract_data__vendor_doing_as_business_n'),
            ('recipient_parent_name', 'award__latest_transaction__contract_data__ultimate_parent_legal_enti'),
            ('recipient_parent_duns', 'award__latest_transaction__contract_data__ultimate_parent_unique_ide'),
            ('recipient_country_code', 'award__latest_transaction__contract_data__legal_entity_country_code'),
            ('recipient_country_name', 'award__latest_transaction__contract_data__legal_entity_country_name'),
            ('recipient_address_line_1', 'award__latest_transaction__contract_data__legal_entity_address_line1'),
            ('recipient_address_line_2', 'award__latest_transaction__contract_data__legal_entity_address_line2'),
            ('recipient_address_line_3', 'award__latest_transaction__contract_data__legal_entity_address_line3'),
            ('recipient_city_name', 'award__latest_transaction__contract_data__legal_entity_city_name'),
            ('recipient_state_code', 'award__latest_transaction__contract_data__legal_entity_state_code'),
            ('recipient_state_name', 'award__latest_transaction__contract_data__legal_entity_state_descrip'),
            ('recipient_zip_4_code', 'award__latest_transaction__contract_data__legal_entity_zip4'),
            ('recipient_congressional_district',
             'award__latest_transaction__contract_data__legal_entity_congressional'),
            ('recipient_phone_number', 'award__latest_transaction__contract_data__vendor_phone_number'),
            ('recipient_fax_number', 'award__latest_transaction__contract_data__vendor_fax_number'),
            ('primary_place_of_performance_country_code',
             'award__latest_transaction__contract_data__place_of_perform_country_c'),
            ('primary_place_of_performance_country_name',
             'award__latest_transaction__contract_data__place_of_perf_country_desc'),
            ('primary_place_of_performance_city_name',
             'award__latest_transaction__contract_data__place_of_perform_city_name'),
            ('primary_place_of_performance_county_name',
             'award__latest_transaction__contract_data__place_of_perform_county_na'),
            ('primary_place_of_performance_state_code',
             'award__latest_transaction__contract_data__place_of_performance_state'),
            ('primary_place_of_performance_state_name',
             'award__latest_transaction__contract_data__place_of_perfor_state_desc'),
            ('primary_place_of_performance_zip_4',
             'award__latest_transaction__contract_data__place_of_performance_zip4a'),
            ('primary_place_of_performance_congressional_district',
             'award__latest_transaction__contract_data__place_of_performance_congr'),
            ('primary_place_of_performance_location_code',
             'award__latest_transaction__contract_data__place_of_performance_locat'),
            ('award_type_code', 'award__latest_transaction__contract_data__contract_award_type'),
            ('award_type', 'award__latest_transaction__contract_data__contract_award_type_desc'),
            ('idv_type_code', 'award__latest_transaction__contract_data__idv_type'),
            ('idv_type', 'award__latest_transaction__contract_data__idv_type_description'),
            ('multiple_or_single_award_idv_code',
             'award__latest_transaction__contract_data__multiple_or_single_award_i'),
            ('multiple_or_single_award_idv', 'award__latest_transaction__contract_data__multiple_or_single_aw_desc'),
            ('type_of_idc_code', 'award__latest_transaction__contract_data__type_of_idc'),
            ('type_of_idc', 'award__latest_transaction__contract_data__type_of_idc_description'),
            ('type_of_contract_pricing_code', 'award__latest_transaction__contract_data__type_of_contract_pricing'),
            ('type_of_contract_pricing', 'award__latest_transaction__contract_data__type_of_contract_pric_desc'),
            ('award_description', 'award__latest_transaction__contract_data__award_description'),
            ('solicitation_identifier', 'award__latest_transaction__contract_data__solicitation_identifier'),
            ('number_of_actions', 'award__latest_transaction__contract_data__number_of_actions'),
            ('product_or_service_code', 'award__latest_transaction__contract_data__product_or_service_code'),
            ('product_or_service_code_description',
             'award__latest_transaction__contract_data__product_or_service_co_desc'),
            ('contract_bundling_code', 'award__latest_transaction__contract_data__contract_bundling'),
            ('contract_bundling', 'award__latest_transaction__contract_data__contract_bundling_descrip'),
            ('dod_claimant_program_code', 'award__latest_transaction__contract_data__dod_claimant_program_code'),
            ('dod_claimant_program_description',
             'award__latest_transaction__contract_data__dod_claimant_prog_cod_desc'),
            ('naics_code', 'award__latest_transaction__contract_data__naics'),
            ('naics_description', 'award__latest_transaction__contract_data__naics_description'),
            ('recovered_materials_sustainability_code',
             'award__latest_transaction__contract_data__recovered_materials_sustai'),
            ('recovered_materials_sustainability',
             'award__latest_transaction__contract_data__recovered_materials_s_desc'),
            ('domestic_or_foreign_entity_code', 'award__latest_transaction__contract_data__domestic_or_foreign_entity'),
            ('domestic_or_foreign_entity', 'award__latest_transaction__contract_data__domestic_or_foreign_e_desc'),
            ('dod_acquisition_program_code', 'award__latest_transaction__contract_data__program_system_or_equipmen'),
            ('dod_acquisition_program_description',
             'award__latest_transaction__contract_data__program_system_or_equ_desc'),
            ('information_technology_commercial_item_category_code',
             'award__latest_transaction__contract_data__information_technology_com'),
            ('information_technology_commercial_item_category',
             'award__latest_transaction__contract_data__information_technolog_desc'),
            ('epa_designated_product_code', 'award__latest_transaction__contract_data__epa_designated_product'),
            ('epa_designated_product', 'award__latest_transaction__contract_data__epa_designated_produc_desc'),
            ('country_of_product_or_service_origin_code',
             'award__latest_transaction__contract_data__country_of_product_or_serv'),
            ('country_of_product_or_service_origin',
             'award__latest_transaction__contract_data__country_of_product_or_desc'),
            ('place_of_manufacture_code', 'award__latest_transaction__contract_data__place_of_manufacture'),
            ('place_of_manufacture', 'award__latest_transaction__contract_data__place_of_manufacture_desc'),
            ('subcontracting_plan_code', 'award__latest_transaction__contract_data__subcontracting_plan'),
            ('subcontracting_plan', 'award__latest_transaction__contract_data__subcontracting_plan_desc'),
            ('extent_competed_code', 'award__latest_transaction__contract_data__extent_competed'),
            ('extent_competed', 'award__latest_transaction__contract_data__extent_compete_description'),
            ('solicitation_procedures_code', 'award__latest_transaction__contract_data__solicitation_procedures'),
            ('solicitation_procedures', 'award__latest_transaction__contract_data__solicitation_procedur_desc'),
            ('type_of_set_aside_code', 'award__latest_transaction__contract_data__type_set_aside'),
            ('type_of_set_aside', 'award__latest_transaction__contract_data__type_set_aside_description'),
            ('evaluated_preference_code', 'award__latest_transaction__contract_data__evaluated_preference'),
            ('evaluated_preference', 'award__latest_transaction__contract_data__evaluated_preference_desc'),
            ('research_code', 'award__latest_transaction__contract_data__research'),
            ('research', 'award__latest_transaction__contract_data__research_description'),
            ('fair_opportunity_limited_sources_code',
             'award__latest_transaction__contract_data__fair_opportunity_limited_s'),
            ('fair_opportunity_limited_sources',
             'award__latest_transaction__contract_data__fair_opportunity_limi_desc'),
            ('other_than_full_and_open_competition_code',
             'award__latest_transaction__contract_data__other_than_full_and_open_c'),
            ('other_than_full_and_open_competition',
             'award__latest_transaction__contract_data__other_than_full_and_o_desc'),
            ('number_of_offers_received', 'award__latest_transaction__contract_data__number_of_offers_received'),
            ('commercial_item_acquisition_procedures_code',
             'award__latest_transaction__contract_data__commercial_item_acquisitio'),
            ('commercial_item_acquisition_procedures',
             'award__latest_transaction__contract_data__commercial_item_acqui_desc'),
            ('small_business_competitiveness_demonstration _program',
             'award__latest_transaction__contract_data__small_business_competitive'),
            ('commercial_item_test_program_code',
             'award__latest_transaction__contract_data__commercial_item_test_progr'),
            ('commercial_item_test_program', 'award__latest_transaction__contract_data__commercial_item_test_desc'),
            ('a76_fair_act_action_code', 'award__latest_transaction__contract_data__a_76_fair_act_action'),
            ('a76_fair_act_action', 'award__latest_transaction__contract_data__a_76_fair_act_action_desc'),
            ('fed_biz_opps_code', 'award__latest_transaction__contract_data__fed_biz_opps'),
            ('fed_biz_opps', 'award__latest_transaction__contract_data__fed_biz_opps_description'),
            ('local_area_set_aside_code', 'award__latest_transaction__contract_data__local_area_set_aside'),
            ('local_area_set_aside', 'award__latest_transaction__contract_data__local_area_set_aside_desc'),
            ('clinger_cohen_act_planning_code', 'award__latest_transaction__contract_data__clinger_cohen_act_planning'),
            ('clinger_cohen_act_planning', 'award__latest_transaction__contract_data__clinger_cohen_act_pla_desc'),
            ('walsh_healey_act_code', 'award__latest_transaction__contract_data__walsh_healey_act'),
            ('walsh_healey_act', 'award__latest_transaction__contract_data__walsh_healey_act_descrip'),
            ('service_contract_act_code', 'award__latest_transaction__contract_data__service_contract_act'),
            ('service_contract_act', 'award__latest_transaction__contract_data__service_contract_act_desc'),
            ('davis_bacon_act_code', 'award__latest_transaction__contract_data__davis_bacon_act'),
            ('davis_bacon_act', 'award__latest_transaction__contract_data__davis_bacon_act_descrip'),
            ('interagency_contracting_authority_code',
             'award__latest_transaction__contract_data__interagency_contracting_au'),
            ('interagency_contracting_authority',
             'award__latest_transaction__contract_data__interagency_contract_desc'),
            ('other_statutory_authority', 'award__latest_transaction__contract_data__other_statutory_authority'),
            ('program_acronym', 'award__latest_transaction__contract_data__program_acronym'),
            ('parent_award_type_code', 'award__latest_transaction__contract_data__referenced_idv_type'),
            ('parent_award_type', 'award__latest_transaction__contract_data__referenced_idv_type_desc'),
            ('parent_award_single_or_multiple_code',
             'award__latest_transaction__contract_data__referenced_mult_or_single'),
            ('parent_award_single_or_multiple', 'award__latest_transaction__contract_data__referenced_mult_or_si_desc'),
            ('major_program', 'award__latest_transaction__contract_data__major_program'),
            ('national_interest_action_code', 'award__latest_transaction__contract_data__national_interest_action'),
            ('national_interest_action', 'award__latest_transaction__contract_data__national_interest_action'),
            ('cost_or_pricing_data_code', 'award__latest_transaction__contract_data__cost_or_pricing_data'),
            ('cost_or_pricing_data', 'award__latest_transaction__contract_data__cost_or_pricing_data_desc'),
            ('cost_accounting_standards_clause_code',
             'award__latest_transaction__contract_data__cost_accounting_standards'),
            ('cost_accounting_standards_clause',
             'award__latest_transaction__contract_data__cost_accounting_stand_desc'),
            ('gfe_gfp_code', 'award__latest_transaction__contract_data__government_furnished_equip'),
            ('gfe_gfp', 'award__latest_transaction__contract_data__government_furnished_desc'),
            ('sea_transportation_code', 'award__latest_transaction__contract_data__sea_transportation'),
            ('sea_transportation', 'award__latest_transaction__contract_data__sea_transportation_desc'),
            ('consolidated_contract_code', 'award__latest_transaction__contract_data__consolidated_contract'),
            ('consolidated_contract', 'award__latest_transaction__contract_data__consolidated_contract_desc'),
            ('performance_based_service_acquisition_code',
             'award__latest_transaction__contract_data__performance_based_service'),
            ('performance_based_service_acquisition',
             'award__latest_transaction__contract_data__performance_based_se_desc'),
            ('multi_year_contract_code', 'award__latest_transaction__contract_data__multi_year_contract'),
            ('multi_year_contract', 'award__latest_transaction__contract_data__multi_year_contract_desc'),
            ('contract_financing_code', 'award__latest_transaction__contract_data__contract_financing'),
            ('contract_financing', 'award__latest_transaction__contract_data__contract_financing_descrip'),
            ('purchase_card_as_payment_method_code',
             'award__latest_transaction__contract_data__purchase_card_as_payment_m'),
            ('purchase_card_as_payment_method', 'award__latest_transaction__contract_data__purchase_card_as_paym_desc'),
            ('contingency_humanitarian_or_peacekeeping_operation_code',
             'award__latest_transaction__contract_data__contingency_humanitarian_o'),
            ('contingency_humanitarian_or_peacekeeping_operation',
             'award__latest_transaction__contract_data__contingency_humanitar_desc'),
            ('alaskan_native_owned_corporation_or_firm',
             'award__latest_transaction__contract_data__alaskan_native_owned_corpo'),
            ('american_indian_owned_business', 'award__latest_transaction__contract_data__american_indian_owned_busi'),
            ('indian_tribe_federally_recognized',
             'award__latest_transaction__contract_data__indian_tribe_federally_rec'),
            ('native_hawaiian_owned_business', 'award__latest_transaction__contract_data__native_hawaiian_owned_busi'),
            ('tribally_owned_business', 'award__latest_transaction__contract_data__tribally_owned_business'),
            ('veteran_owned_business', 'award__latest_transaction__contract_data__veteran_owned_business'),
            ('service_disabled_veteran_owned_business',
             'award__latest_transaction__contract_data__service_disabled_veteran_o'),
            ('woman_owned_business', 'award__latest_transaction__contract_data__woman_owned_business'),
            ('women_owned_small_business', 'award__latest_transaction__contract_data__women_owned_small_business'),
            ('economically_disadvantaged_women_owned_small_business',
             'award__latest_transaction__contract_data__economically_disadvantaged'),
            ('joint_venture_women_owned_small_business',
             'award__latest_transaction__contract_data__joint_venture_women_owned'),
            ('joint_venture_economic_disadvantaged_women_owned_small_bus',
             'award__latest_transaction__contract_data__joint_venture_economically'),
            ('minority_owned_business', 'award__latest_transaction__contract_data__minority_owned_business'),
            ('subcontinent_asian_asian_indian_american_owned_business',
             'award__latest_transaction__contract_data__subcontinent_asian_asian_i'),
            ('asian_pacific_american_owned_business',
             'award__latest_transaction__contract_data__asian_pacific_american_own'),
            ('black_american_owned_business', 'award__latest_transaction__contract_data__black_american_owned_busin'),
            ('hispanic_american_owned_business',
             'award__latest_transaction__contract_data__hispanic_american_owned_bu'),
            ('native_american_owned_business', 'award__latest_transaction__contract_data__native_american_owned_busi'),
            ('other_minority_owned_business', 'award__latest_transaction__contract_data__other_minority_owned_busin'),
            ('contracting_officers_determination_of_business_size',
             'award__latest_transaction__contract_data__contracting_officers_desc'),
            ('contracting_officers_determination_of_business_size_code',
             'award__latest_transaction__contract_data__contracting_officers_deter'),
            ('emerging_small_business', 'award__latest_transaction__contract_data__emerging_small_business'),
            ('community_developed_corporation_owned_firm',
             'award__latest_transaction__contract_data__community_developed_corpor'),
            ('labor_surplus_area_firm', 'award__latest_transaction__contract_data__labor_surplus_area_firm'),
            ('us_federal_government', 'award__latest_transaction__contract_data__us_federal_government'),
            ('federally_funded_research_and_development_corp',
             'award__latest_transaction__contract_data__federally_funded_research'),
            ('federal_agency', 'award__latest_transaction__contract_data__federal_agency'),
            ('us_state_government', 'award__latest_transaction__contract_data__us_state_government'),
            ('us_local_government', 'award__latest_transaction__contract_data__us_local_government'),
            ('city_local_government', 'award__latest_transaction__contract_data__city_local_government'),
            ('county_local_government', 'award__latest_transaction__contract_data__county_local_government'),
            ('inter_municipal_local_government',
             'award__latest_transaction__contract_data__inter_municipal_local_gove'),
            ('local_government_owned', 'award__latest_transaction__contract_data__local_government_owned'),
            ('municipality_local_government', 'award__latest_transaction__contract_data__municipality_local_governm'),
            ('school_district_local_government',
             'award__latest_transaction__contract_data__school_district_local_gove'),
            ('township_local_government', 'award__latest_transaction__contract_data__township_local_government'),
            ('us_tribal_government', 'award__latest_transaction__contract_data__us_tribal_government'),
            ('foreign_government', 'award__latest_transaction__contract_data__foreign_government'),
            ('corporate_entity_not_tax_exempt', 'award__latest_transaction__contract_data__corporate_entity_not_tax_e'),
            ('corporate_entity_tax_exempt', 'award__latest_transaction__contract_data__corporate_entity_tax_exemp'),
            ('partnership_or_limited_liability_partnership',
             'award__latest_transaction__contract_data__partnership_or_limited_lia'),
            ('sole_proprietorship', 'award__latest_transaction__contract_data__sole_proprietorship'),
            ('small_agricultural_cooperative', 'award__latest_transaction__contract_data__small_agricultural_coopera'),
            ('international_organization', 'award__latest_transaction__contract_data__international_organization'),
            ('us_government_entity', 'award__latest_transaction__contract_data__us_government_entity'),
            ('community_development_corporation',
             'award__latest_transaction__contract_data__community_development_corp'),
            ('domestic_shelter', 'award__latest_transaction__contract_data__domestic_shelter'),
            ('educational_institution', 'award__latest_transaction__contract_data__educational_institution'),
            ('foundation', 'award__latest_transaction__contract_data__foundation'),
            ('hospital_flag', 'award__latest_transaction__contract_data__hospital_flag'),
            ('manufacturer_of_goods', 'award__latest_transaction__contract_data__manufacturer_of_goods'),
            ('veterinary_hospital', 'award__latest_transaction__contract_data__veterinary_hospital'),
            ('hispanic_servicing_institution', 'award__latest_transaction__contract_data__hispanic_servicing_institu'),
            ('receives_contracts', 'award__latest_transaction__contract_data__contracts'),
            ('receives_grants', 'award__latest_transaction__contract_data__grants'),
            ('receives_contracts_and_grants', 'award__latest_transaction__contract_data__receives_contracts_and_gra'),
            ('airport_authority', 'award__latest_transaction__contract_data__airport_authority'),
            ('council_of_governments', 'award__latest_transaction__contract_data__council_of_governments'),
            ('housing_authorities_public_tribal',
             'award__latest_transaction__contract_data__housing_authorities_public'),
            ('interstate_entity', 'award__latest_transaction__contract_data__interstate_entity'),
            ('planning_commission', 'award__latest_transaction__contract_data__planning_commission'),
            ('port_authority', 'award__latest_transaction__contract_data__port_authority'),
            ('transit_authority', 'award__latest_transaction__contract_data__transit_authority'),
            ('subchapter_scorporation', 'award__latest_transaction__contract_data__subchapter_s_corporation'),
            ('limited_liability_corporation', 'award__latest_transaction__contract_data__limited_liability_corporat'),
            ('foreign_owned_and_located', 'award__latest_transaction__contract_data__foreign_owned_and_located'),
            ('for_profit_organization', 'award__latest_transaction__contract_data__for_profit_organization'),
            ('nonprofit_organization', 'award__latest_transaction__contract_data__nonprofit_organization'),
            ('other_not_for_profit_organization',
             'award__latest_transaction__contract_data__other_not_for_profit_organ'),
            ('the_ability_one_program', 'award__latest_transaction__contract_data__the_ability_one_program'),
            ('private_university_or_college', 'award__latest_transaction__contract_data__private_university_or_coll'),
            ('state_controlled_institution_of_higher_learning',
             'award__latest_transaction__contract_data__state_controlled_instituti'),
            ('1862_land_grant_college', 'award__latest_transaction__contract_data__c1862_land_grant_college'),
            ('1890_land_grant_college', 'award__latest_transaction__contract_data__c1890_land_grant_college'),
            ('1994_land_grant_college', 'award__latest_transaction__contract_data__c1994_land_grant_college'),
            ('minority_institution', 'award__latest_transaction__contract_data__minority_institution'),
            ('historically_black_college', 'award__latest_transaction__contract_data__historically_black_college'),
            ('tribal_college', 'award__latest_transaction__contract_data__tribal_college'),
            ('alaskan_native_servicing_institution',
             'award__latest_transaction__contract_data__alaskan_native_servicing_i'),
            ('native_hawaiian_servicing_institution',
             'award__latest_transaction__contract_data__native_hawaiian_servicing'),
            ('school_of_forestry', 'award__latest_transaction__contract_data__school_of_forestry'),
            ('veterinary_college', 'award__latest_transaction__contract_data__veterinary_college'),
            ('dot_certified_disadvantage', 'award__latest_transaction__contract_data__dot_certified_disadvantage'),
            ('self_certified_small_disadvantaged_business',
             'award__latest_transaction__contract_data__self_certified_small_disad'),
            ('small_disadvantaged_business', 'award__latest_transaction__contract_data__small_disadvantaged_busine'),
            ('c8a_program_participant', 'award__latest_transaction__contract_data__c8a_program_participant'),
            ('historically_underutilized_business_zone _hubzone_firm',
             'award__latest_transaction__contract_data__historically_underutilized'),
            ('sba_certified_8a_joint_venture', 'award__latest_transaction__contract_data__sba_certified_8_a_joint_ve'),
            ('last_modified_date', 'award__latest_transaction__contract_data__last_modified')
        ]),
        'd2': OrderedDict([
            ('award_id_fain', 'award__fain'),
            ('award_id_uri', 'award__uri'),
            ('sai_number', 'award__latest_transaction__assistance_data__sai_number'),
            ('obligated_amount', 'award__total_obligation'),
            ('non_federal_funding_amount', 'award__latest_transaction__assistance_data__non_federal_funding_amount'),
            ('total_funding_amount', 'award__total_funding_amount'),
            ('face_value_of_loan', 'award__latest_transaction__assistance_data__face_value_loan_guarantee'),
            ('original_subsidy_cost', 'award__latest_transaction__original_loan_subsidy_cost'),
            ('total_subsidy_cost', 'award__total_subsidy_cost'),
            ('total_loan_value', 'award__total_loan_value'),
            ('period_of_performance_start_date', 'award__period_of_performance_start_date'),
            ('period_of_performance_current_end_date', 'award__period_of_performance_current_end_date'),
            ('awarding_agency_code', 'award__latest_transaction__assistance_data__awarding_agency_code'),
            ('awarding_agency_name', 'award__latest_transaction__assistance_data__awarding_agency_name'),
            ('awarding_sub_agency_code', 'award__latest_transaction__assistance_data__awarding_sub_tier_agency_c'),
            ('awarding_sub_agency_name', 'award__latest_transaction__assistance_data__awarding_sub_tier_agency_n'),
            ('awarding_office_code', 'award__latest_transaction__assistance_data__awarding_office_code'),
            ('awarding_office_name', 'award__latest_transaction__assistance_data__awarding_office_name'),
            ('funding_agency_code', 'award__latest_transaction__assistance_data__funding_agency_code'),
            ('funding_agency_name', 'award__latest_transaction__assistance_data__funding_agency_name'),
            ('funding_sub_agency_code', 'award__latest_transaction__assistance_data__funding_sub_tier_agency_co'),
            ('funding_sub_agency_name', 'award__latest_transaction__assistance_data__funding_sub_tier_agency_na'),
            ('funding_office_code', 'award__latest_transaction__assistance_data__funding_office_code'),
            ('funding_office_name', 'award__latest_transaction__assistance_data__funding_office_name'),
            ('recipient_duns', 'award__latest_transaction__assistance_data__awardee_or_recipient_uniqu'),
            ('recipient_name', 'award__latest_transaction__assistance_data__awardee_or_recipient_legal'),
            ('recipient_country_code', 'award__latest_transaction__assistance_data__legal_entity_country_code'),
            ('recipient_country_name', 'award__latest_transaction__assistance_data__legal_entity_country_name'),
            ('recipient_address_line_1', 'award__latest_transaction__assistance_data__legal_entity_address_line1'),
            ('recipient_address_line_2', 'award__latest_transaction__assistance_data__legal_entity_address_line2'),
            ('recipient_address_line_3', 'award__latest_transaction__assistance_data__legal_entity_address_line3'),
            ('recipient_city_code', 'award__latest_transaction__assistance_data__legal_entity_city_code'),
            ('recipient_city_name', 'award__latest_transaction__assistance_data__legal_entity_city_name'),
            ('recipient_county_code', 'award__latest_transaction__assistance_data__legal_entity_county_code'),
            ('recipient_county_name', 'award__latest_transaction__assistance_data__legal_entity_county_name'),
            ('recipient_state_code', 'award__latest_transaction__assistance_data__legal_entity_state_code'),
            ('recipient_state_name', 'award__latest_transaction__assistance_data__legal_entity_state_name'),
            ('recipient_zip_code', 'award__latest_transaction__assistance_data__legal_entity_zip5'),
            ('recipient_zip_last_4_code', 'award__latest_transaction__assistance_data__legal_entity_zip_last4'),
            ('recipient_congressional_district',
             'award__latest_transaction__assistance_data__legal_entity_congressional'),
            ('recipient_foreign_city_name', 'award__latest_transaction__assistance_data__legal_entity_foreign_city'),
            ('recipient_foreign_province_name',
             'award__latest_transaction__assistance_data__legal_entity_foreign_provi'),
            ('recipient_foreign_postal_code',
             'award__latest_transaction__assistance_data__legal_entity_foreign_posta'),
            ('primary_place_of_performance_country_code',
             'award__latest_transaction__assistance_data__place_of_perform_country_c'),
            ('primary_place_of_performance_country_name',
             'award__latest_transaction__assistance_data__place_of_perform_country_n'),
            ('primary_place_of_performance_code',
             'award__latest_transaction__assistance_data__place_of_performance_code'),
            ('primary_place_of_performance_city_name',
             'award__latest_transaction__assistance_data__place_of_performance_city'),
            ('primary_place_of_performance_county_code',
             'award__latest_transaction__assistance_data__place_of_perform_county_co'),
            ('primary_place_of_performance_county_name',
             'award__latest_transaction__assistance_data__place_of_perform_county_na'),
            ('primary_place_of_performance_state_name',
             'award__latest_transaction__assistance_data__place_of_perform_state_nam'),
            ('primary_place_of_performance_zip_4',
             'award__latest_transaction__assistance_data__place_of_performance_zip4a'),
            ('primary_place_of_performance_congressional_district',
             'award__latest_transaction__assistance_data__place_of_performance_congr'),
            ('primary_place_of_performance_foreign_location',
             'award__latest_transaction__assistance_data__place_of_performance_forei'),
            ('cfda_number', 'award__latest_transaction__assistance_data__cfda_number'),
            ('cfda_title', 'award__latest_transaction__assistance_data__cfda_title'),
            ('assistance_type_code', 'award__latest_transaction__assistance_data__assistance_type'),
            ('award_description', 'award__latest_transaction__assistance_data__award_description'),
            ('business_funds_indicator_code', 'award__latest_transaction__assistance_data__business_funds_indicator'),
            ('business_types_code', 'award__latest_transaction__assistance_data__business_types'),
            ('record_type_code', 'award__latest_transaction__assistance_data__record_type'),
            ('last_modified_date', 'award__latest_transaction__assistance_data__modified_at')
        ])
    },
    'transaction': {
        'd1': OrderedDict([
            ('award_id_piid', 'transaction__contract_data__piid'),
            ('modification_number', 'transaction__contract_data__award_modification_amendme'),
            ('transaction_number', 'transaction__contract_data__transaction_number'),
            ('parent_award_agency_id', 'transaction__contract_data__referenced_idv_agency_iden'),
            ('parent_award_agency_name', 'transaction__contract_data__referenced_idv_agency_desc'),
            ('parent_award_id', 'transaction__contract_data__parent_award_id'),
            ('parent_award_modification_number', 'transaction__contract_data__referenced_idv_modificatio'),
            ('federal_action_obligation', 'transaction__federal_action_obligation'),
            ('base_and_exercised_options_value', 'transaction__contract_data__base_exercised_options_val'),
            ('base_and_all_options_value', 'transaction__contract_data__base_and_all_options_value'),
            ('action_date', 'transaction__action_date'),
            ('period_of_performance_start_date', 'transaction__contract_data__period_of_performance_star'),
            ('period_of_performance_current_end_date', 'transaction__contract_data__period_of_performance_curr'),
            ('period_of_performance_potential_end_date', 'transaction__contract_data__period_of_perf_potential_e'),
            ('ordering_period_end_date', 'transaction__contract_data__ordering_period_end_date'),
            ('awarding_agency_code', 'transaction__contract_data__awarding_agency_code'),
            ('awarding_agency_name', 'transaction__contract_data__awarding_agency_name'),
            ('awarding_sub_agency_code', 'transaction__contract_data__awarding_sub_tier_agency_c'),
            ('awarding_sub_agency_name', 'transaction__contract_data__awarding_sub_tier_agency_n'),
            ('awarding_office_code', 'transaction__contract_data__awarding_office_code'),
            ('awarding_office_name', 'transaction__contract_data__awarding_office_name'),
            ('funding_agency_code', 'transaction__contract_data__funding_agency_code'),
            ('funding_agency_name', 'transaction__contract_data__funding_agency_name'),
            ('funding_sub_agency_code', 'transaction__contract_data__funding_sub_tier_agency_co'),
            ('funding_sub_agency_name', 'transaction__contract_data__funding_sub_tier_agency_na'),
            ('funding_office_code', 'transaction__contract_data__funding_office_code'),
            ('funding_office_name', 'transaction__contract_data__funding_office_name'),
            ('foreign_funding', 'transaction__contract_data__foreign_funding'),
            ('sam_exception', 'transaction__contract_data__sam_exception'),
            ('recipient_duns', 'transaction__contract_data__awardee_or_recipient_uniqu'),
            ('recipient_name', 'transaction__contract_data__awardee_or_recipient_legal'),
            ('recipient_doing_business_as_name', 'transaction__contract_data__vendor_doing_as_business_n'),
            ('recipient_parent_name', 'transaction__contract_data__ultimate_parent_legal_enti'),
            ('recipient_parent_duns', 'transaction__contract_data__ultimate_parent_unique_ide'),
            ('recipient_country_code', 'transaction__contract_data__legal_entity_country_code'),
            ('recipient_country_name', 'transaction__contract_data__legal_entity_country_name'),
            ('recipient_address_line_1', 'transaction__contract_data__legal_entity_address_line1'),
            ('recipient_address_line_2', 'transaction__contract_data__legal_entity_address_line2'),
            ('recipient_address_line_3', 'transaction__contract_data__legal_entity_address_line3'),
            ('recipient_city_name', 'transaction__contract_data__legal_entity_city_name'),
            ('recipient_state_code', 'transaction__contract_data__legal_entity_state_code'),
            ('recipient_state_name', 'transaction__contract_data__legal_entity_state_descrip'),
            ('recipient_zip_4_code', 'transaction__contract_data__legal_entity_zip4'),
            ('recipient_congressional_district', 'transaction__contract_data__legal_entity_congressional'),
            ('recipient_phone_number', 'transaction__contract_data__vendor_phone_number'),
            ('recipient_fax_number', 'transaction__contract_data__vendor_fax_number'),
            ('primary_place_of_performance_country_code', 'transaction__contract_data__place_of_perform_country_c'),
            ('primary_place_of_performance_country_name', 'transaction__contract_data__place_of_perf_country_desc'),
            ('primary_place_of_performance_city_name', 'transaction__contract_data__place_of_perform_city_name'),
            ('primary_place_of_performance_county_name', 'transaction__contract_data__place_of_perform_county_na'),
            ('primary_place_of_performance_state_code', 'transaction__contract_data__place_of_performance_state'),
            ('primary_place_of_performance_state_name', 'transaction__contract_data__place_of_perfor_state_desc'),
            ('primary_place_of_performance_zip_4', 'transaction__contract_data__place_of_performance_zip4a'),
            ('primary_place_of_performance_congressional_district',
             'transaction__contract_data__place_of_performance_congr'),
            ('primary_place_of_performance_location_code', 'transaction__contract_data__place_of_performance_locat'),
            ('award_type_code', 'transaction__contract_data__contract_award_type'),
            ('award_type', 'transaction__contract_data__contract_award_type_desc'),
            ('idv_type_code', 'transaction__contract_data__idv_type'),
            ('idv_type', 'transaction__contract_data__idv_type_description'),
            ('multiple_or_single_award_idv_code', 'transaction__contract_data__multiple_or_single_award_i'),
            ('multiple_or_single_award_idv', 'transaction__contract_data__multiple_or_single_aw_desc'),
            ('type_of_idc_code', 'transaction__contract_data__type_of_idc'),
            ('type_of_idc', 'transaction__contract_data__type_of_idc_description'),
            ('type_of_contract_pricing_code', 'transaction__contract_data__type_of_contract_pricing'),
            ('type_of_contract_pricing', 'transaction__contract_data__type_of_contract_pric_desc'),
            ('award_description', 'transaction__contract_data__award_description'),
            ('action_type_code', 'transaction__action_type'),
            ('action_type', 'transaction__action_type_description'),
            ('solicitation_identifier', 'transaction__contract_data__solicitation_identifier'),
            ('number_of_actions', 'transaction__contract_data__number_of_actions'),
            ('product_or_service_code', 'transaction__contract_data__product_or_service_code'),
            ('product_or_service_code_description', 'transaction__contract_data__product_or_service_co_desc'),
            ('contract_bundling_code', 'transaction__contract_data__contract_bundling'),
            ('contract_bundling', 'transaction__contract_data__contract_bundling_descrip'),
            ('dod_claimant_program_code', 'transaction__contract_data__dod_claimant_program_code'),
            ('dod_claimant_program_description', 'transaction__contract_data__dod_claimant_prog_cod_desc'),
            ('naics_code', 'transaction__contract_data__naics'),
            ('naics_description', 'transaction__contract_data__naics_description'),
            ('recovered_materials_sustainability_code', 'transaction__contract_data__recovered_materials_sustai'),
            ('recovered_materials_sustainability', 'transaction__contract_data__recovered_materials_s_desc'),
            ('domestic_or_foreign_entity_code', 'transaction__contract_data__domestic_or_foreign_entity'),
            ('domestic_or_foreign_entity', 'transaction__contract_data__domestic_or_foreign_e_desc'),
            ('dod_acquisition_program_code', 'transaction__contract_data__program_system_or_equipmen'),
            ('dod_acquisition_program_description', 'transaction__contract_data__program_system_or_equ_desc'),
            ('information_technology_commercial_item_category_code',
             'transaction__contract_data__information_technology_com'),
            ('information_technology_commercial_item_category',
             'transaction__contract_data__information_technolog_desc'),
            ('epa_designated_product_code', 'transaction__contract_data__epa_designated_product'),
            ('epa_designated_product', 'transaction__contract_data__epa_designated_produc_desc'),
            ('country_of_product_or_service_origin_code', 'transaction__contract_data__country_of_product_or_serv'),
            ('country_of_product_or_service_origin', 'transaction__contract_data__country_of_product_or_desc'),
            ('place_of_manufacture_code', 'transaction__contract_data__place_of_manufacture'),
            ('place_of_manufacture', 'transaction__contract_data__place_of_manufacture_desc'),
            ('subcontracting_plan_code', 'transaction__contract_data__subcontracting_plan'),
            ('subcontracting_plan', 'transaction__contract_data__subcontracting_plan_desc'),
            ('extent_competed_code', 'transaction__contract_data__extent_competed'),
            ('extent_competed', 'transaction__contract_data__extent_compete_description'),
            ('solicitation_procedures_code', 'transaction__contract_data__solicitation_procedures'),
            ('solicitation_procedures', 'transaction__contract_data__solicitation_procedur_desc'),
            ('type_of_set_aside_code', 'transaction__contract_data__type_set_aside'),
            ('type_of_set_aside', 'transaction__contract_data__type_set_aside_description'),
            ('evaluated_preference_code', 'transaction__contract_data__evaluated_preference'),
            ('evaluated_preference', 'transaction__contract_data__evaluated_preference_desc'),
            ('research_code', 'transaction__contract_data__research'),
            ('research', 'transaction__contract_data__research_description'),
            ('fair_opportunity_limited_sources_code', 'transaction__contract_data__fair_opportunity_limited_s'),
            ('fair_opportunity_limited_sources', 'transaction__contract_data__fair_opportunity_limi_desc'),
            ('other_than_full_and_open_competition_code', 'transaction__contract_data__other_than_full_and_open_c'),
            ('other_than_full_and_open_competition', 'transaction__contract_data__other_than_full_and_o_desc'),
            ('number_of_offers_received', 'transaction__contract_data__number_of_offers_received'),
            ('commercial_item_acquisition_procedures_code', 'transaction__contract_data__commercial_item_acquisitio'),
            ('commercial_item_acquisition_procedures', 'transaction__contract_data__commercial_item_acqui_desc'),
            ('small_business_competitiveness_demonstration _program',
             'transaction__contract_data__small_business_competitive'),
            ('commercial_item_test_program_code', 'transaction__contract_data__commercial_item_test_progr'),
            ('commercial_item_test_program', 'transaction__contract_data__commercial_item_test_desc'),
            ('a76_fair_act_action_code', 'transaction__contract_data__a_76_fair_act_action'),
            ('a76_fair_act_action', 'transaction__contract_data__a_76_fair_act_action_desc'),
            ('fed_biz_opps_code', 'transaction__contract_data__fed_biz_opps'),
            ('fed_biz_opps', 'transaction__contract_data__fed_biz_opps_description'),
            ('local_area_set_aside_code', 'transaction__contract_data__local_area_set_aside'),
            ('local_area_set_aside', 'transaction__contract_data__local_area_set_aside_desc'),
            ('price_evaluation_adjustment_preference_percent_difference',
             'transaction__contract_data__price_evaluation_adjustmen'),
            ('clinger_cohen_act_planning_code', 'transaction__contract_data__clinger_cohen_act_planning'),
            ('clinger_cohen_act_planning', 'transaction__contract_data__clinger_cohen_act_pla_desc'),
            ('walsh_healey_act_code', 'transaction__contract_data__walsh_healey_act'),
            ('walsh_healey_act', 'transaction__contract_data__walsh_healey_act_descrip'),
            ('service_contract_act_code', 'transaction__contract_data__service_contract_act'),
            ('service_contract_act', 'transaction__contract_data__service_contract_act_desc'),
            ('davis_bacon_act_code', 'transaction__contract_data__davis_bacon_act'),
            ('davis_bacon_act', 'transaction__contract_data__davis_bacon_act_descrip'),
            ('interagency_contracting_authority_code', 'transaction__contract_data__interagency_contracting_au'),
            ('interagency_contracting_authority', 'transaction__contract_data__interagency_contract_desc'),
            ('other_statutory_authority', 'transaction__contract_data__other_statutory_authority'),
            ('program_acronym', 'transaction__contract_data__program_acronym'),
            ('parent_award_type_code', 'transaction__contract_data__referenced_idv_type'),
            ('parent_award_type', 'transaction__contract_data__referenced_idv_type_desc'),
            ('parent_award_single_or_multiple_code', 'transaction__contract_data__referenced_mult_or_single'),
            ('parent_award_single_or_multiple', 'transaction__contract_data__referenced_mult_or_si_desc'),
            ('major_program', 'transaction__contract_data__major_program'),
            ('national_interest_action_code', 'transaction__contract_data__national_interest_action'),
            ('national_interest_action', 'transaction__contract_data__national_interest_action'),
            ('cost_or_pricing_data_code', 'transaction__contract_data__cost_or_pricing_data'),
            ('cost_or_pricing_data', 'transaction__contract_data__cost_or_pricing_data_desc'),
            ('cost_accounting_standards_clause_code', 'transaction__contract_data__cost_accounting_standards'),
            ('cost_accounting_standards_clause', 'transaction__contract_data__cost_accounting_stand_desc'),
            ('gfe_gfp_code', 'transaction__contract_data__government_furnished_equip'),
            ('gfe_gfp', 'transaction__contract_data__government_furnished_desc'),
            ('sea_transportation_code', 'transaction__contract_data__sea_transportation'),
            ('sea_transportation', 'transaction__contract_data__sea_transportation_desc'),
            ('undefinitized_action_code', 'transaction__contract_data__undefinitized_action'),
            ('undefinitized_action', 'transaction__contract_data__undefinitized_action_desc'),
            ('consolidated_contract_code', 'transaction__contract_data__consolidated_contract'),
            ('consolidated_contract', 'transaction__contract_data__consolidated_contract_desc'),
            ('performance_based_service_acquisition_code', 'transaction__contract_data__performance_based_service'),
            ('performance_based_service_acquisition', 'transaction__contract_data__performance_based_se_desc'),
            ('multi_year_contract_code', 'transaction__contract_data__multi_year_contract'),
            ('multi_year_contract', 'transaction__contract_data__multi_year_contract_desc'),
            ('contract_financing_code', 'transaction__contract_data__contract_financing'),
            ('contract_financing', 'transaction__contract_data__contract_financing_descrip'),
            ('purchase_card_as_payment_method_code', 'transaction__contract_data__purchase_card_as_payment_m'),
            ('purchase_card_as_payment_method', 'transaction__contract_data__purchase_card_as_paym_desc'),
            ('contingency_humanitarian_or_peacekeeping_operation_code',
             'transaction__contract_data__contingency_humanitarian_o'),
            ('contingency_humanitarian_or_peacekeeping_operation',
             'transaction__contract_data__contingency_humanitar_desc'),
            ('alaskan_native_owned_corporation_or_firm', 'transaction__contract_data__alaskan_native_owned_corpo'),
            ('american_indian_owned_business', 'transaction__contract_data__american_indian_owned_busi'),
            ('indian_tribe_federally_recognized', 'transaction__contract_data__indian_tribe_federally_rec'),
            ('native_hawaiian_owned_business', 'transaction__contract_data__native_hawaiian_owned_busi'),
            ('tribally_owned_business', 'transaction__contract_data__tribally_owned_business'),
            ('veteran_owned_business', 'transaction__contract_data__veteran_owned_business'),
            ('service_disabled_veteran_owned_business', 'transaction__contract_data__service_disabled_veteran_o'),
            ('woman_owned_business', 'transaction__contract_data__woman_owned_business'),
            ('women_owned_small_business', 'transaction__contract_data__women_owned_small_business'),
            ('economically_disadvantaged_women_owned_small_business',
             'transaction__contract_data__economically_disadvantaged'),
            ('joint_venture_women_owned_small_business', 'transaction__contract_data__joint_venture_women_owned'),
            ('joint_venture_economic_disadvantaged_women_owned_small_bus',
             'transaction__contract_data__joint_venture_economically'),
            ('minority_owned_business', 'transaction__contract_data__minority_owned_business'),
            ('subcontinent_asian_asian_indian_american_owned_business',
             'transaction__contract_data__subcontinent_asian_asian_i'),
            ('asian_pacific_american_owned_business', 'transaction__contract_data__asian_pacific_american_own'),
            ('black_american_owned_business', 'transaction__contract_data__black_american_owned_busin'),
            ('hispanic_american_owned_business', 'transaction__contract_data__hispanic_american_owned_bu'),
            ('native_american_owned_business', 'transaction__contract_data__native_american_owned_busi'),
            ('other_minority_owned_business', 'transaction__contract_data__other_minority_owned_busin'),
            ('contracting_officers_determination_of_business_size',
             'transaction__contract_data__contracting_officers_desc'),
            ('contracting_officers_determination_of_business_size_code',
             'transaction__contract_data__contracting_officers_deter'),
            ('emerging_small_business', 'transaction__contract_data__emerging_small_business'),
            ('community_developed_corporation_owned_firm', 'transaction__contract_data__community_developed_corpor'),
            ('labor_surplus_area_firm', 'transaction__contract_data__labor_surplus_area_firm'),
            ('us_federal_government', 'transaction__contract_data__us_federal_government'),
            ('federally_funded_research_and_development_corp', 'transaction__contract_data__federally_funded_research'),
            ('federal_agency', 'transaction__contract_data__federal_agency'),
            ('us_state_government', 'transaction__contract_data__us_state_government'),
            ('us_local_government', 'transaction__contract_data__us_local_government'),
            ('city_local_government', 'transaction__contract_data__city_local_government'),
            ('county_local_government', 'transaction__contract_data__county_local_government'),
            ('inter_municipal_local_government', 'transaction__contract_data__inter_municipal_local_gove'),
            ('local_government_owned', 'transaction__contract_data__local_government_owned'),
            ('municipality_local_government', 'transaction__contract_data__municipality_local_governm'),
            ('school_district_local_government', 'transaction__contract_data__school_district_local_gove'),
            ('township_local_government', 'transaction__contract_data__township_local_government'),
            ('us_tribal_government', 'transaction__contract_data__us_tribal_government'),
            ('foreign_government', 'transaction__contract_data__foreign_government'),
            ('corporate_entity_not_tax_exempt', 'transaction__contract_data__corporate_entity_not_tax_e'),
            ('corporate_entity_tax_exempt', 'transaction__contract_data__corporate_entity_tax_exemp'),
            ('partnership_or_limited_liability_partnership', 'transaction__contract_data__partnership_or_limited_lia'),
            ('sole_proprietorship', 'transaction__contract_data__sole_proprietorship'),
            ('small_agricultural_cooperative', 'transaction__contract_data__small_agricultural_coopera'),
            ('international_organization', 'transaction__contract_data__international_organization'),
            ('us_government_entity', 'transaction__contract_data__us_government_entity'),
            ('community_development_corporation', 'transaction__contract_data__community_development_corp'),
            ('domestic_shelter', 'transaction__contract_data__domestic_shelter'),
            ('educational_institution', 'transaction__contract_data__educational_institution'),
            ('foundation', 'transaction__contract_data__foundation'),
            ('hospital_flag', 'transaction__contract_data__hospital_flag'),
            ('manufacturer_of_goods', 'transaction__contract_data__manufacturer_of_goods'),
            ('veterinary_hospital', 'transaction__contract_data__veterinary_hospital'),
            ('hispanic_servicing_institution', 'transaction__contract_data__hispanic_servicing_institu'),
            ('receives_contracts', 'transaction__contract_data__contracts'),
            ('receives_grants', 'transaction__contract_data__grants'),
            ('receives_contracts_and_grants', 'transaction__contract_data__receives_contracts_and_gra'),
            ('airport_authority', 'transaction__contract_data__airport_authority'),
            ('council_of_governments', 'transaction__contract_data__council_of_governments'),
            ('housing_authorities_public_tribal', 'transaction__contract_data__housing_authorities_public'),
            ('interstate_entity', 'transaction__contract_data__interstate_entity'),
            ('planning_commission', 'transaction__contract_data__planning_commission'),
            ('port_authority', 'transaction__contract_data__port_authority'),
            ('transit_authority', 'transaction__contract_data__transit_authority'),
            ('subchapter_scorporation', 'transaction__contract_data__subchapter_s_corporation'),
            ('limited_liability_corporation', 'transaction__contract_data__limited_liability_corporat'),
            ('foreign_owned_and_located', 'transaction__contract_data__foreign_owned_and_located'),
            ('for_profit_organization', 'transaction__contract_data__for_profit_organization'),
            ('nonprofit_organization', 'transaction__contract_data__nonprofit_organization'),
            ('other_not_for_profit_organization', 'transaction__contract_data__other_not_for_profit_organ'),
            ('the_ability_one_program', 'transaction__contract_data__the_ability_one_program'),
            ('private_university_or_college', 'transaction__contract_data__private_university_or_coll'),
            ('state_controlled_institution_of_higher_learning',
             'transaction__contract_data__state_controlled_instituti'),
            ('1862_land_grant_college', 'transaction__contract_data__c1862_land_grant_college'),
            ('1890_land_grant_college', 'transaction__contract_data__c1890_land_grant_college'),
            ('1994_land_grant_college', 'transaction__contract_data__c1994_land_grant_college'),
            ('minority_institution', 'transaction__contract_data__minority_institution'),
            ('historically_black_college', 'transaction__contract_data__historically_black_college'),
            ('tribal_college', 'transaction__contract_data__tribal_college'),
            ('alaskan_native_servicing_institution', 'transaction__contract_data__alaskan_native_servicing_i'),
            ('native_hawaiian_servicing_institution', 'transaction__contract_data__native_hawaiian_servicing'),
            ('school_of_forestry', 'transaction__contract_data__school_of_forestry'),
            ('veterinary_college', 'transaction__contract_data__veterinary_college'),
            ('dot_certified_disadvantage', 'transaction__contract_data__dot_certified_disadvantage'),
            ('self_certified_small_disadvantaged_business', 'transaction__contract_data__self_certified_small_disad'),
            ('small_disadvantaged_business', 'transaction__contract_data__small_disadvantaged_busine'),
            ('c8a_program_participant', 'transaction__contract_data__c8a_program_participant'),
            ('historically_underutilized_business_zone _hubzone_firm',
             'transaction__contract_data__historically_underutilized'),
            ('sba_certified_8a_joint_venture', 'transaction__contract_data__sba_certified_8_a_joint_ve'),
            ('last_modified_date', 'transaction__contract_data__last_modified')
        ]),
        'd2': OrderedDict([
            ('award_id_fain', 'transaction__assistance_data__fain'),
            ('modification_number', 'transaction__modification_number'),
            ('award_id_uri', 'transaction__assistance_data__uri'),
            ('sai_number', 'transaction__assistance_data__sai_number'),
            ('federal_action_obligation', 'transaction__federal_action_obligation'),
            ('non_federal_funding_amount', 'transaction__assistance_data__non_federal_funding_amount'),
            ('total_funding_amount', 'transaction__assistance_data__total_funding_amount'),
            ('face_value_of_loan', 'transaction__assistance_data__face_value_loan_guarantee'),
            ('original_subsidy_cost', 'transaction__original_loan_subsidy_cost'),
            ('total_subsidy_cost', 'transaction__award__total_subsidy_cost'),
            ('total_loan_value', 'transaction__award__total_loan_value'),
            ('action_date', 'transaction__action_date'),
            ('period_of_performance_start_date', 'transaction__period_of_performance_start_date'),
            ('period_of_performance_current_end_date', 'transaction__period_of_performance_current_end_date'),
            ('awarding_agency_code', 'transaction__assistance_data__awarding_agency_code'),
            ('awarding_agency_name', 'transaction__assistance_data__awarding_agency_name'),
            ('awarding_sub_agency_code', 'transaction__assistance_data__awarding_sub_tier_agency_c'),
            ('awarding_sub_agency_name', 'transaction__assistance_data__awarding_sub_tier_agency_n'),
            ('awarding_office_code', 'transaction__assistance_data__awarding_office_code'),
            ('awarding_office_name', 'transaction__assistance_data__awarding_office_name'),
            ('funding_agency_code', 'transaction__assistance_data__funding_agency_code'),
            ('funding_agency_name', 'transaction__assistance_data__funding_agency_name'),
            ('funding_sub_agency_code', 'transaction__assistance_data__funding_sub_tier_agency_co'),
            ('funding_sub_agency_name', 'transaction__assistance_data__funding_sub_tier_agency_na'),
            ('funding_office_code', 'transaction__assistance_data__funding_office_code'),
            ('funding_office_name', 'transaction__assistance_data__funding_office_name'),
            ('recipient_duns', 'transaction__assistance_data__awardee_or_recipient_uniqu'),
            ('recipient_name', 'transaction__assistance_data__awardee_or_recipient_legal'),
            ('recipient_country_code', 'transaction__assistance_data__legal_entity_country_code'),
            ('recipient_country_name', 'transaction__assistance_data__legal_entity_country_name'),
            ('recipient_address_line_1', 'transaction__assistance_data__legal_entity_address_line1'),
            ('recipient_address_line_2', 'transaction__assistance_data__legal_entity_address_line2'),
            ('recipient_address_line_3', 'transaction__assistance_data__legal_entity_address_line3'),
            ('recipient_city_code', 'transaction__assistance_data__legal_entity_city_code'),
            ('recipient_city_name', 'transaction__assistance_data__legal_entity_city_name'),
            ('recipient_county_code', 'transaction__assistance_data__legal_entity_county_code'),
            ('recipient_county_name', 'transaction__assistance_data__legal_entity_county_name'),
            ('recipient_state_code', 'transaction__assistance_data__legal_entity_state_code'),
            ('recipient_state_name', 'transaction__assistance_data__legal_entity_state_name'),
            ('recipient_zip_code', 'transaction__assistance_data__legal_entity_zip5'),
            ('recipient_zip_last_4_code', 'transaction__assistance_data__legal_entity_zip_last4'),
            ('recipient_congressional_district', 'transaction__assistance_data__legal_entity_congressional'),
            ('recipient_foreign_city_name', 'transaction__assistance_data__legal_entity_foreign_city'),
            ('recipient_foreign_province_name', 'transaction__assistance_data__legal_entity_foreign_provi'),
            ('recipient_foreign_postal_code', 'transaction__assistance_data__legal_entity_foreign_posta'),
            ('primary_place_of_performance_country_code', 'transaction__assistance_data__place_of_perform_country_c'),
            ('primary_place_of_performance_country_name', 'transaction__assistance_data__place_of_perform_country_n'),
            ('primary_place_of_performance_code', 'transaction__assistance_data__place_of_performance_code'),
            ('primary_place_of_performance_city_name', 'transaction__assistance_data__place_of_performance_city'),
            ('primary_place_of_performance_county_code', 'transaction__assistance_data__place_of_perform_county_co'),
            ('primary_place_of_performance_county_name', 'transaction__assistance_data__place_of_perform_county_na'),
            ('primary_place_of_performance_state_name', 'transaction__assistance_data__place_of_perform_state_nam'),
            ('primary_place_of_performance_zip_4', 'transaction__assistance_data__place_of_performance_zip4a'),
            ('primary_place_of_performance_congressional_district',
             'transaction__assistance_data__place_of_performance_congr'),
            ('primary_place_of_performance_foreign_location',
             'transaction__assistance_data__place_of_performance_forei'),
            ('cfda_number', 'transaction__assistance_data__cfda_number'),
            ('cfda_title', 'transaction__assistance_data__cfda_title'),
            ('assistance_type_code', 'transaction__assistance_data__assistance_type'),
            ('award_description', 'transaction__assistance_data__award_description'),
            ('business_funds_indicator_code', 'transaction__assistance_data__business_funds_indicator'),
            ('business_types_code', 'transaction__assistance_data__business_types'),
            ('action_type_code', 'transaction__action_type'),
            ('record_type_code', 'transaction__assistance_data__record_type'),
            ('fiscal_year_and_quarter_correction', 'transaction__assistance_data__fiscal_year_and_quarter_co'),
            ('last_modified_date', 'transaction__assistance_data__modified_at')
        ])
    },
    'subaward': {
        'd1': OrderedDict([
            ('subaward_number', 'subaward_number'),
            ('prime_award_piid', 'award__piid'),
            ('prime_award_parent_piid', 'award__parent_award_piid'),
            ('subaward_amount', 'amount'),
            ('subaward_action_date', 'action_date'),
            ('subaward_report_year', 'award_report_fy_year'),
            ('subaward_report_month', 'award_report_fy_month'),
            ('prime_awarding_agency_code', 'award__latest_transaction__contract_data__awarding_agency_code'),
            ('prime_awarding_agency_name', 'award__latest_transaction__contract_data__awarding_agency_name'),
            ('prime_awarding_sub_agency_code', 'award__latest_transaction__contract_data__awarding_sub_tier_agency_c'),
            ('prime_awarding_sub_agency_name', 'award__latest_transaction__contract_data__awarding_sub_tier_agency_n'),
            ('prime_awarding_office_code', 'award__latest_transaction__contract_data__awarding_office_code'),
            ('prime_awarding_office_name', 'award__latest_transaction__contract_data__awarding_office_name'),
            ('prime_award_principal_place_city',
             'award__latest_transaction__contract_data__place_of_perform_city_name'),
            ('prime_award_principal_place_state',
             'award__latest_transaction__contract_data__place_of_performance_state'),
            ('prime_award_principal_place_zip', 'award__latest_transaction__contract_data__place_of_performance_zip4a'),
            ('prime_award_principal_place_country',
             'award__latest_transaction__contract_data__place_of_perform_country_c'),
            ('prime_awardee_duns', 'award__latest_transaction__contract_data__awardee_or_recipient_uniqu'),
            ('prime_awardee_name', 'award__latest_transaction__contract_data__awardee_or_recipient_legal'),
            ('subawardee_duns', 'recipient__recipient_unique_id'),
            ('subawardee_name', 'recipient__recipient_name'),
            ('subawardee_dba_name', 'recipient__vendor_doing_as_business_name'),
            ('subawardee_parent_duns', 'recipient__parent_recipient_unique_id'),
            ('subawardee_address_line_1', 'recipient__location__address_line1'),
            ('subawardee_city_name', 'recipient__location__city_name'),
            ('subawardee_state_code', 'recipient__location__state_code'),
            ('subawardee_zip_4', 'recipient__location__zip4'),
            ('subawardee_congressional_district', 'recipient__location__congressional_code'),
            ('subawardee_country_code', 'recipient__location__location_country_code'),
            ('subawardee_foreign_postal_code', 'recipient__location__foreign_postal_code'),
            ('subaward_primary_place_of_performance_address_line_1', 'place_of_performance__address_line1'),
            ('subaward_primary_place_of_performance_city_name', 'place_of_performance__city_name'),
            ('subaward_primary_place_of_performance_state_code', 'place_of_performance__state_code'),
            ('subaward_primary_place_of_performance_address_zip_4', 'place_of_performance__zip4'),
            ('subaward_primary_place_of_performance_congressional_district',
             'place_of_performance__congressional_code'),
            ('subaward_primary_place_of_performance_country_code', 'place_of_performance__location_country_code'),
            ('subaward_description', 'description'),
            ('subaward_naics_code', 'award__latest_transaction__contract_data__naics'),
            ('subaward_naics_description', 'award__latest_transaction__contract_data__naics_description'),
            ('subawardee_business_type_code', 'recipient__business_types'),
            ('subawardee_business_type_description', 'recipient__business_types_description')
        ]),
        'd2': OrderedDict([
            ('subaward_number', 'subaward_number'),
            ('prime_award_fain', 'award__fain'),
            ('subaward_amount', 'amount'),
            ('subaward_action_date', 'action_date'),
            ('subaward_report_year', 'award_report_fy_year'),
            ('subaward_report_month', 'award_report_fy_month'),
            ('prime_awarding_agency_code', 'award__latest_transaction__assistance_data__awarding_agency_code'),
            ('prime_awarding_agency_name', 'award__latest_transaction__assistance_data__awarding_agency_name'),
            ('prime_awarding_sub_agency_code',
             'award__latest_transaction__assistance_data__awarding_sub_tier_agency_c'),
            ('prime_awarding_sub_agency_name',
             'award__latest_transaction__assistance_data__awarding_sub_tier_agency_n'),
            ('prime_award_principal_place_city',
             'award__latest_transaction__assistance_data__place_of_performance_city'),
            ('prime_award_principal_place_state',
             'award__latest_transaction__assistance_data__place_of_perform_state_nam'),
            ('prime_award_principal_place_zip',
             'award__latest_transaction__assistance_data__place_of_performance_zip4a'),
            ('prime_award_principal_place_country',
             'award__latest_transaction__assistance_data__place_of_perform_country_c'),
            ('prime_awardee_duns', 'award__latest_transaction__assistance_data__awardee_or_recipient_uniqu'),
            ('prime_awardee_name', 'award__latest_transaction__assistance_data__awardee_or_recipient_legal'),
            ('subawardee_duns', 'recipient__recipient_unique_id'),
            ('subawardee_name', 'recipient__recipient_name'),
            ('subawardee_dba_name', 'recipient__vendor_doing_as_business_name'),
            ('subawardee_address_line_1', 'recipient__location__address_line1'),
            ('subawardee_city_name', 'recipient__location__city_name'),
            ('subawardee_state_code', 'recipient__location__state_code'),
            ('subawardee_zip_4', 'recipient__location__zip4'),
            ('subawardee_congressional_district', 'recipient__location__congressional_code'),
            ('subawardee_country_code', 'recipient__location__location_country_code'),
            ('subawardee_foreign_postal_code', 'recipient__location__foreign_postal_code'),
            ('subaward_primary_place_of_performance_address_line_1', 'place_of_performance__address_line1'),
            ('subaward_primary_place_of_performance_city_name', 'place_of_performance__city_name'),
            ('subaward_primary_place_of_performance_state_code', 'place_of_performance__state_code'),
            ('subaward_primary_place_of_performance_address_zip_4', 'place_of_performance__zip4'),
            ('subaward_primary_place_of_performance_congressional_district',
             'place_of_performance__congressional_code'),
            ('subaward_primary_place_of_performance_country_code', 'place_of_performance__location_country_code'),
            ('subaward_description', 'description'),
            ('subaward_cfda_number', 'award__latest_transaction__assistance_data__cfda_number'),
            ('subaward_cfda_title', 'award__latest_transaction__assistance_data__cfda_title'),
            ('subawardee_business_type_code', 'recipient__business_types'),
            ('subawardee_business_type_description', 'recipient__business_types_description')
        ])
    }
}
