# Generated by Django 4.2.29 on 2026-05-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etl', '0005_create_award_id_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDFVersionTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_schema', models.TextField()),
                ('table_name', models.TextField()),
                ('last_processed_version', models.BigIntegerField()),
                ('last_commit_timestamp', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cdf_version_tracking',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='cdfversiontracking',
            constraint=models.UniqueConstraint(fields=('table_schema', 'table_name'), name='unique_table_schema_and_table_name'),
        ),
    ]
