DROP MATERIALIZED VIEW IF EXISTS summary_award_view_old;
DROP MATERIALIZED VIEW IF EXISTS summary_transaction_month_view_old;
DROP MATERIALIZED VIEW IF EXISTS summary_transaction_view_old;
DROP MATERIALIZED VIEW IF EXISTS summary_view_old;
DROP MATERIALIZED VIEW IF EXISTS summary_view_cfda_number_old;
DROP MATERIALIZED VIEW IF EXISTS summary_view_naics_codes_old;
DROP MATERIALIZED VIEW IF EXISTS summary_view_psc_codes_old;
DROP MATERIALIZED VIEW IF EXISTS universal_award_matview_old;
DROP MATERIALIZED VIEW IF EXISTS universal_transaction_matview_old;