# Generated by Django 2.2.9 on 2021-02-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_auto_20201204_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingagencyoverview',
            name='unlinked_procurement_c_awards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportingagencyoverview',
            name='unlinked_assistance_c_awards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportingagencyoverview',
            name='unlinked_d1_awards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportingagencyoverview',
            name='unlinked_d2_awards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportingagencyoverview',
            name='linked_procurement_awards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportingagencyoverview',
            name='linked_assistance_awards',
            field=models.IntegerField(default=0),
        ),
    ]
