# Generated by Django 2.2.18 on 2021-04-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_auto_20210202_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingagencyoverview',
            name='linked_assistance_awards',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportingagencyoverview',
            name='linked_procurement_awards',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportingagencyoverview',
            name='total_budgetary_resources',
            field=models.DecimalField(decimal_places=2, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='reportingagencyoverview',
            name='total_diff_approp_ocpa_obligated_amounts',
            field=models.DecimalField(decimal_places=2, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='reportingagencyoverview',
            name='total_dollars_obligated_gtas',
            field=models.DecimalField(decimal_places=2, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='reportingagencyoverview',
            name='unlinked_assistance_c_awards',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportingagencyoverview',
            name='unlinked_assistance_d_awards',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportingagencyoverview',
            name='unlinked_procurement_c_awards',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportingagencyoverview',
            name='unlinked_procurement_d_awards',
            field=models.IntegerField(null=True),
        ),
    ]
