# Generated by Django 4.2.29 on 2026-05-11 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_id', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ai_model',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Prompts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prompts',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.BooleanField(blank=True, default=None, help_text='positive=True, negative=False', null=True)),
                ('ai_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='llm.aimodel')),
                ('system_prompt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='llm.prompts')),
            ],
            options={
                'db_table': 'session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('latency', models.IntegerField(default=0, help_text='latency in milliseconds')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='llm.session')),
            ],
            options={
                'db_table': 'message',
                'ordering': ['session', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ToolUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tool_input', models.JSONField()),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_uses', to='llm.message')),
            ],
            options={
                'db_table': 'tool_use',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['name'], name='tool_use_name_d0052d_idx'), models.Index(fields=['created_at'], name='tool_use_created_16feec_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['-started_at'], name='session_started_177785_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['feedback'], name='session_feedbac_4e2233_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'order'], name='message_session_ce0d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='message_created_19da1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('session', 'order')},
        ),
    ]
