# Generated by Django 5.2.14 on 2026-08-13 12:34
# ruff: noqa
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="inference_config",
            field=models.JSONField(
                blank=True, default=dict, help_text="Inference configuration (e.g., temperature, topP, maxTokens)"
            ),
        ),
    ]
