# Generated by Django 5.2.14 on 2026-09-02 16:55
# ruff: noqa
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0002_create_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assistant",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                (
                    "inference_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Inference configuration (e.g., temperature, topP, maxTokens)",
                    ),
                ),
                (
                    "ai_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assistants",
                        to="llm.aimodel",
                    ),
                ),
                (
                    "system_prompt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistants",
                        to="llm.prompts",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Active/Inactive state for the assistant"
                    )
                ),
                (
                    "description",
                    models.TextField(blank=True, default="")
                )
            ],
            options={
                "db_table": "assistant",
                "ordering": ["-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="assistant",
            constraint=models.UniqueConstraint(
                fields=("name", "is_active"),
                condition=models.Q(is_active=True),
                name="only_one_active_assistant_per_name"
            ),
        ),
        migrations.AddIndex(
            model_name="assistant",
            index=models.Index(fields=["name"], name="assistant_name_e87191_idx"),
        ),
    ]
