# Generated by Django 5.2.14 on 2026-08-24 16:22
# ruff: noqa
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0002_create_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assistant",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                (
                    "inference_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Inference configuration (e.g., temperature, topP, maxTokens)",
                    ),
                ),
                (
                    "ai_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistants",
                        to="llm.aimodel",
                    ),
                ),
                (
                    "system_prompt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistants",
                        to="llm.prompts",
                    ),
                ),
            ],
            options={
                "db_table": "assistant",
                "ordering": ["-id"],
            },
        ),
        migrations.AddIndex(
            model_name="assistant",
            index=models.Index(fields=["name"], name="assistant_name_idx"),
        ),
    ]
