# Generated by Django 5.2.14 on 2026-08-31 12:00
# ruff: noqa
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0003_assistant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aimodel",
            name="inference_config",
        ),
    ]
