# Generated by Django 5.2.14
# ruff: noqa
import uuid

from django.db import migrations, models


DROP_SESSION_FKS = """
DO $$
DECLARE
    rec RECORD;
BEGIN
    FOR rec IN 
        SELECT conrelid::regclass AS tbl, conname
        FROM pg_constraint
        WHERE contype = 'f'
          AND confrelid = 'session'::regclass
    LOOP
        EXECUTE format('ALTER TABLE %s DROP CONSTRAINT IF EXISTS %I', rec.tbl, rec.conname);
    END LOOP;
END $$;
"""

FORWARD_CONVERT_SESSION_PK = """
ALTER TABLE session ADD COLUMN new_id uuid;
UPDATE session SET new_id = gen_random_uuid();
ALTER TABLE session ALTER COLUMN new_id SET NOT NULL;

ALTER TABLE message ADD COLUMN new_session_id uuid;
UPDATE message AS m
SET new_session_id = s.new_id
FROM session AS s
WHERE m.session_id = s.id;

ALTER TABLE message DROP COLUMN session_id;
ALTER TABLE session DROP CONSTRAINT session_pkey;
ALTER TABLE session DROP COLUMN id;
DROP SEQUENCE IF EXISTS session_id_seq CASCADE;

ALTER TABLE session RENAME COLUMN new_id TO id;
ALTER TABLE session ADD PRIMARY KEY (id);

ALTER TABLE message RENAME COLUMN new_session_id TO session_id;
    ALTER TABLE message ALTER COLUMN session_id SET NOT NULL;
    ALTER TABLE message
    ADD CONSTRAINT message_session_id_fk
    FOREIGN KEY (session_id) REFERENCES session(id)
    ON DELETE CASCADE
    DEFERRABLE INITIALLY DEFERRED;
"""

REVERSE_CONVERT_SESSION_PK = """
CREATE SEQUENCE IF NOT EXISTS session_id_seq;

ALTER TABLE session ADD COLUMN new_id integer NOT NULL DEFAULT nextval('session_id_seq');
ALTER TABLE message ADD COLUMN new_session_id integer;

UPDATE message AS m
SET new_session_id = s.new_id
FROM session AS s
WHERE m.session_id = s.id;

ALTER TABLE message DROP COLUMN session_id;
ALTER TABLE session DROP CONSTRAINT session_pkey;
ALTER TABLE session DROP COLUMN id;

ALTER TABLE session RENAME COLUMN new_id TO id;
ALTER TABLE session ADD PRIMARY KEY (id);
ALTER SEQUENCE session_id_seq OWNED BY session.id;
SELECT setval('session_id_seq', COALESCE((SELECT MAX(id) FROM session), 1), true);
ALTER TABLE session ALTER COLUMN id SET DEFAULT nextval('session_id_seq');

ALTER TABLE message RENAME COLUMN new_session_id TO session_id;
ALTER TABLE message ALTER COLUMN session_id SET NOT NULL;
ALTER TABLE message
    ADD CONSTRAINT message_session_id_fk
    FOREIGN KEY (session_id) REFERENCES session(id)
    ON DELETE CASCADE
    DEFERRABLE INITIALLY DEFERRED; 
"""


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0004_assistant"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="message",
            unique_together=set(),
        ),
        migrations.RemoveIndex(
            model_name="message",
            name="message_session_ce0d2f_idx",
        ),
        # Integer PKs cannot be altered to UUID in place; convert columns in SQL and
        # keep django's model state in sync via SeparateDatabaseAndState
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="session",
                    name="id",
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
            database_operations=[
                migrations.RunSQL(sql=DROP_SESSION_FKS, reverse_sql=DROP_SESSION_FKS),
                migrations.RunSQL(sql=FORWARD_CONVERT_SESSION_PK, reverse_sql=REVERSE_CONVERT_SESSION_PK),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="message",
            unique_together={("session", "order")},
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["session", "order"], name="message_session_ce0d2f_idx"),
        ),
    ]
