# Generated by Django 5.2.14 on 2026-09-02 16:55
# ruff: noqa
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("llm", "0004_assistant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistant",
            name="ai_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assistants",
                to="llm.aimodel",
            ),
        ),
        migrations.AddField(
            model_name="assistant",
            name="is_active",
            field=models.BooleanField(default=False, help_text="Active/Inactive state for the assistant"),
        ),
        migrations.AddField(
            model_name="assistant",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddConstraint(
            model_name="assistant",
            constraint=models.UniqueConstraint(
                fields=("name", "is_active"),
                condition=models.Q(is_active=True),
                name="only_one_active_assistant_per_name",
            ),
        ),
        migrations.RenameIndex(
            model_name="assistant",
            new_name="assistant_name_e87191_idx",
            old_name="assistant_name_idx",
        ),
        migrations.RemoveField(
            model_name="aimodel",
            name="inference_config",
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="model_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
