DETACHED_AWARD_PROCUREMENT_COLUMNS = {
    "detached_award_procurement_id" : {"delta": "INTEGER", "postgres": "INTEGER"},

"detached_award_proc_unique" : {"delta": "INTEGER", "postgres": "INTEGER"},
"a_76_fair_act_action" : {"delta": "INTEGER", "postgres": "INTEGER"},
"a_76_fair_act_action_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"action_date"  : {"delta": "INTEGER", "postgres": "INTEGER"},
"action_type" : {"delta": "INTEGER", "postgres": "INTEGER"},
"action_type_description" : {"delta": "INTEGER", "postgres": "INTEGER"},
"additional_reporting" : {"delta": "INTEGER", "postgres": "INTEGER"},
"agency_id" : {"delta": "INTEGER", "postgres": "INTEGER"},
"airport_authority" : {"delta": "INTEGER", "postgres": "INTEGER"},
"alaskan_native_owned_corpo" : {"delta": "INTEGER", "postgres": "INTEGER"},
"alaskan_native_servicing_i" : {"delta": "INTEGER", "postgres": "INTEGER"},
"american_indian_owned_busi" : {"delta": "INTEGER", "postgres": "INTEGER"},
"annual_revenue" : {"delta": "INTEGER", "postgres": "INTEGER"},
"asian_pacific_american_own" : {"delta": "INTEGER", "postgres": "INTEGER"},
"award_description" : {"delta": "INTEGER", "postgres": "INTEGER"},
"award_modification_amendme" : {"delta": "INTEGER", "postgres": "INTEGER"},
"award_or_idv_flag" : {"delta": "INTEGER", "postgres": "INTEGER"},
"awardee_or_recipient_legal" : {"delta": "INTEGER", "postgres": "INTEGER"},
"awardee_or_recipient_uei" : {"delta": "INTEGER", "postgres": "INTEGER"},
"awardee_or_recipient_uniqu" : {"delta": "INTEGER", "postgres": "INTEGER"},
"awarding_agency_code" : {"delta": "INTEGER", "postgres": "INTEGER"},
"awarding_agency_name" : {"delta": "INTEGER", "postgres": "INTEGER"},
"awarding_office_code" : {"delta": "INTEGER", "postgres": "INTEGER"},
"awarding_office_name" : {"delta": "INTEGER", "postgres": "INTEGER"},
"awarding_sub_tier_agency_c" : {"delta": "INTEGER", "postgres": "INTEGER"},
"awarding_sub_tier_agency_n" : {"delta": "INTEGER", "postgres": "INTEGER"},
"base_and_all_options_value" : {"delta": "INTEGER", "postgres": "INTEGER"},
"base_exercised_options_val" : {"delta": "INTEGER", "postgres": "INTEGER"},
"black_american_owned_busin" : {"delta": "INTEGER", "postgres": "INTEGER"},
"business_categories" : {"delta": "INTEGER", "postgres": "INTEGER"},
"c1862_land_grant_college" : {"delta": "INTEGER", "postgres": "INTEGER"},
"c1890_land_grant_college" : {"delta": "INTEGER", "postgres": "INTEGER"},
"c1994_land_grant_college" : {"delta": "INTEGER", "postgres": "INTEGER"},
"c8a_program_participant" : {"delta": "INTEGER", "postgres": "INTEGER"},
"cage_code" : {"delta": "INTEGER", "postgres": "INTEGER"},
"city_local_government" : {"delta": "INTEGER", "postgres": "INTEGER"},
"clinger_cohen_act_pla_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"clinger_cohen_act_planning" : {"delta": "INTEGER", "postgres": "INTEGER"},
"commercial_item_acqui_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"commercial_item_acquisitio" : {"delta": "INTEGER", "postgres": "INTEGER"},
"commercial_item_test_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"commercial_item_test_progr" : {"delta": "INTEGER", "postgres": "INTEGER"},
"community_developed_corpor" : {"delta": "INTEGER", "postgres": "INTEGER"},
"community_development_corp" : {"delta": "INTEGER", "postgres": "INTEGER"},
"consolidated_contract" : {"delta": "INTEGER", "postgres": "INTEGER"},
"consolidated_contract_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"construction_wage_rat_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"construction_wage_rate_req" : {"delta": "INTEGER", "postgres": "INTEGER"},
"contingency_humanitar_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"contingency_humanitarian_o" : {"delta": "INTEGER", "postgres": "INTEGER"},
"contract_award_type" : {"delta": "INTEGER", "postgres": "INTEGER"},
"contract_award_type_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"contract_bundling" : {"delta": "INTEGER", "postgres": "INTEGER"},
"contract_bundling_descrip" : {"delta": "INTEGER", "postgres": "INTEGER"},
"contract_financing" : {"delta": "INTEGER", "postgres": "INTEGER"},
"contract_financing_descrip" : {"delta": "INTEGER", "postgres": "INTEGER"},
"contracting_officers_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"contracting_officers_deter" : {"delta": "INTEGER", "postgres": "INTEGER"},
"contracts" : {"delta": "INTEGER", "postgres": "INTEGER"},
"corporate_entity_not_tax_e" : {"delta": "INTEGER", "postgres": "INTEGER"},
"corporate_entity_tax_exemp" : {"delta": "INTEGER", "postgres": "INTEGER"},
"cost_accounting_stand_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"cost_accounting_standards" : {"delta": "INTEGER", "postgres": "INTEGER"},
"cost_or_pricing_data" : {"delta": "INTEGER", "postgres": "INTEGER"},
"cost_or_pricing_data_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"council_of_governments" : {"delta": "INTEGER", "postgres": "INTEGER"},
"country_of_product_or_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"country_of_product_or_serv" : {"delta": "INTEGER", "postgres": "INTEGER"},
"county_local_government" : {"delta": "INTEGER", "postgres": "INTEGER"},
"created_at" : {"delta": "INTEGER", "postgres": "INTEGER"},
"current_total_value_award" : {"delta": "INTEGER", "postgres": "INTEGER"},
"division_name" : {"delta": "INTEGER", "postgres": "INTEGER"},
"division_number_or_office" : {"delta": "INTEGER", "postgres": "INTEGER"},
"dod_claimant_prog_cod_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"dod_claimant_program_code" : {"delta": "INTEGER", "postgres": "INTEGER"},
"domestic_or_foreign_e_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"domestic_or_foreign_entity" : {"delta": "INTEGER", "postgres": "INTEGER"},
"domestic_shelter" : {"delta": "INTEGER", "postgres": "INTEGER"},
"dot_certified_disadvantage" : {"delta": "INTEGER", "postgres": "INTEGER"},
"economically_disadvantaged" : {"delta": "INTEGER", "postgres": "INTEGER"},
"educational_institution" : {"delta": "INTEGER", "postgres": "INTEGER"},
"emerging_small_business" : {"delta": "INTEGER", "postgres": "INTEGER"},
"entity_data_source" : {"delta": "INTEGER", "postgres": "INTEGER"},
"epa_designated_produc_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"epa_designated_product" : {"delta": "INTEGER", "postgres": "INTEGER"},
"evaluated_preference" : {"delta": "INTEGER", "postgres": "INTEGER"},
"evaluated_preference_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"extent_compete_description" : {"delta": "INTEGER", "postgres": "INTEGER"},
"extent_competed" : {"delta": "INTEGER", "postgres": "INTEGER"},
"fair_opportunity_limi_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"fair_opportunity_limited_s" : {"delta": "INTEGER", "postgres": "INTEGER"},
"fed_biz_opps" : {"delta": "INTEGER", "postgres": "INTEGER"},
"fed_biz_opps_description" : {"delta": "INTEGER", "postgres": "INTEGER"},
"federal_action_obligation" : {"delta": "INTEGER", "postgres": "INTEGER"},
"federal_agency" : {"delta": "INTEGER", "postgres": "INTEGER"},
"federally_funded_research" : {"delta": "INTEGER", "postgres": "INTEGER"},
"for_profit_organization" : {"delta": "INTEGER", "postgres": "INTEGER"},
"foreign_funding" : {"delta": "INTEGER", "postgres": "INTEGER"},
"foreign_funding_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"foreign_government" : {"delta": "INTEGER", "postgres": "INTEGER"},
"foreign_owned_and_located" : {"delta": "INTEGER", "postgres": "INTEGER"},
"foundation" : {"delta": "INTEGER", "postgres": "INTEGER"},
"funding_agency_code" : {"delta": "INTEGER", "postgres": "INTEGER"},
"funding_agency_name" : {"delta": "INTEGER", "postgres": "INTEGER"},
"funding_office_code" : {"delta": "INTEGER", "postgres": "INTEGER"},
"funding_office_name" : {"delta": "INTEGER", "postgres": "INTEGER"},
"funding_sub_tier_agency_co" : {"delta": "INTEGER", "postgres": "INTEGER"},
"funding_sub_tier_agency_na" : {"delta": "INTEGER", "postgres": "INTEGER"},
"government_furnished_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"government_furnished_prope" : {"delta": "INTEGER", "postgres": "INTEGER"},
"grants" : {"delta": "INTEGER", "postgres": "INTEGER"},
"high_comp_officer1_amount" : {"delta": "INTEGER", "postgres": "INTEGER"},
"high_comp_officer1_full_na" : {"delta": "INTEGER", "postgres": "INTEGER"},
"high_comp_officer2_amount" : {"delta": "INTEGER", "postgres": "INTEGER"},
"high_comp_officer2_full_na" : {"delta": "INTEGER", "postgres": "INTEGER"},
"high_comp_officer3_amount" : {"delta": "INTEGER", "postgres": "INTEGER"},
"high_comp_officer3_full_na" : {"delta": "INTEGER", "postgres": "INTEGER"},
"high_comp_officer4_amount" : {"delta": "INTEGER", "postgres": "INTEGER"},
"high_comp_officer4_full_na" : {"delta": "INTEGER", "postgres": "INTEGER"},
"high_comp_officer5_amount" : {"delta": "INTEGER", "postgres": "INTEGER"},
"high_comp_officer5_full_na" : {"delta": "INTEGER", "postgres": "INTEGER"},
"hispanic_american_owned_bu" : {"delta": "INTEGER", "postgres": "INTEGER"},
"hispanic_servicing_institu" : {"delta": "INTEGER", "postgres": "INTEGER"},
"historically_black_college" : {"delta": "INTEGER", "postgres": "INTEGER"},
"historically_underutilized" : {"delta": "INTEGER", "postgres": "INTEGER"},
"hospital_flag" : {"delta": "INTEGER", "postgres": "INTEGER"},
"housing_authorities_public" : {"delta": "INTEGER", "postgres": "INTEGER"},
"idv_type" : {"delta": "INTEGER", "postgres": "INTEGER"},
"idv_type_description" : {"delta": "INTEGER", "postgres": "INTEGER"},
"indian_tribe_federally_rec" : {"delta": "INTEGER", "postgres": "INTEGER"},
"information_technolog_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"information_technology_com" : {"delta": "INTEGER", "postgres": "INTEGER"},
"inherently_government_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"inherently_government_func" : {"delta": "INTEGER", "postgres": "INTEGER"},
"initial_report_date" : {"delta": "INTEGER", "postgres": "INTEGER"},
"inter_municipal_local_gove" : {"delta": "INTEGER", "postgres": "INTEGER"},
"interagency_contract_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"interagency_contracting_au": {"delta": "INTEGER", "postgres": "INTEGER"},
"international_organization" : {"delta": "INTEGER", "postgres": "INTEGER"},
"interstate_entity" : {"delta": "INTEGER", "postgres": "INTEGER"},
"joint_venture_economically" : {"delta": "INTEGER", "postgres": "INTEGER"},
"joint_venture_women_owned" : {"delta": "INTEGER", "postgres": "INTEGER"},
"labor_standards" : {"delta": "INTEGER", "postgres": "INTEGER"},
"labor_standards_descrip" : {"delta": "INTEGER", "postgres": "INTEGER"},
"labor_surplus_area_firm" : {"delta": "INTEGER", "postgres": "INTEGER"},
"last_modified" : {"delta": "INTEGER", "postgres": "INTEGER"},
"legal_entity_address_line1" : {"delta": "INTEGER", "postgres": "INTEGER"},
"legal_entity_address_line2" : {"delta": "INTEGER", "postgres": "INTEGER"},
"legal_entity_address_line3" : {"delta": "INTEGER", "postgres": "INTEGER"},
"legal_entity_city_name" : {"delta": "INTEGER", "postgres": "INTEGER"},
"legal_entity_congressional" : {"delta": "INTEGER", "postgres": "INTEGER"},
"legal_entity_country_code" : {"delta": "INTEGER", "postgres": "INTEGER"},
"legal_entity_country_name" : {"delta": "INTEGER", "postgres": "INTEGER"},
"legal_entity_county_code" : {"delta": "INTEGER", "postgres": "INTEGER"},
"legal_entity_county_name" : {"delta": "INTEGER", "postgres": "INTEGER"},
"legal_entity_state_code" : {"delta": "INTEGER", "postgres": "INTEGER"},
"legal_entity_state_descrip" : {"delta": "INTEGER", "postgres": "INTEGER"},
"legal_entity_zip4" : {"delta": "INTEGER", "postgres": "INTEGER"},
"legal_entity_zip5" : {"delta": "INTEGER", "postgres": "INTEGER"},
"legal_entity_zip_last4" : {"delta": "INTEGER", "postgres": "INTEGER"},
"limited_liability_corporat" : {"delta": "INTEGER", "postgres": "INTEGER"},
"local_area_set_aside": {"delta": "INTEGER", "postgres": "INTEGER"},
"local_area_set_aside_desc": {"delta": "INTEGER", "postgres": "INTEGER"},
"local_government_owned": {"delta": "INTEGER", "postgres": "INTEGER"},
"major_program": {"delta": "INTEGER", "postgres": "INTEGER"},
"manufacturer_of_goods": {"delta": "INTEGER", "postgres": "INTEGER"},
"materials_supplies_article": {"delta": "INTEGER", "postgres": "INTEGER"},
"materials_supplies_descrip": {"delta": "INTEGER", "postgres": "INTEGER"},
"minority_institution": {"delta": "INTEGER", "postgres": "INTEGER"},
"minority_owned_business": {"delta": "INTEGER", "postgres": "INTEGER"},
"multi_year_contract": {"delta": "INTEGER", "postgres": "INTEGER"},
"multi_year_contract_desc": {"delta": "INTEGER", "postgres": "INTEGER"},
"multiple_or_single_aw_desc": {"delta": "INTEGER", "postgres": "INTEGER"},
"multiple_or_single_award_i": {"delta": "INTEGER", "postgres": "INTEGER"},
"municipality_local_governm": {"delta": "INTEGER", "postgres": "INTEGER"},
"naics": {"delta": "INTEGER", "postgres": "INTEGER"},
"naics_description": {"delta": "INTEGER", "postgres": "INTEGER"},
"national_interest_action": {"delta": "INTEGER", "postgres": "INTEGER"},
"national_interest_desc": {"delta": "INTEGER", "postgres": "INTEGER"},
"native_american_owned_busi": {"delta": "INTEGER", "postgres": "INTEGER"},
"native_hawaiian_owned_busi": {"delta": "INTEGER", "postgres": "INTEGER"},
"native_hawaiian_servicing": {"delta": "INTEGER", "postgres": "INTEGER"},
"nonprofit_organization": {"delta": "INTEGER", "postgres": "INTEGER"},
"number_of_actions": {"delta": "INTEGER", "postgres": "INTEGER"},
"number_of_employees": {"delta": "INTEGER", "postgres": "INTEGER"},
"number_of_offers_received": {"delta": "INTEGER", "postgres": "INTEGER"},
"ordering_period_end_date": {"delta": "INTEGER", "postgres": "INTEGER"},
"organizational_type": {"delta": "INTEGER", "postgres": "INTEGER"},
"other_minority_owned_busin": {"delta": "INTEGER", "postgres": "INTEGER"},
"other_not_for_profit_organ": {"delta": "INTEGER", "postgres": "INTEGER"},
"other_statutory_authority": {"delta": "INTEGER", "postgres": "INTEGER"},
"other_than_full_and_o_desc": {"delta": "INTEGER", "postgres": "INTEGER"},
"other_than_full_and_open_c": {"delta": "INTEGER", "postgres": "INTEGER"},
"parent_award_id": {"delta": "INTEGER", "postgres": "INTEGER"},
"partnership_or_limited_lia": {"delta": "INTEGER", "postgres": "INTEGER"},
"performance_based_se_desc": {"delta": "INTEGER", "postgres": "INTEGER"},
"performance_based_service": {"delta": "INTEGER", "postgres": "INTEGER"},
"period_of_perf_potential_e": {"delta": "INTEGER", "postgres": "INTEGER"},
"period_of_performance_curr": {"delta": "INTEGER", "postgres": "INTEGER"},
"period_of_performance_star": {"delta": "INTEGER", "postgres": "INTEGER"},
"piid": {"delta": "INTEGER", "postgres": "INTEGER"},
"place_of_manufacture": {"delta": "INTEGER", "postgres": "INTEGER"},
"place_of_manufacture_desc": {"delta": "INTEGER", "postgres": "INTEGER"},
"place_of_perf_country_desc": {"delta": "INTEGER", "postgres": "INTEGER"},
"place_of_perfor_state_desc": {"delta": "INTEGER", "postgres": "INTEGER"},
"place_of_perform_city_name": {"delta": "INTEGER", "postgres": "INTEGER"},
"place_of_perform_country_c": {"delta": "INTEGER", "postgres": "INTEGER"},
"place_of_perform_country_n": {"delta": "INTEGER", "postgres": "INTEGER"},
"place_of_perform_county_co": {"delta": "INTEGER", "postgres": "INTEGER"},
"place_of_perform_county_na": {"delta": "INTEGER", "postgres": "INTEGER"},
"place_of_perform_state_nam": {"delta": "INTEGER", "postgres": "INTEGER"},
"place_of_perform_zip_last4": {"delta": "INTEGER", "postgres": "INTEGER"},
"place_of_performance_congr": {"delta": "INTEGER", "postgres": "INTEGER"},
"place_of_performance_locat": {"delta": "INTEGER", "postgres": "INTEGER"},
"place_of_performance_state": {"delta": "INTEGER", "postgres": "INTEGER"},
"place_of_performance_zip4a": {"delta": "INTEGER", "postgres": "INTEGER"},
"place_of_performance_zip5" : {"delta": "INTEGER", "postgres": "INTEGER"},
"planning_commission" : {"delta": "INTEGER", "postgres": "INTEGER"},
"port_authority" : {"delta": "INTEGER", "postgres": "INTEGER"},
"potential_total_value_awar" : {"delta": "INTEGER", "postgres": "INTEGER"},
"price_evaluation_adjustmen" : {"delta": "INTEGER", "postgres": "INTEGER"},
"private_university_or_coll" : {"delta": "INTEGER", "postgres": "INTEGER"},
"product_or_service_co_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"product_or_service_code" : {"delta": "INTEGER", "postgres": "INTEGER"},
"program_acronym" : {"delta": "INTEGER", "postgres": "INTEGER"},
"program_system_or_equ_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"program_system_or_equipmen" : {"delta": "INTEGER", "postgres": "INTEGER"},
"pulled_from" : {"delta": "INTEGER", "postgres": "INTEGER"},
"purchase_card_as_paym_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"purchase_card_as_payment_m" : {"delta": "INTEGER", "postgres": "INTEGER"},
"receives_contracts_and_gra" : {"delta": "INTEGER", "postgres": "INTEGER"},
"recovered_materials_s_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"recovered_materials_sustai" : {"delta": "INTEGER", "postgres": "INTEGER"},
"referenced_idv_agency_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"referenced_idv_agency_iden" : {"delta": "INTEGER", "postgres": "INTEGER"},
"referenced_idv_agency_name" : {"delta": "INTEGER", "postgres": "INTEGER"},
"referenced_idv_modificatio" : {"delta": "INTEGER", "postgres": "INTEGER"},
"referenced_idv_type" : {"delta": "INTEGER", "postgres": "INTEGER"},
"referenced_idv_type_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"referenced_mult_or_si_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"referenced_mult_or_single" : {"delta": "INTEGER", "postgres": "INTEGER"},
"research" : {"delta": "INTEGER", "postgres": "INTEGER"},
"research_description" : {"delta": "INTEGER", "postgres": "INTEGER"},
"sam_exception" : {"delta": "INTEGER", "postgres": "INTEGER"},
"sam_exception_description" : {"delta": "INTEGER", "postgres": "INTEGER"},
"sba_certified_8_a_joint_ve" : {"delta": "INTEGER", "postgres": "INTEGER"},
"school_district_local_gove" : {"delta": "INTEGER", "postgres": "INTEGER"},
"school_of_forestry" : {"delta": "INTEGER", "postgres": "INTEGER"},
"sea_transportation" : {"delta": "INTEGER", "postgres": "INTEGER"},
"sea_transportation_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"self_certified_small_disad" : {"delta": "INTEGER", "postgres": "INTEGER"},
"service_disabled_veteran_o" : {"delta": "INTEGER", "postgres": "INTEGER"},
"small_agricultural_coopera" : {"delta": "INTEGER", "postgres": "INTEGER"},
"small_business_competitive" : {"delta": "INTEGER", "postgres": "INTEGER"},
"small_disadvantaged_busine" : {"delta": "INTEGER", "postgres": "INTEGER"},
"sole_proprietorship" : {"delta": "INTEGER", "postgres": "INTEGER"},
"solicitation_date" : {"delta": "INTEGER", "postgres": "INTEGER"},
"solicitation_identifier" : {"delta": "INTEGER", "postgres": "INTEGER"},
"solicitation_procedur_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"solicitation_procedures" : {"delta": "INTEGER", "postgres": "INTEGER"},
"state_controlled_instituti": {"delta": "INTEGER", "postgres": "INTEGER"},
"subchapter_s_corporation" : {"delta": "INTEGER", "postgres": "INTEGER"},
"subcontinent_asian_asian_i" : {"delta": "INTEGER", "postgres": "INTEGER"},
"subcontracting_plan" : {"delta": "INTEGER", "postgres": "INTEGER"},
"subcontracting_plan_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"the_ability_one_program" : {"delta": "INTEGER", "postgres": "INTEGER"},
"total_obligated_amount" : {"delta": "INTEGER", "postgres": "INTEGER"},
"township_local_government" : {"delta": "INTEGER", "postgres": "INTEGER"},
"transaction_number" : {"delta": "INTEGER", "postgres": "INTEGER"},
"transit_authority" : {"delta": "INTEGER", "postgres": "INTEGER"},
"tribal_college" : {"delta": "INTEGER", "postgres": "INTEGER"},
"tribally_owned_business" : {"delta": "INTEGER", "postgres": "INTEGER"},
"type_of_contract_pric_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"type_of_contract_pricing" : {"delta": "INTEGER", "postgres": "INTEGER"},
"type_of_idc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"type_of_idc_description" : {"delta": "INTEGER", "postgres": "INTEGER"},
"type_set_aside" : {"delta": "INTEGER", "postgres": "INTEGER"},
"type_set_aside_description" : {"delta": "INTEGER", "postgres": "INTEGER"},
"ultimate_parent_legal_enti" : {"delta": "INTEGER", "postgres": "INTEGER"},
"ultimate_parent_uei" : {"delta": "INTEGER", "postgres": "INTEGER"},
"ultimate_parent_unique_ide" : {"delta": "INTEGER", "postgres": "INTEGER"},
"undefinitized_action" : {"delta": "INTEGER", "postgres": "INTEGER"},
"undefinitized_action_desc" : {"delta": "INTEGER", "postgres": "INTEGER"},
"unique_award_key" : {"delta": "INTEGER", "postgres": "INTEGER"},
"updated_at" : {"delta": "INTEGER", "postgres": "INTEGER"},
"us_federal_government" : {"delta": "INTEGER", "postgres": "INTEGER"},
"us_government_entity" : {"delta": "INTEGER", "postgres": "INTEGER"},
"us_local_government" : {"delta": "INTEGER", "postgres": "INTEGER"},
"us_state_government" : {"delta": "INTEGER", "postgres": "INTEGER"},
"us_tribal_government" : {"delta": "INTEGER", "postgres": "INTEGER"},
"vendor_alternate_name" : {"delta": "INTEGER", "postgres": "INTEGER"},
"vendor_alternate_site_code" : {"delta": "INTEGER", "postgres": "INTEGER"},
"vendor_doing_as_business_n" : {"delta": "INTEGER", "postgres": "INTEGER"},
"vendor_enabled" : {"delta": "INTEGER", "postgres": "INTEGER"},
"vendor_fax_number" : {"delta": "INTEGER", "postgres": "INTEGER"},
"vendor_legal_org_name" : {"delta": "INTEGER", "postgres": "INTEGER"},
"vendor_location_disabled_f" : {"delta": "INTEGER", "postgres": "INTEGER"},
"vendor_phone_number" : {"delta": "INTEGER", "postgres": "INTEGER"},
"vendor_site_code" : {"delta": "INTEGER", "postgres": "INTEGER"},
"veteran_owned_business" : {"delta": "INTEGER", "postgres": "INTEGER"},
"veterinary_college" : {"delta": "INTEGER", "postgres": "INTEGER"},
"veterinary_hospital" : {"delta": "INTEGER", "postgres": "INTEGER"},
"woman_owned_business" : {"delta": "INTEGER", "postgres": "INTEGER"},
"women_owned_small_business" : {"delta": "INTEGER", "postgres": "INTEGER"},

}



DETACHED_AWARD_PROCUREMENT_DELTA_COLUMNS = {k: v["delta"] for k, v in DETACHED_AWARD_PROCUREMENT_COLUMNS.items()}
DETACHED_AWARD_PROCUREMENT_POSTGRES_COLUMNS = {k: v["postgres"] for k, v in DETACHED_AWARD_PROCUREMENT_COLUMNS.items()}

detached_award_procurement_create_sql_string = fr"""
    CREATE OR REPLACE TABLE {{DESTINATION_TABLE}} (
        {", ".join([f'{key} {val}' for key, val in DETACHED_AWARD_PROCUREMENT_DELTA_COLUMNS.items()])}
    )
    USING DELTA
    LOCATION 's3a://{{SPARK_S3_BUCKET}}/{{DELTA_LAKE_S3_PATH}}/{{DESTINATION_DATABASE}}/{{DESTINATION_TABLE}}'
"""

detached_award_procurement_load_sql_string =fr""