from usaspending_api.common.data_classes import TransactionColumn

TRANSACTION_FABS_COLUMN_INFO = [
    TransactionColumn("action_date", "action_date", "STRING", False),
    TransactionColumn("action_type", "action_type", "STRING", False),
    TransactionColumn("action_type_description", "action_type_description", "STRING", False),
    TransactionColumn("afa_generated_unique", "afa_generated_unique", "STRING", False),
    TransactionColumn("assistance_type", "assistance_type", "STRING", False),
    TransactionColumn("assistance_type_desc", "assistance_type_desc", "STRING", False),
    TransactionColumn("award_description", "award_description", "STRING", False),
    TransactionColumn("award_modification_amendme", "award_modification_amendme", "STRING", False),
    TransactionColumn("awardee_or_recipient_legal", "awardee_or_recipient_legal", "STRING", False),
    TransactionColumn("awardee_or_recipient_uniqu", "awardee_or_recipient_uniqu", "STRING", False),
    TransactionColumn("awarding_agency_code", "awarding_agency_code", "STRING", False),
    TransactionColumn("awarding_agency_name", "awarding_agency_name", "STRING", False),
    TransactionColumn("awarding_office_code", "awarding_office_code", "STRING", False),
    TransactionColumn("awarding_office_name", "awarding_office_name", "STRING", False),
    TransactionColumn("awarding_sub_tier_agency_c", "awarding_sub_tier_agency_c", "STRING", False),
    TransactionColumn("awarding_sub_tier_agency_n", "awarding_sub_tier_agency_n", "STRING", False),
    TransactionColumn("business_funds_ind_desc", "business_funds_ind_desc", "STRING", False),
    TransactionColumn("business_funds_indicator", "business_funds_indicator", "STRING", False),
    TransactionColumn("business_types", "business_types", "STRING", False),
    TransactionColumn("business_types_desc", "business_types_desc", "STRING", False),
    TransactionColumn("cfda_number", "cfda_number", "STRING", False),
    TransactionColumn("cfda_title", "cfda_title", "STRING", False),
    TransactionColumn("correction_delete_ind_desc", "correction_delete_ind_desc", "STRING", False),
    TransactionColumn("correction_delete_indicatr", "correction_delete_indicatr", "STRING", False),
    TransactionColumn("created_at", "created_at", "TIMESTAMP", False),
    TransactionColumn("face_value_loan_guarantee", "face_value_loan_guarantee", "NUMERIC(23,2)", False),
    TransactionColumn("fain", "fain", "STRING", False),
    TransactionColumn("federal_action_obligation", "federal_action_obligation", "NUMERIC(23,2)", False),
    TransactionColumn("fiscal_year_and_quarter_co", "fiscal_year_and_quarter_co", "STRING", False),
    TransactionColumn("funding_agency_code", "funding_agency_code", "STRING", False),
    TransactionColumn("funding_agency_name", "funding_agency_name", "STRING", False),
    TransactionColumn("funding_office_code", "funding_office_code", "STRING", False),
    TransactionColumn("funding_office_name", "funding_office_name", "STRING", False),
    TransactionColumn("funding_opportunity_goals", "funding_opportunity_goals", "STRING", False),
    TransactionColumn("funding_opportunity_number", "funding_opportunity_number", "STRING", False),
    TransactionColumn("funding_sub_tier_agency_co", "funding_sub_tier_agency_co", "STRING", False),
    TransactionColumn("funding_sub_tier_agency_na", "funding_sub_tier_agency_na", "STRING", False),
    TransactionColumn("indirect_federal_sharing", "indirect_federal_sharing", "NUMERIC(38,18)", False),
    TransactionColumn("is_active", "is_active", "BOOLEAN", False),
    TransactionColumn("is_historical", "is_historical", "BOOLEAN", False),
    TransactionColumn("legal_entity_address_line1", "legal_entity_address_line1", "STRING", False),
    TransactionColumn("legal_entity_address_line2", "legal_entity_address_line2", "STRING", False),
    TransactionColumn("legal_entity_address_line3", "legal_entity_address_line3", "STRING", False),
    TransactionColumn("legal_entity_city_code", "legal_entity_city_code", "STRING", False),
    TransactionColumn("legal_entity_city_name", "legal_entity_city_name", "STRING", False),
    TransactionColumn("legal_entity_congressional", "legal_entity_congressional", "STRING", False),
    TransactionColumn("legal_entity_country_code", "legal_entity_country_code", "STRING", False),
    TransactionColumn("legal_entity_country_name", "legal_entity_country_name", "STRING", False),
    TransactionColumn("legal_entity_county_code", "legal_entity_county_code", "STRING", False),
    TransactionColumn("legal_entity_county_name", "legal_entity_county_name", "STRING", False),
    TransactionColumn("legal_entity_foreign_city", "legal_entity_foreign_city", "STRING", False),
    TransactionColumn("legal_entity_foreign_descr", "legal_entity_foreign_descr", "STRING", False),
    TransactionColumn("legal_entity_foreign_posta", "legal_entity_foreign_posta", "STRING", False),
    TransactionColumn("legal_entity_foreign_provi", "legal_entity_foreign_provi", "STRING", False),
    TransactionColumn("legal_entity_state_code", "legal_entity_state_code", "STRING", False),
    TransactionColumn("legal_entity_state_name", "legal_entity_state_name", "STRING", False),
    TransactionColumn("legal_entity_zip5", "legal_entity_zip5", "STRING", False),
    TransactionColumn("legal_entity_zip_last4", "legal_entity_zip_last4", "STRING", False),
    TransactionColumn("modified_at", "modified_at", "TIMESTAMP", False),
    TransactionColumn("non_federal_funding_amount", "non_federal_funding_amount", "NUMERIC(23,2)", False),
    TransactionColumn("officer_1_amount", "high_comp_officer1_amount", "NUMERIC(23,2)", True),
    TransactionColumn("officer_1_name", "high_comp_officer1_full_na", "STRING", False),
    TransactionColumn("officer_2_amount", "high_comp_officer2_amount", "NUMERIC(23,2)", True),
    TransactionColumn("officer_2_name", "high_comp_officer2_full_na", "STRING", False),
    TransactionColumn("officer_3_amount", "high_comp_officer3_amount", "NUMERIC(23,2)", True),
    TransactionColumn("officer_3_name", "high_comp_officer3_full_na", "STRING", False),
    TransactionColumn("officer_4_amount", "high_comp_officer4_amount", "NUMERIC(23,2)", True),
    TransactionColumn("officer_4_name", "high_comp_officer4_full_na", "STRING", False),
    TransactionColumn("officer_5_amount", "high_comp_officer5_amount", "NUMERIC(23,2)", True),
    TransactionColumn("officer_5_name", "high_comp_officer5_full_na", "STRING", False),
    TransactionColumn("original_loan_subsidy_cost", "original_loan_subsidy_cost", "NUMERIC(23,2)", False),
    TransactionColumn("period_of_performance_curr", "period_of_performance_curr", "STRING", False),
    TransactionColumn("period_of_performance_star", "period_of_performance_star", "STRING", False),
    TransactionColumn("place_of_perfor_state_code", "place_of_perfor_state_code", "STRING", False),
    TransactionColumn("place_of_perform_country_c", "place_of_perform_country_c", "STRING", False),
    TransactionColumn("place_of_perform_country_n", "place_of_perform_country_n", "STRING", False),
    TransactionColumn("place_of_perform_county_co", "place_of_perform_county_co", "STRING", False),
    TransactionColumn("place_of_perform_county_na", "place_of_perform_county_na", "STRING", False),
    TransactionColumn("place_of_perform_state_nam", "place_of_perform_state_nam", "STRING", False),
    TransactionColumn("place_of_perform_zip_last4", "place_of_perform_zip_last4", "STRING", False),
    TransactionColumn("place_of_performance_city", "place_of_performance_city", "STRING", False),
    TransactionColumn("place_of_performance_code", "place_of_performance_code", "STRING", False),
    TransactionColumn("place_of_performance_congr", "place_of_performance_congr", "STRING", False),
    TransactionColumn("place_of_performance_forei", "place_of_performance_forei", "STRING", False),
    TransactionColumn("place_of_performance_scope", "place_of_performance_scope", "STRING", False),
    TransactionColumn("place_of_performance_zip4a", "place_of_performance_zip4a", "STRING", False),
    TransactionColumn("place_of_performance_zip5", "place_of_performance_zip5", "STRING", False),
    TransactionColumn("published_fabs_id", "published_fabs_id", "INTEGER", False),
    TransactionColumn("record_type", "record_type", "INTEGER", False),
    TransactionColumn("record_type_description", "record_type_description", "STRING", False),
    TransactionColumn("sai_number", "sai_number", "STRING", False),
    TransactionColumn("submission_id", "submission_id", "INTEGER", False),
    TransactionColumn("total_funding_amount", "total_funding_amount", "STRING", False),
    TransactionColumn("transaction_id", None, "LONG NOT NULL", False),
    TransactionColumn("uei", "uei", "STRING", False),
    TransactionColumn("ultimate_parent_legal_enti", "ultimate_parent_legal_enti", "STRING", False),
    TransactionColumn("ultimate_parent_uei", "ultimate_parent_uei", "STRING", False),
    TransactionColumn("ultimate_parent_unique_ide", "ultimate_parent_unique_ide", "STRING", False),
    TransactionColumn("unique_award_key", "unique_award_key", "STRING", False),
    TransactionColumn("updated_at", "updated_at", "TIMESTAMP", False),
    TransactionColumn("uri", "uri", "STRING", False),
]

delta_columns_not_in_view = [
    "fiscal_year_and_quarter_co",
    "is_active",
    "is_historical",
    "submission_id",
    "created_at",
    "updated_at",
]
TRANSACTION_FABS_COLUMNS = [
    col.silver_name for col in TRANSACTION_FABS_COLUMN_INFO if col.silver_name not in delta_columns_not_in_view
]

transaction_fabs_sql_string = rf"""
    CREATE OR REPLACE TABLE {{DESTINATION_TABLE}} (
        {", ".join([f'{col.silver_name} {col.delta_type}' for col in TRANSACTION_FABS_COLUMN_INFO])}
    )
    USING DELTA
    LOCATION 's3a://{{SPARK_S3_BUCKET}}/{{DELTA_LAKE_S3_PATH}}/{{DESTINATION_DATABASE}}/{{DESTINATION_TABLE}}'
    """
