from usaspending_api.awards.v2.lookups.lookups import award_type_mapping

TRANSACTION_SEARCH_COLUMNS = {
    # Keys
    "transaction_id": {"delta": "LONG NOT NULL", "postgres": "BIGINT NOT NULL", "gold": False},
    "award_id": {"delta": "LONG NOT NULL", "postgres": "BIGINT NOT NULL", "gold": False},
    # while transaction_unique_id is gold, it can't be NULL
    "transaction_unique_id": {"delta": "STRING NOT NULL", "postgres": "TEXT NOT NULL", "gold": False},
    "usaspending_unique_transaction_id": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "modification_number": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "generated_unique_award_id": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    # Dates
    "action_date": {"delta": "DATE", "postgres": "DATE", "gold": False},
    "fiscal_action_date": {"delta": "DATE", "postgres": "DATE", "gold": False},
    "last_modified_date": {"delta": "DATE", "postgres": "DATE", "gold": False},
    "fiscal_year": {"delta": "INTEGER", "postgres": "INTEGER", "gold": False},
    "award_certified_date": {"delta": "DATE", "postgres": "DATE", "gold": False},
    "award_fiscal_year": {"delta": "INTEGER", "postgres": "INTEGER", "gold": False},
    "create_date": {"delta": "TIMESTAMP", "postgres": "TIMESTAMP", "gold": True},
    "update_date": {"delta": "TIMESTAMP", "postgres": "TIMESTAMP", "gold": False},
    "award_update_date": {"delta": "TIMESTAMP", "postgres": "TIMESTAMP", "gold": False},
    "award_date_signed": {"delta": "DATE", "postgres": "DATE", "gold": False},
    "etl_update_date": {"delta": "TIMESTAMP", "postgres": "TIMESTAMP", "gold": False},
    "period_of_performance_start_date": {"delta": "DATE", "postgres": "DATE", "gold": False},
    "period_of_performance_current_end_date": {"delta": "DATE", "postgres": "DATE", "gold": False},
    "initial_report_date": {"delta": "DATE", "postgres": "DATE", "gold": False},
    # Agencies
    "awarding_agency_code": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "awarding_toptier_agency_name": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "awarding_toptier_agency_name_raw": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "funding_agency_code": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "funding_toptier_agency_name": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "funding_toptier_agency_name_raw": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "awarding_sub_tier_agency_c": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "awarding_subtier_agency_name": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "awarding_subtier_agency_name_raw": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "funding_sub_tier_agency_co": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "funding_subtier_agency_name": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "funding_subtier_agency_name_raw": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "awarding_toptier_agency_id": {"delta": "INTEGER", "postgres": "INTEGER", "gold": False},
    "funding_toptier_agency_id": {"delta": "INTEGER", "postgres": "INTEGER", "gold": False},
    "awarding_agency_id": {"delta": "INTEGER", "postgres": "INTEGER", "gold": False},
    "funding_agency_id": {"delta": "INTEGER", "postgres": "INTEGER", "gold": False},
    "awarding_toptier_agency_abbreviation": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "funding_toptier_agency_abbreviation": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "awarding_subtier_agency_abbreviation": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "funding_subtier_agency_abbreviation": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "awarding_office_code": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "awarding_office_name": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "funding_office_code": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "funding_office_name": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    # Typing
    # while is_fpds is gold, it also can't be NULL
    "is_fpds": {"delta": "BOOLEAN NOT NULL", "postgres": "BOOLEAN NOT NULL", "gold": False},
    "type_raw": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "type_description_raw": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "type": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "type_description": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "action_type": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "action_type_description": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "award_category": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "transaction_description": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "business_categories": {"delta": "ARRAY<STRING>", "postgres": "TEXT[]", "gold": False},
    # Amounts
    "award_amount": {"delta": "NUMERIC(23,2)", "postgres": "NUMERIC(23,2)", "gold": False},
    "generated_pragmatic_obligation": {"delta": "NUMERIC(23,2)", "postgres": "NUMERIC(23,2)", "gold": False},
    "federal_action_obligation": {"delta": "NUMERIC(23,2)", "postgres": "NUMERIC(23,2)", "gold": False},
    "original_loan_subsidy_cost": {"delta": "NUMERIC(23,2)", "postgres": "NUMERIC(23,2)", "gold": False},
    "face_value_loan_guarantee": {"delta": "NUMERIC(23,2)", "postgres": "NUMERIC(23,2)", "gold": False},
    "indirect_federal_sharing": {"delta": "NUMERIC(23,2)", "postgres": "NUMERIC(23,2)", "gold": True},
    "funding_amount": {"delta": "NUMERIC(23,2)", "postgres": "NUMERIC(23,2)", "gold": True},
    "total_funding_amount": {"delta": "NUMERIC(23,2)", "postgres": "NUMERIC(23,2)", "gold": True},
    "non_federal_funding_amount": {"delta": "NUMERIC(23,2)", "postgres": "NUMERIC(23,2)", "gold": True},
    # Recipient
    "recipient_hash": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "recipient_levels": {"delta": "ARRAY<STRING>", "postgres": "TEXT[]", "gold": False},
    "recipient_uei": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "recipient_name_raw": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "recipient_name": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "recipient_unique_id": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "parent_recipient_hash": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "parent_uei": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "parent_recipient_name_raw": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "parent_recipient_name": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "parent_recipient_unique_id": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    # Recipient Location
    "recipient_location_country_code": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "recipient_location_country_name": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "recipient_location_state_code": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "recipient_location_state_name": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "recipient_location_state_fips": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "recipient_location_state_population": {"delta": "INTEGER", "postgres": "INTEGER", "gold": False},
    "recipient_location_county_code": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "recipient_location_county_name": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "recipient_location_county_population": {"delta": "INTEGER", "postgres": "INTEGER", "gold": False},
    "recipient_location_congressional_code": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "recipient_location_congressional_population": {"delta": "INTEGER", "postgres": "INTEGER", "gold": False},
    "recipient_location_congressional_code_current": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "recipient_location_zip5": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "legal_entity_zip4": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "legal_entity_zip_last4": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "legal_entity_city_code": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "recipient_location_city_name": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "legal_entity_address_line1": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "legal_entity_address_line2": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "legal_entity_address_line3": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "legal_entity_foreign_city": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "legal_entity_foreign_descr": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "legal_entity_foreign_posta": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "legal_entity_foreign_provi": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "recipient_location_county_fips": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    # Place of Performance
    "place_of_performance_code": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "place_of_performance_scope": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "pop_country_code": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "pop_country_name": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "pop_state_code": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "pop_state_name": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "pop_state_fips": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "pop_state_population": {"delta": "INTEGER", "postgres": "INTEGER", "gold": False},
    "pop_county_code": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "pop_county_name": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "pop_county_population": {"delta": "INTEGER", "postgres": "INTEGER", "gold": False},
    "pop_congressional_code": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "pop_congressional_population": {"delta": "INTEGER", "postgres": "INTEGER", "gold": False},
    "pop_congressional_code_current": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "pop_zip5": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "place_of_performance_zip4a": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "place_of_perform_zip_last4": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "pop_city_name": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "place_of_performance_forei": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "pop_county_fips": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    # Accounts
    "treasury_account_identifiers": {"delta": "ARRAY<INTEGER>", "postgres": "TEXT[]", "gold": False},
    "tas_paths": {"delta": "ARRAY<STRING>", "postgres": "TEXT[]", "gold": False},
    "tas_components": {"delta": "ARRAY<STRING>", "postgres": "TEXT[]", "gold": False},
    "federal_accounts": {"delta": "STRING", "postgres": "JSONB", "gold": False},
    "disaster_emergency_fund_codes": {"delta": "ARRAY<STRING>", "postgres": "TEXT[]", "gold": False},
    # Officer Amounts
    "officer_1_name": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "officer_1_amount": {"delta": "NUMERIC(23,2)", "postgres": "NUMERIC(23,2)", "gold": True},
    "officer_2_name": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "officer_2_amount": {"delta": "NUMERIC(23,2)", "postgres": "NUMERIC(23,2)", "gold": True},
    "officer_3_name": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "officer_3_amount": {"delta": "NUMERIC(23,2)", "postgres": "NUMERIC(23,2)", "gold": True},
    "officer_4_name": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "officer_4_amount": {"delta": "NUMERIC(23,2)", "postgres": "NUMERIC(23,2)", "gold": True},
    "officer_5_name": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "officer_5_amount": {"delta": "NUMERIC(23,2)", "postgres": "NUMERIC(23,2)", "gold": True},
    # Exclusively FABS
    "published_fabs_id": {"delta": "INTEGER", "postgres": "INTEGER", "gold": False},
    "afa_generated_unique": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "business_funds_ind_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "business_funds_indicator": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "business_types": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "business_types_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "cfda_number": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "cfda_title": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "cfda_id": {"delta": "INTEGER", "postgres": "INTEGER", "gold": False},
    "correction_delete_indicatr": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "correction_delete_ind_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "fain": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "funding_opportunity_goals": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "funding_opportunity_number": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "record_type": {"delta": "INTEGER", "postgres": "INTEGER", "gold": True},
    "record_type_description": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "sai_number": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "uri": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    # Exclusively FPDS
    "detached_award_procurement_id": {"delta": "INTEGER", "postgres": "INTEGER", "gold": False},
    "detached_award_proc_unique": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "a_76_fair_act_action": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "a_76_fair_act_action_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "agency_id": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "airport_authority": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "alaskan_native_owned_corpo": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "alaskan_native_servicing_i": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "american_indian_owned_busi": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "asian_pacific_american_own": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "base_and_all_options_value": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "base_exercised_options_val": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "black_american_owned_busin": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "c1862_land_grant_college": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "c1890_land_grant_college": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "c1994_land_grant_college": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "c8a_program_participant": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "cage_code": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "city_local_government": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "clinger_cohen_act_planning": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "clinger_cohen_act_pla_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "commercial_item_acqui_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "commercial_item_acquisitio": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "commercial_item_test_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "commercial_item_test_progr": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "community_developed_corpor": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "community_development_corp": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "consolidated_contract": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "consolidated_contract_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "construction_wage_rat_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "construction_wage_rate_req": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "contingency_humanitar_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "contingency_humanitarian_o": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "contract_award_type": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "contract_award_type_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "contract_bundling": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "contract_bundling_descrip": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "contract_financing": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "contract_financing_descrip": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "contracting_officers_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "contracting_officers_deter": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "contracts": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "corporate_entity_not_tax_e": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "corporate_entity_tax_exemp": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "cost_accounting_stand_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "cost_accounting_standards": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "cost_or_pricing_data": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "cost_or_pricing_data_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "council_of_governments": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "country_of_product_or_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "country_of_product_or_serv": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "county_local_government": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "current_total_value_award": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "dod_claimant_prog_cod_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "dod_claimant_program_code": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "domestic_or_foreign_e_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "domestic_or_foreign_entity": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "domestic_shelter": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "dot_certified_disadvantage": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "economically_disadvantaged": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "educational_institution": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "emerging_small_business": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "epa_designated_produc_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "epa_designated_product": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "evaluated_preference": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "evaluated_preference_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "extent_competed": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "extent_compete_description": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "fair_opportunity_limi_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "fair_opportunity_limited_s": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "fed_biz_opps": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "fed_biz_opps_description": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "federal_agency": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "federally_funded_research": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "for_profit_organization": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "foreign_funding": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "foreign_funding_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "foreign_government": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "foreign_owned_and_located": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "foundation": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "government_furnished_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "government_furnished_prope": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "grants": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "hispanic_american_owned_bu": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "hispanic_servicing_institu": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "historically_black_college": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "historically_underutilized": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "hospital_flag": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "housing_authorities_public": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "idv_type": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "idv_type_description": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "indian_tribe_federally_rec": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "information_technolog_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "information_technology_com": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "inherently_government_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "inherently_government_func": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "inter_municipal_local_gove": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "interagency_contract_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "interagency_contracting_au": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "international_organization": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "interstate_entity": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "joint_venture_economically": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "joint_venture_women_owned": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "labor_standards": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "labor_standards_descrip": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "labor_surplus_area_firm": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "limited_liability_corporat": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "local_area_set_aside": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "local_area_set_aside_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "local_government_owned": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "major_program": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "manufacturer_of_goods": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "materials_supplies_article": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "materials_supplies_descrip": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "minority_institution": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "minority_owned_business": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "multi_year_contract": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "multi_year_contract_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "multiple_or_single_aw_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "multiple_or_single_award_i": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "municipality_local_governm": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "naics_code": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "naics_description": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "national_interest_action": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "national_interest_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "native_american_owned_busi": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "native_hawaiian_owned_busi": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "native_hawaiian_servicing": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "nonprofit_organization": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "number_of_actions": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "number_of_offers_received": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "ordering_period_end_date": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "organizational_type": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "other_minority_owned_busin": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "other_not_for_profit_organ": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "other_statutory_authority": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "other_than_full_and_o_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "other_than_full_and_open_c": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "parent_award_id": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "partnership_or_limited_lia": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "performance_based_se_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "performance_based_service": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "period_of_perf_potential_e": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "piid": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "place_of_manufacture": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "place_of_manufacture_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "planning_commission": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "port_authority": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "potential_total_value_awar": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "price_evaluation_adjustmen": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "private_university_or_coll": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "product_or_service_code": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "product_or_service_description": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "program_acronym": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "program_system_or_equ_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "program_system_or_equipmen": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "pulled_from": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "purchase_card_as_paym_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "purchase_card_as_payment_m": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "receives_contracts_and_gra": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "recovered_materials_s_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "recovered_materials_sustai": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "referenced_idv_agency_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "referenced_idv_agency_iden": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "referenced_idv_modificatio": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "referenced_idv_type": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "referenced_idv_type_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "referenced_mult_or_si_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "referenced_mult_or_single": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "research": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "research_description": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "sam_exception": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "sam_exception_description": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "sba_certified_8_a_joint_ve": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "school_district_local_gove": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "school_of_forestry": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "sea_transportation": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "sea_transportation_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "self_certified_small_disad": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "service_disabled_veteran_o": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "small_agricultural_coopera": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "small_business_competitive": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "small_disadvantaged_busine": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "sole_proprietorship": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "solicitation_date": {"delta": "DATE", "postgres": "DATE", "gold": True},
    "solicitation_identifier": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "solicitation_procedur_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "solicitation_procedures": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "state_controlled_instituti": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "subchapter_s_corporation": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "subcontinent_asian_asian_i": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "subcontracting_plan": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "subcontracting_plan_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "the_ability_one_program": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "total_obligated_amount": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "township_local_government": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "transaction_number": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "transit_authority": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "tribal_college": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "tribally_owned_business": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "type_of_contract_pricing": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "type_of_contract_pric_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "type_of_idc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "type_of_idc_description": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "type_set_aside": {"delta": "STRING", "postgres": "TEXT", "gold": False},
    "type_set_aside_description": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "undefinitized_action": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "undefinitized_action_desc": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "us_federal_government": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "us_government_entity": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "us_local_government": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "us_state_government": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "us_tribal_government": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "vendor_doing_as_business_n": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "vendor_fax_number": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "vendor_phone_number": {"delta": "STRING", "postgres": "TEXT", "gold": True},
    "veteran_owned_business": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "veterinary_college": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "veterinary_hospital": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "woman_owned_business": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "women_owned_small_business": {"delta": "BOOLEAN", "postgres": "BOOLEAN", "gold": True},
    "program_activities": {"delta": "STRING", "postgres": "JSONB", "gold": False},
}
DELTA_ONLY_COLUMNS = {
    "merge_hash_key": "LONG",
}
TRANSACTION_SEARCH_DELTA_COLUMNS = {
    **{k: v["delta"] for k, v in TRANSACTION_SEARCH_COLUMNS.items() if not v["gold"]},
    **DELTA_ONLY_COLUMNS,
}
TRANSACTION_SEARCH_GOLD_DELTA_COLUMNS = {
    **{k: v["delta"] for k, v in TRANSACTION_SEARCH_COLUMNS.items()},
    **DELTA_ONLY_COLUMNS,
}

TRANSACTION_SEARCH_POSTGRES_COLUMNS = {k: v["postgres"] for k, v in TRANSACTION_SEARCH_COLUMNS.items() if not v["gold"]}
TRANSACTION_SEARCH_POSTGRES_GOLD_COLUMNS = {k: v["postgres"] for k, v in TRANSACTION_SEARCH_COLUMNS.items()}

ALL_AWARD_TYPES = list(award_type_mapping.keys())

transaction_search_create_sql_string = rf"""
    CREATE OR REPLACE TABLE {{DESTINATION_TABLE}} (
        {", ".join([f'{key} {val}' for key, val in TRANSACTION_SEARCH_GOLD_DELTA_COLUMNS.items()])}
    )
    USING DELTA
    LOCATION 's3a://{{SPARK_S3_BUCKET}}/{{DELTA_LAKE_S3_PATH}}/{{DESTINATION_DATABASE}}/{{DESTINATION_TABLE}}'
    TBLPROPERTIES (delta.enableChangeDataFeed = true)
"""
