# Generated by Django 3.2.25 on 2024-07-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidFABASpending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spending_level', models.TextField()),
                ('funding_toptier_agency_id', models.TextField(null=True)),
                ('funding_toptier_agency_code', models.TextField(null=True)),
                ('funding_toptier_agency_name', models.TextField(null=True)),
                ('funding_subtier_agency_id', models.IntegerField(null=True)),
                ('funding_subtier_agency_code', models.TextField(null=True)),
                ('funding_subtier_agency_name', models.TextField(null=True)),
                ('funding_federal_account_id', models.IntegerField(null=True)),
                ('funding_federal_account_code', models.TextField(null=True)),
                ('funding_federal_account_name', models.TextField(null=True)),
                ('funding_treasury_account_id', models.IntegerField(null=True)),
                ('funding_treasury_account_code', models.TextField(null=True)),
                ('funding_treasury_account_name', models.TextField(null=True)),
                ('funding_major_object_class_id', models.TextField(null=True)),
                ('funding_major_object_class_code', models.TextField(null=True)),
                ('funding_major_object_class_name', models.TextField(null=True)),
                ('funding_object_class_id', models.IntegerField(null=True)),
                ('funding_object_class_code', models.TextField(null=True)),
                ('funding_object_class_name', models.TextField(null=True)),
                ('defc', models.TextField()),
                ('award_type', models.TextField(null=True)),
                ('award_count', models.IntegerField()),
                ('obligation_sum', models.DecimalField(decimal_places=2, max_digits=23, null=True)),
                ('outlay_sum', models.DecimalField(decimal_places=2, max_digits=23, null=True)),
                ('face_value_of_loan', models.DecimalField(decimal_places=2, max_digits=23, null=True)),
            ],
            options={
                'db_table': '"rpt"."covid_faba_spending"',
                'managed': True,
            },
        ),
    ]
