# Generated by Django 3.2.25 on 2024-07-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0002_update_covid_faba_spending_schema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidfabaspending',
            old_name='DEFC',
            new_name='defc',
        ),
    ]
