# Generated by Django 2.2.17 on 2021-07-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20210512_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourceprocurementtransaction',
            name='awardee_or_recipient_uei_n',
        ),
        migrations.RemoveField(
            model_name='sourceprocurementtransaction',
            name='ultimate_parent_uei_name',
        ),
    ]
