# Generated by Django 2.2.23 on 2021-07-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20210512_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceassistancetransaction',
            name='awardee_or_recipient_uei',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceassistancetransaction',
            name='ultimate_parent_uei',
            field=models.TextField(blank=True, null=True),
        ),
    ]
