# Generated by Django 2.2.23 on 2022-01-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20210929_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceprocurementtransaction',
            name='small_business_competitive',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
