# Generated by Django 2.2.24 on 2021-11-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20210929_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceassistancetransaction',
            name='awardee_or_recipient_uniqu',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourceassistancetransaction',
            name='uei',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourceassistancetransaction',
            name='ultimate_parent_uei',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourceassistancetransaction',
            name='ultimate_parent_unique_ide',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourceprocurementtransaction',
            name='awardee_or_recipient_uei',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourceprocurementtransaction',
            name='awardee_or_recipient_uniqu',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourceprocurementtransaction',
            name='ultimate_parent_uei',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sourceprocurementtransaction',
            name='ultimate_parent_unique_ide',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
