# Generated by Django 2.2.23 on 2022-01-06 18:24

from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Cast


def copy_fields(apps, _):
    """
        Used in the migration below to copy over the disaster_emergecny_fund_code column below so that
        it can be converted to a Foreign Key. This approach minimizes any downtime.
    """
    SourceProcurementTransaction = apps.get_model("transactions", "SourceProcurementTransaction")
    SourceProcurementTransaction.objects.all().update(small_business_competitive_temp=Cast(F("small_business_competitive"), output_field=models.BooleanField()))


def reverse_copy_fields(apps, _):
    """
        Used in the migration below to copy over the disaster_emergecny_fund_code column below so that
        it can be converted to a Foreign Key. This approach minimizes any downtime.
    """
    SourceProcurementTransaction = apps.get_model("transactions", "SourceProcurementTransaction")
    SourceProcurementTransaction.objects.all().update(small_business_competitive=Cast(F("small_business_competitive_temp"), output_field=models.TextField()))

class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20210929_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceprocurementtransaction',
            name='small_business_competitive_temp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.RunPython(copy_fields, reverse_code=reverse_copy_fields),
        migrations.RenameField(
            model_name='sourceprocurementtransaction',
            old_name='small_business_competitive',
            new_name='small_business_competitive_old'
        ),
        migrations.RenameField(
            model_name='sourceprocurementtransaction',
            old_name='small_business_competitive_temp',
            new_name='small_business_competitive'
        ),
        migrations.RemoveField(
            model_name='sourceprocurementtransaction',
            name='small_business_competitive_old'
        )
    ]
