# Generated by Django 4.2.23 on 2025-09-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0010_auto_20240126_1915"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="sourceassistancetransaction",
            index=models.Index(
                fields=["awarding_office_code", "funding_office_code"], name="source_assi_awardin_84f9a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sourceprocurementtransaction",
            index=models.Index(
                fields=["awarding_office_code", "funding_office_code"], name="source_proc_awardin_bdae78_idx"
            ),
        ),
    ]
