# Generated by Django 4.2.23 on 2025-10-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0010_auto_20240126_1915"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceprocurementtransaction",
            name="sba_cert_econ_disadv_wosb",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourceprocurementtransaction",
            name="sba_cert_women_own_small_bus",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourceprocurementtransaction",
            name="ser_disabvet_own_bus_join_ven",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourceprocurementtransaction",
            name="small_business_joint_venture",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
