# Generated by Django 5.2.14 on 2026-08-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_new_fpds_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceassistancetransaction',
            name='award_amount_basis_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceassistancetransaction',
            name='award_amount_basis_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceassistancetransaction',
            name='award_recipient_basis_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sourceassistancetransaction',
            name='award_recipient_basis_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
