# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltransactionassistance',
            old_name='cfda',
            new_name='cfda_old',
        ),
        migrations.RenameField(
            model_name='subaward',
            old_name='cfda',
            new_name='cfda_old',
        ),
        migrations.RenameField(
            model_name='transactionassistance',
            old_name='cfda',
            new_name='cfda_old',
        ),
    ]
