# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
        ('accounts', '0001_initial'),
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccountsByAwards',
            fields=[
                ('financial_accounts_by_awards_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_activity_name', models.CharField(blank=True, max_length=164, null=True)),
                ('by_direct_reimbursable_fun', models.CharField(blank=True, max_length=1, null=True)),
                ('piid', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_award_id', models.CharField(blank=True, max_length=50, null=True)),
                ('fain', models.CharField(blank=True, max_length=30, null=True)),
                ('uri', models.CharField(blank=True, max_length=70, null=True)),
                ('award_type', models.CharField(blank=True, max_length=30, null=True)),
                ('ussgl480100_undelivered_or_fyb', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('ussgl480100_undelivered_or_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('ussgl483100_undelivered_or_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('ussgl488100_upward_adjustm_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('ussgl490100_delivered_orde_fyb', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('ussgl490100_delivered_orde_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('ussgl493100_delivered_orde_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('ussgl498100_upward_adjustm_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('ussgl480200_undelivered_or_fyb', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('ussgl480200_undelivered_or_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('ussgl483200_undelivered_or_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('ussgl488200_upward_adjustm_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('ussgl490200_delivered_orde_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('ussgl490800_authority_outl_fyb', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('ussgl490800_authority_outl_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('ussgl498200_upward_adjustm_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('obligations_undelivered_or_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('obligations_delivered_orde_fyb', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('obligations_delivered_orde_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('gross_outlays_undelivered_fyb', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('gross_outlays_undelivered_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('gross_outlays_delivered_or_fyb', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('gross_outlay_amount_by_awa_fyb', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('gross_outlay_amount_by_awa_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('obligations_incurred_byawa_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('ussgl487100_downward_adjus_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('ussgl497100_downward_adjus_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('ussgl487200_downward_adjus_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('ussgl497200_downward_adjus_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('deobligations_recov_by_awa_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('obligations_undelivered_or_fyb', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('gross_outlays_delivered_or_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('drv_award_id_field_type', models.CharField(blank=True, max_length=10, null=True)),
                ('drv_oblig_incur_total_by_award', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('reporting_period_start', models.DateField(blank=True, null=True)),
                ('reporting_period_end', models.DateField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('create_user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('update_user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('appropriation_account_balances', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.AppropriationAccountBalances')),
                ('object_class', models.ForeignKey(db_column='object_class', on_delete=django.db.models.deletion.DO_NOTHING, to='references.RefObjectClassCode')),
                ('program_activity_code', models.ForeignKey(blank=True, db_column='program_activity_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='references.RefProgramActivity')),
            ],
            options={
                'db_table': 'financial_accounts_by_awards',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FinancialAccountsByAwardsTransactionObligations',
            fields=[
                ('financial_accounts_by_awards_transaction_obligations_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_obligated_amou', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('reporting_period_start', models.DateField(blank=True, null=True)),
                ('reporting_period_end', models.DateField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('create_user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('update_user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('financial_accounts_by_awards', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='awards.FinancialAccountsByAwards')),
            ],
            options={
                'db_table': 'financial_accounts_by_awards_transaction_obligations',
                'managed': True,
            },
        ),
    ]
