# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='awarding_agency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='date_signed',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='obligated_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='recipient_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
