# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20160912_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='award_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
