# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0006_cfda'),
        ('awards', '0002_auto_20170515_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransactionassistance',
            name='cfda_new',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='references.CFDA'),
        ),
        migrations.AddField(
            model_name='subaward',
            name='cfda_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_subawards', to='references.CFDA'),
        ),
        migrations.AddField(
            model_name='transactionassistance',
            name='cfda_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_assistance', to='references.CFDA'),
        ),
    ]
