# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_auto_20171102_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subaward',
            name='submission',
        ),
    ]
