# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_auto_20160912_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='recipient_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
