# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0007_migrate_cfda_data'),
        ('awards', '0003_auto_20170515_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltransactionassistance',
            old_name='cfda_new',
            new_name='cfda',
        ),
        migrations.RenameField(
            model_name='subaward',
            old_name='cfda_new',
            new_name='cfda',
        ),
        migrations.RenameField(
            model_name='transactionassistance',
            old_name='cfda_new',
            new_name='cfda',
        ),
        migrations.RemoveField(
            model_name='historicaltransactionassistance',
            name='cfda_old',
        ),
        migrations.RemoveField(
            model_name='subaward',
            name='cfda_old',
        ),
        migrations.RemoveField(
            model_name='transactionassistance',
            name='cfda_old',
        ),
    ]
