# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20160912_1756'),
        ('awards', '0004_auto_20160912_1744'),
    ]

    operations = [
    ]
