# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_auto_20171107_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='category',
            field=models.TextField(db_index=True, help_text="A field that generalizes the award's type.", null=True, verbose_name='Category'),
        ),
    ]
