# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_remove_subaward_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subaward',
            name='naics',
        ),
        migrations.RemoveField(
            model_name='subaward',
            name='naics_description',
        ),
    ]
