# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_auto_20171102_1849'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subaward',
            unique_together=set([]),
        ),
    ]
