# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_auto_20170518_1919'),
        ('awards', '0003_auto_20170517_1830'),
    ]

    operations = [
    ]
