# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_merge_20160912_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='appropriation_account_balances',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AppropriationAccountBalances'),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawardstransactionobligations',
            name='financial_accounts_by_awards',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.FinancialAccountsByAwards'),
        ),
    ]
