# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_merge_20170523_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='fiscal_year',
            field=models.IntegerField(blank=True, help_text='Fiscal Year calculated based on Action Date', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fiscal_year',
            field=models.IntegerField(blank=True, help_text='Fiscal Year calculated based on Action Date', null=True),
        ),
    ]
