# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_auto_20171115_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionfpds',
            name='parent_award_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
