# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-06 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0007_auto_20170602_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='ordering_period_end_date',
            field=models.DateField(blank=True, help_text='The end date for the ordering period', null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='ordering_period_end_date',
            field=models.DateField(blank=True, help_text='The end date for the ordering period', null=True),
        ),
    ]

    # Django automatically updates the existing text values to dates - even though the formats
    # vary - and gets them right.  Impressive.
