# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0007_auto_20171115_2106'),
        ('awards', '0003_update_award_subaward_table'),
    ]

    operations = [
    ]
