# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0007_auto_20160921_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialassistanceaward',
            name='action_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='action_date',
            field=models.CharField(max_length=10),
        ),
    ]
