# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-13 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0008_auto_20170606_1838'),
        ('awards', '0007_auto_20170601_1715'),
    ]

    operations = [
    ]
