# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0009_auto_20160921_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='current_aggregated_total_v',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='current_total_value_adjust',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='parent_award_awarding_agency_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='potential_aggregated_idv_t',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='potential_aggregated_total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='potential_idv_total_est',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='potential_total_value_adju',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='rec_flag',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
