# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-15 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0009_merge_20170613_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransaction',
            name='action_date',
            field=models.DateField(db_index=True, help_text='The date this transaction was actioned', verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='type',
            field=models.TextField(db_index=True, help_text='The type for this transaction. For example, A, B, C, D', null=True, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='historicaltransactionassistance',
            name='fain',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactionassistance',
            name='uri',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='parent_award_id',
            field=models.TextField(blank=True, db_index=True, help_text='The parent award id for this transaction. This is generally the piid of an IDV', null=True, verbose_name='Parent Award ID'),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='piid',
            field=models.TextField(blank=True, db_index=True, help_text='The PIID of this transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action_date',
            field=models.DateField(db_index=True, help_text='The date this transaction was actioned', verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.TextField(db_index=True, help_text='The type for this transaction. For example, A, B, C, D', null=True, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='transactionassistance',
            name='fain',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionassistance',
            name='uri',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='parent_award_id',
            field=models.TextField(blank=True, db_index=True, help_text='The parent award id for this transaction. This is generally the piid of an IDV', null=True, verbose_name='Parent Award ID'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='piid',
            field=models.TextField(blank=True, db_index=True, help_text='The PIID of this transaction'),
        ),
    ]
