# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 19:08
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0009_sumaryviews_universal'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientLookupView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_unique_id', models.TextField()),
                ('recipient_name', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'recipient_lookup_view',
            },
        ),
        migrations.CreateModel(
            name='SummaryTransactionView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateField(blank=True)),
                ('fiscal_year', models.IntegerField()),
                ('month', models.TextField()),
                ('type', models.TextField(blank=True, null=True)),
                ('total_obl_bin', models.TextField()),
                ('federal_action_obligation', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=20, null=True)),
                ('recipient_location_country_code', models.TextField()),
                ('recipient_location_country_name', models.TextField()),
                ('recipient_location_state_code', models.TextField()),
                ('recipient_location_county_code', models.TextField()),
                ('recipient_location_county_name', models.TextField()),
                ('recipient_location_congressional_code', models.TextField()),
                ('recipient_location_zip5', models.TextField()),
                ('pop_country_code', models.TextField()),
                ('pop_country_name', models.TextField()),
                ('pop_zip5', models.TextField()),
                ('pop_county_code', models.TextField()),
                ('pop_county_name', models.TextField()),
                ('pop_state_code', models.TextField()),
                ('pop_congressional_code', models.TextField()),
                ('awarding_toptier_agency_name', models.TextField()),
                ('funding_toptier_agency_name', models.TextField()),
                ('awarding_toptier_agency_abbreviation', models.TextField()),
                ('funding_toptier_agency_abbreviation', models.TextField()),
                ('business_categories', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('cfda_number', models.TextField()),
                ('cfda_title', models.TextField()),
                ('cfda_popular_name', models.TextField()),
                ('psc_code', models.TextField()),
                ('psc_description', models.TextField()),
                ('naics_code', models.TextField()),
                ('naics_description', models.TextField()),
                ('type_of_contract_pricing', models.TextField()),
                ('type_set_aside', models.TextField()),
                ('extent_competed', models.TextField()),
                ('counts', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'summary_transaction_view',
            },
        ),
    ]
