# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-07 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0010_indices_d1_d2_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='category',
            field=models.TextField(help_text="A field that generalizes the award's type.", null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.TextField(db_index=True, help_text='A description of the award', null=True, verbose_name='Award Description'),
        ),
        migrations.AlterField(
            model_name='award',
            name='type',
            field=models.TextField(db_index=True, help_text='The mechanism used to distribute funding. The federal government can distribute funding in several forms. These award types include contracts, grants, loans, and direct payments.', null=True, verbose_name='Award Type'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='description',
            field=models.TextField(db_index=True, help_text='The description of this transaction', null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='extent_competed',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='naics',
            field=models.TextField(blank=True, db_index=True, help_text='Specified which industry the work for this transaction falls into. A 6-digit code', null=True, verbose_name='NAICS'),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='product_or_service_code',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='type_of_contract_pricing',
            field=models.TextField(blank=True, db_index=True, default='UN', help_text='The type of contract pricing data, as a code', null=True, verbose_name='Type of Contract Pricing'),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='type_set_aside',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Type Set Aside'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(db_index=True, help_text='The description of this transaction', null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='extent_competed',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='naics',
            field=models.TextField(blank=True, db_index=True, help_text='Specified which industry the work for this transaction falls into. A 6-digit code', null=True, verbose_name='NAICS'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='product_or_service_code',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='type_of_contract_pricing',
            field=models.TextField(blank=True, db_index=True, default='UN', help_text='The type of contract pricing data, as a code', null=True, verbose_name='Type of Contract Pricing'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='type_set_aside',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Type Set Aside'),
        ),
    ]
