# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-13 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0011_auto_20170907_1648'),
        ('awards', '0011_auto_20170907_1421'),
    ]

    operations = [
    ]
