# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-19 16:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awards', '0012_auto_20170919_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='base_and_all_options_value',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2,
                                      help_text='The sum of the base_and_all_options_value from associated transactions',
                                      max_digits=20, null=True, verbose_name='Base and All Options Value'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='base_and_all_options_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The base and all options value',
                                      max_digits=20, null=True, verbose_name='Base and all Options Value'),
        ),
        migrations.AlterField(
            model_name='award',
            name='latest_transaction',
            field=models.ForeignKey(help_text='The latest transaction by action_date associated with this award',
                                    null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='latest_for_award', to='awards.TransactionNormalized'),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='base_and_all_options_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The base and all options value',
                                      max_digits=20, null=True, verbose_name='Base and all Options Value'),
        ),
    ]
