# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-12 18:47
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0012_upper_index_fain_uri_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.TextField(blank=True)),
                ('type_name', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'award_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SummaryCfdaNumbersView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateField(blank=True, null=True)),
                ('fiscal_year', models.IntegerField()),
                ('type', models.TextField(blank=True, null=True)),
                ('pulled_from', models.TextField()),
                ('cfda_number', models.TextField(blank=True, null=True)),
                ('cfda_title', models.TextField(blank=True, null=True)),
                ('federal_action_obligation', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('counts', models.IntegerField()),
            ],
            options={
                'db_table': 'summary_view_cfda_number',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SummaryNaicsCodesView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateField(blank=True, null=True)),
                ('fiscal_year', models.IntegerField()),
                ('type', models.TextField(blank=True, null=True)),
                ('pulled_from', models.TextField()),
                ('naics_code', models.TextField(blank=True, null=True)),
                ('naics_description', models.TextField(blank=True, null=True)),
                ('federal_action_obligation', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('counts', models.IntegerField()),
            ],
            options={
                'db_table': 'summary_view_naics_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SummaryPscCodesView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateField(blank=True, null=True)),
                ('fiscal_year', models.IntegerField()),
                ('type', models.TextField(blank=True, null=True)),
                ('pulled_from', models.TextField()),
                ('product_or_service_code', models.TextField(blank=True, null=True)),
                ('federal_action_obligation', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('counts', models.IntegerField()),
            ],
            options={
                'db_table': 'summary_view_psc_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SummaryTransactionMonthView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateField()),
                ('fiscal_year', models.IntegerField()),
                ('type', models.TextField()),
                ('pulled_from', models.TextField()),
                ('recipient_location_country_name', models.TextField()),
                ('recipient_location_country_code', models.TextField()),
                ('recipient_location_state_code', models.TextField()),
                ('recipient_location_county_name', models.TextField()),
                ('recipient_location_county_code', models.TextField()),
                ('recipient_location_zip5', models.TextField()),
                ('recipient_location_congressional_code', models.TextField()),
                ('recipient_location_foreign_province', models.TextField()),
                ('pop_country_name', models.TextField()),
                ('pop_country_code', models.TextField()),
                ('pop_state_code', models.TextField()),
                ('pop_county_name', models.TextField()),
                ('pop_county_code', models.TextField()),
                ('pop_zip5', models.TextField()),
                ('pop_congressional_code', models.TextField()),
                ('awarding_toptier_agency_name', models.TextField(blank=True, null=True)),
                ('awarding_toptier_agency_abbreviation', models.TextField(blank=True, null=True)),
                ('funding_toptier_agency_name', models.TextField(blank=True, null=True)),
                ('funding_toptier_agency_abbreviation', models.TextField(blank=True, null=True)),
                ('awarding_subtier_agency_name', models.TextField(blank=True, null=True)),
                ('awarding_subtier_agency_abbreviation', models.TextField(blank=True, null=True)),
                ('funding_subtier_agency_name', models.TextField(blank=True, null=True)),
                ('funding_subtier_agency_abbreviation', models.TextField(blank=True, null=True)),
                ('business_categories', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('cfda_number', models.TextField(blank=True, null=True)),
                ('cfda_title', models.TextField(blank=True, null=True)),
                ('cfda_popular_name', models.TextField(blank=True, null=True)),
                ('product_or_service_code', models.TextField()),
                ('product_or_service_description', models.TextField()),
                ('naics_code', models.TextField(blank=True, null=True)),
                ('naics_description', models.TextField(blank=True, null=True)),
                ('total_obl_bin', models.TextField()),
                ('type_of_contract_pricing', models.TextField()),
                ('type_set_aside', models.TextField()),
                ('extent_competed', models.TextField()),
                ('federal_action_obligation', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('counts', models.IntegerField()),
            ],
            options={
                'db_table': 'summary_transaction_month_view',
                'managed': False,
            },
        ),
    ]
