# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0012_auto_20160926_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialaccountsbyawards',
            name='create_user_id',
        ),
        migrations.RemoveField(
            model_name='financialaccountsbyawards',
            name='update_user_id',
        ),
        migrations.RemoveField(
            model_name='financialaccountsbyawardstransactionobligations',
            name='create_user_id',
        ),
        migrations.RemoveField(
            model_name='financialaccountsbyawardstransactionobligations',
            name='update_user_id',
        ),
        migrations.RemoveField(
            model_name='financialassistanceaward',
            name='create_user_id',
        ),
        migrations.RemoveField(
            model_name='financialassistanceaward',
            name='update_user_id',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='create_user_id',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='update_user_id',
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawardstransactionobligations',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawardstransactionobligations',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialassistanceaward',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialassistanceaward',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
