# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 20:51
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0012_upper_index_fain_uri_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfabs',
            name='place_of_perfor_state_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfabs',
            name='place_of_perform_zip_last4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfabs',
            name='place_of_performance_zip5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfpds',
            name='legal_entity_county_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfpds',
            name='legal_entity_county_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfpds',
            name='legal_entity_zip5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfpds',
            name='legal_entity_zip_last4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfpds',
            name='place_of_perform_county_co',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfpds',
            name='place_of_perform_zip_last4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfpds',
            name='place_of_performance_zip5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
