# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0011_auto_20160927_1911'),
        ('awards', '0013_auto_20160927_1154'),
    ]

    operations = [
    ]
