# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-21 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0013_historicaltransactionfabs_historicaltransactionfpds'),
        ('awards', '0012_merge_20170913_2000'),
    ]

    operations = [
    ]
