# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-20 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0014_auto_20170919_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltransactionfabs',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltransactionfabs',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='historicaltransactionfpds',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltransactionfpds',
            name='transaction',
        ),
        migrations.AlterField(
            model_name='award',
            name='base_and_all_options_value',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='The sum of the base_and_all_options_value from associated transactions', max_digits=20, null=True, verbose_name='Base and All Options Value'),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='base_and_all_options_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The base and all options value', max_digits=20, null=True, verbose_name='Base and all Options Value'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='base_and_all_options_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The base and all options value', max_digits=20, null=True, verbose_name='Base and all Options Value'),
        ),
        migrations.DeleteModel(
            name='HistoricalTransactionFABS',
        ),
        migrations.DeleteModel(
            name='HistoricalTransactionFPDS',
        ),
    ]
