# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0015_auto_20160929_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subaward',
            name='award',
        ),
        migrations.RemoveField(
            model_name='subaward',
            name='legal_entity',
        ),
        migrations.RemoveField(
            model_name='subaward',
            name='place_of_performance_relationship',
        ),
        migrations.RemoveField(
            model_name='placeofperformancerelationship',
            name='sub_award',
        ),
        migrations.DeleteModel(
            name='SubAward',
        ),
    ]
