# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0015_auto_20180123_2011'),
        ('awards', '0016_transactionnormalized_generated_unique_award_id'),
    ]

    operations = [
    ]
