# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0019_merge_20160928_1603'),
        ('awards', '0016_auto_20160929_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeofperformancerelationship',
            name='award',
        ),
        migrations.RemoveField(
            model_name='placeofperformancerelationship',
            name='location',
        ),
        migrations.AddField(
            model_name='award',
            name='place_of_performance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='references.Location'),
        ),
        migrations.DeleteModel(
            name='PlaceOfPerformanceRelationship',
        ),
    ]
