# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-29 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0017_merge_20180125_2132'),
        ('awards', '0015_summarytransactiongeoview'),
    ]

    operations = [
    ]
