# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0018_merge_20180129_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='base_and_all_options_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The sum of the base_and_all_options_value from associated transactions', max_digits=20, null=True, verbose_name='Base and All Options Value'),
        ),
        migrations.AlterField(
            model_name='award',
            name='category',
            field=models.TextField(help_text="A field that generalizes the award's type.", null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='award',
            name='date_signed',
            field=models.DateField(help_text='The date the award was signed', null=True, verbose_name='Award Date'),
        ),
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.TextField(help_text='A description of the award', null=True, verbose_name='Award Description'),
        ),
        migrations.AlterField(
            model_name='award',
            name='fain',
            field=models.TextField(blank=True, help_text="An identification code assigned to each financial assistance award tracking purposes. The FAIN is tied to that award (and all future modifications to that award) throughout the award's life. Each FAIN is assigned by an agency. Within an agency, FAIN are unique: each new award must be issued a new FAIN. FAIN stands for Federal Award Identification Number, though the digits are letters, not numbers.", null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='period_of_performance_current_end_date',
            field=models.DateField(help_text='The current, not original, period of performance end date', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='award',
            name='period_of_performance_start_date',
            field=models.DateField(help_text='The start date for the period of performance', null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='award',
            name='piid',
            field=models.TextField(blank=True, help_text='Procurement Instrument Identifier - A unique identifier assigned to a federal contract, purchase order, basic ordering agreement, basic agreement, and blanket purchase agreement. It is used to track the contract, and any modifications or transactions related to it. After October 2017, it is between 13 and 17 digits, both letters and numbers.', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='potential_total_value_of_award',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The sum of the potential_value_of_award from associated transactions', max_digits=20, null=True, verbose_name='Potential Total Value of Award'),
        ),
        migrations.AlterField(
            model_name='award',
            name='total_obligation',
            field=models.DecimalField(decimal_places=2, help_text='The amount of money the government is obligated to pay for the award', max_digits=15, null=True, verbose_name='Total Obligated'),
        ),
        migrations.AlterField(
            model_name='award',
            name='total_outlay',
            field=models.DecimalField(decimal_places=2, help_text='The total amount of money paid out for this award', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='uri',
            field=models.TextField(blank=True, help_text='The uri of the award', null=True),
        ),
        migrations.AlterField(
            model_name='transactionfabs',
            name='fain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionfabs',
            name='published_award_financial_assistance_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionfabs',
            name='uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionfpds',
            name='detached_award_procurement_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionfpds',
            name='parent_award_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionfpds',
            name='piid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionfpds',
            name='pulled_from',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionfpds',
            name='type_of_contract_pricing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionfpds',
            name='type_set_aside',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionnormalized',
            name='last_modified_date',
            field=models.DateField(blank=True, db_index=True, help_text='The date this transaction was last modified', null=True),
        ),
        migrations.AlterField(
            model_name='transactionnormalized',
            name='type',
            field=models.TextField(help_text='The type for this transaction. For example, A, B, C, D', null=True, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='transactionnormalized',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='The last time this transaction was updated in the API', null=True),
        ),
    ]
