# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0018_auto_20161004_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialaccountsbyawardstransactionobligations',
            old_name='transaction_obligated_amou',
            new_name='transaction_obligated_amount',
        ),
    ]
