# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0019_auto_20180201_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionnormalized',
            name='is_fpds',
            field=models.BooleanField(default=False, verbose_name='Is FPDS'),
        ),
    ]
