# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0020_auto_20161004_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialassistanceaward',
            old_name='award_modification_amendme',
            new_name='award_modification_amendment_number',
        ),
        migrations.RenameField(
            model_name='financialassistanceaward',
            old_name='current_total_value_award',
            new_name='current_total_award_value_amount_adjustment',
        ),
        migrations.RenameField(
            model_name='financialassistanceaward',
            old_name='potential_total_value_adju',
            new_name='potential_total_award_value_amount_adjustment',
        ),
        migrations.RenameField(
            model_name='procurement',
            old_name='award_modification_amendme',
            new_name='award_modification_amendment_number',
        ),
        migrations.AddField(
            model_name='procurement',
            name='current_total_award_value_amount_adjustment',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='potential_total_award_value_amount_adjustment',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
    ]
