# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0020_transactionnormalized_is_fpds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionfabs',
            name='afa_generated_unique',
            field=models.TextField(unique=True),
        ),
    ]
