# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0022_auto_20161004_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialassistanceaward',
            old_name='correction_late_delete_ind',
            new_name='correction_late_delete_indicator',
        ),
        migrations.RenameField(
            model_name='financialassistanceaward',
            old_name='drv_awd_fin_assist_type_label',
            new_name='drv_award_finance_assistance_type_label',
        ),
        migrations.RenameField(
            model_name='financialassistanceaward',
            old_name='federal_funding_amount',
            new_name='drv_federal_funding_amount',
        ),
        migrations.RenameField(
            model_name='financialassistanceaward',
            old_name='fiscal_year_and_quarter_co',
            new_name='fiscal_year_and_quarter_correction',
        ),
    ]
