# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0023_auto_20161004_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialaccountsbyawards',
            old_name='drv_oblig_incur_total_by_award',
            new_name='drv_obligations_incurred_total_by_award',
        ),
    ]
