# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0024_auto_20161004_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialassistanceaward',
            old_name='current_total_award_value_amount_adjustment',
            new_name='drv_current_total_award_value_amount_adjustment',
        ),
        migrations.RenameField(
            model_name='financialassistanceaward',
            old_name='potential_total_award_value_amount_adjustment',
            new_name='drv_potential_total_award_value_amount_adjustment',
        ),
        migrations.RenameField(
            model_name='procurement',
            old_name='current_total_award_value_amount_adjustment',
            new_name='drv_current_total_award_value_amount_adjustment',
        ),
        migrations.RenameField(
            model_name='procurement',
            old_name='potential_total_award_value_amount_adjustment',
            new_name='drv_potential_total_award_value_amount_adjustment',
        ),
    ]
