# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0027_auto_20161005_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='price_evaluation_adjustment_preference_percent_difference',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
