# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-02 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0027_add_loan_value_to_awards_and_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='total_funding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="A summation of this award's transactions' funding amount", max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transactionnormalized',
            name='funding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Assistance data variable.  non_federal_funding_amount + federal_action_obligation', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transactionnormalized',
            name='non_federal_funding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Assistance Data variable.', max_digits=20, null=True),
        ),
    ]
