# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-23 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0028_auto_20180402_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionfabs',
            old_name='correction_late_delete_ind',
            new_name='correction_delete_indicatr',
        ),
        migrations.RenameField(
            model_name='transactionfpds',
            old_name='davis_bacon_act_descrip',
            new_name='construction_wage_rat_desc',
        ),
        migrations.RenameField(
            model_name='transactionfpds',
            old_name='davis_bacon_act',
            new_name='construction_wage_rate_req',
        ),
        migrations.RenameField(
            model_name='transactionfpds',
            old_name='government_furnished_equip',
            new_name='government_furnished_prope',
        ),
        migrations.RenameField(
            model_name='transactionfpds',
            old_name='service_contract_act',
            new_name='labor_standards',
        ),
        migrations.RenameField(
            model_name='transactionfpds',
            old_name='service_contract_act_desc',
            new_name='labor_standards_descrip',
        ),
        migrations.RenameField(
            model_name='transactionfpds',
            old_name='walsh_healey_act',
            new_name='materials_supplies_article',
        ),
        migrations.RenameField(
            model_name='transactionfpds',
            old_name='walsh_healey_act_descrip',
            new_name='materials_supplies_descrip',
        ),
        migrations.AddField(
            model_name='transactionfabs',
            name='action_type_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfabs',
            name='assistance_type_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfabs',
            name='business_funds_ind_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfabs',
            name='business_types_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfabs',
            name='correction_delete_ind_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfabs',
            name='record_type_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfabs',
            name='ultimate_parent_legal_enti',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfabs',
            name='ultimate_parent_unique_ide',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfpds',
            name='cage_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfpds',
            name='inherently_government_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfpds',
            name='inherently_government_func',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfpds',
            name='organizational_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
