# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-02 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0028_auto_20180329_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionnormalized',
            old_name='total_funding_amount',
            new_name='funding_amount',
        ),
        migrations.AddField(
            model_name='transactionfabs',
            name='funding_amount',
            field=models.TextField(blank=True, null=True),
        ),
    ]
