# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0029_auto_20161006_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='deobligations_recoveries_refunds_of_prior_year_by_award_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='drv_obligations_incurred_total_by_award',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='gross_outlay_amount_by_award_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='gross_outlay_amount_by_award_fyb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='gross_outlays_delivered_orders_paid_total_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='gross_outlays_delivered_orders_paid_total_fyb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='gross_outlays_undelivered_orders_prepaid_total_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='gross_outlays_undelivered_orders_prepaid_total_fyb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='obligations_delivered_orders_unpaid_total_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='obligations_delivered_orders_unpaid_total_fyb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='obligations_incurred_total_by_award_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='obligations_undelivered_orders_unpaid_total_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='obligations_undelivered_orders_unpaid_total_fyb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='ussgl480100_undelivered_orders_obligations_unpaid_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='ussgl480100_undelivered_orders_obligations_unpaid_fyb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='ussgl480200_undelivered_orders_oblig_prepaid_advanced_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='ussgl480200_undelivered_orders_oblig_prepaid_advanced_fyb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='ussgl483100_undelivered_orders_oblig_transferred_unpaid_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='ussgl483200_undeliv_orders_oblig_transferred_prepaid_adv_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='ussgl487100_down_adj_pri_unpaid_undel_orders_oblig_recov_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='ussgl487200_down_adj_pri_ppaid_undel_orders_oblig_refund_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='ussgl488100_upward_adjust_pri_undeliv_order_oblig_unpaid_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='ussgl488200_up_adjust_pri_undeliv_order_oblig_ppaid_adv_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='ussgl490100_delivered_orders_obligations_unpaid_fyb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='ussgl490200_delivered_orders_obligations_paid_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='ussgl490800_authority_outlayed_not_yet_disbursed_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='ussgl490800_authority_outlayed_not_yet_disbursed_fyb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='ussgl493100_delivered_orders_oblig_transferred_unpaid_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='ussgl497100_down_adj_pri_unpaid_deliv_orders_oblig_recov_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='ussgl497200_down_adj_pri_paid_deliv_orders_oblig_refund_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='ussgl498100_upward_adjust_pri_deliv_orders_oblig_unpaid_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='ussgl498200_upward_adjust_pri_deliv_orders_oblig_paid_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawardstransactionobligations',
            name='transaction_obligated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='financialassistanceaward',
            name='award_transaction_usaspend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialassistanceaward',
            name='drv_current_total_award_value_amount_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialassistanceaward',
            name='drv_federal_funding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialassistanceaward',
            name='drv_potential_total_award_value_amount_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialassistanceaward',
            name='face_value_loan_guarantee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialassistanceaward',
            name='federal_action_obligation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialassistanceaward',
            name='non_federal_funding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialassistanceaward',
            name='original_loan_subsidy_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='financialassistanceaward',
            name='total_funding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='award_transaction_usaspend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='current_total_value_award',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='drv_current_aggregated_total_value_of_award',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='drv_current_total_award_value_amount_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='drv_current_total_value_of_award',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='drv_potential_aggregated_award_idv_amount_total_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='drv_potential_aggregated_total_value_of_award',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='drv_potential_award_idv_amount_total_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='drv_potential_total_award_value_amount_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='drv_potential_total_value_of_award',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='federal_action_obligation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='potential_total_value_of_award',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
