# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0030_auto_20161006_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='price_evaluation_adjustment_preference_percent_difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
