# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-23 17:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0016_create_gtas_total_obligation_table'),
        ('awards', '0030_merge_20180517_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubawardView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('keyword_ts_vector', django.contrib.postgres.search.SearchVectorField()),
                ('award_ts_vector', django.contrib.postgres.search.SearchVectorField()),
                ('recipient_name_ts_vector', django.contrib.postgres.search.SearchVectorField()),
                ('latest_transaction_id', models.IntegerField()),
                ('last_modified_date', models.DateField()),
                ('subaward_number', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_obl_bin', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('fiscal_year', models.IntegerField()),
                ('action_date', models.DateField()),
                ('award_report_fy_month', models.IntegerField()),
                ('award_report_fy_year', models.IntegerField()),
                ('award', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='awards.Award')),
                ('generated_unique_award_id', models.TextField()),
                ('awarding_agency_id', models.IntegerField()),
                ('funding_agency_id', models.IntegerField()),
                ('awarding_toptier_agency_name', models.TextField()),
                ('awarding_subtier_agency_name', models.TextField()),
                ('funding_toptier_agency_name', models.TextField()),
                ('funding_subtier_agency_name', models.TextField()),
                ('place_of_performance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='references.Location')),
                ('award_type', models.TextField()),
                ('prime_award_type', models.TextField()),
                ('cfda_id', models.IntegerField()),
                ('piid', models.TextField()),
                ('fain', models.TextField()),
                ('business_categories', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('recipient_name', models.TextField()),
                ('prime_recipient_name', models.TextField()),
                ('recipient_unique_id', models.TextField()),
                ('parent_recipient_unique_id', models.TextField()),
                ('pulled_from', models.TextField()),
                ('type_of_contract_pricing', models.TextField()),
                ('type_set_aside', models.TextField()),
                ('extent_competed', models.TextField()),
                ('product_or_service_code', models.TextField()),
                ('product_or_service_description', models.TextField()),
                ('cfda_number', models.TextField()),
                ('recipient_location_country_code', models.TextField()),
                ('recipient_location_country_name', models.TextField()),
                ('recipient_location_state_code', models.TextField()),
                ('recipient_location_county_code', models.TextField()),
                ('recipient_location_county_name', models.TextField()),
                ('recipient_location_zip5', models.TextField()),
                ('recipient_location_congressional_code', models.TextField()),
                ('pop_country_code', models.TextField()),
                ('pop_country_name', models.TextField()),
                ('pop_state_code', models.TextField()),
                ('pop_county_code', models.TextField()),
                ('pop_county_name', models.TextField()),
                ('pop_city_code', models.TextField()),
                ('pop_zip5', models.TextField()),
                ('pop_congressional_code', models.TextField()),
            ],
            options={
                'db_table': 'subaward_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SummaryStateView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateField()),
                ('fiscal_year', models.IntegerField()),
                ('type', models.TextField()),
                ('pulled_from', models.TextField()),
                ('distinct_awards', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('pop_country_code', models.TextField()),
                ('pop_state_code', models.TextField()),
                ('generated_pragmatic_obligation', models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True)),
                ('federal_action_obligation', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('original_loan_subsidy_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True)),
                ('face_value_loan_guarantee', models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True)),
                ('counts', models.IntegerField()),
            ],
            options={
                'db_table': 'summary_state_view',
                'managed': False,
            },
        ),
    ]
