# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0031_auto_20161006_1630'),
        ('awards', '0030_auto_20161006_1351'),
    ]

    operations = [
    ]
