# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-17 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0032_auto_20180614_1929'),
    ]

    operations = [
        migrations.RunSQL(sql="CREATE INDEX faba_fain_and_uri ON financial_accounts_by_awards(fain, uri, award_id) "
                              "WHERE fain IS NOT NULL AND uri IS NOT NULL AND award_id IS NULL;",
                          reverse_sql="DROP INDEX faba_fain_and_uri;"),
        migrations.RunSQL(sql="CREATE INDEX faba_fain ON financial_accounts_by_awards(fain, uri, award_id) WHERE fain "
                              "IS NOT NULL AND uri IS NULL AND award_id IS NULL;",
                          reverse_sql="DROP INDEX faba_fain;"),
        migrations.RunSQL(sql="CREATE INDEX faba_uri ON financial_accounts_by_awards(fain, uri, award_id) WHERE fain "
                              "IS NULL AND uri IS NOT NULL AND award_id IS NULL;",
                          reverse_sql="DROP INDEX faba_uri;"),
        migrations.RunSQL(sql="CREATE INDEX faba_piid ON financial_accounts_by_awards(piid, award_id) WHERE piid IS "
                              "NOT NULL AND award_id IS NULL;",
                          reverse_sql="DROP INDEX faba_piid;"),
    ]
