# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0032_merge_20161006_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialassistanceaward',
            old_name='description',
            new_name='award_description',
        ),
        migrations.RenameField(
            model_name='financialassistanceaward',
            old_name='award_transaction_usaspend',
            new_name='drv_award_transaction_usaspend',
        ),
        migrations.RenameField(
            model_name='financialassistanceaward',
            old_name='award_modification_amendment_number',
            new_name='modification_number',
        ),
        migrations.RenameField(
            model_name='procurement',
            old_name='description',
            new_name='award_description',
        ),
        migrations.RenameField(
            model_name='procurement',
            old_name='award_transaction_usaspend',
            new_name='drv_award_transaction_usaspend',
        ),
        migrations.RenameField(
            model_name='procurement',
            old_name='award_modification_amendment_number',
            new_name='modification_number',
        ),
    ]
