# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-24 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0034_summarytransactionrecipientview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryAwardRecipientView',
            fields=[
                ('duh', models.UUIDField(primary_key=True, serialize=False)),
                ('date_signed', models.DateField()),
                ('action_date', models.DateField(blank=True)),
                ('fiscal_year', models.IntegerField()),
                ('type', models.TextField(blank=True, null=True)),
                ('recipient_hash', models.UUIDField(null=True)),
                ('parent_recipient_unique_id', models.TextField(blank=True, null=True)),
                ('counts', models.IntegerField()),
            ],
            options={
                'db_table': 'summary_award_recipient_view',
                'managed': False,
            },
        ),
    ]
