# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0035_auto_20161018_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='certified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='last_modified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialaccountsbyawards',
            name='certified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialaccountsbyawards',
            name='last_modified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialaccountsbyawardstransactionobligations',
            name='certified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialaccountsbyawardstransactionobligations',
            name='last_modified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialassistanceaward',
            name='certified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialassistanceaward',
            name='last_modified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='certified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='last_modified_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
