# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0038_auto_20161103_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='ussgl490100_delivered_orders_obligations_unpaid_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
    ]
