# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-22 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0038_auto_20180815_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='subaward',
            name='parent_recipient_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
