# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0039_auto_20161107_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='date_signed',
            field=models.DateField(null=True, verbose_name='Award Date'),
        ),
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.CharField(max_length=4000, null=True, verbose_name='Award Description'),
        ),
        migrations.AlterField(
            model_name='award',
            name='parent_award_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parent Award ID'),
        ),
        migrations.AlterField(
            model_name='award',
            name='period_of_performance_current_end_date',
            field=models.DateField(null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='award',
            name='period_of_performance_start_date',
            field=models.DateField(null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='award',
            name='total_obligation',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Total Obligated'),
        ),
        migrations.AlterField(
            model_name='award',
            name='type',
            field=models.CharField(choices=[('2', 'Block Grant'), ('3', 'Formula Grant'), ('4', 'Project Grant'), ('5', 'Cooperative Agreement'), ('6', 'Direct Payment for Specified Use'), ('7', 'Direct Loan'), ('8', 'Guaranteed/Insured Loan'), ('9', 'Insurance'), ('10', 'Direct Payment unrestricted'), ('11', 'Other'), ('C', 'Contract'), ('G', 'Grant'), ('DP', 'Direct Payment'), ('L', 'Loan')], max_length=5, verbose_name='Award Type'),
        ),
        migrations.AlterField(
            model_name='financialassistanceaward',
            name='action_date',
            field=models.CharField(max_length=10, verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='financialassistanceaward',
            name='assistance_type',
            field=models.CharField(max_length=2, verbose_name='Assistance Type'),
        ),
        migrations.AlterField(
            model_name='financialassistanceaward',
            name='cfda_number',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='CFDA Number'),
        ),
        migrations.AlterField(
            model_name='financialassistanceaward',
            name='cfda_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CFDA Title'),
        ),
        migrations.AlterField(
            model_name='financialassistanceaward',
            name='modification_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modification Number'),
        ),
        migrations.AlterField(
            model_name='financialassistanceaward',
            name='sai_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SAI Number'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='a76_fair_act_action',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='A-76 FAIR Act Action'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='action_date',
            field=models.CharField(max_length=10, verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='contract_award_type',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Contract Award Type'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='idv_type',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='IDV Type'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='modification_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modification Number'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='naics',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='NAICS'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='naics_description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='NAICS Description'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='parent_award_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parent Award ID'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='period_of_performance_potential_end_date',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Period of Performance Potential End Date'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='potential_total_value_of_award',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Potential Total Value of Award'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='solicitation_identifier',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Solicitation ID'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='type_of_contract_pricing',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Type of Contract Pricing'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='type_of_idc',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Type of IDC'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='type_set_aside',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Type Set Aside'),
        ),
        migrations.AlterField(
            model_name='subaward',
            name='sub_award_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Sub-Award ID'),
        ),
    ]
