# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0041_auto_20161130_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='financial_accounts_by_awards',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.FinancialAccountsByAwards'),
        ),
    ]
