# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-20 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0042_auto_20161220_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialassistanceaward',
            name='action_date',
            field=models.DateField(max_length=10, verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='action_date',
            field=models.DateField(max_length=10, verbose_name='Transaction Date'),
        ),
    ]
