# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-22 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0043_summarytransactionfedacctview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactionnormalized',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
