# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-22 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0043_summarytransactionfedacctview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='data_source',
            field=models.TextField(choices=[('USA', 'USAspending'), ('DBR', 'DATA Act Broker')], help_text='The source of this entry, either Data Broker (DBR) or USASpending (USA)', null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='data_source',
            field=models.TextField(choices=[('USA', 'USAspending'), ('DBR', 'DATA Act Broker')], help_text='The source of this entry, either Data Broker (DBR) or USASpending (USA)', null=True),
        ),
    ]
