# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-20 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0043_auto_20161220_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='type_description',
        ),
    ]
