# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-25 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0044_auto_20181022_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='non_federal_funding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="A summation of this award's transactions' non-federal funding amount", max_digits=20, null=True),
        ),
    ]
