# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-26 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0044_auto_20181022_1239'),
        ('awards', '0045_award_non_federal_funding_amount'),
    ]

    operations = [
    ]
