# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0046_auto_20161222_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='type',
            field=models.CharField(choices=[('U', 'Unknown Type'), ('2', 'Block Grant'), ('3', 'Formula Grant'), ('4', 'Project Grant'), ('5', 'Cooperative Agreement'), ('6', 'Direct Payment for Specified Use'), ('7', 'Direct Loan'), ('8', 'Guaranteed/Insured Loan'), ('9', 'Insurance'), ('10', 'Direct Payment unrestricted'), ('11', 'Other'), ('C', 'Contract'), ('G', 'Grant'), ('DP', 'Direct Payment'), ('L', 'Loan')], default='U', max_length=5, null=True, verbose_name='Award Type'),
        ),
    ]
