# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0046_merge_20181026_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentAward',
            fields=[
                ('award_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='awards.Award')),
                ('generated_unique_award_id', models.TextField()),
                ('total_obligation', models.DecimalField(decimal_places=2, max_digits=23)),
                ('base_and_all_options_value', models.DecimalField(decimal_places=2, max_digits=23)),
                ('base_exercised_options_val', models.DecimalField(decimal_places=2, max_digits=23)),
                ('parent_award_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='awards.ParentAward')),
            ],
            options={
                'db_table': 'parent_award',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='award',
            name='parent_award',
        ),
        migrations.AddField(
            model_name='award',
            name='fpds_agency_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='fpds_parent_agency_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
