# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0048_auto_20181126_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.TextField(help_text='A description of the award', null=True, verbose_name='Award Description'),
        ),
    ]
