# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-11 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0049_auto_20170109_2032'),
        ('awards', '0049_auto_20170109_1831'),
    ]

    operations = [
    ]
