# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-01 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0049_auto_20181219_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialaccountsbyawards',
            name='award_type',
        ),
    ]
