# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0051_auto_20190425_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDelta',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='awards.TransactionNormalized')),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'transaction_delta',
            },
        ),
    ]
