# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0053_auto_20170111_2100'),
    ]

    operations = [

        # add and rename some fields
        migrations.AddField(
            model_name='financialassistanceaward',
            name='description',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='financialassistanceaward',
            name='period_of_performance_current_end_date',
            field=models.DateField(max_length=10, null=True, verbose_name='Period of Performance Current End Date'),
        ),
        migrations.AddField(
            model_name='financialassistanceaward',
            name='period_of_performance_start_date',
            field=models.DateField(max_length=10, null=True, verbose_name='Period of Performance Start Date'),
        ),
        migrations.AddField(
            model_name='financialassistanceaward',
            name='type',
            field=models.CharField(choices=[('U', 'Unknown Type'), ('02', 'Block Grant'), ('03', 'Formula Grant'), ('04', 'Project Grant'), ('05', 'Cooperative Agreement'), ('06', 'Direct Payment for Specified Use'), ('07', 'Direct Loan'), ('08', 'Guaranteed/Insured Loan'), ('09', 'Insurance'), ('10', 'Direct Payment unrestricted'), ('11', 'Other'), ('A', 'BPA Call'), ('B', 'Purchase Order'), ('C', 'Delivery Order'), ('D', 'Definitive Contract')], default='U', max_length=5, null=True, verbose_name='Action Type'),
        ),
        migrations.AddField(
            model_name='financialassistanceaward',
            name='type_description',
            field=models.CharField(default='Unknown Type', max_length=50, null=True, verbose_name='Action Type Description'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='description',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='period_of_performance_current_end_date',
            field=models.DateField(max_length=10, null=True, verbose_name='Period of Performance Current End Date'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='period_of_performance_start_date',
            field=models.DateField(max_length=10, null=True, verbose_name='Period of Performance Start Date'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='type',
            field=models.CharField(choices=[('U', 'Unknown Type'), ('02', 'Block Grant'), ('03', 'Formula Grant'), ('04', 'Project Grant'), ('05', 'Cooperative Agreement'), ('06', 'Direct Payment for Specified Use'), ('07', 'Direct Loan'), ('08', 'Guaranteed/Insured Loan'), ('09', 'Insurance'), ('10', 'Direct Payment unrestricted'), ('11', 'Other'), ('A', 'BPA Call'), ('B', 'Purchase Order'), ('C', 'Delivery Order'), ('D', 'Definitive Contract')], default='U', max_length=5, null=True, verbose_name='Action Type'),
        ),
        migrations.AddField(
            model_name='procurement',
            name='type_description',
            field=models.CharField(default='Unknown Type', max_length=50, null=True, verbose_name='Action Type Description'),
        )

    ]
