# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0053_auto_20170111_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialassistanceaward',
            name='period_of_performance_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialassistanceaward',
            name='period_of_performance_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
