# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0054_auto_20190625_2242'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "alter table subaward alter column id drop default",
                "drop sequence if exists awards_subaward_id_seq",
            ],
            reverse_sql=[
                "create sequence awards_subaward_id_seq as integer owned by subaward.id",
                "select setval('awards_subaward_id_seq', coalesce((select max(id) + 1 from subaward), 1), false)",
                "alter table subaward alter column id set default nextval('awards_subaward_id_seq')",
            ],
        ),
    ]
