# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-23 16:34
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import Case, F, Value, When


def update_award_actions(apps, schema_editor):
    # Use procurement model at time of migration
    Procurement = apps.get_model("awards", "Procurement")
    # set new description field equal to value of current award_description
    Procurement.objects.all().update(description=F("award_description"))
    # set new type field equal to value of contract_award_type
    Procurement.objects.all().update(type=F("contract_award_type"))
    # set new type description field =
    Procurement.objects.all().update(type_description=(Case(
        When(contract_award_type='A', then=Value('BPA Call')),
        When(contract_award_type='B', then=Value('Purchase Order')),
        When(contract_award_type='C', then=Value('Delivery Order')),
        When(contract_award_type='D', then=Value('Definitive Contract')),
        default=Value('Unknown Type')
    )))

    FinancialAssistanceAward = apps.get_model("awards", "FinancialAssistanceAward")
    # set new description field equal to value of current award_description
    FinancialAssistanceAward.objects.all().update(description=F("award_description"))
    # set new type field equal to value of contract_award_type
    FinancialAssistanceAward.objects.all().update(type=F("assistance_type"))
    # set new type description field =
    FinancialAssistanceAward.objects.all().update(type_description=(Case(
        When(assistance_type='02', then=Value('Block Grant')),
        When(assistance_type='03', then=Value('Formula Grant')),
        When(assistance_type='04', then=Value('Project Grant')),
        When(assistance_type='05', then=Value('Cooperative Agreement')),
        When(assistance_type='06', then=Value('Direct Payment for Specified Use')),
        When(assistance_type='07', then=Value('Direct Loan')),
        When(assistance_type='08', then=Value('Guaranteed/Insured Loan')),
        When(assistance_type='09', then=Value('Insurance')),
        When(assistance_type='10', then=Value('Direct Payment unrestricted')),
        When(assistance_type='11', then=Value('Other')),
        default=Value('Unknown Type')
    )))


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0054_auto_20170119_2012'),
    ]

    operations = [
        # populate newly-added fields using data in old fields
        migrations.RunPython(update_award_actions, reverse_code=migrations.RunPython.noop),
    ]
