# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-23 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0055_migrate_txn_data'),
    ]

    operations = [
        # remove old fields
        migrations.RemoveField(
            model_name='financialassistanceaward',
            name='assistance_type',
        ),
        migrations.RemoveField(
            model_name='financialassistanceaward',
            name='award_description',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='award_description',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='contract_award_type',
        ),
    ]
