# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-10 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0056_transaction_officer_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionfabs',
            unique_together=set([('awarding_sub_tier_agency_c', 'award_modification_amendme', 'fain', 'uri', 'cfda_number')]),
        ),
    ]
