# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-24 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0056_auto_20170123_1637'),
        ('awards', '0054_auto_20170119_2038'),
    ]

    operations = [
    ]
