# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-07 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0058_auto_20170207_1822'),
    ]

    operations = [
        migrations.RunSQL("UPDATE financial_accounts_by_awards SET treasury_account_id = (SELECT treasury_account_identifier FROM appropriation_account_balances WHERE financial_accounts_by_awards.appropriation_account_balances_id=appropriation_account_balances.appropriation_account_balances_id)"),
    ]
