# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-07 18:22
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import connection, migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20161219_1422'),
        ('awards', '0057_merge_20170124_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccountsbyawards',
            name='treasury_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.TreasuryAppropriationAccount'),
        ),
    ]
