# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-09 15:43
from __future__ import unicode_literals

from django.db import migrations

CREATE_VIEW = (
    "CREATE VIEW reporting_award_download AS ("
    "  SELECT * FROM reporting_award_contracts_view"
    "  UNION ALL"
    "  SELECT * FROM reporting_award_directpayments_view"
    "  UNION ALL"
    "  SELECT * FROM reporting_award_grants_view"
    "  UNION ALL"
    "  SELECT * FROM reporting_award_idvs_view"
    "  UNION ALL"
    "  SELECT * FROM reporting_award_loans_view"
    "  UNION ALL"
    "  SELECT * FROM reporting_award_other_view"
    "  UNION ALL"
    "  SELECT * FROM reporting_award_all_pre2008_view"
    ")",
)


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0057_reporting_matviews'),
    ]

    operations = [migrations.RunSQL(sql=CREATE_VIEW, reverse_sql="DROP VIEW reporting_award_download")]
