# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-06 19:44
from __future__ import unicode_literals

from django.db import migrations, models
from usaspending_api.common.helpers import FY_PG_FUNCTION_DEF
# I don't like reaching between apps this way, but don't see
# a better place to put a cross-app function definition


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0057_merge_20170124_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialassistanceaward',
            name='period_of_performance_current_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialassistanceaward',
            name='period_of_performance_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunSQL(FY_PG_FUNCTION_DEF)
    ]
