# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-02 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0057_merge_20170124_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccountsbyawards',
            name='certified_date_fy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialaccountsbyawards',
            name='reporting_period_end_fy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialaccountsbyawards',
            name='reporting_period_start_fy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
