# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-07 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0059_award_potential_total_value_of_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='type_of_contract_pricing',
            field=models.CharField(blank=True, choices=[('A', 'Fixed Price Redetermination'), ('B', 'Fixed Price Level of Effort'), ('J', 'Firm Fixed Price'), ('K', 'Fixed Price with Economic Price Adjustment'), ('L', 'Fixed Price Incentive'), ('M', 'Fixed Price Award Fee'), ('R', 'Cost Plus Award Fee'), ('S', 'Cost No Fee'), ('T', 'Cost Sharing'), ('U', 'Cost Plus Fixed Fee'), ('V', 'Cost Plus Incentive Fee'), ('Y', 'Time and Materials'), ('Z', 'Labor Hours'), ('UN', 'Unknown Type')], default='UN', max_length=2, null=True, verbose_name='Type of Contract Pricing'),
        ),
    ]
