# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-15 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0059_auto_20190819_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfpds',
            name='solicitation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
