# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-07 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0060_auto_20170207_1606'),
        ('awards', '0059_auto_20170207_1854'),
    ]

    operations = [
    ]
