# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-26 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0061_award_search_matviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardSummaryMatview',
            fields=[
                ('duh', models.UUIDField(help_text='Deterministic Unique Hash', primary_key=True, serialize=False)),
                ('action_date', models.DateField(blank=True, null=True)),
                ('fiscal_year', models.IntegerField()),
                ('type', models.TextField(blank=True, null=True)),
                ('pulled_from', models.TextField()),
                ('category', models.TextField(blank=True, null=True)),
                ('awarding_agency_id', models.IntegerField()),
                ('funding_agency_id', models.IntegerField()),
                ('awarding_toptier_agency_name', models.TextField()),
                ('funding_toptier_agency_name', models.TextField()),
                ('awarding_subtier_agency_name', models.TextField()),
                ('funding_subtier_agency_name', models.TextField()),
                ('awarding_toptier_agency_abbreviation', models.TextField()),
                ('funding_toptier_agency_abbreviation', models.TextField()),
                ('awarding_subtier_agency_abbreviation', models.TextField()),
                ('funding_subtier_agency_abbreviation', models.TextField()),
                ('federal_action_obligation', models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True)),
                ('original_loan_subsidy_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True)),
                ('face_value_loan_guarantee', models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True)),
                ('counts', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'mv_award_summary',
            },
        ),
    ]
