# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-07 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0061_merge_20170207_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaccountsbyawardstransactionobligations',
            name='financial_accounts_by_awards',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_obligations', to='awards.FinancialAccountsByAwards'),
        ),
    ]
