# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-07 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0058_auto_20170206_1944'),
        ('awards', '0062_auto_20170207_2014'),
    ]

    operations = [
    ]
