# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-17 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0062_awardsummarymatview'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='earliest_transaction',
            field=models.ForeignKey(help_text='The earliest transaction by action_date and mod associated with this award', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earliest_for_award', to='awards.TransactionNormalized'),
        ),
    ]
