# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-18 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0063_earliest_transaction_and_exec_comp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionfpds',
            name='solicitation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
