# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-11 16:23

# Data migration corresponding to schema migrations in
# commit 41e92 / 0064_auto_20170210_0416.py

# To run data imports from before the schema change:
# ./manage.py migrate awards 0064_auto_20170210_0416
# (perform )
# ./manage.py migrate awards 0065_auto_20170211_1623

from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('awards', '0064_auto_20170210_0416'), ]

    _RAW_SQL = [
        '''
    CREATE TEMPORARY TABLE template_faa_mapping AS
    SELECT NEXTVAL('transaction_id_seq') AS transaction_id,
           financial_assistance_award_id
    FROM   financial_assistance_award;
    ''', '''
    INSERT INTO transaction (
         id,
         action_date,
         action_type,
         award_id,
         awarding_agency_id,
         certified_date,
         create_date,
         data_source,
         description,
         drv_award_transaction_usaspend,
         drv_current_total_award_value_amount_adjustment,
         drv_potential_total_award_value_amount_adjustment,
         federal_action_obligation,
         funding_agency_id,
         last_modified_date,
         modification_number,
         period_of_performance_current_end_date,
         period_of_performance_start_date,
         place_of_performance_id,
         recipient_id,
         submission_id,
         type,
         type_description,
         update_date,
         usaspending_unique_transaction_id
    )
    SELECT tfm.transaction_id,
           action_date,
         action_type,
         award_id,
         awarding_agency_id,
         certified_date,
         create_date,
         data_source,
         description,
         drv_award_transaction_usaspend,
         drv_current_total_award_value_amount_adjustment,
         drv_potential_total_award_value_amount_adjustment,
         federal_action_obligation,
         funding_agency_id,
         last_modified_date,
         modification_number,
         period_of_performance_current_end_date,
         period_of_performance_start_date,
         place_of_performance_id,
         recipient_id,
         submission_id,
         type,
         type_description,
         update_date,
         usaspending_unique_transaction_id
    FROM financial_assistance_award
    JOIN template_faa_mapping tfm USING (financial_assistance_award_id);
    ''', '''
    INSERT INTO transaction_assistance (
        transaction_id,
        business_funds_indicator,
        certified_date,
        cfda_number,
        cfda_title,
        correction_late_delete_indicator,
        create_date,
        data_source,
        drv_award_finance_assistance_type_label,
        drv_federal_funding_amount,
        face_value_loan_guarantee,
        fain,
        fiscal_year_and_quarter_correction,
        last_modified_date,
        non_federal_funding_amount,
        original_loan_subsidy_cost,
        period_of_performance_current_end_date,
        period_of_performance_start_date,
        record_type,
        reporting_period_end,
        reporting_period_start,
        sai_number,
        submission_id,
        submitted_type,
        total_funding_amount,
        update_date,
        uri
    ) SELECT
        tfm.transaction_id,
        business_funds_indicator,
        certified_date,
        cfda_number,
        cfda_title,
        correction_late_delete_indicator,
        create_date,
        data_source,
        drv_award_finance_assistance_type_label,
        drv_federal_funding_amount,
        face_value_loan_guarantee,
        fain,
        fiscal_year_and_quarter_correction,
        last_modified_date,
        non_federal_funding_amount,
        original_loan_subsidy_cost,
        period_of_performance_current_end_date,
        period_of_performance_start_date,
        record_type,
        reporting_period_end,
        reporting_period_start,
        sai_number,
        submission_id,
        submitted_type,
        total_funding_amount,
        update_date,
        uri
    FROM financial_assistance_award
    JOIN template_faa_mapping tfm USING (financial_assistance_award_id);
    ''', '''
    CREATE TEMPORARY TABLE template_pcmt_mapping AS
    SELECT NEXTVAL('transaction_id_seq') AS transaction_id,
           procurement_id
    FROM   awards_procurement;
    ''', '''
    INSERT INTO transaction (
         id,
         action_date,
         action_type,
         award_id,
         awarding_agency_id,
         certified_date,
         create_date,
         data_source,
         description,
         drv_award_transaction_usaspend,
         drv_current_total_award_value_amount_adjustment,
         drv_potential_total_award_value_amount_adjustment,
         federal_action_obligation,
         funding_agency_id,
         last_modified_date,
         modification_number,
         period_of_performance_current_end_date,
         period_of_performance_start_date,
         place_of_performance_id,
         recipient_id,
         submission_id,
         type,
         type_description,
         update_date,
         usaspending_unique_transaction_id
    )
    SELECT tpm.transaction_id,
         action_date,
         action_type,
         award_id,
         awarding_agency_id,
         certified_date,
         create_date,
         data_source,
         description,
         drv_award_transaction_usaspend,
         drv_current_total_award_value_amount_adjustment,
         drv_potential_total_award_value_amount_adjustment,
         federal_action_obligation,
         funding_agency_id,
         last_modified_date,
         modification_number,
         period_of_performance_current_end_date,
         period_of_performance_start_date,
         place_of_performance_id,
         recipient_id,
         submission_id,
         type,
         type_description,
         update_date,
         usaspending_unique_transaction_id
    FROM awards_procurement
    JOIN template_pcmt_mapping tpm USING (procurement_id);
    ''', '''
    INSERT INTO transaction_contract (
        transaction_id,
         a76_fair_act_action,
         certified_date,
         clinger_cohen_act_planning,
         commercial_item_acquisition_procedures,
         commercial_item_test_program,
         consolidated_contract,
         contingency_humanitarian_or_peacekeeping_operation,
         contract_bundling,
         contract_financing,
         contracting_officers_determination_of_business_size,
         cost_accounting_standards,
         cost_or_pricing_data,
         country_of_product_or_service_origin,
         create_date,
         current_total_value_award,
         data_source,
         davis_bacon_act,
         dod_claimant_program_code,
         drv_current_aggregated_total_value_of_award,
         drv_current_total_value_of_award,
         drv_parent_award_awarding_agency_code,
         drv_potential_aggregated_award_idv_amount_total_estimate,
         drv_potential_aggregated_total_value_of_award,
         drv_potential_award_idv_amount_total_estimate,
         drv_potential_total_value_of_award,
         epa_designated_product,
         evaluated_preference,
         extent_competed,
         fair_opportunity_limited_sources,
         fed_biz_opps,
         foreign_funding,
         gfe_gfp,
         idv_type,
         information_technology_commercial_item_category,
         interagency_contracting_authority,
         last_modified_date,
         local_area_set_aside,
         major_program,
         multi_year_contract,
         multiple_or_single_award_idv,
         naics,
         naics_description,
         national_interest_action,
         number_of_actions,
         number_of_offers_received,
         ordering_period_end_date,
         other_statutory_authority,
         other_than_full_and_open_competition,
         parent_award_id,
         performance_based_service_acquisition,
         period_of_performance_potential_end_date,
         piid,
         place_of_manufacture,
         potential_total_value_of_award,
         price_evaluation_adjustment_preference_percent_difference,
         product_or_service_code,
         program_acronym,
         program_system_or_equipment_code,
         purchase_card_as_payment_method,
         rec_flag,
         recovered_materials_sustainability,
         referenced_idv_agency_identifier,
         referenced_idv_modification_number,
         reporting_period_end,
         reporting_period_start,
         research,
         sea_transportation,
         service_contract_act,
         small_business_competitiveness_demonstration_program,
         solicitation_identifier,
         solicitation_procedures,
         subcontracting_plan,
         submission_id,
         transaction_number,
         type_of_contract_pricing,
         type_of_contract_pricing_description,
         type_of_idc,
         type_set_aside,
         update_date,
         walsh_healey_act
    ) SELECT
        tpm.transaction_id,
         a76_fair_act_action,
         certified_date,
         clinger_cohen_act_planning,
         commercial_item_acquisition_procedures,
         commercial_item_test_program,
         consolidated_contract,
         contingency_humanitarian_or_peacekeeping_operation,
         contract_bundling,
         contract_financing,
         contracting_officers_determination_of_business_size,
         cost_accounting_standards,
         cost_or_pricing_data,
         country_of_product_or_service_origin,
         create_date,
         current_total_value_award,
         data_source,
         davis_bacon_act,
         dod_claimant_program_code,
         drv_current_aggregated_total_value_of_award,
         drv_current_total_value_of_award,
         drv_parent_award_awarding_agency_code,
         drv_potential_aggregated_award_idv_amount_total_estimate,
         drv_potential_aggregated_total_value_of_award,
         drv_potential_award_idv_amount_total_estimate,
         drv_potential_total_value_of_award,
         epa_designated_product,
         evaluated_preference,
         extent_competed,
         fair_opportunity_limited_sources,
         fed_biz_opps,
         foreign_funding,
         gfe_gfp,
         idv_type,
         information_technology_commercial_item_category,
         interagency_contracting_authority,
         last_modified_date,
         local_area_set_aside,
         major_program,
         multi_year_contract,
         multiple_or_single_award_idv,
         naics,
         naics_description,
         national_interest_action,
         number_of_actions,
         number_of_offers_received,
         ordering_period_end_date,
         other_statutory_authority,
         other_than_full_and_open_competition,
         parent_award_id,
         performance_based_service_acquisition,
         period_of_performance_potential_end_date,
         piid,
         place_of_manufacture,
         potential_total_value_of_award,
         price_evaluation_adjustment_preference_percent_difference,
         product_or_service_code,
         program_acronym,
         program_system_or_equipment_code,
         purchase_card_as_payment_method,
         rec_flag,
         recovered_materials_sustainability,
         referenced_idv_agency_identifier,
         referenced_idv_modification_number,
         reporting_period_end,
         reporting_period_start,
         research,
         sea_transportation,
         service_contract_act,
         small_business_competitiveness_demonstration_program,
         solicitation_identifier,
         solicitation_procedures,
         subcontracting_plan,
         submission_id,
         transaction_number,
         type_of_contract_pricing,
         type_of_contract_pricing_description,
         type_of_idc,
         type_set_aside,
         update_date,
         walsh_healey_act
    FROM awards_procurement
    JOIN template_pcmt_mapping tpm USING (procurement_id);
    ''',
        'DROP TABLE template_faa_mapping',
        'DROP TABLE template_pcmt_mapping'
    ]

    operations = [
        migrations.RunSQL(sql, migrations.RunSQL.noop) for sql in _RAW_SQL
    ]
    # migrations.noop b/c otherwise creating the
    # temporary table throws an IrreversibleError


'''
These column lists were generated with queries on the
information schema:

-- 1. insertion to transaction_assistance

-- columns for transaction
WITH faa_cols AS (
  SELECT column_name
  FROM   information_schema.columns
  WHERE  table_name = 'financial_assistance_award'
),
t_cols AS (
  SELECT column_name
  FROM   information_schema.columns
  WHERE  table_name = 'transaction'
)
SELECT '    ' || faa_cols.column_name || ','
FROM   faa_cols
NATURAL JOIN t_cols
ORDER BY faa_cols.column_name;


-- columns for transaction_assistance
WITH faa_cols AS (
  SELECT column_name
  FROM   information_schema.columns
  WHERE  table_name = 'financial_assistance_award'
),
ta_cols AS (
  SELECT column_name
  FROM   information_schema.columns
  WHERE  table_name = 'transaction_assistance'
)
SELECT '    ' || faa_cols.column_name || ','
FROM   faa_cols
NATURAL JOIN ta_cols
ORDER BY faa_cols.column_name;

-- 2. insertion to transaction_contract

-- columns for transaction
WITH ctr_cols AS (
  SELECT column_name
  FROM   information_schema.columns
  WHERE  table_name = 'awards_procurement'
),
t_cols AS (
  SELECT column_name
  FROM   information_schema.columns
  WHERE  table_name = 'transaction'
)
SELECT '    ' || ctr_cols.column_name || ','
FROM   ctr_cols
NATURAL JOIN t_cols
ORDER BY ctr_cols.column_name;


-- columns for transaction_contract
WITH ap_cols AS (
  SELECT column_name
  FROM   information_schema.columns
  WHERE  table_name = 'awards_procurement'
),
tc_cols AS (
  SELECT column_name
  FROM   information_schema.columns
  WHERE  table_name = 'transaction_contract'
)
SELECT '    ' || ap_cols.column_name || ','
FROM   ap_cols
NATURAL JOIN tc_cols
ORDER BY ap_cols.column_name;

'''
