# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0064_auto_20170210_0416'),
        ('awards', '0064_auto_20170210_1753'),
    ]

    operations = [
    ]
