# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0066_auto_20170213_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncontract',
            name='period_of_performance_potential_end_date',
            field=models.DateField(max_length=10, null=True, verbose_name='Period of Performance Potential End Date'),
        ),
    ]
