# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-07 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0066_remove_brokersubaward_imported'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                migrations.AlterField(
                    model_name='award',
                    name='awarding_agency',
                    field=models.ForeignKey(help_text='The awarding agency for the award', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='agencies.Agency'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                migrations.AlterField(
                    model_name='award',
                    name='funding_agency',
                    field=models.ForeignKey(help_text='The funding agency for the award', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='agencies.Agency'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                migrations.AlterField(
                    model_name='subaward',
                    name='awarding_agency',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='awarding_subawards', to='agencies.Agency'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                migrations.AlterField(
                    model_name='subaward',
                    name='funding_agency',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='funding_subawards', to='agencies.Agency'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                migrations.AlterField(
                    model_name='transactionnormalized',
                    name='awarding_agency',
                    field=models.ForeignKey(help_text='The agency which awarded this transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards_transactionnormalized_awarding_agency', to='agencies.Agency'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                migrations.AlterField(
                    model_name='transactionnormalized',
                    name='funding_agency',
                    field=models.ForeignKey(help_text='The agency which is funding this transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards_transactionnormalized_funding_agency', to='agencies.Agency'),
                ),
            ],
        ),
    ]
