# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-22 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0068_merge_20170216_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccountsbyawards',
            name='transaction_obligated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        )
    ]
