# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-27 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0069_auto_20191226_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='transactionnormalized',
            name='recipient',
        ),
    ]
