# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-28 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0068_merge_20170216_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialassistanceaward',
            name='award',
        ),
        migrations.RemoveField(
            model_name='financialassistanceaward',
            name='awarding_agency',
        ),
        migrations.RemoveField(
            model_name='financialassistanceaward',
            name='funding_agency',
        ),
        migrations.RemoveField(
            model_name='financialassistanceaward',
            name='place_of_performance',
        ),
        migrations.RemoveField(
            model_name='financialassistanceaward',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='financialassistanceaward',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='award',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='awarding_agency',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='funding_agency',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='place_of_performance',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='procurement',
            name='submission',
        ),
        migrations.DeleteModel(
            name='FinancialAssistanceAward',
        ),
        migrations.DeleteModel(
            name='Procurement',
        ),
    ]
