# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-03 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0068_merge_20170216_1631'),
    ]

    operations = [
        migrations.RunSQL("CREATE INDEX awards_awarding_agency_id ON awards (awarding_agency_id)"),
        migrations.RunSQL("CREATE INDEX awards_funding_agency_id ON awards (funding_agency_id)"),
        migrations.RunSQL("CREATE INDEX awards_pop_id ON awards (place_of_performance_id)"),
        migrations.RunSQL("CREATE INDEX awards_recipient_id ON awards (recipient_id)"),
        migrations.RunSQL("CREATE INDEX transaction_awarding_agency_id ON transaction (awarding_agency_id)"),
        migrations.RunSQL("CREATE INDEX transaction_funding_agency_id ON transaction (funding_agency_id)"),
        migrations.RunSQL("CREATE INDEX transaction_pop_id ON transaction (place_of_performance_id)"),
        migrations.RunSQL("CREATE INDEX transaction_recipient_id ON transaction (recipient_id)"),
    ]
