# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-28 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0068_merge_20170216_1631'),
    ]

    _RAW_SQL = [
        'DROP TABLE awards_procurement;',
        'DROP TABLE financial_assistance_award;'
    ]
    operations = [
        migrations.RunSQL(sql, migrations.RunSQL.noop) for sql in _RAW_SQL
    ]
