# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-26 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subaward',
            name='place_of_perform_scope',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfabs',
            name='place_of_performance_scope',
            field=models.TextField(blank=True, null=True),
        ),
    ]
