# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-07 19:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("awards", "0069_auto_20191226_1602")]

    operations = [
        migrations.DeleteModel(name="AwardSearchView"),
        migrations.DeleteModel(name="AwardSummaryMatview"),
        migrations.DeleteModel(name="ContractAwardSearchMatview"),
        migrations.DeleteModel(name="DirectPaymentAwardSearchMatview"),
        migrations.DeleteModel(name="GrantAwardSearchMatview"),
        migrations.DeleteModel(name="IDVAwardSearchMatview"),
        migrations.DeleteModel(name="LoanAwardSearchMatview"),
        migrations.DeleteModel(name="OtherAwardSearchMatview"),
        migrations.DeleteModel(name="Pre2008AwardSearchMatview"),
        migrations.DeleteModel(name="SubawardView"),
        migrations.DeleteModel(name="SummaryCfdaNumbersView"),
        migrations.DeleteModel(name="SummaryNaicsCodesView"),
        migrations.DeleteModel(name="SummaryPscCodesView"),
        migrations.DeleteModel(name="SummaryStateView"),
        migrations.DeleteModel(name="SummaryTransactionFedAcctView"),
        migrations.DeleteModel(name="SummaryTransactionGeoView"),
        migrations.DeleteModel(name="SummaryTransactionMonthView"),
        migrations.DeleteModel(name="SummaryTransactionRecipientView"),
        migrations.DeleteModel(name="SummaryTransactionView"),
        migrations.DeleteModel(name="SummaryView"),
        migrations.DeleteModel(name="UniversalTransactionView"),
    ]
