# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-02 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0069_auto_20191226_1602'),
        ('awards', '0069_auto_20191227_1603'),
    ]

    operations = [
    ]
