# Generated by Django 2.2.9 on 2020-05-29 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0044_disasteremergencyfundcode'),
        ('awards', '0070_auto_20200116_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccountsbyawards',
            name='disaster_emergency_fund_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='references.DisasterEmergencyFundCode'),
        ),
    ]
