# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-08 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0070_award_latest_transaction'),
        ('awards', '0069_txn_cleanup'),
    ]

    operations = [
    ]
