# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-10 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0071_auto_20170228_1402'),
        ('awards', '0072_auto_20170309_1648'),
    ]

    operations = [
    ]
