# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-19 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0056_auto_20170318_2052'),
        ('awards', '0072_merge_20170310_2025'),
    ]

    operations = [
        # Rename the existing object_class field. Using raw SQL to do this
        # because the RenameField migration operation didn't work (possibly
        # because the model column/FK reference didn't follow typical Django
        # standard naming pattern)
        migrations.RunSQL(
            'ALTER TABLE financial_accounts_by_awards RENAME COLUMN object_class TO object_class_old',
            migrations.RunSQL.noop),
        # create a new object_class column that points to the new object class model
        migrations.AddField(
            model_name='financialaccountsbyawards',
            name='object_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='references.ObjectClass'),
        ),
    ]
