# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-20 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0072_merge_20170310_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='awarding_agency',
            field=models.ForeignKey(help_text='The awarding agency for the award', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='references.Agency'),
        ),
        migrations.AlterField(
            model_name='award',
            name='certified_date',
            field=models.DateField(blank=True, help_text='The date this record was certified', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date this record was created in the API', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='data_source',
            field=models.CharField(choices=[('USA', 'USAspending'), ('DBR', 'DATA Act Broker')], help_text='The source of this entry, either Data Broker (DBR) or USASpending (USA)', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='date_signed',
            field=models.DateField(db_index=True, help_text='The date the award was signed', null=True, verbose_name='Award Date'),
        ),
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.CharField(help_text='A description of the award', max_length=4000, null=True, verbose_name='Award Description'),
        ),
        migrations.AlterField(
            model_name='award',
            name='fain',
            field=models.CharField(blank=True, help_text='An identification code assigned to each financial assistance award tracking purposes. The FAIN is tied to that award (and all future modifications to that award) throughout the award’s life. Each FAIN is assigned by an agency. Within an agency, FAIN are unique: each new award must be issued a new FAIN. FAIN stands for Federal Award Identification Number, though the digits are letters, not numbers.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='funding_agency',
            field=models.ForeignKey(help_text='The funding agency for the award', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='references.Agency'),
        ),
        migrations.AlterField(
            model_name='award',
            name='last_modified_date',
            field=models.DateField(blank=True, help_text='The date this award was last modified', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='latest_submission',
            field=models.ForeignKey(help_text='The submission attribute object that created this award', null=True, on_delete=django.db.models.deletion.CASCADE, to='submissions.SubmissionAttributes'),
        ),
        migrations.AlterField(
            model_name='award',
            name='latest_transaction',
            field=models.ForeignKey(help_text='The latest transaction by action_date associated with this award', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latest_for_award', to='awards.Transaction'),
        ),
        migrations.AlterField(
            model_name='award',
            name='parent_award',
            field=models.ForeignKey(help_text='The parent award, if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_award', to='awards.Award'),
        ),
        migrations.AlterField(
            model_name='award',
            name='period_of_performance_current_end_date',
            field=models.DateField(help_text='The current, not original, period of performance end date', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='award',
            name='period_of_performance_start_date',
            field=models.DateField(help_text='The start date for the period of performance', null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='award',
            name='piid',
            field=models.CharField(blank=True, help_text='Procurement Instrument Identifier - A unique identifier assigned to a federal contract, purchase order, basic ordering agreement, basic agreement, and blanket purchase agreement. It is used to track the contract, and any modifications or transactions related to it. After October 2017, it is between 13 and 17 digits, both letters and numbers.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='place_of_performance',
            field=models.ForeignKey(help_text='The principal place of business, where the majority of the work is performed. For example, in a manufacturing contract, this would be the main plant where items are produced.', null=True, on_delete=django.db.models.deletion.CASCADE, to='references.Location'),
        ),
        migrations.AlterField(
            model_name='award',
            name='potential_total_value_of_award',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The sum of the potential_value_of_award from associated transactions', max_digits=20, null=True, verbose_name='Potential Total Value of Award'),
        ),
        migrations.AlterField(
            model_name='award',
            name='recipient',
            field=models.ForeignKey(help_text='The recipient of the award', null=True, on_delete=django.db.models.deletion.CASCADE, to='references.LegalEntity'),
        ),
        migrations.AlterField(
            model_name='award',
            name='total_obligation',
            field=models.DecimalField(decimal_places=2, help_text='The amount of money the government is obligated to pay for the award', max_digits=15, null=True, verbose_name='Total Obligated'),
        ),
        migrations.AlterField(
            model_name='award',
            name='total_outlay',
            field=models.DecimalField(decimal_places=2, help_text='The total amount of money paid out for this award', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='type',
            field=models.CharField(choices=[('U', 'Unknown Type'), ('02', 'Block Grant'), ('03', 'Formula Grant'), ('04', 'Project Grant'), ('05', 'Cooperative Agreement'), ('06', 'Direct Payment for Specified Use'), ('07', 'Direct Loan'), ('08', 'Guaranteed/Insured Loan'), ('09', 'Insurance'), ('10', 'Direct Payment unrestricted'), ('11', 'Other'), ('A', 'BPA Call'), ('B', 'Purchase Order'), ('C', 'Delivery Order'), ('D', 'Definitive Contract')], default='U', help_text='\tThe mechanism used to distribute funding. The federal government can distribute funding in several forms. These award types include contracts, grants, loans, and direct payments.', max_length=5, null=True, verbose_name='Award Type'),
        ),
        migrations.AlterField(
            model_name='award',
            name='type_description',
            field=models.CharField(default='Unknown Type', help_text='The plain text description of the type of the award', max_length=50, null=True, verbose_name='Award Type Description'),
        ),
        migrations.AlterField(
            model_name='award',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='The last time this record was updated in the API', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='uri',
            field=models.CharField(blank=True, help_text='The uri of the award', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='data_source',
            field=models.CharField(choices=[('USA', 'USAspending'), ('DBR', 'DATA Act Broker')], help_text='The source of this entry, either Data Broker (DBR) or USASpending (USA)', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='subaward',
            name='data_source',
            field=models.CharField(choices=[('USA', 'USAspending'), ('DBR', 'DATA Act Broker')], help_text='The source of this entry, either Data Broker (DBR) or USASpending (USA)', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action_date',
            field=models.DateField(help_text='The date this transaction was actioned', max_length=10, verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action_type',
            field=models.CharField(blank=True, help_text='The type of transaction. For example, A, B, C, D', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='award',
            field=models.ForeignKey(help_text='The award which this transaction is contained in', on_delete=django.db.models.deletion.CASCADE, to='awards.Award'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='awarding_agency',
            field=models.ForeignKey(help_text='The agency which awarded this transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards_transaction_awarding_agency', to='references.Agency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='certified_date',
            field=models.DateField(blank=True, help_text='The date this transaction was certified', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date this transaction was created in the API', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='data_source',
            field=models.CharField(choices=[('USA', 'USAspending'), ('DBR', 'DATA Act Broker')], help_text='The source of this entry, either Data Broker (DBR) or USASpending (USA)', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(help_text='The description of this transaction', max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='federal_action_obligation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The obligation of the federal government for this transaction', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='funding_agency',
            field=models.ForeignKey(help_text='The agency which is funding this transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards_transaction_funding_agency', to='references.Agency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='last_modified_date',
            field=models.DateField(blank=True, help_text='The date this transaction was last modified', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='modification_number',
            field=models.CharField(blank=True, help_text='The modification number for this transaction', max_length=50, null=True, verbose_name='Modification Number'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='period_of_performance_current_end_date',
            field=models.DateField(help_text='The current end date of the period of performance', max_length=10, null=True, verbose_name='Period of Performance Current End Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='period_of_performance_start_date',
            field=models.DateField(help_text='The period of performance start date', max_length=10, null=True, verbose_name='Period of Performance Start Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='place_of_performance',
            field=models.ForeignKey(help_text='The location where the work on this transaction was performed', null=True, on_delete=django.db.models.deletion.CASCADE, to='references.Location'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=models.ForeignKey(help_text='The recipient for this transaction', null=True, on_delete=django.db.models.deletion.CASCADE, to='references.LegalEntity'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='submission',
            field=models.ForeignKey(help_text='The submission which created this record', on_delete=django.db.models.deletion.CASCADE, to='submissions.SubmissionAttributes'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('U', 'Unknown Type'), ('02', 'Block Grant'), ('03', 'Formula Grant'), ('04', 'Project Grant'), ('05', 'Cooperative Agreement'), ('06', 'Direct Payment for Specified Use'), ('07', 'Direct Loan'), ('08', 'Guaranteed/Insured Loan'), ('09', 'Insurance'), ('10', 'Direct Payment unrestricted'), ('11', 'Other'), ('A', 'BPA Call'), ('B', 'Purchase Order'), ('C', 'Delivery Order'), ('D', 'Definitive Contract')], default='U', help_text='The type for this transaction. For example, A, B, C, D', max_length=5, null=True, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_description',
            field=models.CharField(default='Unknown Type', help_text='The plain text description of the transaction type', max_length=50, null=True, verbose_name='Action Type Description'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='The last time this transaction was updated in the API', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='usaspending_unique_transaction_id',
            field=models.CharField(blank=True, help_text='If this record is legacy USASpending data, this is the unique transaction identifier from that system', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='transactionassistance',
            name='data_source',
            field=models.CharField(choices=[('USA', 'USAspending'), ('DBR', 'DATA Act Broker')], help_text='The source of this entry, either Data Broker (DBR) or USASpending (USA)', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='a76_fair_act_action',
            field=models.CharField(blank=True, help_text='A-76 FAIR act action', max_length=1, null=True, verbose_name='A-76 FAIR Act Action'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='certified_date',
            field=models.DateField(blank=True, help_text='The date this record was certified', null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, help_text='The date this record was created in the API', null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='current_total_value_award',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The current value of the award', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='data_source',
            field=models.CharField(choices=[('USA', 'USAspending'), ('DBR', 'DATA Act Broker')], help_text='The source of this entry, either Data Broker (DBR) or USASpending (USA)', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='idv_type',
            field=models.CharField(blank=True, help_text='The IDV type code', max_length=1, null=True, verbose_name='IDV Type'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='last_modified_date',
            field=models.DateField(blank=True, help_text='The last time this transaction was modified', null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='multiple_or_single_award_idv',
            field=models.CharField(blank=True, help_text='Specifies whether the IDV is a single more multiple award vehicle', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='naics',
            field=models.CharField(blank=True, help_text='Specified which industry the work for this transaction falls into. A 6-digit code', max_length=6, null=True, verbose_name='NAICS'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='naics_description',
            field=models.CharField(blank=True, help_text='A plain text description of the NAICS code', max_length=150, null=True, verbose_name='NAICS Description'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='ordering_period_end_date',
            field=models.CharField(blank=True, help_text='The end date for the ordering period', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='parent_award_id',
            field=models.CharField(blank=True, help_text='The parent award id for this transaction. This is generally the piid of an IDV', max_length=50, null=True, verbose_name='Parent Award ID'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='period_of_performance_potential_end_date',
            field=models.DateField(help_text='The potential end date of the period of performance', max_length=10, null=True, verbose_name='Period of Performance Potential End Date'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='piid',
            field=models.CharField(blank=True, help_text='The PIID of this transaction', max_length=50),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='potential_total_value_of_award',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The potential total value of the award', max_digits=20, null=True, verbose_name='Potential Total Value of Award'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='rec_flag',
            field=models.CharField(blank=True, help_text='The rec flag', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='referenced_idv_agency_identifier',
            field=models.CharField(blank=True, help_text='The agency identifier of the agency on the IDV', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='referenced_idv_modification_number',
            field=models.CharField(blank=True, help_text='The modification number for the referenced IDV', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='reporting_period_end',
            field=models.DateField(blank=True, help_text='The date marking the end of the reporting period', null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='reporting_period_start',
            field=models.DateField(blank=True, help_text='The date marking the start of the reporting period', null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='transaction',
            field=models.OneToOneField(help_text='Non-specific transaction data, fields shared among both assistance and contract transactions', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contract_data', serialize=False, to='awards.Transaction'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='transaction_number',
            field=models.CharField(blank=True, help_text='The transaction number for this transaction', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='type_of_contract_pricing',
            field=models.CharField(blank=True, choices=[('A', 'Fixed Price Redetermination'), ('B', 'Fixed Price Level of Effort'), ('J', 'Firm Fixed Price'), ('K', 'Fixed Price with Economic Price Adjustment'), ('L', 'Fixed Price Incentive'), ('M', 'Fixed Price Award Fee'), ('R', 'Cost Plus Award Fee'), ('S', 'Cost No Fee'), ('T', 'Cost Sharing'), ('U', 'Cost Plus Fixed Fee'), ('V', 'Cost Plus Incentive Fee'), ('Y', 'Time and Materials'), ('Z', 'Labor Hours'), ('UN', 'Unknown Type')], default='UN', help_text='The type of contract pricing data, as a code', max_length=2, null=True, verbose_name='Type of Contract Pricing'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='type_of_contract_pricing_description',
            field=models.CharField(blank=True, help_text='A plain text description of the type of contract pricing data', max_length=150, null=True, verbose_name='Type of Contract Pricing Description'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='type_of_idc',
            field=models.CharField(blank=True, help_text='Code representing the type of IDC', max_length=1, null=True, verbose_name='Type of IDC'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='update_date',
            field=models.DateTimeField(auto_now=True, help_text='The last time this record was updated in the API', null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='walsh_healey_act',
            field=models.CharField(blank=True, help_text='Denotes whether this transaction is subject to the Walsh-Healey act', max_length=1, null=True),
        ),
    ]
