# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-19 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0074_accounts_awards_oc_data_migration'),
    ]

    operations = [
        # Remove old column. Using raw SQL to do this
        # because Django migrations won't recognize this as the temporarily-
        # renamed original object_class field
        migrations.RunSQL(
            'ALTER TABLE financial_accounts_by_awards DROP COLUMN IF EXISTS object_class_old',
            migrations.RunSQL.noop),
    ]
