# Generated by Django 2.2.13 on 2020-08-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0074_financialaccountsbyawards_distinct_award_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='distinct_award_key',
            field=models.TextField(db_index=True),
        ),
    ]
