# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-21 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0074_auto_20170320_1607'),
        ('awards', '0075_accounts_awards_oc_cleanup'),
    ]

    operations = [
    ]
