# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-10 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0077_auto_20170405_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncontract',
            name='modification_reason',
            field=models.TextField(blank=True, help_text='Code for the modification reason', null=True, verbose_name='Modification reason code'),
        ),
        migrations.AddField(
            model_name='transactioncontract',
            name='modification_reason_description',
            field=models.TextField(blank=True, help_text='Description of the reason for modification', null=True, verbose_name='Modification reason description'),
        ),
    ]
