# Generated by Django 2.2.18 on 2021-02-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0077_auto_20200917_2223'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='financialaccountsbyawards',
            name='faba_subid_awardkey_sums_idx',
        ),
        migrations.AddIndex(
            model_name='financialaccountsbyawards',
            index=models.Index(condition=models.Q(disaster_emergency_fund__in=['L', 'M', 'N', 'O', 'P', 'U']), fields=['submission', 'distinct_award_key', 'piid', 'transaction_obligated_amount', 'gross_outlay_amount_by_award_cpe'], name='faba_subid_awardkey_sums_idx'),
        ),
    ]
