# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-09 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0078_auto_20170409_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='type',
            field=models.CharField(db_index=True, help_text='\tThe mechanism used to distribute funding. The federal government can distribute funding in several forms. These award types include contracts, grants, loans, and direct payments.', max_length=5, null=True, verbose_name='Award Type'),
        ),
        migrations.AlterField(
            model_name='award',
            name='type_description',
            field=models.TextField(blank=True, help_text='The plain text description of the type of the award', null=True, verbose_name='Award Type Description'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(help_text='The type for this transaction. For example, A, B, C, D', max_length=5, null=True, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_description',
            field=models.TextField(blank=True, help_text='The plain text description of the transaction type', null=True, verbose_name='Action Type Description'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='type_of_contract_pricing',
            field=models.CharField(blank=True, default='UN', help_text='The type of contract pricing data, as a code', max_length=2, null=True, verbose_name='Type of Contract Pricing'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='type_of_contract_pricing_description',
            field=models.TextField(blank=True, help_text='A plain text description of the type of contract pricing data', null=True, verbose_name='Type of Contract Pricing Description'),
        ),
    ]
