# Generated by Django 2.2.9 on 2021-03-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0078_auto_20210211_2237'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='financialaccountsbyawards',
            name='faba_subid_awardkey_sums_idx',
        ),
        migrations.AddIndex(
            model_name='financialaccountsbyawards',
            index=models.Index(condition=models.Q(disaster_emergency_fund__in=['L', 'M', 'N', 'O', 'P', 'U']), fields=['submission', 'distinct_award_key', 'piid', 'transaction_obligated_amount', 'gross_outlay_amount_by_award_cpe', 'ussgl497200_down_adj_pri_paid_deliv_orders_oblig_refund_cpe', 'ussgl487200_down_adj_pri_ppaid_undel_orders_oblig_refund_cpe'], name='faba_subid_awardkey_sums_idx'),
        ),
    ]
