# Generated by Django 2.2.18 on 2021-05-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0080_auto_20210331_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfpds',
            name='awardee_or_recipient_uei',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfpds',
            name='awardee_or_recipient_uei_n',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfpds',
            name='ultimate_parent_uei',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionfpds',
            name='ultimate_parent_uei_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
