# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-13 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0080_fix_u_defaults_update_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncontract',
            name='price_evaluation_adjustment_preference_percent_difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
