# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-14 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0081_auto_20170413_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subaward',
            name='award',
        ),
        migrations.RemoveField(
            model_name='subaward',
            name='legal_entity',
        ),
        migrations.DeleteModel(
            name='SubAward',
        ),
    ]
