# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-14 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0081_auto_20170413_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='latest_submission',
            field=models.ForeignKey(help_text='The submission attribute object that created this award', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='submissions.SubmissionAttributes'),
        ),
    ]
