# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-14 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_auto_20170404_1741'),
        ('references', '0065_merge_20170410_2025'),
        ('awards', '0082_auto_20170414_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(choices=[('USA', 'USAspending'), ('DBR', 'DATA Act Broker')], help_text='The source of this entry, either Data Broker (DBR) or USASpending (USA)', max_length=3, null=True)),
                ('subaward_number', models.IntegerField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('recovery_model_question1', models.CharField(blank=True, max_length=1, null=True)),
                ('recovery_model_question2', models.CharField(blank=True, max_length=1, null=True)),
                ('action_date', models.DateField(blank=True, null=True)),
                ('award_report_month', models.IntegerField()),
                ('award_report_year', models.IntegerField()),
                ('naics', models.CharField(blank=True, help_text='Specified which industry the work for this transaction falls into. A 6-digit code', max_length=6, null=True, verbose_name='NAICS')),
                ('naics_description', models.TextField(blank=True, help_text='A plain text description of the NAICS code', null=True, verbose_name='NAICS Description')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='award',
            name='subaward_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='award',
            name='total_subaward_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='subaward',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subawards', to='awards.Award'),
        ),
        migrations.AddField(
            model_name='subaward',
            name='cfda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='references.CFDAProgram'),
        ),
        migrations.AddField(
            model_name='subaward',
            name='funding_agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='references.Agency'),
        ),
        migrations.AddField(
            model_name='subaward',
            name='place_of_performance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='references.Location'),
        ),
        migrations.AddField(
            model_name='subaward',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='references.LegalEntity'),
        ),
        migrations.AddField(
            model_name='subaward',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.SubmissionAttributes'),
        ),
    ]
