# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-17 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0083_auto_20170414_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subaward',
            old_name='award_report_month',
            new_name='award_report_fy_month',
        ),
        migrations.RenameField(
            model_name='subaward',
            old_name='award_report_year',
            new_name='award_report_fy_year',
        ),
        migrations.AlterField(
            model_name='subaward',
            name='naics',
            field=models.TextField(blank=True, help_text='Specified which industry the work for this transaction falls into. A 6-digit code', null=True, verbose_name='NAICS'),
        ),
        migrations.AlterField(
            model_name='subaward',
            name='recovery_model_question1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subaward',
            name='recovery_model_question2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
