# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-18 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0068_merge_20170416_2014'),
        ('awards', '0084_auto_20170417_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='subaward',
            name='awarding_agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='awarding_subawards', to='references.Agency'),
        ),
        migrations.AlterField(
            model_name='subaward',
            name='funding_agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='funding_subawards', to='references.Agency'),
        ),
        migrations.AlterField(
            model_name='subaward',
            name='subaward_number',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='subaward',
            unique_together=set([('subaward_number', 'award')]),
        ),
    ]
