# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-18 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0084_auto_20170417_1414'),
        ('awards', '0082_remove_award_latest_submission'),
    ]

    operations = [
    ]
