# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-17 19:22
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def create_initial_history(apps, schema_editor):
    call_command('populate_history', '--auto')


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0085_historicaltransaction_historicaltransactionassistance_historicaltransactioncontract'),
    ]

    operations = [
        migrations.RunPython(create_initial_history),
    ]
