# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-19 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0086_auto_20170418_0225'),
        ('awards', '0085_auto_20170418_1643'),
    ]

    operations = [
    ]
