# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-25 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0088_merge_20170419_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.TextField(help_text='A description of the award', null=True, verbose_name='Award Description'),
        ),
        migrations.AlterField(
            model_name='award',
            name='fain',
            field=models.TextField(blank=True, db_index=True, help_text='An identification code assigned to each financial assistance award tracking purposes. The FAIN is tied to that award (and all future modifications to that award) throughout the award’s life. Each FAIN is assigned by an agency. Within an agency, FAIN are unique: each new award must be issued a new FAIN. FAIN stands for Federal Award Identification Number, though the digits are letters, not numbers.', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='piid',
            field=models.TextField(blank=True, db_index=True, help_text='Procurement Instrument Identifier - A unique identifier assigned to a federal contract, purchase order, basic ordering agreement, basic agreement, and blanket purchase agreement. It is used to track the contract, and any modifications or transactions related to it. After October 2017, it is between 13 and 17 digits, both letters and numbers.', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='type',
            field=models.TextField(db_index=True, help_text='\tThe mechanism used to distribute funding. The federal government can distribute funding in several forms. These award types include contracts, grants, loans, and direct payments.', null=True, verbose_name='Award Type'),
        ),
        migrations.AlterField(
            model_name='award',
            name='uri',
            field=models.TextField(blank=True, db_index=True, help_text='The uri of the award', null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='award_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='drv_award_id_field_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='fain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='parent_award_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='piid',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='action_date',
            field=models.DateField(help_text='The date this transaction was actioned', verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='action_type',
            field=models.TextField(blank=True, help_text='The type of transaction. For example, A, B, C, D', null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='description',
            field=models.TextField(help_text='The description of this transaction', null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='modification_number',
            field=models.TextField(blank=True, help_text='The modification number for this transaction', null=True, verbose_name='Modification Number'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='period_of_performance_current_end_date',
            field=models.DateField(help_text='The current end date of the period of performance', null=True, verbose_name='Period of Performance Current End Date'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='period_of_performance_start_date',
            field=models.DateField(help_text='The period of performance start date', null=True, verbose_name='Period of Performance Start Date'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='type',
            field=models.TextField(help_text='The type for this transaction. For example, A, B, C, D', null=True, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='usaspending_unique_transaction_id',
            field=models.TextField(blank=True, help_text='If this record is legacy USASpending data, this is the unique transaction identifier from that system', null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactionassistance',
            name='business_funds_indicator',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicaltransactionassistance',
            name='cfda_number',
            field=models.TextField(blank=True, null=True, verbose_name='CFDA Number'),
        ),
        migrations.AlterField(
            model_name='historicaltransactionassistance',
            name='cfda_title',
            field=models.TextField(blank=True, null=True, verbose_name='CFDA Title'),
        ),
        migrations.AlterField(
            model_name='historicaltransactionassistance',
            name='correction_late_delete_indicator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactionassistance',
            name='drv_award_finance_assistance_type_label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactionassistance',
            name='fain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactionassistance',
            name='fiscal_year_and_quarter_correction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactionassistance',
            name='sai_number',
            field=models.TextField(blank=True, null=True, verbose_name='SAI Number'),
        ),
        migrations.AlterField(
            model_name='historicaltransactionassistance',
            name='submitted_type',
            field=models.TextField(blank=True, null=True, verbose_name='Submitted Type'),
        ),
        migrations.AlterField(
            model_name='historicaltransactionassistance',
            name='uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='a76_fair_act_action',
            field=models.TextField(blank=True, help_text='A-76 FAIR act action', null=True, verbose_name='A-76 FAIR Act Action'),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='clinger_cohen_act_planning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='commercial_item_acquisition_procedures',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='commercial_item_test_program',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='consolidated_contract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='contingency_humanitarian_or_peacekeeping_operation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='contract_bundling',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='contract_financing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='contracting_officers_determination_of_business_size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='cost_accounting_standards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='cost_or_pricing_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='country_of_product_or_service_origin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='davis_bacon_act',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='dod_claimant_program_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='drv_parent_award_awarding_agency_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='epa_designated_product',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='evaluated_preference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='extent_competed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='fair_opportunity_limited_sources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='fed_biz_opps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='foreign_funding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='gfe_gfp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='idv_type',
            field=models.TextField(blank=True, help_text='The IDV type code', null=True, verbose_name='IDV Type'),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='information_technology_commercial_item_category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='interagency_contracting_authority',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='local_area_set_aside',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='major_program',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='multi_year_contract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='multiple_or_single_award_idv',
            field=models.TextField(blank=True, help_text='Specifies whether the IDV is a single more multiple award vehicle', null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='naics',
            field=models.TextField(blank=True, help_text='Specified which industry the work for this transaction falls into. A 6-digit code', null=True, verbose_name='NAICS'),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='naics_description',
            field=models.TextField(blank=True, help_text='A plain text description of the NAICS code', null=True, verbose_name='NAICS Description'),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='national_interest_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='number_of_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='number_of_offers_received',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='other_statutory_authority',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='other_than_full_and_open_competition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='parent_award_id',
            field=models.TextField(blank=True, help_text='The parent award id for this transaction. This is generally the piid of an IDV', null=True, verbose_name='Parent Award ID'),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='performance_based_service_acquisition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='piid',
            field=models.TextField(blank=True, help_text='The PIID of this transaction'),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='place_of_manufacture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='product_or_service_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='program_acronym',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='program_system_or_equipment_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='purchase_card_as_payment_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='rec_flag',
            field=models.TextField(blank=True, help_text='The rec flag', null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='recovered_materials_sustainability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='referenced_idv_agency_identifier',
            field=models.TextField(blank=True, help_text='The agency identifier of the agency on the IDV', null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='referenced_idv_modification_number',
            field=models.TextField(blank=True, help_text='The modification number for the referenced IDV', null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='research',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='sea_transportation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='service_contract_act',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='small_business_competitiveness_demonstration_program',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='solicitation_identifier',
            field=models.TextField(blank=True, null=True, verbose_name='Solicitation ID'),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='solicitation_procedures',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='subcontracting_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='transaction_number',
            field=models.TextField(blank=True, help_text='The transaction number for this transaction', null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='type_of_contract_pricing',
            field=models.TextField(blank=True, default='UN', help_text='The type of contract pricing data, as a code', null=True, verbose_name='Type of Contract Pricing'),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='type_of_idc',
            field=models.TextField(blank=True, help_text='Code representing the type of IDC', null=True, verbose_name='Type of IDC'),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='type_set_aside',
            field=models.TextField(blank=True, null=True, verbose_name='Type Set Aside'),
        ),
        migrations.AlterField(
            model_name='historicaltransactioncontract',
            name='walsh_healey_act',
            field=models.TextField(blank=True, help_text='Denotes whether this transaction is subject to the Walsh-Healey act', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action_date',
            field=models.DateField(help_text='The date this transaction was actioned', verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='action_type',
            field=models.TextField(blank=True, help_text='The type of transaction. For example, A, B, C, D', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(help_text='The description of this transaction', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='modification_number',
            field=models.TextField(blank=True, help_text='The modification number for this transaction', null=True, verbose_name='Modification Number'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='period_of_performance_current_end_date',
            field=models.DateField(help_text='The current end date of the period of performance', null=True, verbose_name='Period of Performance Current End Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='period_of_performance_start_date',
            field=models.DateField(help_text='The period of performance start date', null=True, verbose_name='Period of Performance Start Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.TextField(help_text='The type for this transaction. For example, A, B, C, D', null=True, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='usaspending_unique_transaction_id',
            field=models.TextField(blank=True, help_text='If this record is legacy USASpending data, this is the unique transaction identifier from that system', null=True),
        ),
        migrations.AlterField(
            model_name='transactionassistance',
            name='business_funds_indicator',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transactionassistance',
            name='cfda_number',
            field=models.TextField(blank=True, null=True, verbose_name='CFDA Number'),
        ),
        migrations.AlterField(
            model_name='transactionassistance',
            name='cfda_title',
            field=models.TextField(blank=True, null=True, verbose_name='CFDA Title'),
        ),
        migrations.AlterField(
            model_name='transactionassistance',
            name='correction_late_delete_indicator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionassistance',
            name='drv_award_finance_assistance_type_label',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionassistance',
            name='fain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionassistance',
            name='fiscal_year_and_quarter_correction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionassistance',
            name='sai_number',
            field=models.TextField(blank=True, null=True, verbose_name='SAI Number'),
        ),
        migrations.AlterField(
            model_name='transactionassistance',
            name='submitted_type',
            field=models.TextField(blank=True, null=True, verbose_name='Submitted Type'),
        ),
        migrations.AlterField(
            model_name='transactionassistance',
            name='uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='a76_fair_act_action',
            field=models.TextField(blank=True, help_text='A-76 FAIR act action', null=True, verbose_name='A-76 FAIR Act Action'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='clinger_cohen_act_planning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='commercial_item_acquisition_procedures',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='commercial_item_test_program',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='consolidated_contract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='contingency_humanitarian_or_peacekeeping_operation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='contract_bundling',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='contract_financing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='contracting_officers_determination_of_business_size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='cost_accounting_standards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='cost_or_pricing_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='country_of_product_or_service_origin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='davis_bacon_act',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='dod_claimant_program_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='drv_parent_award_awarding_agency_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='epa_designated_product',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='evaluated_preference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='extent_competed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='fair_opportunity_limited_sources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='fed_biz_opps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='foreign_funding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='gfe_gfp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='idv_type',
            field=models.TextField(blank=True, help_text='The IDV type code', null=True, verbose_name='IDV Type'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='information_technology_commercial_item_category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='interagency_contracting_authority',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='local_area_set_aside',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='major_program',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='multi_year_contract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='multiple_or_single_award_idv',
            field=models.TextField(blank=True, help_text='Specifies whether the IDV is a single more multiple award vehicle', null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='naics',
            field=models.TextField(blank=True, help_text='Specified which industry the work for this transaction falls into. A 6-digit code', null=True, verbose_name='NAICS'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='naics_description',
            field=models.TextField(blank=True, help_text='A plain text description of the NAICS code', null=True, verbose_name='NAICS Description'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='national_interest_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='number_of_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='number_of_offers_received',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='other_statutory_authority',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='other_than_full_and_open_competition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='parent_award_id',
            field=models.TextField(blank=True, help_text='The parent award id for this transaction. This is generally the piid of an IDV', null=True, verbose_name='Parent Award ID'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='performance_based_service_acquisition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='piid',
            field=models.TextField(blank=True, help_text='The PIID of this transaction'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='place_of_manufacture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='product_or_service_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='program_acronym',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='program_system_or_equipment_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='purchase_card_as_payment_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='rec_flag',
            field=models.TextField(blank=True, help_text='The rec flag', null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='recovered_materials_sustainability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='referenced_idv_agency_identifier',
            field=models.TextField(blank=True, help_text='The agency identifier of the agency on the IDV', null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='referenced_idv_modification_number',
            field=models.TextField(blank=True, help_text='The modification number for the referenced IDV', null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='research',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='sea_transportation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='service_contract_act',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='small_business_competitiveness_demonstration_program',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='solicitation_identifier',
            field=models.TextField(blank=True, null=True, verbose_name='Solicitation ID'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='solicitation_procedures',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='subcontracting_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='transaction_number',
            field=models.TextField(blank=True, help_text='The transaction number for this transaction', null=True),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='type_of_contract_pricing',
            field=models.TextField(blank=True, default='UN', help_text='The type of contract pricing data, as a code', null=True, verbose_name='Type of Contract Pricing'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='type_of_idc',
            field=models.TextField(blank=True, help_text='Code representing the type of IDC', null=True, verbose_name='Type of IDC'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='type_set_aside',
            field=models.TextField(blank=True, null=True, verbose_name='Type Set Aside'),
        ),
        migrations.AlterField(
            model_name='transactioncontract',
            name='walsh_healey_act',
            field=models.TextField(blank=True, help_text='Denotes whether this transaction is subject to the Walsh-Healey act', null=True),
        ),
    ]
