# Generated by Django 2.2.28 on 2022-05-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0092_transactionfpds_entity_data_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CovidFinancialAccountMatview',
        ),
    ]
