# Generated by Django 2.2.28 on 2022-05-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0093_auto_20220512_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CovidFinancialAccountMatview',
        ),
    ]
