# Generated by Django 3.2.13 on 2022-08-26 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0095_auto_20220617_1620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrokerSubaward',
        ),
        migrations.DeleteModel(
            name='Subaward',
        ),
    ]
