# Generated by Django 3.2.13 on 2022-08-26 20:10

from django.db import migrations
from usaspending_api.awards.models.transaction_fabs import vw_transaction_fabs_sql
from usaspending_api.awards.models.transaction_fpds import vw_transaction_fpds_sql
from usaspending_api.awards.models.transaction_normalized import vw_transaction_normalized_sql


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0096_removing_subaward_models'),
        ('search', '0014_additional_transaction_search_cols'),
    ]

    operations = [
        migrations.RunSQL(
            sql=vw_transaction_fabs_sql,
            reverse_sql="DROP VIEW IF EXISTS vw_transaction_fabs",
            # Without this, Django will try to actually change the old table names in another migration
            # This says we've already done it.
            state_operations=[
                migrations.AlterModelTable(
                    name='transactionfabs',
                    table='vw_transaction_fabs',
                )
            ]
        ),
        migrations.AlterModelOptions(
            name='transactionfabs',
            options={'managed': False},
        ),

        migrations.RunSQL(
            sql=vw_transaction_fpds_sql,
            reverse_sql="DROP VIEW IF EXISTS vw_transaction_fpds",
            # Without this, Django will try to actually change the old table names in another migration
            # This says we've already done it.
            state_operations=[
                migrations.AlterModelTable(
                    name='transactionfpds',
                    table='vw_transaction_fpds',
                )
            ]
        ),
        migrations.AlterModelOptions(
            name='transactionfpds',
            options={'managed': False},
        ),

        migrations.RunSQL(
            sql=vw_transaction_normalized_sql,
            reverse_sql="DROP VIEW IF EXISTS vw_transaction_normalized",
            # Without this, Django will try to actually change the old table names in another migration
            # This says we've already done it.
            state_operations=[
                migrations.AlterModelTable(
                    name='transactionnormalized',
                    table='vw_transaction_normalized',
                )
            ]
        ),
        migrations.AlterModelOptions(
            name='transactionnormalized',
            options={'managed': False},
        ),
    ]
