# Generated by Django 3.2.15 on 2022-10-26 19:13

from django.db import migrations
from usaspending_api.awards.models.award import vw_awards_sql


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0097_transaction_views'),
        ('search', '0020_awardsearch_data_source'),
    ]

    operations = [
        migrations.RunSQL(
            sql=vw_awards_sql,
            reverse_sql="DROP VIEW IF EXISTS vw_awards",
            # Without this, Django will try to actually change the old table names in another migration
            # This says we've already done it.
            state_operations=[
                migrations.AlterModelTable(
                    name='award',
                    table='vw_awards',
                )
            ]
        ),
        migrations.AlterModelOptions(
            name='award',
            options={'managed': False},
        ),
    ]
