# Generated by Django 3.2.15 on 2022-12-15 20:29

from django.db import migrations, models
import django.db.models.deletion

from usaspending_api.awards.models.award import vw_awards_sql


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0020_auto_20221215_2029'),
        ('awards', '0097_transaction_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'managed': False},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE financial_accounts_by_awards DROP CONSTRAINT financial_accounts_by_awards_award_id_eb90a5fa_fk_awards_id",
            reverse_sql="",
            state_operations=[
                migrations.AlterField(
                    model_name='financialaccountsbyawards',
                    name='award',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='financial_set', to='search.awardsearch'),
                )
            ]
        ),
        migrations.RunSQL(
            sql="ALTER TABLE rpt.parent_award DROP CONSTRAINT parent_award_award_id_97f76a63_fk_awards_id",
            reverse_sql="",
            state_operations=[
                migrations.AlterField(
                    model_name='parentaward',
                    name='award',
                    field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                               serialize=False, to='search.awardsearch'),
                )
            ]
        ),
        migrations.RunSQL(
            sql=vw_awards_sql,
            reverse_sql="DROP VIEW IF EXISTS vw_awards",
            # Without this, Django will try to actually change the old table names in another migration
            # This says we've already done it.
            state_operations=[
                migrations.AlterModelTable(
                    name='award',
                    table='vw_awards',
                )
            ]
        ),
        migrations.AlterModelOptions(
            name='award',
            options={'managed': False},
        ),
    ]
