# Generated by Django 3.2.15 on 2022-12-08 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0021_auto_20221208_1432'),
        ('awards', '0098_award_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaccountsbyawards',
            name='award',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_set', to='search.awardsearch'),
        ),
        migrations.AlterField(
            model_name='parentaward',
            name='award',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='search.awardsearch'),
        ),
    ]
