# Generated by Django 3.2.13 on 2023-02-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0099_auto_20230113_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='CToDLinkageUpdates',
            fields=[
                ('financial_accounts_by_awards_id', models.IntegerField(primary_key=True, serialize=False)),
                ('award_id', models.IntegerField()),
            ],
            options={
                'db_table': 'c_to_d_linkage_updates',
                'managed': True,
            },
        ),
    ]
