# Generated by Django 5.0.4 on 2024-04-15 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0103_transaction_fabs_view_add_current_cd_cols"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactiondelta",
            name="transaction",
            field=models.OneToOneField(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="awards.transactionnormalized",
            ),
        ),
    ]
