# Generated by Django 3.2.25 on 2024-10-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0105_alter_financialaccountsbyawards_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccountsbyawards',
            name='pa_reporting_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialaccountsbyawards',
            name='prior_year_adjustment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialaccountsbyawards',
            name='ussgl480110_reinstated_del_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name='financialaccountsbyawards',
            name='ussgl490110_reinstated_del_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),
    ]
