# Generated by Django 4.2.17 on 2024-12-10 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0106_auto_20241018_1526"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialaccountsbyawards",
            name="pa_reporting_key",
            field=models.TextField(blank=True, help_text="A unique identifier for a Program Activity", null=True),
        ),
        migrations.AlterField(
            model_name="transactiondelta",
            name="transaction",
            field=models.OneToOneField(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="awards.transactionnormalized",
            ),
        ),
    ]
