# Generated by Django 4.2.19 on 2025-04-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0110_financialaccountsbyawards_faba_object_sumission_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="financialaccountsbyawards",
            index=models.Index(
                condition=models.Q(("transaction_obligated_amount", False)),
                fields=["submission_id", "treasury_account_id"],
                name="faba_treasury_submission_idx",
            ),
        ),
    ]
