# Generated by Django 4.2.23 on 2025-08-06 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0070_programactivitypark"),
        ("awards", "0110_financialaccountsbyawards_faba_treasury_submission_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialaccountsbyawards",
            name="program_activity_reporting_key",
            field=models.ForeignKey(
                blank=True,
                db_column="program_activity_reporting_key",
                help_text="A unique identifier for a Program Activity",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="references.programactivitypark",
            ),
        ),
    ]
