# Generated by Django 4.2.23 on 2025-08-08 19:43

from django.db import migrations

from usaspending_api.awards.models.award import vw_awards_sql


class Migration(migrations.Migration):
    dependencies = [
        ("awards", "0111_alter_financialaccountsbyawards_program_activity_reporting_key"),
        ("search", "0058_add_transaction_count_field"),
    ]

    operations = [
        migrations.RunSQL(
            sql=vw_awards_sql,
            reverse_sql="DROP VIEW IF EXISTS vw_awards",
            # Without this, Django will try to actually change the old table names in another migration
            # This says we've already done it.
            state_operations=[
                migrations.AlterModelTable(
                    name="award",
                    table="vw_awards",
                )
            ],
        )
    ]
