# Generated by Django 4.2.23 on 2025-09-11 20:32
from pathlib import Path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0112_move_vw_awards_creation_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialaccountsbyawards",
            name="ussgl480210_rein_undel_obs_cpe",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name="financialaccountsbyawards",
            name="ussgl497210_down_adj_refun_cpe",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),

        migrations.RunSQL(
            sql=[f"{Path('usaspending_api/download/sql/vw_financial_accounts_by_awards_download.sql').read_text()}"],
            reverse_sql=["DROP VIEW IF EXISTS vw_financial_accounts_by_awards_download;"],
        ),
    ]


