# Generated by Django 4.2.23 on 2025-09-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0112_move_vw_awards_creation_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialaccountsbyawards",
            name="ussgl480210_rein_undel_obs_cpe",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),
        migrations.AddField(
            model_name="financialaccountsbyawards",
            name="ussgl497210_down_adj_refun_cpe",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),
    ]
