# Generated by Django 4.2.23 on 2025-10-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0113_financialaccountsbyawards_ussgl480210_rein_undel_obs_cpe_and_more"),
    ]

    operations = [
        # This recreates the table that was originally created as part of Awards migration "0100_ctodlinkageupdates.py".
        # A management command was previously recreating this table without any indexes or constraints. The SQL below
        # was taken directly from the sqlmigrate for the migration mentioned above. Additionally, the "NOT NULL"
        # constraint is carried forward so that Django can manage the table in the following AlterField statement.
        migrations.RunSQL(
            sql="""
                DROP TABLE IF EXISTS c_to_d_linkage_updates;
                CREATE TABLE "c_to_d_linkage_updates" ("financial_accounts_by_awards_id" integer NOT NULL PRIMARY KEY, "award_id" integer NOT NULL);
            """
        ),
        migrations.AlterField(
            model_name="ctodlinkageupdates",
            name="award_id",
            field=models.IntegerField(null=True),
        ),
    ]
