# Generated by Django 5.2.14 on 2026-05-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0114_alter_ctodlinkageupdates_award_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='financialaccountsbyawards',
            new_name='financial_a_disaste_396e45_idx',
            old_fields=('disaster_emergency_fund', 'submission', 'award', 'piid', 'fain', 'uri', 'parent_award_id', 'transaction_obligated_amount', 'gross_outlay_amount_by_award_cpe'),
        ),
    ]
