# Generated by Django 5.2.14 on 2026-09-10 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0115_rename_financialaccountsbyawards_disaster_emergency_fund_submission_award_piid_fain_uri_parent_award'),
        ('search', '0061_awardsearch_object_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondelta',
            name='transaction',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='search.transactionsearch'),
        ),
    ]
