# Generated by Django 5.2.14 on 2026-08-20 14:21

from django.db import migrations

from usaspending_api.awards.models.transaction_fabs import vw_transaction_fabs_sql


class Migration(migrations.Migration):

    dependencies = [
        (
            'awards',
            '0115_rename_financialaccountsbyawards_disaster_emergency_fund_submission_award_piid_fain_uri_parent_award'
        ),
        (
            'search',
            '0062_new_award_amount_award_recipient_fields'
        )
    ]

    operations = [
        migrations.RunSQL(
            sql=vw_transaction_fabs_sql,
            reverse_sql="DROP VIEW IF EXISTS vw_transaction_fabs",
            # Without this, Django will try to actually change the old table names in another migration
            # This says we've already done it.
            state_operations=[
                migrations.AlterModelTable(
                    name="transactionfabs",
                    table="vw_transaction_fabs",
                )
            ],
        ),
        migrations.AlterModelOptions(
            name="transactionfabs",
            options={"managed": False},
        ),
    ]
