worker_processes  1;
daemon off;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout  65;

    server {
        listen 80;
        server_name _;

        # Route anything starting with /llm to Daphne (ASGI)
        location ~* /llm/ {
            proxy_pass http://0.0.0.0:8001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Everything else goes to uWSGI (WSGI)
        location / {
            include uwsgi_params;
            uwsgi_pass 0.0.0.0:8000;
        }
    }
}
