[program:daphne]
command=daphne -b 0.0.0.0 -p 8001 --access-log - --proxy-headers usaspending_api.asgi:application
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
directory=/data-act/backend
startsecs=1
startretries=10
user=ec2-user
environment=PYTHONPATH=%(ENV_PATH)s:/data-act/backend
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:uwsgi]
command=uwsgi --ini /data-act/backend/config/uwsgi.ini --socket :3030 --stats /tmp/stats.socket
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
directory=/data-act/backend
startsecs=1
startretries=10
user=ec2-user
environment=PYTHONPATH=%(ENV_PATH)s:/data-act/backend
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
directory=/data-act/backend
startsecs=1
startretries=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[supervisord]
nodaemon=true
logfile_maxbytes=104857600
logfile=/data-act/backend/usaspending_api/logs/supervisord.log
