award_search_sql_string = r"""
CREATE OR REPLACE TABLE {DESTINATION_TABLE} (
    treasury_account_identifiers ARRAY<INTEGER>,
    award_id LONG NOT NULL,
    category STRING,
    type STRING,
    type_description STRING,
    generated_unique_award_id STRING,
    display_award_id STRING,
    update_date TIMESTAMP,
    piid STRING,
    fain STRING,
    uri STRING,
    award_amount NUMERIC(23, 2),
    total_obligation NUMERIC(23, 2),
    description STRING,
    total_obl_bin STRING,
    total_subsidy_cost NUMERIC(23, 2),
    total_loan_value NUMERIC(23, 2),
    recipient_hash STRING,
    recipient_levels ARRAY<STRING>,
    recipient_name STRING,
    recipient_unique_id STRING,
    parent_recipient_unique_id STRING,
    recipient_uei STRING,
    parent_uei STRING,
    business_categories ARRAY<STRING>,
    action_date DATE,
    fiscal_year INTEGER,
    last_modified_date DATE,
    period_of_performance_start_date DATE,
    period_of_performance_current_end_date DATE,
    date_signed DATE,
    ordering_period_end_date DATE,
    original_loan_subsidy_cost NUMERIC(23, 2),
    face_value_loan_guarantee NUMERIC(23, 2),
    awarding_agency_id INTEGER,
    funding_agency_id INTEGER,
    awarding_toptier_agency_name STRING,
    funding_toptier_agency_name STRING,
    awarding_subtier_agency_name STRING,
    funding_subtier_agency_name STRING,
    awarding_toptier_agency_code STRING,
    funding_toptier_agency_code STRING,
    awarding_subtier_agency_code STRING ,
    funding_subtier_agency_code STRING,
    funding_toptier_agency_id STRING,
    funding_subtier_agency_id STRING,
    recipient_location_country_code STRING,
    recipient_location_country_name STRING,
    recipient_location_state_code STRING,
    recipient_location_county_code STRING,
    recipient_location_county_name STRING,
    recipient_location_congressional_code STRING,
    recipient_location_zip5 STRING,
    recipient_location_city_name STRING,
    recipient_location_state_name STRING,
    recipient_location_state_fips STRING,
    recipient_location_state_population INTEGER,
    recipient_location_county_population INTEGER,
    recipient_location_congressional_population INTEGER,
    pop_country_name STRING,
    pop_country_code STRING,
    pop_state_code STRING,
    pop_county_code STRING,
    pop_county_name STRING,
    pop_city_code STRING,
    pop_zip5 STRING,
    pop_congressional_code STRING,
    pop_city_name STRING,
    pop_state_name STRING,
    pop_state_fips STRING,
    pop_state_population INTEGER,
    pop_county_population INTEGER,
    pop_congressional_population INTEGER,
    cfda_program_title STRING,
    cfda_number STRING,
    cfdas ARRAY<STRING>,
    sai_number STRING,
    type_of_contract_pricing STRING,
    extent_competed STRING,
    type_set_aside STRING,
    product_or_service_code STRING,
    product_or_service_description STRING,
    naics_code STRING,
    naics_description STRING,
    tas_paths ARRAY<STRING>,
    tas_components ARRAY<STRING>,
    disaster_emergency_fund_codes ARRAY<STRING>,
    covid_spending_by_defc STRING,
    total_covid_outlay NUMERIC(23, 2),
    total_covid_obligation NUMERIC(23, 2)
)
USING DELTA
LOCATION 's3a://{SPARK_S3_BUCKET}/{DELTA_LAKE_S3_PATH}/{DESTINATION_DATABASE}/{DESTINATION_TABLE}'
"""
