from django.db import models

# Create your models here.

# AJ 09/07/2016...Added 5 tables below for financial_activities

class TreasuryAppropriationAccount(models.Model):
    treasury_account_identifier = models.IntegerField(primary_key=True)
    tas_rendering_label = models.CharField(max_length=22)
    allocation_transfer_agency_id = models.CharField(max_length=3, blank=True, null=True)
    responsible_agency_id = models.CharField(max_length=3)
    beginning_period_of_availa = models.CharField(max_length=4, blank=True, null=True)
    ending_period_of_availabil = models.CharField(max_length=4, blank=True, null=True)
    availability_type_code = models.CharField(max_length=1, blank=True, null=True)
    main_account_code = models.CharField(max_length=4)
    sub_account_code = models.CharField(max_length=3)
    drv_approp_avail_pd_start_date = models.DateField(blank=True, null=True)
    drv_approp_avail_pd_end_date = models.DateField(blank=True, null=True)
    drv_approp_account_exp_status = models.CharField(max_length=10, blank=True, null=True)
    create_date = models.DateTimeField(blank=True, null=True)
    update_date = models.DateTimeField(blank=True, null=True)
    create_user_id = models.CharField(max_length=50, blank=True, null=True)
    update_user_id = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'treasury_appropriation_account'

class AppropriationAccountBalances(models.Model):
    appropriation_account_balances_id = models.AutoField(primary_key=True)
    treasury_account_identifier = models.ForeignKey('TreasuryAppropriationAccount', models.DO_NOTHING, db_column='treasury_account_identifier')
    submission_process = models.ForeignKey('SubmissionProcess', models.DO_NOTHING)
    budget_authority_unobligat_fyb = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    adjustments_to_unobligated_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    budget_authority_appropria_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    borrowing_authority_amount_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    contract_authority_amount_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    spending_authority_from_of_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    other_budgetary_resources_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    budget_authority_available_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    gross_outlay_amount_by_tas_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    deobligations_recoveries_r_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    unobligated_balance_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    status_of_budgetary_resour_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    obligations_incurred_total_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    drv_approp_avail_pd_start_date = models.DateField(blank=True, null=True)
    drv_approp_avail_pd_end_date = models.DateField(blank=True, null=True)
    drv_approp_account_exp_status = models.CharField(max_length=10, blank=True, null=True)
    tas_rendering_label = models.CharField(max_length=22, blank=True, null=True)
    drv_obligations_unpaid_amount = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    drv_other_obligated_amount = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    reporting_period_start = models.DateField(blank=True, null=True)
    reporting_period_end = models.DateField(blank=True, null=True)
    create_date = models.DateTimeField(blank=True, null=True)
    update_date = models.DateTimeField(blank=True, null=True)
    create_user_id = models.CharField(max_length=50, blank=True, null=True)
    update_user_id = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'appropriation_account_balances'

class FinancialAccountsByProgramActivityObjectClass(models.Model):
    financial_accounts_by_program_activity_object_class_id = models.AutoField(primary_key=True)
    program_activity_name = models.CharField(max_length=164)
    program_activity_code = models.ForeignKey('RefProgramActivity', models.DO_NOTHING, db_column='program_activity_code')
    object_class = models.ForeignKey('RefObjectClassCode', models.DO_NOTHING, db_column='object_class')
    by_direct_reimbursable_fun = models.CharField(max_length=1)
    appropriation_account_balances = models.ForeignKey(AppropriationAccountBalances, models.DO_NOTHING)
    ussgl480100_undelivered_or_fyb = models.DecimalField(max_digits=21, decimal_places=0)
    ussgl480100_undelivered_or_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    ussgl483100_undelivered_or_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    ussgl488100_upward_adjustm_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    ussgl490100_delivered_orde_fyb = models.DecimalField(max_digits=21, decimal_places=0)
    ussgl490100_delivered_orde_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    ussgl493100_delivered_orde_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    ussgl498100_upward_adjustm_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    ussgl480200_undelivered_or_fyb = models.DecimalField(max_digits=21, decimal_places=0)
    ussgl480200_undelivered_or_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    ussgl483200_undelivered_or_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    ussgl488200_upward_adjustm_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    ussgl490200_delivered_orde_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    ussgl490800_authority_outl_fyb = models.DecimalField(max_digits=21, decimal_places=0)
    ussgl490800_authority_outl_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    ussgl498200_upward_adjustm_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    obligations_undelivered_or_fyb = models.DecimalField(max_digits=21, decimal_places=0)
    obligations_undelivered_or_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    obligations_delivered_orde_fyb = models.DecimalField(max_digits=21, decimal_places=0)
    obligations_delivered_orde_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    gross_outlays_undelivered_fyb = models.DecimalField(max_digits=21, decimal_places=0)
    gross_outlays_undelivered_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    gross_outlays_delivered_or_fyb = models.DecimalField(max_digits=21, decimal_places=0)
    gross_outlays_delivered_or_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    gross_outlay_amount_by_pro_fyb = models.DecimalField(max_digits=21, decimal_places=0)
    gross_outlay_amount_by_pro_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    obligations_incurred_by_pr_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    ussgl487100_downward_adjus_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    ussgl497100_downward_adjus_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    ussgl487200_downward_adjus_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    ussgl497200_downward_adjus_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    deobligations_recov_by_pro_cpe = models.DecimalField(max_digits=21, decimal_places=0)
    drv_obli_inc_by_prog_obj_class = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    drv_obligations_undel_ord_unp = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    reporting_period_start = models.DateField(blank=True, null=True)
    reporting_period_end = models.DateField(blank=True, null=True)
    create_date = models.DateTimeField(blank=True, null=True)
    update_date = models.DateTimeField(blank=True, null=True)
    create_user_id = models.CharField(max_length=50, blank=True, null=True)
    update_user_id = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'financial_accounts_by_program_activity_object_class'
        
class FinancialAccountsByAwards(models.Model):
    financial_accounts_by_awards_id = models.AutoField(primary_key=True)
    appropriation_account_balances = models.ForeignKey(AppropriationAccountBalances, models.DO_NOTHING)
    program_activity_name = models.CharField(max_length=164, blank=True, null=True)    
    program_activity_code = models.ForeignKey('RefProgramActivity', models.DO_NOTHING, db_column='program_activity_code', blank=True, null=True)
    object_class = models.ForeignKey('RefObjectClassCode', models.DO_NOTHING, db_column='object_class')
    by_direct_reimbursable_fun = models.CharField(max_length=1, blank=True, null=True)
    piid = models.CharField(max_length=50, blank=True, null=True)
    parent_award_id = models.CharField(max_length=50, blank=True, null=True)
    fain = models.CharField(max_length=30, blank=True, null=True)
    uri = models.CharField(max_length=70, blank=True, null=True)
    award_type = models.CharField(max_length=30, blank=True, null=True)
    ussgl480100_undelivered_or_fyb = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    ussgl480100_undelivered_or_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    ussgl483100_undelivered_or_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    ussgl488100_upward_adjustm_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    ussgl490100_delivered_orde_fyb = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    ussgl490100_delivered_orde_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    ussgl493100_delivered_orde_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    ussgl498100_upward_adjustm_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    ussgl480200_undelivered_or_fyb = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    ussgl480200_undelivered_or_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    ussgl483200_undelivered_or_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    ussgl488200_upward_adjustm_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    ussgl490200_delivered_orde_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    ussgl490800_authority_outl_fyb = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    ussgl490800_authority_outl_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    ussgl498200_upward_adjustm_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    obligations_undelivered_or_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    obligations_delivered_orde_fyb = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    obligations_delivered_orde_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    gross_outlays_undelivered_fyb = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    gross_outlays_undelivered_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    gross_outlays_delivered_or_fyb = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    gross_outlay_amount_by_awa_fyb = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    gross_outlay_amount_by_awa_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    obligations_incurred_byawa_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    ussgl487100_downward_adjus_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    ussgl497100_downward_adjus_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    ussgl487200_downward_adjus_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    ussgl497200_downward_adjus_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    deobligations_recov_by_awa_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    obligations_undelivered_or_fyb = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    gross_outlays_delivered_or_cpe = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    drv_award_id_field_type = models.CharField(max_length=10, blank=True, null=True)
    drv_oblig_incur_total_by_award = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    reporting_period_start = models.DateField(blank=True, null=True)
    reporting_period_end = models.DateField(blank=True, null=True)
    create_date = models.DateTimeField(blank=True, null=True)
    update_date = models.DateTimeField(blank=True, null=True)
    create_user_id = models.CharField(max_length=50, blank=True, null=True)
    update_user_id = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'financial_accounts_by_awards'

class FinancialAccountsByAwardsTransactionObligations(models.Model):
    financial_accounts_by_awards_transaction_obligations_id = models.AutoField(primary_key=True)
    financial_accounts_by_awards = models.ForeignKey(FinancialAccountsByAwards, models.DO_NOTHING)
    transaction_obligated_amou = models.DecimalField(max_digits=21, decimal_places=0, blank=True, null=True)
    reporting_period_start = models.DateField(blank=True, null=True)
    reporting_period_end = models.DateField(blank=True, null=True)
    create_date = models.DateTimeField(blank=True, null=True)
    update_date = models.DateTimeField(blank=True, null=True)
    create_user_id = models.CharField(max_length=50, blank=True, null=True)
    update_user_id = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'financial_accounts_by_awards_transaction_obligations'
