# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-24 19:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcatalog',
            name='request',
            field=django.contrib.postgres.fields.jsonb.JSONField(help_text='The serialized form of the POST request'),
        ),
    ]
