# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-04 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_csvdownloadableresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdownloadableresponse',
            name='download_location',
            field=models.TextField(null=True),
        ),
    ]
