# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-03 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import usaspending_api.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20170324_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVdownloadableResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_path', models.TextField()),
                ('file_name', models.TextField()),
                ('status_code', models.IntegerField(default=0)),
                ('status_description', models.TextField(default='This file has been requested, and is awaiting queueing')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_files', to='common.RequestCatalog')),
            ],
        ),
    ]
