# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 16:17
from __future__ import unicode_literals

from pathlib import Path

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Unmanaged Models for Download Views
        migrations.CreateModel(
            name="AccountBalancesView",
            fields=[],
            options={
                "db_table": "vw_account_balances",
                "managed": False
            }
        ),
        migrations.RunSQL(
            sql=[f"{Path('usaspending_api/download/sql/account_balances.sql').read_text()}"],
            reverse_sql=["DROP VIEW IF EXISTS vw_account_balances;"],
        ),
        migrations.CreateModel(
            name="AwardFinancialView",
            fields=[],
            options={
                "db_table": "vw_award_financial",
                "managed": False
            }
        ),
        migrations.RunSQL(
            sql=[f"{Path('usaspending_api/download/sql/award_financial.sql').read_text()}"],
            reverse_sql=["DROP VIEW IF EXISTS vw_award_financial;"],
        ),
        migrations.CreateModel(
            name="ObjectClassProgramActivityView",
            fields=[],
            options={
                "db_table": "vw_object_class_program_activity",
                "managed": False
            }
        ),
        migrations.RunSQL(
            sql=[f"{Path('usaspending_api/download/sql/object_class_program_activity.sql').read_text()}"],
            reverse_sql=["DROP VIEW IF EXISTS vw_object_class_program_activity;"],
        ),

        # Other migrations
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('download_job_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.TextField()),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('number_of_rows', models.IntegerField(blank=True, null=True)),
                ('number_of_columns', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'download_job',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('job_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'job_status',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='downloadjob',
            name='job_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='download.JobStatus'),
        ),
    ]
