# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadjob',
            name='json_request',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadjob',
            name='monthly_download',
            field=models.BooleanField(default=False),
        ),
    ]
