# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 20:47
from __future__ import unicode_literals

from django.db import migrations, models

transaction_index = 'CREATE INDEX transaction_normalized_id_asc_idx ON transaction_normalized(id ASC)'
award_index = 'CREATE INDEX awards_id_asc_idx ON awards (id ASC)'
subaward_index = 'CREATE INDEX subwards_id_asc_idx ON awards_subaward (id ASC)'

class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_auto_20180216_2047'),
    ]

    operations = [
        migrations.RunSQL(sql=transaction_index,
                          reverse_sql="DROP INDEX transaction_normalized_id_asc_idx"),
        migrations.RunSQL(sql=award_index,
                          reverse_sql="DROP INDEX awards_id_asc_idx"),
        migrations.RunSQL(sql=subaward_index,
                          reverse_sql="DROP INDEX subwards_id_asc_idx")
    ]
