# Generated by Django 2.2.23 on 2021-06-10 13:36
from pathlib import Path

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("awards", "0001_initial"),
        ("download", "0003_auto_20180306_1726"),
        ("financial_activities", "0001_initial")
    ]

    operations = [
        migrations.CreateModel(
            name="AccountBalancesView",
            fields=[],
            options={
                "db_table": "vw_account_balances",
                "managed": False
            }
        ),
        migrations.RunSQL(
            sql=[f"{Path('usaspending_api/download/sql/account_balances.sql').read_text()}"],
            reverse_sql=["DROP VIEW IF EXISTS vw_account_balances;"],
        ),
        migrations.CreateModel(
            name="AwardFinancialView",
            fields=[],
            options={
                "db_table": "vw_award_financial",
                "managed": False
            }
        ),
        migrations.RunSQL(
            sql=[f"{Path('usaspending_api/download/sql/award_financial.sql').read_text()}"],
            reverse_sql=["DROP VIEW IF EXISTS vw_award_financial;"],
        ),
        migrations.CreateModel(
            name="ObjectClassProgramActivityView",
            fields=[],
            options={
                "db_table": "vw_object_class_program_activity",
                "managed": False
            }
        ),
        migrations.RunSQL(
            sql=[f"{Path('usaspending_api/download/sql/object_class_program_activity.sql').read_text()}"],
            reverse_sql=["DROP VIEW IF EXISTS vw_object_class_program_activity;"],
        ),
    ]
