# Generated by Django 2.2.23 on 2021-12-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0004_download_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadJobLookup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('download_job_id', models.IntegerField(db_index=True)),
                ('lookup_id', models.BigIntegerField()),
                ('lookup_id_type', models.TextField()),
            ],
            options={
                'db_table': 'download_job_lookup',
                'managed': True,
            },
        ),
    ]
