# Generated by Django 4.2.23 on 2025-10-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("download", "0005_downloadjoblookup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadjob",
            name="file_name",
            field=models.TextField(db_index=True),
        ),
    ]
