# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppropriationAccountBalances',
            fields=[
                ('appropriation_account_balances_id', models.AutoField(primary_key=True, serialize=False)),
                ('budget_authority_unobligat_fyb', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('adjustments_to_unobligated_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('budget_authority_appropria_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('borrowing_authority_amount_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('contract_authority_amount_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('spending_authority_from_of_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('other_budgetary_resources_cpe', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('budget_authority_available_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('gross_outlay_amount_by_tas_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('deobligations_recoveries_r_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('unobligated_balance_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('status_of_budgetary_resour_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('obligations_incurred_total_cpe', models.DecimalField(decimal_places=0, max_digits=21)),
                ('drv_approp_avail_pd_start_date', models.DateField(blank=True, null=True)),
                ('drv_approp_avail_pd_end_date', models.DateField(blank=True, null=True)),
                ('drv_approp_account_exp_status', models.CharField(blank=True, max_length=10, null=True)),
                ('tas_rendering_label', models.CharField(blank=True, max_length=22, null=True)),
                ('drv_obligations_unpaid_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('drv_other_obligated_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=21, null=True)),
                ('reporting_period_start', models.DateField(blank=True, null=True)),
                ('reporting_period_end', models.DateField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('create_user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('update_user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('submission_process', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='submissions.SubmissionProcess')),
            ],
            options={
                'db_table': 'appropriation_account_balances',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TreasuryAppropriationAccount',
            fields=[
                ('treasury_account_identifier', models.IntegerField(primary_key=True, serialize=False)),
                ('tas_rendering_label', models.CharField(max_length=22)),
                ('allocation_transfer_agency_id', models.CharField(blank=True, max_length=3, null=True)),
                ('responsible_agency_id', models.CharField(max_length=3)),
                ('beginning_period_of_availa', models.CharField(blank=True, max_length=4, null=True)),
                ('ending_period_of_availabil', models.CharField(blank=True, max_length=4, null=True)),
                ('availability_type_code', models.CharField(blank=True, max_length=1, null=True)),
                ('main_account_code', models.CharField(max_length=4)),
                ('sub_account_code', models.CharField(max_length=3)),
                ('drv_approp_avail_pd_start_date', models.DateField(blank=True, null=True)),
                ('drv_approp_avail_pd_end_date', models.DateField(blank=True, null=True)),
                ('drv_approp_account_exp_status', models.CharField(blank=True, max_length=10, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('create_user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('update_user_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'treasury_appropriation_account',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='appropriationaccountbalances',
            name='treasury_account_identifier',
            field=models.ForeignKey(db_column='treasury_account_identifier', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.TreasuryAppropriationAccount'),
        ),
    ]
