# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 03:07
from __future__ import unicode_literals

from django.db import migrations

from usaspending_api.common.helpers import CORRECTED_CGAC_PG_FUNCTION_DEF


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(CORRECTED_CGAC_PG_FUNCTION_DEF),
    ]
