# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_auto_20170504_2254'),
        ('accounts', '0002_appropriationaccountbalances_final_of_fy'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryappropriationaccount',
            name='awarding_toptier_agency',
            field=models.ForeignKey(help_text='The toptier agency object associated with the ATA', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tas_ata', to='references.ToptierAgency'),
        ),
        migrations.AddField(
            model_name='treasuryappropriationaccount',
            name='funding_toptier_agency',
            field=models.ForeignKey(help_text='The toptier agency object associated with the AID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tas_aid', to='references.ToptierAgency'),
        ),
    ]
