# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160912_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='submission_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.SubmissionProcess'),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='treasury_account_identifier',
            field=models.ForeignKey(db_column='treasury_account_identifier', on_delete=django.db.models.deletion.CASCADE, to='accounts.TreasuryAppropriationAccount'),
        ),
    ]
