# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160915_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appropriationaccountbalances',
            name='create_user_id',
        ),
        migrations.RemoveField(
            model_name='appropriationaccountbalances',
            name='update_user_id',
        ),
        migrations.RemoveField(
            model_name='treasuryappropriationaccount',
            name='create_user_id',
        ),
        migrations.RemoveField(
            model_name='treasuryappropriationaccount',
            name='update_user_id',
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
