# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-26 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_budget_columns_reflecting_broker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='adjustments_to_unobligated_balance_brought_forward_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=23),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='borrowing_authority_amount_total_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='budget_authority_appropriated_amount_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=23),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='budget_authority_unobligated_balance_brought_forward_fyb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='contract_authority_amount_total_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='data_source',
            field=models.TextField(choices=[('USA', 'USAspending'), ('DBR', 'DATA Act Broker')], help_text='The source of this entry, either Data Broker (DBR) or USASpending (USA)', null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='deobligations_recoveries_refunds_by_tas_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=23),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='drv_obligations_unpaid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='drv_other_obligated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='gross_outlay_amount_by_tas_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=23),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='obligations_incurred_total_by_tas_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=23),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='other_budgetary_resources_amount_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='spending_authority_from_offsetting_collections_amount_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='status_of_budgetary_resources_total_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=23),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='total_budgetary_resources_amount_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=23),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='unobligated_balance_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=23),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalancesquarterly',
            name='adjustments_to_unobligated_balance_brought_forward_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=23),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalancesquarterly',
            name='borrowing_authority_amount_total_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalancesquarterly',
            name='budget_authority_appropriated_amount_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=23),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalancesquarterly',
            name='budget_authority_unobligated_balance_brought_forward_fyb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalancesquarterly',
            name='contract_authority_amount_total_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalancesquarterly',
            name='data_source',
            field=models.TextField(choices=[('USA', 'USAspending'), ('DBR', 'DATA Act Broker')], help_text='The source of this entry, either Data Broker (DBR) or USASpending (USA)', null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalancesquarterly',
            name='deobligations_recoveries_refunds_by_tas_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=23),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalancesquarterly',
            name='gross_outlay_amount_by_tas_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=23),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalancesquarterly',
            name='obligations_incurred_total_by_tas_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=23),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalancesquarterly',
            name='other_budgetary_resources_amount_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalancesquarterly',
            name='spending_authority_from_offsetting_collections_amount_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=23, null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalancesquarterly',
            name='status_of_budgetary_resources_total_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=23),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalancesquarterly',
            name='total_budgetary_resources_amount_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=23),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalancesquarterly',
            name='unobligated_balance_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=23),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='data_source',
            field=models.TextField(choices=[('USA', 'USAspending'), ('DBR', 'DATA Act Broker')], help_text='The source of this entry, either Data Broker (DBR) or USASpending (USA)', null=True),
        ),
    ]
