# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-22 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_budget_columns_reflecting_broker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='data_source',
            field=models.TextField(choices=[('USA', 'USAspending'), ('DBR', 'DATA Act Broker')], help_text='The source of this entry, either Data Broker (DBR) or USASpending (USA)', null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalancesquarterly',
            name='data_source',
            field=models.TextField(choices=[('USA', 'USAspending'), ('DBR', 'DATA Act Broker')], help_text='The source of this entry, either Data Broker (DBR) or USASpending (USA)', null=True),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='data_source',
            field=models.TextField(choices=[('USA', 'USAspending'), ('DBR', 'DATA Act Broker')], help_text='The source of this entry, either Data Broker (DBR) or USASpending (USA)', null=True),
        ),
    ]
