# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 20:13
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    tases = apps.get_model("accounts", "TreasuryAppropriationAccount")
    ToptierAgency = apps.get_model("references", "ToptierAgency")
    for tas in tases.objects.all():
        tas.awarding_toptier_agency = ToptierAgency.objects.filter(cgac_code=tas.allocation_transfer_agency_id).first()
        tas.funding_toptier_agency = ToptierAgency.objects.filter(cgac_code=tas.agency_id).first()
        tas.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170511_1816'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
