# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-25 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181126_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='TASAwardMatview',
            fields=[
                ('tas_award_id', models.UUIDField(primary_key=True, serialize=False)),
                ('allocation_transfer_agency_id', models.TextField(null=True)),
                ('agency_id', models.TextField()),
                ('beginning_period_of_availability', models.TextField(null=True)),
                ('ending_period_of_availability', models.TextField(null=True)),
                ('availability_type_code', models.TextField(null=True)),
                ('main_account_code', models.TextField()),
                ('sub_account_code', models.TextField(null=True)),
                ('award_id', models.BigIntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'tas_award_matview',
            },
        ),
    ]
