# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160927_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appropriationaccountbalances',
            old_name='adjustments_to_unobligated_cpe',
            new_name='adjustments_to_unobligated_balance_brought_forward_cpe',
        ),
        migrations.RenameField(
            model_name='appropriationaccountbalances',
            old_name='borrowing_authority_amount_cpe',
            new_name='borrowing_authority_amount_total_cpe',
        ),
        migrations.RenameField(
            model_name='appropriationaccountbalances',
            old_name='budget_authority_appropria_cpe',
            new_name='budget_authority_appropriated_amount_cpe',
        ),
        migrations.RenameField(
            model_name='appropriationaccountbalances',
            old_name='budget_authority_available_cpe',
            new_name='budget_authority_available_amount_total_cpe',
        ),
        migrations.RenameField(
            model_name='appropriationaccountbalances',
            old_name='budget_authority_unobligat_fyb',
            new_name='budget_authority_unobligated_balance_brought_forward_fyb',
        ),
        migrations.RenameField(
            model_name='appropriationaccountbalances',
            old_name='contract_authority_amount_cpe',
            new_name='contract_authority_amount_total_cpe',
        ),
        migrations.RenameField(
            model_name='appropriationaccountbalances',
            old_name='deobligations_recoveries_r_cpe',
            new_name='deobligations_recoveries_refunds_by_tas_cpe',
        ),
        migrations.RenameField(
            model_name='appropriationaccountbalances',
            old_name='obligations_incurred_total_cpe',
            new_name='obligations_incurred_total_by_tas_cpe',
        ),
        migrations.RenameField(
            model_name='appropriationaccountbalances',
            old_name='other_budgetary_resources_cpe',
            new_name='other_budgetary_resources_amount_cpe',
        ),
        migrations.RenameField(
            model_name='appropriationaccountbalances',
            old_name='spending_authority_from_of_cpe',
            new_name='spending_authority_from_offsetting_collections_amount_cpe',
        ),
        migrations.RenameField(
            model_name='appropriationaccountbalances',
            old_name='status_of_budgetary_resour_cpe',
            new_name='status_of_budgetary_resources_total_cpe',
        ),
        migrations.RenameField(
            model_name='treasuryappropriationaccount',
            old_name='responsible_agency_id',
            new_name='agency_id',
        ),
        migrations.RenameField(
            model_name='treasuryappropriationaccount',
            old_name='beginning_period_of_availa',
            new_name='beginning_period_of_availability',
        ),
        migrations.RenameField(
            model_name='treasuryappropriationaccount',
            old_name='ending_period_of_availabil',
            new_name='ending_period_of_availability',
        ),
        migrations.AddField(
            model_name='appropriationaccountbalances',
            name='create_user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appropriationaccountbalances',
            name='update_user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='treasuryappropriationaccount',
            name='create_user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='treasuryappropriationaccount',
            name='update_user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='submission_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='submissions.SubmissionProcess'),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='treasury_account_identifier',
            field=models.ForeignKey(db_column='treasury_account_identifier', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.TreasuryAppropriationAccount'),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
