# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-26 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_federalaccount_federal_account_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('amount', models.BigIntegerField(null=True)),
                ('federal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.FederalAccount')),
            ],
            options={
                'db_table': 'budget_authority',
            },
        ),
        migrations.AlterUniqueTogether(
            name='budgetauthority',
            unique_together=set([('federal_account', 'year')]),
        ),
    ]
