# Generated by Django 2.2.24 on 2021-08-10 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_appropriationaccountbalancesquarterly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appropriation_account_balances', to='submissions.SubmissionAttributes'),
        ),
    ]
