# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-05 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tasautocompletematview_tassearchmatview'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'drop materialized view if exists tas_search_matview',
                'drop materialized view if exists tas_search_matview_old',
                'drop materialized view if exists tas_search_matview_temp',
            ],
        ),
    ]
