# Generated by Django 3.2.15 on 2022-09-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_adjustments_to_unobligated_balance_brought_forward_cpe_appropriationaccountbalances_adjustmen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appropriationaccountbalances',
            old_name='adjustments_to_unobligated_balance_cpe',
            new_name='adjustments_to_unobligated_balance_brought_forward_cpe',
        ),
    ]
