# Generated by Django 5.2.14 on 2026-08-13 21:38

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_treasuryappropriationaccount_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryappropriationaccount',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=256, null=True),
        ),
        migrations.AddField(
            model_name='treasuryappropriationaccount',
            name='embedding_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
