# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20161006_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='adjustments_to_unobligated_balance_brought_forward_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=21),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='borrowing_authority_amount_total_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='budget_authority_appropriated_amount_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=21),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='budget_authority_available_amount_total_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=21),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='budget_authority_unobligated_balance_brought_forward_fyb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='contract_authority_amount_total_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='deobligations_recoveries_refunds_by_tas_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=21),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='drv_obligations_unpaid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='drv_other_obligated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='gross_outlay_amount_by_tas_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=21),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='obligations_incurred_total_by_tas_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=21),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='other_budgetary_resources_amount_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='spending_authority_from_offsetting_collections_amount_cpe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=21, null=True),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='status_of_budgetary_resources_total_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=21),
        ),
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='unobligated_balance_cpe',
            field=models.DecimalField(decimal_places=2, max_digits=21),
        ),
    ]
