# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20161103_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treasuryappropriationaccount',
            old_name='gwa_tas_name',
            new_name='account_title',
        ),
        migrations.RenameField(
            model_name='treasuryappropriationaccount',
            old_name='admin_org',
            new_name='budget_bureau_code',
        ),
        migrations.RenameField(
            model_name='treasuryappropriationaccount',
            old_name='admin_org_name',
            new_name='budget_bureau_name',
        ),
        migrations.RenameField(
            model_name='treasuryappropriationaccount',
            old_name='agency_aid',
            new_name='budget_function_code',
        ),
        migrations.RenameField(
            model_name='treasuryappropriationaccount',
            old_name='agency_name',
            new_name='budget_function_title',
        ),
        migrations.RenameField(
            model_name='treasuryappropriationaccount',
            old_name='function_code',
            new_name='budget_subfunction_code',
        ),
        migrations.RenameField(
            model_name='treasuryappropriationaccount',
            old_name='fin_type_2_description',
            new_name='budget_subfunction_title',
        ),
        migrations.RenameField(
            model_name='treasuryappropriationaccount',
            old_name='fr_entity_type_code',
            new_name='fr_entity_code',
        ),
        migrations.RenameField(
            model_name='treasuryappropriationaccount',
            old_name='sub_function_code',
            new_name='reporting_agency_id',
        ),
        migrations.RenameField(
            model_name='treasuryappropriationaccount',
            old_name='function_description',
            new_name='reporting_agency_name',
        ),
        migrations.RemoveField(
            model_name='treasuryappropriationaccount',
            name='fin_type_2',
        ),
        migrations.RemoveField(
            model_name='treasuryappropriationaccount',
            name='gwa_tas',
        ),
        migrations.RemoveField(
            model_name='treasuryappropriationaccount',
            name='sub_function_description',
        ),
    ]
