# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-19 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20161219_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='tas_rendering_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
