# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-24 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20170322_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='appropriationaccountbalances',
            name='final_of_fy',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
