# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-24 15:19
from __future__ import unicode_literals

from django.db import migrations, models

from usaspending_api.accounts.models import AppropriationAccountBalances
from usaspending_api.common.helpers import FY_PG_FUNCTION_DEF


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20170322_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='appropriationaccountbalances',
            name='final_of_fy',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunSQL(FY_PG_FUNCTION_DEF),
        migrations.RunSQL(AppropriationAccountBalances.FINAL_OF_FY_SQL),
    ]
