# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-30 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_appropriationaccountbalances_final_of_fy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appropriationaccountbalances',
            name='tas_rendering_label',
        ),
    ]
