# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-09 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_insert_quarterly_tas_balances'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuryappropriationaccount',
            name='availability_type_code_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
