# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-25 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_treasuryappropriationaccount_availability_type_code_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appropriationaccountbalances',
            name='drv_appropriation_account_expired_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='federalaccount',
            name='account_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='federalaccount',
            name='agency_identifier',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='federalaccount',
            name='main_account_code',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='account_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='agency_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='allocation_transfer_agency_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='availability_type_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='beginning_period_of_availability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='budget_bureau_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='budget_bureau_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='budget_function_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='budget_function_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='budget_subfunction_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='budget_subfunction_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='drv_appropriation_account_expired_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='ending_period_of_availability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='fr_entity_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='fr_entity_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='main_account_code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='reporting_agency_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='reporting_agency_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='sub_account_code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='treasuryappropriationaccount',
            name='tas_rendering_label',
            field=models.TextField(blank=True, null=True),
        ),
    ]
