--------------------------------------------------------
-- Created using matview_sql_generator.py             --
--    The SQL definition is stored in a json file     --
--    Look in matview_generator for the code.         --
--                                                    --
--         !!DO NOT DIRECTLY EDIT THIS FILE!!         --
--------------------------------------------------------
ALTER MATERIALIZED VIEW IF EXISTS universal_transaction_matview RENAME TO universal_transaction_matview_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_transaction_id RENAME TO idx_cb0c2fed$e51_transaction_id_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_action_date RENAME TO idx_cb0c2fed$e51_action_date_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_fiscal_year RENAME TO idx_cb0c2fed$e51_fiscal_year_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_type RENAME TO idx_cb0c2fed$e51_type_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_ordered_type RENAME TO idx_cb0c2fed$e51_ordered_type_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_action_type RENAME TO idx_cb0c2fed$e51_action_type_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_award_id RENAME TO idx_cb0c2fed$e51_award_id_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_award_category RENAME TO idx_cb0c2fed$e51_award_category_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_total_obligation RENAME TO idx_cb0c2fed$e51_total_obligation_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_ordered_total_obligation RENAME TO idx_cb0c2fed$e51_ordered_total_obligation_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_total_obl_bin RENAME TO idx_cb0c2fed$e51_total_obl_bin_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_total_subsidy_cost RENAME TO idx_cb0c2fed$e51_total_subsidy_cost_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_ordered_total_subsidy_cost RENAME TO idx_cb0c2fed$e51_ordered_total_subsidy_cost_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_pop_country_code RENAME TO idx_cb0c2fed$e51_pop_country_code_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_pop_state_code RENAME TO idx_cb0c2fed$e51_pop_state_code_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_pop_county_code RENAME TO idx_cb0c2fed$e51_pop_county_code_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_pop_zip5 RENAME TO idx_cb0c2fed$e51_pop_zip5_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_pop_congressional_code RENAME TO idx_cb0c2fed$e51_pop_congressional_code_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_gin_recipient_name RENAME TO idx_cb0c2fed$e51_gin_recipient_name_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_gin_recipient_unique_id RENAME TO idx_cb0c2fed$e51_gin_recipient_unique_id_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_gin_parent_recipient_unique_id RENAME TO idx_cb0c2fed$e51_gin_parent_recipient_unique_id_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_recipient_id RENAME TO idx_cb0c2fed$e51_recipient_id_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_recipient_unique_id RENAME TO idx_cb0c2fed$e51_recipient_unique_id_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_parent_recipient_unique_id RENAME TO idx_cb0c2fed$e51_parent_recipient_unique_id_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_awarding_agency_id RENAME TO idx_cb0c2fed$e51_awarding_agency_id_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_funding_agency_id RENAME TO idx_cb0c2fed$e51_funding_agency_id_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_awarding_toptier_agency_name RENAME TO idx_cb0c2fed$e51_awarding_toptier_agency_name_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_awarding_subtier_agency_name RENAME TO idx_cb0c2fed$e51_awarding_subtier_agency_name_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_funding_toptier_agency_name RENAME TO idx_cb0c2fed$e51_funding_toptier_agency_name_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_funding_subtier_agency_name RENAME TO idx_cb0c2fed$e51_funding_subtier_agency_name_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_recipient_location_country_code RENAME TO idx_cb0c2fed$e51_recipient_location_country_code_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_recipient_location_state_code RENAME TO idx_cb0c2fed$e51_recipient_location_state_code_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_recipient_location_county_code RENAME TO idx_cb0c2fed$e51_recipient_location_county_code_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_recipient_location_zip5 RENAME TO idx_cb0c2fed$e51_recipient_location_zip5_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_recipient_location_congressional_code RENAME TO idx_cb0c2fed$e51_recipient_location_congressional_code_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_cfda_multi RENAME TO idx_cb0c2fed$e51_cfda_multi_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_pulled_from RENAME TO idx_cb0c2fed$e51_pulled_from_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_type_of_contract_pricing RENAME TO idx_cb0c2fed$e51_type_of_contract_pricing_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_extent_competed RENAME TO idx_cb0c2fed$e51_extent_competed_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_type_set_aside RENAME TO idx_cb0c2fed$e51_type_set_aside_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_product_or_service_code RENAME TO idx_cb0c2fed$e51_product_or_service_code_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_gin_naics_code RENAME TO idx_cb0c2fed$e51_gin_naics_code_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_naics_code RENAME TO idx_cb0c2fed$e51_naics_code_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_business_categories RENAME TO idx_cb0c2fed$e51_business_categories_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_keyword_string RENAME TO idx_cb0c2fed$e51_keyword_string_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_award_id_string RENAME TO idx_cb0c2fed$e51_award_id_string_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_recipient_name_ts_vector RENAME TO idx_cb0c2fed$e51_recipient_name_ts_vector_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_compound_geo_pop_1 RENAME TO idx_cb0c2fed$e51_compound_geo_pop_1_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_compound_geo_pop_2 RENAME TO idx_cb0c2fed$e51_compound_geo_pop_2_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_compound_geo_pop_3 RENAME TO idx_cb0c2fed$e51_compound_geo_pop_3_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_compound_geo_rl_1 RENAME TO idx_cb0c2fed$e51_compound_geo_rl_1_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_compound_geo_rl_2 RENAME TO idx_cb0c2fed$e51_compound_geo_rl_2_old;
ALTER INDEX IF EXISTS idx_cb0c2fed$e51_compound_geo_rl_3 RENAME TO idx_cb0c2fed$e51_compound_geo_rl_3_old;

ALTER MATERIALIZED VIEW universal_transaction_matview_temp RENAME TO universal_transaction_matview;
ALTER INDEX idx_cb0c2fed$e51_transaction_id_temp RENAME TO idx_cb0c2fed$e51_transaction_id;
ALTER INDEX idx_cb0c2fed$e51_action_date_temp RENAME TO idx_cb0c2fed$e51_action_date;
ALTER INDEX idx_cb0c2fed$e51_fiscal_year_temp RENAME TO idx_cb0c2fed$e51_fiscal_year;
ALTER INDEX idx_cb0c2fed$e51_type_temp RENAME TO idx_cb0c2fed$e51_type;
ALTER INDEX idx_cb0c2fed$e51_ordered_type_temp RENAME TO idx_cb0c2fed$e51_ordered_type;
ALTER INDEX idx_cb0c2fed$e51_action_type_temp RENAME TO idx_cb0c2fed$e51_action_type;
ALTER INDEX idx_cb0c2fed$e51_award_id_temp RENAME TO idx_cb0c2fed$e51_award_id;
ALTER INDEX idx_cb0c2fed$e51_award_category_temp RENAME TO idx_cb0c2fed$e51_award_category;
ALTER INDEX idx_cb0c2fed$e51_total_obligation_temp RENAME TO idx_cb0c2fed$e51_total_obligation;
ALTER INDEX idx_cb0c2fed$e51_ordered_total_obligation_temp RENAME TO idx_cb0c2fed$e51_ordered_total_obligation;
ALTER INDEX idx_cb0c2fed$e51_total_obl_bin_temp RENAME TO idx_cb0c2fed$e51_total_obl_bin;
ALTER INDEX idx_cb0c2fed$e51_total_subsidy_cost_temp RENAME TO idx_cb0c2fed$e51_total_subsidy_cost;
ALTER INDEX idx_cb0c2fed$e51_ordered_total_subsidy_cost_temp RENAME TO idx_cb0c2fed$e51_ordered_total_subsidy_cost;
ALTER INDEX idx_cb0c2fed$e51_pop_country_code_temp RENAME TO idx_cb0c2fed$e51_pop_country_code;
ALTER INDEX idx_cb0c2fed$e51_pop_state_code_temp RENAME TO idx_cb0c2fed$e51_pop_state_code;
ALTER INDEX idx_cb0c2fed$e51_pop_county_code_temp RENAME TO idx_cb0c2fed$e51_pop_county_code;
ALTER INDEX idx_cb0c2fed$e51_pop_zip5_temp RENAME TO idx_cb0c2fed$e51_pop_zip5;
ALTER INDEX idx_cb0c2fed$e51_pop_congressional_code_temp RENAME TO idx_cb0c2fed$e51_pop_congressional_code;
ALTER INDEX idx_cb0c2fed$e51_gin_recipient_name_temp RENAME TO idx_cb0c2fed$e51_gin_recipient_name;
ALTER INDEX idx_cb0c2fed$e51_gin_recipient_unique_id_temp RENAME TO idx_cb0c2fed$e51_gin_recipient_unique_id;
ALTER INDEX idx_cb0c2fed$e51_gin_parent_recipient_unique_id_temp RENAME TO idx_cb0c2fed$e51_gin_parent_recipient_unique_id;
ALTER INDEX idx_cb0c2fed$e51_recipient_id_temp RENAME TO idx_cb0c2fed$e51_recipient_id;
ALTER INDEX idx_cb0c2fed$e51_recipient_unique_id_temp RENAME TO idx_cb0c2fed$e51_recipient_unique_id;
ALTER INDEX idx_cb0c2fed$e51_parent_recipient_unique_id_temp RENAME TO idx_cb0c2fed$e51_parent_recipient_unique_id;
ALTER INDEX idx_cb0c2fed$e51_awarding_agency_id_temp RENAME TO idx_cb0c2fed$e51_awarding_agency_id;
ALTER INDEX idx_cb0c2fed$e51_funding_agency_id_temp RENAME TO idx_cb0c2fed$e51_funding_agency_id;
ALTER INDEX idx_cb0c2fed$e51_awarding_toptier_agency_name_temp RENAME TO idx_cb0c2fed$e51_awarding_toptier_agency_name;
ALTER INDEX idx_cb0c2fed$e51_awarding_subtier_agency_name_temp RENAME TO idx_cb0c2fed$e51_awarding_subtier_agency_name;
ALTER INDEX idx_cb0c2fed$e51_funding_toptier_agency_name_temp RENAME TO idx_cb0c2fed$e51_funding_toptier_agency_name;
ALTER INDEX idx_cb0c2fed$e51_funding_subtier_agency_name_temp RENAME TO idx_cb0c2fed$e51_funding_subtier_agency_name;
ALTER INDEX idx_cb0c2fed$e51_recipient_location_country_code_temp RENAME TO idx_cb0c2fed$e51_recipient_location_country_code;
ALTER INDEX idx_cb0c2fed$e51_recipient_location_state_code_temp RENAME TO idx_cb0c2fed$e51_recipient_location_state_code;
ALTER INDEX idx_cb0c2fed$e51_recipient_location_county_code_temp RENAME TO idx_cb0c2fed$e51_recipient_location_county_code;
ALTER INDEX idx_cb0c2fed$e51_recipient_location_zip5_temp RENAME TO idx_cb0c2fed$e51_recipient_location_zip5;
ALTER INDEX idx_cb0c2fed$e51_recipient_location_congressional_code_temp RENAME TO idx_cb0c2fed$e51_recipient_location_congressional_code;
ALTER INDEX idx_cb0c2fed$e51_cfda_multi_temp RENAME TO idx_cb0c2fed$e51_cfda_multi;
ALTER INDEX idx_cb0c2fed$e51_pulled_from_temp RENAME TO idx_cb0c2fed$e51_pulled_from;
ALTER INDEX idx_cb0c2fed$e51_type_of_contract_pricing_temp RENAME TO idx_cb0c2fed$e51_type_of_contract_pricing;
ALTER INDEX idx_cb0c2fed$e51_extent_competed_temp RENAME TO idx_cb0c2fed$e51_extent_competed;
ALTER INDEX idx_cb0c2fed$e51_type_set_aside_temp RENAME TO idx_cb0c2fed$e51_type_set_aside;
ALTER INDEX idx_cb0c2fed$e51_product_or_service_code_temp RENAME TO idx_cb0c2fed$e51_product_or_service_code;
ALTER INDEX idx_cb0c2fed$e51_gin_naics_code_temp RENAME TO idx_cb0c2fed$e51_gin_naics_code;
ALTER INDEX idx_cb0c2fed$e51_naics_code_temp RENAME TO idx_cb0c2fed$e51_naics_code;
ALTER INDEX idx_cb0c2fed$e51_business_categories_temp RENAME TO idx_cb0c2fed$e51_business_categories;
ALTER INDEX idx_cb0c2fed$e51_keyword_string_temp RENAME TO idx_cb0c2fed$e51_keyword_string;
ALTER INDEX idx_cb0c2fed$e51_award_id_string_temp RENAME TO idx_cb0c2fed$e51_award_id_string;
ALTER INDEX idx_cb0c2fed$e51_recipient_name_ts_vector_temp RENAME TO idx_cb0c2fed$e51_recipient_name_ts_vector;
ALTER INDEX idx_cb0c2fed$e51_compound_geo_pop_1_temp RENAME TO idx_cb0c2fed$e51_compound_geo_pop_1;
ALTER INDEX idx_cb0c2fed$e51_compound_geo_pop_2_temp RENAME TO idx_cb0c2fed$e51_compound_geo_pop_2;
ALTER INDEX idx_cb0c2fed$e51_compound_geo_pop_3_temp RENAME TO idx_cb0c2fed$e51_compound_geo_pop_3;
ALTER INDEX idx_cb0c2fed$e51_compound_geo_rl_1_temp RENAME TO idx_cb0c2fed$e51_compound_geo_rl_1;
ALTER INDEX idx_cb0c2fed$e51_compound_geo_rl_2_temp RENAME TO idx_cb0c2fed$e51_compound_geo_rl_2;
ALTER INDEX idx_cb0c2fed$e51_compound_geo_rl_3_temp RENAME TO idx_cb0c2fed$e51_compound_geo_rl_3;
