DROP TABLE IF EXISTS transaction_fpds_new;

CREATE TABLE transaction_fpds_new AS
(

    SELECT
        *
    FROM
        dblink ('broker_server', '(
            SELECT
                detached_award_procurement_id,
                UPPER(detached_award_proc_unique) AS detached_award_proc_unique,
                UPPER(piid) AS piid,
                UPPER(agency_id) AS agency_id,
                UPPER(awarding_sub_tier_agency_c) AS awarding_sub_tier_agency_c,
                UPPER(awarding_sub_tier_agency_n) AS awarding_sub_tier_agency_n,
                UPPER(awarding_agency_code) AS awarding_agency_code,
                UPPER(awarding_agency_name) AS awarding_agency_name,
                UPPER(parent_award_id) AS parent_award_id,
                UPPER(award_modification_amendme) AS award_modification_amendme,
                UPPER(type_of_contract_pricing) AS type_of_contract_pricing,
                UPPER(type_of_contract_pric_desc) AS type_of_contract_pric_desc,
                UPPER(contract_award_type) AS contract_award_type,
                UPPER(contract_award_type_desc) AS contract_award_type_desc,
                UPPER(naics) AS naics,
                UPPER(naics_description) AS naics_description,
                UPPER(awardee_or_recipient_uniqu) AS awardee_or_recipient_uniqu,
                UPPER(ultimate_parent_legal_enti) AS ultimate_parent_legal_enti,
                UPPER(ultimate_parent_unique_ide) AS ultimate_parent_unique_ide,
                UPPER(award_description) AS award_description,
                UPPER(place_of_performance_zip4a) AS place_of_performance_zip4a,
                UPPER(place_of_performance_zip5) AS place_of_performance_zip5,
                UPPER(place_of_perform_zip_last4) AS place_of_perform_zip_last4,
                UPPER(place_of_perform_city_name) AS place_of_perform_city_name,
                UPPER(place_of_perform_county_co) AS place_of_perform_county_co,
                UPPER(place_of_perform_county_na) AS place_of_perform_county_na,
                UPPER(place_of_performance_congr) AS place_of_performance_congr,
                UPPER(awardee_or_recipient_legal) AS awardee_or_recipient_legal,
                UPPER(legal_entity_city_name) AS legal_entity_city_name,
                UPPER(legal_entity_county_code) AS legal_entity_county_code,
                UPPER(legal_entity_county_name) AS legal_entity_county_name,
                UPPER(legal_entity_state_code) AS legal_entity_state_code,
                UPPER(legal_entity_state_descrip) AS legal_entity_state_descrip,
                UPPER(legal_entity_zip4) AS legal_entity_zip4,
                UPPER(legal_entity_zip5) AS legal_entity_zip5,
                UPPER(legal_entity_zip_last4) AS legal_entity_zip_last4,
                UPPER(legal_entity_congressional) AS legal_entity_congressional,
                UPPER(legal_entity_address_line1) AS legal_entity_address_line1,
                UPPER(legal_entity_address_line2) AS legal_entity_address_line2,
                UPPER(legal_entity_address_line3) AS legal_entity_address_line3,
                UPPER(legal_entity_country_code) AS legal_entity_country_code,
                UPPER(legal_entity_country_name) AS legal_entity_country_name,
                UPPER(period_of_performance_star) AS period_of_performance_star,
                UPPER(period_of_performance_curr) AS period_of_performance_curr,
                UPPER(period_of_perf_potential_e) AS period_of_perf_potential_e,
                UPPER(ordering_period_end_date) AS ordering_period_end_date,
                NULLIF(action_date, '''''''') AS action_date,
                UPPER(action_type) AS action_type,
                UPPER(action_type_description) AS action_type_description,
                federal_action_obligation,
                UPPER(current_total_value_award) AS current_total_value_award,
                UPPER(potential_total_value_awar) AS potential_total_value_awar,
                UPPER(total_obligated_amount) AS total_obligated_amount,
                UPPER(base_exercised_options_val) AS base_exercised_options_val,
                UPPER(base_and_all_options_value) AS base_and_all_options_value,
                UPPER(funding_sub_tier_agency_co) AS funding_sub_tier_agency_co,
                UPPER(funding_sub_tier_agency_na) AS funding_sub_tier_agency_na,
                UPPER(funding_office_code) AS funding_office_code,
                UPPER(funding_office_name) AS funding_office_name,
                UPPER(awarding_office_code) AS awarding_office_code,
                UPPER(awarding_office_name) AS awarding_office_name,
                UPPER(referenced_idv_agency_iden) AS referenced_idv_agency_iden,
                UPPER(referenced_idv_agency_desc) AS referenced_idv_agency_desc,
                UPPER(funding_agency_code) AS funding_agency_code,
                UPPER(funding_agency_name) AS funding_agency_name,
                UPPER(place_of_performance_locat) AS place_of_performance_locat,
                UPPER(place_of_performance_state) AS place_of_performance_state,
                UPPER(place_of_perfor_state_desc) AS place_of_perfor_state_desc,
                UPPER(place_of_perform_country_c) AS place_of_perform_country_c,
                UPPER(place_of_perf_country_desc) AS place_of_perf_country_desc,
                UPPER(idv_type) AS idv_type,
                UPPER(idv_type_description) AS idv_type_description,
                UPPER(referenced_idv_type) AS referenced_idv_type,
                UPPER(referenced_idv_type_desc) AS referenced_idv_type_desc,
                UPPER(vendor_doing_as_business_n) AS vendor_doing_as_business_n,
                UPPER(vendor_phone_number) AS vendor_phone_number,
                UPPER(vendor_fax_number) AS vendor_fax_number,
                UPPER(multiple_or_single_award_i) AS multiple_or_single_award_i,
                UPPER(multiple_or_single_aw_desc) AS multiple_or_single_aw_desc,
                UPPER(referenced_mult_or_single) AS referenced_mult_or_single,
                UPPER(referenced_mult_or_si_desc) AS referenced_mult_or_si_desc,
                UPPER(type_of_idc) AS type_of_idc,
                UPPER(type_of_idc_description) AS type_of_idc_description,
                UPPER(a_76_fair_act_action) AS a_76_fair_act_action,
                UPPER(a_76_fair_act_action_desc) AS a_76_fair_act_action_desc,
                UPPER(dod_claimant_program_code) AS dod_claimant_program_code,
                UPPER(dod_claimant_prog_cod_desc) AS dod_claimant_prog_cod_desc,
                UPPER(clinger_cohen_act_planning) AS clinger_cohen_act_planning,
                UPPER(clinger_cohen_act_pla_desc) AS clinger_cohen_act_pla_desc,
                UPPER(commercial_item_acquisitio) AS commercial_item_acquisitio,
                UPPER(commercial_item_acqui_desc) AS commercial_item_acqui_desc,
                UPPER(commercial_item_test_progr) AS commercial_item_test_progr,
                UPPER(commercial_item_test_desc) AS commercial_item_test_desc,
                UPPER(consolidated_contract) AS consolidated_contract,
                UPPER(consolidated_contract_desc) AS consolidated_contract_desc,
                UPPER(contingency_humanitarian_o) AS contingency_humanitarian_o,
                UPPER(contingency_humanitar_desc) AS contingency_humanitar_desc,
                UPPER(contract_bundling) AS contract_bundling,
                UPPER(contract_bundling_descrip) AS contract_bundling_descrip,
                UPPER(contract_financing) AS contract_financing,
                UPPER(contract_financing_descrip) AS contract_financing_descrip,
                UPPER(contracting_officers_deter) AS contracting_officers_deter,
                UPPER(contracting_officers_desc) AS contracting_officers_desc,
                UPPER(cost_accounting_standards) AS cost_accounting_standards,
                UPPER(cost_accounting_stand_desc) AS cost_accounting_stand_desc,
                UPPER(cost_or_pricing_data) AS cost_or_pricing_data,
                UPPER(cost_or_pricing_data_desc) AS cost_or_pricing_data_desc,
                UPPER(country_of_product_or_serv) AS country_of_product_or_serv,
                UPPER(country_of_product_or_desc) AS country_of_product_or_desc,
                UPPER(construction_wage_rate_req) AS construction_wage_rate_req,
                UPPER(construction_wage_rat_desc) AS construction_wage_rat_desc,
                UPPER(evaluated_preference) AS evaluated_preference,
                UPPER(evaluated_preference_desc) AS evaluated_preference_desc,
                UPPER(extent_competed) AS extent_competed,
                UPPER(extent_compete_description) AS extent_compete_description,
                UPPER(fed_biz_opps) AS fed_biz_opps,
                UPPER(fed_biz_opps_description) AS fed_biz_opps_description,
                UPPER(foreign_funding) AS foreign_funding,
                UPPER(foreign_funding_desc) AS foreign_funding_desc,
                UPPER(government_furnished_prope) AS government_furnished_prope,
                UPPER(government_furnished_desc) AS government_furnished_desc,
                UPPER(information_technology_com) AS information_technology_com,
                UPPER(information_technolog_desc) AS information_technolog_desc,
                UPPER(interagency_contracting_au) AS interagency_contracting_au,
                UPPER(interagency_contract_desc) AS interagency_contract_desc,
                UPPER(local_area_set_aside) AS local_area_set_aside,
                UPPER(local_area_set_aside_desc) AS local_area_set_aside_desc,
                UPPER(major_program) AS major_program,
                UPPER(purchase_card_as_payment_m) AS purchase_card_as_payment_m,
                UPPER(purchase_card_as_paym_desc) AS purchase_card_as_paym_desc,
                UPPER(multi_year_contract) AS multi_year_contract,
                UPPER(multi_year_contract_desc) AS multi_year_contract_desc,
                UPPER(national_interest_action) AS national_interest_action,
                UPPER(national_interest_desc) AS national_interest_desc,
                UPPER(number_of_actions) AS number_of_actions,
                UPPER(number_of_offers_received) AS number_of_offers_received,
                UPPER(other_statutory_authority) AS other_statutory_authority,
                UPPER(performance_based_service) AS performance_based_service,
                UPPER(performance_based_se_desc) AS performance_based_se_desc,
                UPPER(place_of_manufacture) AS place_of_manufacture,
                UPPER(place_of_manufacture_desc) AS place_of_manufacture_desc,
                UPPER(price_evaluation_adjustmen) AS price_evaluation_adjustmen,
                UPPER(product_or_service_code) AS product_or_service_code,
                UPPER(product_or_service_co_desc) AS product_or_service_co_desc,
                UPPER(program_acronym) AS program_acronym,
                UPPER(other_than_full_and_open_c) AS other_than_full_and_open_c,
                UPPER(other_than_full_and_o_desc) AS other_than_full_and_o_desc,
                UPPER(recovered_materials_sustai) AS recovered_materials_sustai,
                UPPER(recovered_materials_s_desc) AS recovered_materials_s_desc,
                UPPER(research) AS research,
                UPPER(research_description) AS research_description,
                UPPER(sea_transportation) AS sea_transportation,
                UPPER(sea_transportation_desc) AS sea_transportation_desc,
                UPPER(labor_standards) AS labor_standards,
                UPPER(labor_standards_descrip) AS labor_standards_descrip,
                COALESCE(NULLIF(small_business_competitive, ''''), ''0'')::BOOLEAN AS small_business_competitive,
                UPPER(solicitation_identifier) AS solicitation_identifier,
                UPPER(solicitation_procedures) AS solicitation_procedures,
                UPPER(solicitation_procedur_desc) AS solicitation_procedur_desc,
                UPPER(fair_opportunity_limited_s) AS fair_opportunity_limited_s,
                UPPER(fair_opportunity_limi_desc) AS fair_opportunity_limi_desc,
                UPPER(subcontracting_plan) AS subcontracting_plan,
                UPPER(subcontracting_plan_desc) AS subcontracting_plan_desc,
                UPPER(program_system_or_equipmen) AS program_system_or_equipmen,
                UPPER(program_system_or_equ_desc) AS program_system_or_equ_desc,
                UPPER(type_set_aside) AS type_set_aside,
                UPPER(type_set_aside_description) AS type_set_aside_description,
                UPPER(epa_designated_product) AS epa_designated_product,
                UPPER(epa_designated_produc_desc) AS epa_designated_produc_desc,
                UPPER(materials_supplies_article) AS materials_supplies_article,
                UPPER(materials_supplies_descrip) AS materials_supplies_descrip,
                UPPER(transaction_number) AS transaction_number,
                UPPER(sam_exception) AS sam_exception,
                UPPER(sam_exception_description) AS sam_exception_description,
                COALESCE(NULLIF(city_local_government, ''''), ''0'')::BOOLEAN AS city_local_government,
                COALESCE(NULLIF(county_local_government, ''''), ''0'')::BOOLEAN AS county_local_government,
                COALESCE(NULLIF(inter_municipal_local_gove, ''''), ''0'')::BOOLEAN AS inter_municipal_local_gove,
                COALESCE(NULLIF(local_government_owned, ''''), ''0'')::BOOLEAN AS local_government_owned,
                COALESCE(NULLIF(municipality_local_governm, ''''), ''0'')::BOOLEAN AS municipality_local_governm,
                COALESCE(NULLIF(school_district_local_gove, ''''), ''0'')::BOOLEAN AS school_district_local_gove,
                COALESCE(NULLIF(township_local_government, ''''), ''0'')::BOOLEAN AS township_local_government,
                COALESCE(NULLIF(us_state_government, ''''), ''0'')::BOOLEAN AS us_state_government,
                COALESCE(NULLIF(us_federal_government, ''''), ''0'')::BOOLEAN AS us_federal_government,
                COALESCE(NULLIF(federal_agency, ''''), ''0'')::BOOLEAN AS federal_agency,
                COALESCE(NULLIF(federally_funded_research, ''''), ''0'')::BOOLEAN AS federally_funded_research,
                COALESCE(NULLIF(us_tribal_government, ''''), ''0'')::BOOLEAN AS us_tribal_government,
                COALESCE(NULLIF(foreign_government, ''''), ''0'')::BOOLEAN AS foreign_government,
                COALESCE(NULLIF(community_developed_corpor, ''''), ''0'')::BOOLEAN AS community_developed_corpor,
                COALESCE(NULLIF(labor_surplus_area_firm, ''''), ''0'')::BOOLEAN AS labor_surplus_area_firm,
                COALESCE(NULLIF(corporate_entity_not_tax_e, ''''), ''0'')::BOOLEAN AS corporate_entity_not_tax_e,
                COALESCE(NULLIF(corporate_entity_tax_exemp, ''''), ''0'')::BOOLEAN AS corporate_entity_tax_exemp,
                COALESCE(NULLIF(partnership_or_limited_lia, ''''), ''0'')::BOOLEAN AS partnership_or_limited_lia,
                COALESCE(NULLIF(sole_proprietorship, ''''), ''0'')::BOOLEAN AS sole_proprietorship,
                COALESCE(NULLIF(small_agricultural_coopera, ''''), ''0'')::BOOLEAN AS small_agricultural_coopera,
                COALESCE(NULLIF(international_organization, ''''), ''0'')::BOOLEAN AS international_organization,
                COALESCE(NULLIF(us_government_entity, ''''), ''0'')::BOOLEAN AS us_government_entity,
                COALESCE(NULLIF(emerging_small_business, ''''), ''0'')::BOOLEAN AS emerging_small_business,
                COALESCE(NULLIF(c8a_program_participant, ''''), ''0'')::BOOLEAN AS c8a_program_participant,
                COALESCE(NULLIF(sba_certified_8_a_joint_ve, ''''), ''0'')::BOOLEAN AS sba_certified_8_a_joint_ve,
                COALESCE(NULLIF(dot_certified_disadvantage, ''''), ''0'')::BOOLEAN AS dot_certified_disadvantage,
                COALESCE(NULLIF(self_certified_small_disad, ''''), ''0'')::BOOLEAN AS self_certified_small_disad,
                COALESCE(NULLIF(historically_underutilized, ''''), ''0'')::BOOLEAN AS historically_underutilized,
                COALESCE(NULLIF(small_disadvantaged_busine, ''''), ''0'')::BOOLEAN AS small_disadvantaged_busine,
                COALESCE(NULLIF(the_ability_one_program, ''''), ''0'')::BOOLEAN AS the_ability_one_program,
                COALESCE(NULLIF(historically_black_college, ''''), ''0'')::BOOLEAN AS historically_black_college,
                COALESCE(NULLIF(c1862_land_grant_college, ''''), ''0'')::BOOLEAN AS c1862_land_grant_college,
                COALESCE(NULLIF(c1890_land_grant_college, ''''), ''0'')::BOOLEAN AS c1890_land_grant_college,
                COALESCE(NULLIF(c1994_land_grant_college, ''''), ''0'')::BOOLEAN AS c1994_land_grant_college,
                COALESCE(NULLIF(minority_institution, ''''), ''0'')::BOOLEAN AS minority_institution,
                COALESCE(NULLIF(private_university_or_coll, ''''), ''0'')::BOOLEAN AS private_university_or_coll,
                COALESCE(NULLIF(school_of_forestry, ''''), ''0'')::BOOLEAN AS school_of_forestry,
                COALESCE(NULLIF(state_controlled_instituti, ''''), ''0'')::BOOLEAN AS state_controlled_instituti,
                COALESCE(NULLIF(tribal_college, ''''), ''0'')::BOOLEAN AS tribal_college,
                COALESCE(NULLIF(veterinary_college, ''''), ''0'')::BOOLEAN AS veterinary_college,
                COALESCE(NULLIF(educational_institution, ''''), ''0'')::BOOLEAN AS educational_institution,
                COALESCE(NULLIF(alaskan_native_servicing_i, ''''), ''0'')::BOOLEAN AS alaskan_native_servicing_i,
                COALESCE(NULLIF(community_development_corp, ''''), ''0'')::BOOLEAN AS community_development_corp,
                COALESCE(NULLIF(native_hawaiian_servicing, ''''), ''0'')::BOOLEAN AS native_hawaiian_servicing,
                COALESCE(NULLIF(domestic_shelter, ''''), ''0'')::BOOLEAN AS domestic_shelter,
                COALESCE(NULLIF(manufacturer_of_goods, ''''), ''0'')::BOOLEAN AS manufacturer_of_goods,
                COALESCE(NULLIF(hospital_flag, ''''), ''0'')::BOOLEAN AS hospital_flag,
                COALESCE(NULLIF(veterinary_hospital, ''''), ''0'')::BOOLEAN AS veterinary_hospital,
                COALESCE(NULLIF(hispanic_servicing_institu, ''''), ''0'')::BOOLEAN AS hispanic_servicing_institu,
                COALESCE(NULLIF(foundation, ''''), ''0'')::BOOLEAN AS foundation,
                COALESCE(NULLIF(woman_owned_business, ''''), ''0'')::BOOLEAN AS woman_owned_business,
                COALESCE(NULLIF(minority_owned_business, ''''), ''0'')::BOOLEAN AS minority_owned_business,
                COALESCE(NULLIF(women_owned_small_business, ''''), ''0'')::BOOLEAN AS women_owned_small_business,
                COALESCE(NULLIF(economically_disadvantaged, ''''), ''0'')::BOOLEAN AS economically_disadvantaged,
                COALESCE(NULLIF(joint_venture_women_owned, ''''), ''0'')::BOOLEAN AS joint_venture_women_owned,
                COALESCE(NULLIF(joint_venture_economically, ''''), ''0'')::BOOLEAN AS joint_venture_economically,
                COALESCE(NULLIF(veteran_owned_business, ''''), ''0'')::BOOLEAN AS veteran_owned_business,
                COALESCE(NULLIF(service_disabled_veteran_o, ''''), ''0'')::BOOLEAN AS service_disabled_veteran_o,
                COALESCE(NULLIF(contracts, ''''), ''0'')::BOOLEAN AS contracts,
                COALESCE(NULLIF(grants, ''''), ''0'')::BOOLEAN AS grants,
                COALESCE(NULLIF(receives_contracts_and_gra, ''''), ''0'')::BOOLEAN AS receives_contracts_and_gra,
                COALESCE(NULLIF(airport_authority, ''''), ''0'')::BOOLEAN AS airport_authority,
                COALESCE(NULLIF(council_of_governments, ''''), ''0'')::BOOLEAN AS council_of_governments,
                COALESCE(NULLIF(housing_authorities_public, ''''), ''0'')::BOOLEAN AS housing_authorities_public,
                COALESCE(NULLIF(interstate_entity, ''''), ''0'')::BOOLEAN AS interstate_entity,
                COALESCE(NULLIF(planning_commission, ''''), ''0'')::BOOLEAN AS planning_commission,
                COALESCE(NULLIF(port_authority, ''''), ''0'')::BOOLEAN AS port_authority,
                COALESCE(NULLIF(transit_authority, ''''), ''0'')::BOOLEAN AS transit_authority,
                COALESCE(NULLIF(subchapter_s_corporation, ''''), ''0'')::BOOLEAN AS subchapter_s_corporation,
                COALESCE(NULLIF(limited_liability_corporat, ''''), ''0'')::BOOLEAN AS limited_liability_corporat,
                COALESCE(NULLIF(foreign_owned_and_located, ''''), ''0'')::BOOLEAN AS foreign_owned_and_located,
                COALESCE(NULLIF(american_indian_owned_busi, ''''), ''0'')::BOOLEAN AS american_indian_owned_busi,
                COALESCE(NULLIF(alaskan_native_owned_corpo, ''''), ''0'')::BOOLEAN AS alaskan_native_owned_corpo,
                COALESCE(NULLIF(indian_tribe_federally_rec, ''''), ''0'')::BOOLEAN AS indian_tribe_federally_rec,
                COALESCE(NULLIF(native_hawaiian_owned_busi, ''''), ''0'')::BOOLEAN AS native_hawaiian_owned_busi,
                COALESCE(NULLIF(tribally_owned_business, ''''), ''0'')::BOOLEAN AS tribally_owned_business,
                COALESCE(NULLIF(asian_pacific_american_own, ''''), ''0'')::BOOLEAN AS asian_pacific_american_own,
                COALESCE(NULLIF(black_american_owned_busin, ''''), ''0'')::BOOLEAN AS black_american_owned_busin,
                COALESCE(NULLIF(hispanic_american_owned_bu, ''''), ''0'')::BOOLEAN AS hispanic_american_owned_bu,
                COALESCE(NULLIF(native_american_owned_busi, ''''), ''0'')::BOOLEAN AS native_american_owned_busi,
                COALESCE(NULLIF(subcontinent_asian_asian_i, ''''), ''0'')::BOOLEAN AS subcontinent_asian_asian_i,
                COALESCE(NULLIF(other_minority_owned_busin, ''''), ''0'')::BOOLEAN AS other_minority_owned_busin,
                COALESCE(NULLIF(for_profit_organization, ''''), ''0'')::BOOLEAN AS for_profit_organization,
                COALESCE(NULLIF(nonprofit_organization, ''''), ''0'')::BOOLEAN AS nonprofit_organization,
                COALESCE(NULLIF(other_not_for_profit_organ, ''''), ''0'')::BOOLEAN AS other_not_for_profit_organ,
                COALESCE(NULLIF(us_local_government, ''''), ''0'')::BOOLEAN AS us_local_government,
                UPPER(referenced_idv_modificatio) AS referenced_idv_modificatio,
                UPPER(undefinitized_action) AS undefinitized_action,
                UPPER(undefinitized_action_desc) AS undefinitized_action_desc,
                UPPER(domestic_or_foreign_entity) AS domestic_or_foreign_entity,
                UPPER(domestic_or_foreign_e_desc) AS domestic_or_foreign_e_desc,
                UPPER(annual_revenue) AS annual_revenue,
                UPPER(division_name) AS division_name,
                UPPER(division_number_or_office) AS division_number_or_office,
                UPPER(number_of_employees) AS number_of_employees,
                UPPER(vendor_alternate_name) AS vendor_alternate_name,
                UPPER(vendor_alternate_site_code) AS vendor_alternate_site_code,
                UPPER(vendor_enabled) AS vendor_enabled,
                UPPER(vendor_legal_org_name) AS vendor_legal_org_name,
                UPPER(vendor_location_disabled_f) AS vendor_location_disabled_f,
                UPPER(vendor_site_code) AS vendor_site_code,
                UPPER(pulled_from) AS pulled_from,
                UPPER(last_modified) AS last_modified,
                UPPER(initial_report_date) AS initial_report_date,
                UPPER(referenced_idv_agency_name) AS referenced_idv_agency_name,
                UPPER(award_or_idv_flag) AS award_or_idv_flag,
                UPPER(place_of_perform_country_n) AS place_of_perform_country_n,
                UPPER(place_of_perform_state_nam) AS place_of_perform_state_nam,
                UPPER(cage_code) AS cage_code,
                UPPER(inherently_government_func) AS inherently_government_func,
                UPPER(inherently_government_desc) AS inherently_government_desc,
                UPPER(organizational_type) AS organizational_type,
                created_at,
                updated_at
            FROM detached_award_procurement
        )') AS transaction_contracts
    (
        detached_award_procurement_id int,
        detached_award_proc_unique text,
        piid text,
        agency_id text,
        awarding_sub_tier_agency_c text,
        awarding_sub_tier_agency_n text,
        awarding_agency_code text,
        awarding_agency_name text,
        parent_award_id text,
        award_modification_amendme text,
        type_of_contract_pricing text,
        type_of_contract_pric_desc text,
        contract_award_type text,
        contract_award_type_desc text,
        naics text,
        naics_description text,
        awardee_or_recipient_uniqu text,
        ultimate_parent_legal_enti text,
        ultimate_parent_unique_ide text,
        award_description text,
        place_of_performance_zip4a text,
        place_of_performance_zip5 text,
        place_of_perform_zip_last4 text,
        place_of_perform_city_name text,
        place_of_perform_county_co text,
        place_of_perform_county_na text,
        place_of_performance_congr text,
        awardee_or_recipient_legal text,
        legal_entity_city_name text,
        legal_entity_county_code text,
        legal_entity_county_name text,
        legal_entity_state_code text,
        legal_entity_state_descrip text,
        legal_entity_zip4 text,
        legal_entity_zip5 text,
        legal_entity_zip_last4 text,
        legal_entity_congressional text,
        legal_entity_address_line1 text,
        legal_entity_address_line2 text,
        legal_entity_address_line3 text,
        legal_entity_country_code text,
        legal_entity_country_name text,
        period_of_performance_star text,
        period_of_performance_curr text,
        period_of_perf_potential_e text,
        ordering_period_end_date text,
        action_date text,
        action_type text,
        action_type_description text,
        federal_action_obligation numeric,
        current_total_value_award text,
        potential_total_value_awar text,
        total_obligated_amount text,
        base_exercised_options_val text,
        base_and_all_options_value text,
        funding_sub_tier_agency_co text,
        funding_sub_tier_agency_na text,
        funding_office_code text,
        funding_office_name text,
        awarding_office_code text,
        awarding_office_name text,
        referenced_idv_agency_iden text,
        referenced_idv_agency_desc text,
        funding_agency_code text,
        funding_agency_name text,
        place_of_performance_locat text,
        place_of_performance_state text,
        place_of_perfor_state_desc text,
        place_of_perform_country_c text,
        place_of_perf_country_desc text,
        idv_type text,
        idv_type_description text,
        referenced_idv_type text,
        referenced_idv_type_desc text,
        vendor_doing_as_business_n text,
        vendor_phone_number text,
        vendor_fax_number text,
        multiple_or_single_award_i text,
        multiple_or_single_aw_desc text,
        referenced_mult_or_single text,
        referenced_mult_or_si_desc text,
        type_of_idc text,
        type_of_idc_description text,
        a_76_fair_act_action text,
        a_76_fair_act_action_desc text,
        dod_claimant_program_code text,
        dod_claimant_prog_cod_desc text,
        clinger_cohen_act_planning text,
        clinger_cohen_act_pla_desc text,
        commercial_item_acquisitio text,
        commercial_item_acqui_desc text,
        commercial_item_test_progr text,
        commercial_item_test_desc text,
        consolidated_contract text,
        consolidated_contract_desc text,
        contingency_humanitarian_o text,
        contingency_humanitar_desc text,
        contract_bundling text,
        contract_bundling_descrip text,
        contract_financing text,
        contract_financing_descrip text,
        contracting_officers_deter text,
        contracting_officers_desc text,
        cost_accounting_standards text,
        cost_accounting_stand_desc text,
        cost_or_pricing_data text,
        cost_or_pricing_data_desc text,
        country_of_product_or_serv text,
        country_of_product_or_desc text,
        construction_wage_rate_req text,
        construction_wage_rat_desc text,
        evaluated_preference text,
        evaluated_preference_desc text,
        extent_competed text,
        extent_compete_description text,
        fed_biz_opps text,
        fed_biz_opps_description text,
        foreign_funding text,
        foreign_funding_desc text,
        government_furnished_prope text,
        government_furnished_desc text,
        information_technology_com text,
        information_technolog_desc text,
        interagency_contracting_au text,
        interagency_contract_desc text,
        local_area_set_aside text,
        local_area_set_aside_desc text,
        major_program text,
        purchase_card_as_payment_m text,
        purchase_card_as_paym_desc text,
        multi_year_contract text,
        multi_year_contract_desc text,
        national_interest_action text,
        national_interest_desc text,
        number_of_actions text,
        number_of_offers_received text,
        other_statutory_authority text,
        performance_based_service text,
        performance_based_se_desc text,
        place_of_manufacture text,
        place_of_manufacture_desc text,
        price_evaluation_adjustmen text,
        product_or_service_code text,
        product_or_service_co_desc text,
        program_acronym text,
        other_than_full_and_open_c text,
        other_than_full_and_o_desc text,
        recovered_materials_sustai text,
        recovered_materials_s_desc text,
        research text,
        research_description text,
        sea_transportation text,
        sea_transportation_desc text,
        labor_standards text,
        labor_standards_descrip text,
        small_business_competitive boolean,
        solicitation_identifier text,
        solicitation_procedures text,
        solicitation_procedur_desc text,
        fair_opportunity_limited_s text,
        fair_opportunity_limi_desc text,
        subcontracting_plan text,
        subcontracting_plan_desc text,
        program_system_or_equipmen text,
        program_system_or_equ_desc text,
        type_set_aside text,
        type_set_aside_description text,
        epa_designated_product text,
        epa_designated_produc_desc text,
        materials_supplies_article text,
        materials_supplies_descrip text,
        transaction_number text,
        sam_exception text,
        sam_exception_description text,
        city_local_government boolean,
        county_local_government boolean,
        inter_municipal_local_gove boolean,
        local_government_owned boolean,
        municipality_local_governm boolean,
        school_district_local_gove boolean,
        township_local_government boolean,
        us_state_government boolean,
        us_federal_government boolean,
        federal_agency boolean,
        federally_funded_research boolean,
        us_tribal_government boolean,
        foreign_government boolean,
        community_developed_corpor boolean,
        labor_surplus_area_firm boolean,
        corporate_entity_not_tax_e boolean,
        corporate_entity_tax_exemp boolean,
        partnership_or_limited_lia boolean,
        sole_proprietorship boolean,
        small_agricultural_coopera boolean,
        international_organization boolean,
        us_government_entity boolean,
        emerging_small_business boolean,
        c8a_program_participant boolean,
        sba_certified_8_a_joint_ve boolean,
        dot_certified_disadvantage boolean,
        self_certified_small_disad boolean,
        historically_underutilized boolean,
        small_disadvantaged_busine boolean,
        the_ability_one_program boolean,
        historically_black_college boolean,
        c1862_land_grant_college boolean,
        c1890_land_grant_college boolean,
        c1994_land_grant_college boolean,
        minority_institution boolean,
        private_university_or_coll boolean,
        school_of_forestry boolean,
        state_controlled_instituti boolean,
        tribal_college boolean,
        veterinary_college boolean,
        educational_institution boolean,
        alaskan_native_servicing_i boolean,
        community_development_corp boolean,
        native_hawaiian_servicing boolean,
        domestic_shelter boolean,
        manufacturer_of_goods boolean,
        hospital_flag boolean,
        veterinary_hospital boolean,
        hispanic_servicing_institu boolean,
        foundation boolean,
        woman_owned_business boolean,
        minority_owned_business boolean,
        women_owned_small_business boolean,
        economically_disadvantaged boolean,
        joint_venture_women_owned boolean,
        joint_venture_economically boolean,
        veteran_owned_business boolean,
        service_disabled_veteran_o boolean,
        contracts boolean,
        grants boolean,
        receives_contracts_and_gra boolean,
        airport_authority boolean,
        council_of_governments boolean,
        housing_authorities_public boolean,
        interstate_entity boolean,
        planning_commission boolean,
        port_authority boolean,
        transit_authority boolean,
        subchapter_s_corporation boolean,
        limited_liability_corporat boolean,
        foreign_owned_and_located boolean,
        american_indian_owned_busi boolean,
        alaskan_native_owned_corpo boolean,
        indian_tribe_federally_rec boolean,
        native_hawaiian_owned_busi boolean,
        tribally_owned_business boolean,
        asian_pacific_american_own boolean,
        black_american_owned_busin boolean,
        hispanic_american_owned_bu boolean,
        native_american_owned_busi boolean,
        subcontinent_asian_asian_i boolean,
        other_minority_owned_busin boolean,
        for_profit_organization boolean,
        nonprofit_organization boolean,
        other_not_for_profit_organ boolean,
        us_local_government boolean,
        referenced_idv_modificatio text,
        undefinitized_action text,
        undefinitized_action_desc text,
        domestic_or_foreign_entity text,
        domestic_or_foreign_e_desc text,
        annual_revenue text,
        division_name text,
        division_number_or_office text,
        number_of_employees text,
        vendor_alternate_name text,
        vendor_alternate_site_code text,
        vendor_enabled text,
        vendor_legal_org_name text,
        vendor_location_disabled_f text,
        vendor_site_code text,
        pulled_from text,
        last_modified text,
        initial_report_date text,
        referenced_idv_agency_name text,
        award_or_idv_flag text,
        place_of_perform_country_n text,
        place_of_perform_state_nam text,
        cage_code text,
        inherently_government_func text,
        inherently_government_desc text,
        organizational_type text,
        created_at timestamp without time zone,
        updated_at timestamp without time zone
    )
);