DROP TABLE IF EXISTS transaction_fpds_new;

CREATE TABLE transaction_fpds_new AS
(

    SELECT
        NULL::bigint as transaction_id,
        *
    FROM
        dblink ('broker_server', '(
            SELECT
                detached_award_procurement_id,
                UPPER(detached_award_proc_unique) AS detached_award_proc_unique,
                UPPER(piid) AS piid,
                UPPER(agency_id) AS agency_id,
                UPPER(awarding_sub_tier_agency_c) AS awarding_sub_tier_agency_c,
                UPPER(awarding_sub_tier_agency_n) AS awarding_sub_tier_agency_n,
                UPPER(awarding_agency_code) AS awarding_agency_code,
                UPPER(awarding_agency_name) AS awarding_agency_name,
                UPPER(parent_award_id) AS parent_award_id,
                UPPER(award_modification_amendme) AS award_modification_amendme,
                UPPER(type_of_contract_pricing) AS type_of_contract_pricing,
                UPPER(type_of_contract_pric_desc) AS type_of_contract_pric_desc,
                UPPER(contract_award_type) AS contract_award_type,
                UPPER(contract_award_type_desc) AS contract_award_type_desc,
                UPPER(naics) AS naics,
                UPPER(naics_description) AS naics_description,
                UPPER(awardee_or_recipient_uniqu) AS awardee_or_recipient_uniqu,
                UPPER(ultimate_parent_legal_enti) AS ultimate_parent_legal_enti,
                UPPER(ultimate_parent_unique_ide) AS ultimate_parent_unique_ide,
                UPPER(award_description) AS award_description,
                UPPER(place_of_performance_zip4a) AS place_of_performance_zip4a,
                UPPER(place_of_performance_zip5) AS place_of_performance_zip5,
                UPPER(place_of_perform_zip_last4) AS place_of_perform_zip_last4,
                UPPER(place_of_perform_city_name) AS place_of_perform_city_name,
                UPPER(place_of_perform_county_co) AS place_of_perform_county_co,
                UPPER(place_of_perform_county_na) AS place_of_perform_county_na,
                UPPER(place_of_performance_congr) AS place_of_performance_congr,
                UPPER(awardee_or_recipient_legal) AS awardee_or_recipient_legal,
                UPPER(legal_entity_city_name) AS legal_entity_city_name,
                UPPER(legal_entity_county_code) AS legal_entity_county_code,
                UPPER(legal_entity_county_name) AS legal_entity_county_name,
                UPPER(legal_entity_state_code) AS legal_entity_state_code,
                UPPER(legal_entity_state_descrip) AS legal_entity_state_descrip,
                UPPER(legal_entity_zip4) AS legal_entity_zip4,
                UPPER(legal_entity_zip5) AS legal_entity_zip5,
                UPPER(legal_entity_zip_last4) AS legal_entity_zip_last4,
                UPPER(legal_entity_congressional) AS legal_entity_congressional,
                UPPER(legal_entity_address_line1) AS legal_entity_address_line1,
                UPPER(legal_entity_address_line2) AS legal_entity_address_line2,
                UPPER(legal_entity_address_line3) AS legal_entity_address_line3,
                UPPER(legal_entity_country_code) AS legal_entity_country_code,
                UPPER(legal_entity_country_name) AS legal_entity_country_name,
                UPPER(period_of_performance_star) AS period_of_performance_star,
                UPPER(period_of_performance_curr) AS period_of_performance_curr,
                UPPER(period_of_perf_potential_e) AS period_of_perf_potential_e,
                UPPER(ordering_period_end_date) AS ordering_period_end_date,
                NULLIF(action_date, '''') AS action_date,
                UPPER(action_type) AS action_type,
                UPPER(action_type_description) AS action_type_description,
                federal_action_obligation,
                UPPER(current_total_value_award) AS current_total_value_award,
                UPPER(potential_total_value_awar) AS potential_total_value_awar,
                UPPER(total_obligated_amount) AS total_obligated_amount,
                UPPER(base_exercised_options_val) AS base_exercised_options_val,
                UPPER(base_and_all_options_value) AS base_and_all_options_value,
                UPPER(funding_sub_tier_agency_co) AS funding_sub_tier_agency_co,
                UPPER(funding_sub_tier_agency_na) AS funding_sub_tier_agency_na,
                UPPER(funding_office_code) AS funding_office_code,
                UPPER(funding_office_name) AS funding_office_name,
                UPPER(awarding_office_code) AS awarding_office_code,
                UPPER(awarding_office_name) AS awarding_office_name,
                UPPER(referenced_idv_agency_iden) AS referenced_idv_agency_iden,
                UPPER(referenced_idv_agency_desc) AS referenced_idv_agency_desc,
                UPPER(funding_agency_code) AS funding_agency_code,
                UPPER(funding_agency_name) AS funding_agency_name,
                UPPER(place_of_performance_locat) AS place_of_performance_locat,
                UPPER(place_of_performance_state) AS place_of_performance_state,
                UPPER(place_of_perfor_state_desc) AS place_of_perfor_state_desc,
                UPPER(place_of_perform_country_c) AS place_of_perform_country_c,
                UPPER(place_of_perf_country_desc) AS place_of_perf_country_desc,
                UPPER(idv_type) AS idv_type,
                UPPER(idv_type_description) AS idv_type_description,
                UPPER(referenced_idv_type) AS referenced_idv_type,
                UPPER(referenced_idv_type_desc) AS referenced_idv_type_desc,
                UPPER(vendor_doing_as_business_n) AS vendor_doing_as_business_n,
                UPPER(vendor_phone_number) AS vendor_phone_number,
                UPPER(vendor_fax_number) AS vendor_fax_number,
                UPPER(multiple_or_single_award_i) AS multiple_or_single_award_i,
                UPPER(multiple_or_single_aw_desc) AS multiple_or_single_aw_desc,
                UPPER(referenced_mult_or_single) AS referenced_mult_or_single,
                UPPER(referenced_mult_or_si_desc) AS referenced_mult_or_si_desc,
                UPPER(type_of_idc) AS type_of_idc,
                UPPER(type_of_idc_description) AS type_of_idc_description,
                UPPER(a_76_fair_act_action) AS a_76_fair_act_action,
                UPPER(a_76_fair_act_action_desc) AS a_76_fair_act_action_desc,
                UPPER(dod_claimant_program_code) AS dod_claimant_program_code,
                UPPER(dod_claimant_prog_cod_desc) AS dod_claimant_prog_cod_desc,
                UPPER(clinger_cohen_act_planning) AS clinger_cohen_act_planning,
                UPPER(clinger_cohen_act_pla_desc) AS clinger_cohen_act_pla_desc,
                UPPER(commercial_item_acquisitio) AS commercial_item_acquisitio,
                UPPER(commercial_item_acqui_desc) AS commercial_item_acqui_desc,
                UPPER(commercial_item_test_progr) AS commercial_item_test_progr,
                UPPER(commercial_item_test_desc) AS commercial_item_test_desc,
                UPPER(consolidated_contract) AS consolidated_contract,
                UPPER(consolidated_contract_desc) AS consolidated_contract_desc,
                UPPER(contingency_humanitarian_o) AS contingency_humanitarian_o,
                UPPER(contingency_humanitar_desc) AS contingency_humanitar_desc,
                UPPER(contract_bundling) AS contract_bundling,
                UPPER(contract_bundling_descrip) AS contract_bundling_descrip,
                UPPER(contract_financing) AS contract_financing,
                UPPER(contract_financing_descrip) AS contract_financing_descrip,
                UPPER(contracting_officers_deter) AS contracting_officers_deter,
                UPPER(contracting_officers_desc) AS contracting_officers_desc,
                UPPER(cost_accounting_standards) AS cost_accounting_standards,
                UPPER(cost_accounting_stand_desc) AS cost_accounting_stand_desc,
                UPPER(cost_or_pricing_data) AS cost_or_pricing_data,
                UPPER(cost_or_pricing_data_desc) AS cost_or_pricing_data_desc,
                UPPER(country_of_product_or_serv) AS country_of_product_or_serv,
                UPPER(country_of_product_or_desc) AS country_of_product_or_desc,
                UPPER(davis_bacon_act) AS davis_bacon_act,
                UPPER(davis_bacon_act_descrip) AS davis_bacon_act_descrip,
                UPPER(evaluated_preference) AS evaluated_preference,
                UPPER(evaluated_preference_desc) AS evaluated_preference_desc,
                UPPER(extent_competed) AS extent_competed,
                UPPER(extent_compete_description) AS extent_compete_description,
                UPPER(fed_biz_opps) AS fed_biz_opps,
                UPPER(fed_biz_opps_description) AS fed_biz_opps_description,
                UPPER(foreign_funding) AS foreign_funding,
                UPPER(foreign_funding_desc) AS foreign_funding_desc,
                UPPER(government_furnished_equip) AS government_furnished_equip,
                UPPER(government_furnished_desc) AS government_furnished_desc,
                UPPER(information_technology_com) AS information_technology_com,
                UPPER(information_technolog_desc) AS information_technolog_desc,
                UPPER(interagency_contracting_au) AS interagency_contracting_au,
                UPPER(interagency_contract_desc) AS interagency_contract_desc,
                UPPER(local_area_set_aside) AS local_area_set_aside,
                UPPER(local_area_set_aside_desc) AS local_area_set_aside_desc,
                UPPER(major_program) AS major_program,
                UPPER(purchase_card_as_payment_m) AS purchase_card_as_payment_m,
                UPPER(purchase_card_as_paym_desc) AS purchase_card_as_paym_desc,
                UPPER(multi_year_contract) AS multi_year_contract,
                UPPER(multi_year_contract_desc) AS multi_year_contract_desc,
                UPPER(national_interest_action) AS national_interest_action,
                UPPER(national_interest_desc) AS national_interest_desc,
                UPPER(number_of_actions) AS number_of_actions,
                UPPER(number_of_offers_received) AS number_of_offers_received,
                UPPER(other_statutory_authority) AS other_statutory_authority,
                UPPER(performance_based_service) AS performance_based_service,
                UPPER(performance_based_se_desc) AS performance_based_se_desc,
                UPPER(place_of_manufacture) AS place_of_manufacture,
                UPPER(place_of_manufacture_desc) AS place_of_manufacture_desc,
                UPPER(price_evaluation_adjustmen) AS price_evaluation_adjustmen,
                UPPER(product_or_service_code) AS product_or_service_code,
                UPPER(product_or_service_co_desc) AS product_or_service_co_desc,
                UPPER(program_acronym) AS program_acronym,
                UPPER(other_than_full_and_open_c) AS other_than_full_and_open_c,
                UPPER(other_than_full_and_o_desc) AS other_than_full_and_o_desc,
                UPPER(recovered_materials_sustai) AS recovered_materials_sustai,
                UPPER(recovered_materials_s_desc) AS recovered_materials_s_desc,
                UPPER(research) AS research,
                UPPER(research_description) AS research_description,
                UPPER(sea_transportation) AS sea_transportation,
                UPPER(sea_transportation_desc) AS sea_transportation_desc,
                UPPER(service_contract_act) AS service_contract_act,
                UPPER(service_contract_act_desc) AS service_contract_act_desc,
                UPPER(small_business_competitive) AS small_business_competitive,
                UPPER(solicitation_identifier) AS solicitation_identifier,
                UPPER(solicitation_procedures) AS solicitation_procedures,
                UPPER(solicitation_procedur_desc) AS solicitation_procedur_desc,
                UPPER(fair_opportunity_limited_s) AS fair_opportunity_limited_s,
                UPPER(fair_opportunity_limi_desc) AS fair_opportunity_limi_desc,
                UPPER(subcontracting_plan) AS subcontracting_plan,
                UPPER(subcontracting_plan_desc) AS subcontracting_plan_desc,
                UPPER(program_system_or_equipmen) AS program_system_or_equipmen,
                UPPER(program_system_or_equ_desc) AS program_system_or_equ_desc,
                UPPER(type_set_aside) AS type_set_aside,
                UPPER(type_set_aside_description) AS type_set_aside_description,
                UPPER(epa_designated_product) AS epa_designated_product,
                UPPER(epa_designated_produc_desc) AS epa_designated_produc_desc,
                UPPER(walsh_healey_act) AS walsh_healey_act,
                UPPER(walsh_healey_act_descrip) AS walsh_healey_act_descrip,
                UPPER(transaction_number) AS transaction_number,
                UPPER(sam_exception) AS sam_exception,
                UPPER(sam_exception_description) AS sam_exception_description,
                UPPER(city_local_government) AS city_local_government,
                UPPER(county_local_government) AS county_local_government,
                UPPER(inter_municipal_local_gove) AS inter_municipal_local_gove,
                UPPER(local_government_owned) AS local_government_owned,
                UPPER(municipality_local_governm) AS municipality_local_governm,
                UPPER(school_district_local_gove) AS school_district_local_gove,
                UPPER(township_local_government) AS township_local_government,
                UPPER(us_state_government) AS us_state_government,
                UPPER(us_federal_government) AS us_federal_government,
                UPPER(federal_agency) AS federal_agency,
                UPPER(federally_funded_research) AS federally_funded_research,
                UPPER(us_tribal_government) AS us_tribal_government,
                UPPER(foreign_government) AS foreign_government,
                UPPER(community_developed_corpor) AS community_developed_corpor,
                UPPER(labor_surplus_area_firm) AS labor_surplus_area_firm,
                UPPER(corporate_entity_not_tax_e) AS corporate_entity_not_tax_e,
                UPPER(corporate_entity_tax_exemp) AS corporate_entity_tax_exemp,
                UPPER(partnership_or_limited_lia) AS partnership_or_limited_lia,
                UPPER(sole_proprietorship) AS sole_proprietorship,
                UPPER(small_agricultural_coopera) AS small_agricultural_coopera,
                UPPER(international_organization) AS international_organization,
                UPPER(us_government_entity) AS us_government_entity,
                UPPER(emerging_small_business) AS emerging_small_business,
                UPPER(c8a_program_participant) AS c8a_program_participant,
                UPPER(sba_certified_8_a_joint_ve) AS sba_certified_8_a_joint_ve,
                UPPER(dot_certified_disadvantage) AS dot_certified_disadvantage,
                UPPER(self_certified_small_disad) AS self_certified_small_disad,
                UPPER(historically_underutilized) AS historically_underutilized,
                UPPER(small_disadvantaged_busine) AS small_disadvantaged_busine,
                UPPER(the_ability_one_program) AS the_ability_one_program,
                UPPER(historically_black_college) AS historically_black_college,
                UPPER(c1862_land_grant_college) AS c1862_land_grant_college,
                UPPER(c1890_land_grant_college) AS c1890_land_grant_college,
                UPPER(c1994_land_grant_college) AS c1994_land_grant_college,
                UPPER(minority_institution) AS minority_institution,
                UPPER(private_university_or_coll) AS private_university_or_coll,
                UPPER(school_of_forestry) AS school_of_forestry,
                UPPER(state_controlled_instituti) AS state_controlled_instituti,
                UPPER(tribal_college) AS tribal_college,
                UPPER(veterinary_college) AS veterinary_college,
                UPPER(educational_institution) AS educational_institution,
                UPPER(alaskan_native_servicing_i) AS alaskan_native_servicing_i,
                UPPER(community_development_corp) AS community_development_corp,
                UPPER(native_hawaiian_servicing) AS native_hawaiian_servicing,
                UPPER(domestic_shelter) AS domestic_shelter,
                UPPER(manufacturer_of_goods) AS manufacturer_of_goods,
                UPPER(hospital_flag) AS hospital_flag,
                UPPER(veterinary_hospital) AS veterinary_hospital,
                UPPER(hispanic_servicing_institu) AS hispanic_servicing_institu,
                UPPER(foundation) AS foundation,
                UPPER(woman_owned_business) AS woman_owned_business,
                UPPER(minority_owned_business) AS minority_owned_business,
                UPPER(women_owned_small_business) AS women_owned_small_business,
                UPPER(economically_disadvantaged) AS economically_disadvantaged,
                UPPER(joint_venture_women_owned) AS joint_venture_women_owned,
                UPPER(joint_venture_economically) AS joint_venture_economically,
                UPPER(veteran_owned_business) AS veteran_owned_business,
                UPPER(service_disabled_veteran_o) AS service_disabled_veteran_o,
                UPPER(contracts) AS contracts,
                UPPER(grants) AS grants,
                UPPER(receives_contracts_and_gra) AS receives_contracts_and_gra,
                UPPER(airport_authority) AS airport_authority,
                UPPER(council_of_governments) AS council_of_governments,
                UPPER(housing_authorities_public) AS housing_authorities_public,
                UPPER(interstate_entity) AS interstate_entity,
                UPPER(planning_commission) AS planning_commission,
                UPPER(port_authority) AS port_authority,
                UPPER(transit_authority) AS transit_authority,
                UPPER(subchapter_s_corporation) AS subchapter_s_corporation,
                UPPER(limited_liability_corporat) AS limited_liability_corporat,
                UPPER(foreign_owned_and_located) AS foreign_owned_and_located,
                UPPER(american_indian_owned_busi) AS american_indian_owned_busi,
                UPPER(alaskan_native_owned_corpo) AS alaskan_native_owned_corpo,
                UPPER(indian_tribe_federally_rec) AS indian_tribe_federally_rec,
                UPPER(native_hawaiian_owned_busi) AS native_hawaiian_owned_busi,
                UPPER(tribally_owned_business) AS tribally_owned_business,
                UPPER(asian_pacific_american_own) AS asian_pacific_american_own,
                UPPER(black_american_owned_busin) AS black_american_owned_busin,
                UPPER(hispanic_american_owned_bu) AS hispanic_american_owned_bu,
                UPPER(native_american_owned_busi) AS native_american_owned_busi,
                UPPER(subcontinent_asian_asian_i) AS subcontinent_asian_asian_i,
                UPPER(other_minority_owned_busin) AS other_minority_owned_busin,
                UPPER(for_profit_organization) AS for_profit_organization,
                UPPER(nonprofit_organization) AS nonprofit_organization,
                UPPER(other_not_for_profit_organ) AS other_not_for_profit_organ,
                UPPER(us_local_government) AS us_local_government,
                UPPER(referenced_idv_modificatio) AS referenced_idv_modificatio,
                UPPER(undefinitized_action) AS undefinitized_action,
                UPPER(undefinitized_action_desc) AS undefinitized_action_desc,
                UPPER(domestic_or_foreign_entity) AS domestic_or_foreign_entity,
                UPPER(domestic_or_foreign_e_desc) AS domestic_or_foreign_e_desc,
                UPPER(annual_revenue) AS annual_revenue,
                UPPER(division_name) AS division_name,
                UPPER(division_number_or_office) AS division_number_or_office,
                UPPER(number_of_employees) AS number_of_employees,
                UPPER(vendor_alternate_name) AS vendor_alternate_name,
                UPPER(vendor_alternate_site_code) AS vendor_alternate_site_code,
                UPPER(vendor_enabled) AS vendor_enabled,
                UPPER(vendor_legal_org_name) AS vendor_legal_org_name,
                UPPER(vendor_location_disabled_f) AS vendor_location_disabled_f,
                UPPER(vendor_site_code) AS vendor_site_code,
                UPPER(pulled_from) AS pulled_from,
                UPPER(last_modified) AS last_modified,
                UPPER(initial_report_date) AS initial_report_date,
                UPPER(referenced_idv_agency_name) AS referenced_idv_agency_name,
                UPPER(referenced_multi_or_single) AS referenced_multi_or_single,
                UPPER(award_or_idv_flag) AS award_or_idv_flag,
                UPPER(place_of_perform_country_n) AS place_of_perform_country_n,
                UPPER(place_of_perform_state_nam) AS place_of_perform_state_nam,
                created_at,
                updated_at
            FROM detached_award_procurement
        )') AS transaction_contracts
    (
        detached_award_procurement_id int,
        detached_award_proc_unique text,
        piid text,
        agency_id text,
        awarding_sub_tier_agency_c text,
        awarding_sub_tier_agency_n text,
        awarding_agency_code text,
        awarding_agency_name text,
        parent_award_id text,
        award_modification_amendme text,
        type_of_contract_pricing text,
        type_of_contract_pric_desc text,
        contract_award_type text,
        contract_award_type_desc text,
        naics text,
        naics_description text,
        awardee_or_recipient_uniqu text,
        ultimate_parent_legal_enti text,
        ultimate_parent_unique_ide text,
        award_description text,
        place_of_performance_zip4a text,
        place_of_performance_zip5 text,
        place_of_perform_zip_last4 text,
        place_of_perform_city_name text,
        place_of_perform_county_co text,
        place_of_perform_county_na text,
        place_of_performance_congr text,
        awardee_or_recipient_legal text,
        legal_entity_city_name text,
        legal_entity_county_code text,
        legal_entity_county_name text,
        legal_entity_state_code text,
        legal_entity_state_descrip text,
        legal_entity_zip4 text,
        legal_entity_zip5 text,
        legal_entity_zip_last4 text,
        legal_entity_congressional text,
        legal_entity_address_line1 text,
        legal_entity_address_line2 text,
        legal_entity_address_line3 text,
        legal_entity_country_code text,
        legal_entity_country_name text,
        period_of_performance_star text,
        period_of_performance_curr text,
        period_of_perf_potential_e text,
        ordering_period_end_date text,
        action_date text,
        action_type text,
        action_type_description text,
        federal_action_obligation numeric,
        current_total_value_award text,
        potential_total_value_awar text,
        total_obligated_amount text,
        base_exercised_options_val text,
        base_and_all_options_value text,
        funding_sub_tier_agency_co text,
        funding_sub_tier_agency_na text,
        funding_office_code text,
        funding_office_name text,
        awarding_office_code text,
        awarding_office_name text,
        referenced_idv_agency_iden text,
        referenced_idv_agency_desc text,
        funding_agency_code text,
        funding_agency_name text,
        place_of_performance_locat text,
        place_of_performance_state text,
        place_of_perfor_state_desc text,
        place_of_perform_country_c text,
        place_of_perf_country_desc text,
        idv_type text,
        idv_type_description text,
        referenced_idv_type text,
        referenced_idv_type_desc text,
        vendor_doing_as_business_n text,
        vendor_phone_number text,
        vendor_fax_number text,
        multiple_or_single_award_i text,
        multiple_or_single_aw_desc text,
        referenced_mult_or_single text,
        referenced_mult_or_si_desc text,
        type_of_idc text,
        type_of_idc_description text,
        a_76_fair_act_action text,
        a_76_fair_act_action_desc text,
        dod_claimant_program_code text,
        dod_claimant_prog_cod_desc text,
        clinger_cohen_act_planning text,
        clinger_cohen_act_pla_desc text,
        commercial_item_acquisitio text,
        commercial_item_acqui_desc text,
        commercial_item_test_progr text,
        commercial_item_test_desc text,
        consolidated_contract text,
        consolidated_contract_desc text,
        contingency_humanitarian_o text,
        contingency_humanitar_desc text,
        contract_bundling text,
        contract_bundling_descrip text,
        contract_financing text,
        contract_financing_descrip text,
        contracting_officers_deter text,
        contracting_officers_desc text,
        cost_accounting_standards text,
        cost_accounting_stand_desc text,
        cost_or_pricing_data text,
        cost_or_pricing_data_desc text,
        country_of_product_or_serv text,
        country_of_product_or_desc text,
        davis_bacon_act text,
        davis_bacon_act_descrip text,
        evaluated_preference text,
        evaluated_preference_desc text,
        extent_competed text,
        extent_compete_description text,
        fed_biz_opps text,
        fed_biz_opps_description text,
        foreign_funding text,
        foreign_funding_desc text,
        government_furnished_equip text,
        government_furnished_desc text,
        information_technology_com text,
        information_technolog_desc text,
        interagency_contracting_au text,
        interagency_contract_desc text,
        local_area_set_aside text,
        local_area_set_aside_desc text,
        major_program text,
        purchase_card_as_payment_m text,
        purchase_card_as_paym_desc text,
        multi_year_contract text,
        multi_year_contract_desc text,
        national_interest_action text,
        national_interest_desc text,
        number_of_actions text,
        number_of_offers_received text,
        other_statutory_authority text,
        performance_based_service text,
        performance_based_se_desc text,
        place_of_manufacture text,
        place_of_manufacture_desc text,
        price_evaluation_adjustmen text,
        product_or_service_code text,
        product_or_service_co_desc text,
        program_acronym text,
        other_than_full_and_open_c text,
        other_than_full_and_o_desc text,
        recovered_materials_sustai text,
        recovered_materials_s_desc text,
        research text,
        research_description text,
        sea_transportation text,
        sea_transportation_desc text,
        service_contract_act text,
        service_contract_act_desc text,
        small_business_competitive text,
        solicitation_identifier text,
        solicitation_procedures text,
        solicitation_procedur_desc text,
        fair_opportunity_limited_s text,
        fair_opportunity_limi_desc text,
        subcontracting_plan text,
        subcontracting_plan_desc text,
        program_system_or_equipmen text,
        program_system_or_equ_desc text,
        type_set_aside text,
        type_set_aside_description text,
        epa_designated_product text,
        epa_designated_produc_desc text,
        walsh_healey_act text,
        walsh_healey_act_descrip text,
        transaction_number text,
        sam_exception text,
        sam_exception_description text,
        city_local_government text,
        county_local_government text,
        inter_municipal_local_gove text,
        local_government_owned text,
        municipality_local_governm text,
        school_district_local_gove text,
        township_local_government text,
        us_state_government text,
        us_federal_government text,
        federal_agency text,
        federally_funded_research text,
        us_tribal_government text,
        foreign_government text,
        community_developed_corpor text,
        labor_surplus_area_firm text,
        corporate_entity_not_tax_e text,
        corporate_entity_tax_exemp text,
        partnership_or_limited_lia text,
        sole_proprietorship text,
        small_agricultural_coopera text,
        international_organization text,
        us_government_entity text,
        emerging_small_business text,
        c8a_program_participant text,
        sba_certified_8_a_joint_ve text,
        dot_certified_disadvantage text,
        self_certified_small_disad text,
        historically_underutilized text,
        small_disadvantaged_busine text,
        the_ability_one_program text,
        historically_black_college text,
        c1862_land_grant_college text,
        c1890_land_grant_college text,
        c1994_land_grant_college text,
        minority_institution text,
        private_university_or_coll text,
        school_of_forestry text,
        state_controlled_instituti text,
        tribal_college text,
        veterinary_college text,
        educational_institution text,
        alaskan_native_servicing_i text,
        community_development_corp text,
        native_hawaiian_servicing text,
        domestic_shelter text,
        manufacturer_of_goods text,
        hospital_flag text,
        veterinary_hospital text,
        hispanic_servicing_institu text,
        foundation text,
        woman_owned_business text,
        minority_owned_business text,
        women_owned_small_business text,
        economically_disadvantaged text,
        joint_venture_women_owned text,
        joint_venture_economically text,
        veteran_owned_business text,
        service_disabled_veteran_o text,
        contracts text,
        grants text,
        receives_contracts_and_gra text,
        airport_authority text,
        council_of_governments text,
        housing_authorities_public text,
        interstate_entity text,
        planning_commission text,
        port_authority text,
        transit_authority text,
        subchapter_s_corporation text,
        limited_liability_corporat text,
        foreign_owned_and_located text,
        american_indian_owned_busi text,
        alaskan_native_owned_corpo text,
        indian_tribe_federally_rec text,
        native_hawaiian_owned_busi text,
        tribally_owned_business text,
        asian_pacific_american_own text,
        black_american_owned_busin text,
        hispanic_american_owned_bu text,
        native_american_owned_busi text,
        subcontinent_asian_asian_i text,
        other_minority_owned_busin text,
        for_profit_organization text,
        nonprofit_organization text,
        other_not_for_profit_organ text,
        us_local_government text,
        referenced_idv_modificatio text,
        undefinitized_action text,
        undefinitized_action_desc text,
        domestic_or_foreign_entity text,
        domestic_or_foreign_e_desc text,
        annual_revenue text,
        division_name text,
        division_number_or_office text,
        number_of_employees text,
        vendor_alternate_name text,
        vendor_alternate_site_code text,
        vendor_enabled text,
        vendor_legal_org_name text,
        vendor_location_disabled_f text,
        vendor_site_code text,
        pulled_from text,
        last_modified text,
        initial_report_date text,
        referenced_idv_agency_name text,
        referenced_multi_or_single text,
        award_or_idv_flag text,
        place_of_perform_country_n text,
        place_of_perform_state_nam text,
        created_at timestamp without time zone,
        updated_at timestamp without time zone
    )
);