DROP TABLE IF EXISTS transaction_fabs_new;

CREATE TABLE transaction_fabs_new AS
(

    SELECT
        NULL::bigint as transaction_id,
        *
    FROM
        dblink ('broker_server', '(
            SELECT
                published_award_financial_assistance_id,
                action_date,
                action_type,
                assistance_type,
                award_description,
                awardee_or_recipient_legal,
                awardee_or_recipient_uniqu,
                awarding_agency_code,
                awarding_office_code,
                awarding_sub_tier_agency_c,
                award_modification_amendme,
                business_funds_indicator,
                business_types,
                cfda_number,
                correction_late_delete_ind,
                face_value_loan_guarantee,
                fain,
                federal_action_obligation,
                fiscal_year_and_quarter_co,
                funding_agency_code,
                funding_office_code,
                funding_sub_tier_agency_co,
                legal_entity_address_line1,
                legal_entity_address_line2,
                legal_entity_address_line3,
                legal_entity_country_code,
                legal_entity_foreign_city,
                legal_entity_foreign_posta,
                legal_entity_foreign_provi,
                legal_entity_zip5,
                legal_entity_zip_last4,
                non_federal_funding_amount,
                original_loan_subsidy_cost,
                period_of_performance_curr,
                period_of_performance_star,
                place_of_performance_code,
                place_of_performance_congr,
                place_of_perform_country_c,
                place_of_performance_forei,
                place_of_performance_zip4a,
                record_type,
                sai_number,
                uri,
                legal_entity_congressional,
                total_funding_amount,
                cfda_title,
                awarding_agency_name,
                awarding_sub_tier_agency_n,
                funding_agency_name,
                funding_sub_tier_agency_na,
                is_historical,
                place_of_perform_county_na,
                place_of_perform_state_nam,
                place_of_performance_city,
                legal_entity_city_name,
                legal_entity_county_code,
                legal_entity_county_name,
                legal_entity_state_code,
                legal_entity_state_name,
                modified_at,
                afa_generated_unique,
                is_active,
                legal_entity_country_name,
                place_of_perform_country_n,
                place_of_perform_county_co,
                awarding_office_name,
                funding_office_name,
                legal_entity_city_code,
                legal_entity_foreign_descr,
                submission_id,
                place_of_perfor_state_code,
                place_of_performance_zip5,
                place_of_perform_zip_last4
            FROM published_award_financial_assistance
            WHERE is_active = True
        )') AS transaction_assistance
    (
        published_award_financial_assistance_id integer,
        action_date text,
        action_type text,
        assistance_type text,
        award_description text,
        awardee_or_recipient_legal text,
        awardee_or_recipient_uniqu text,
        awarding_agency_code text,
        awarding_office_code text,
        awarding_sub_tier_agency_c text,
        award_modification_amendme text,
        business_funds_indicator text,
        business_types text,
        cfda_number text,
        correction_late_delete_ind text,
        face_value_loan_guarantee numeric,
        fain text,
        federal_action_obligation numeric,
        fiscal_year_and_quarter_co text,
        funding_agency_code text,
        funding_office_code text,
        funding_sub_tier_agency_co text,
        legal_entity_address_line1 text,
        legal_entity_address_line2 text,
        legal_entity_address_line3 text,
        legal_entity_country_code text,
        legal_entity_foreign_city text,
        legal_entity_foreign_posta text,
        legal_entity_foreign_provi text,
        legal_entity_zip5 text,
        legal_entity_zip_last4 text,
        non_federal_funding_amount numeric,
        original_loan_subsidy_cost numeric,
        period_of_performance_curr text,
        period_of_performance_star text,
        place_of_performance_code text,
        place_of_performance_congr text,
        place_of_perform_country_c text,
        place_of_performance_forei text,
        place_of_performance_zip4a text,
        record_type integer,
        sai_number text,
        uri text,
        legal_entity_congressional text,
        total_funding_amount text,
        cfda_title text,
        awarding_agency_name text,
        awarding_sub_tier_agency_n text,
        funding_agency_name text,
        funding_sub_tier_agency_na text,
        is_historical boolean,
        place_of_perform_county_na text,
        place_of_perform_state_nam text,
        place_of_performance_city text,
        legal_entity_city_name text,
        legal_entity_county_code text,
        legal_entity_county_name text,
        legal_entity_state_code text,
        legal_entity_state_name text,
        modified_at timestamp without time zone,
        afa_generated_unique text,
        is_active boolean,
        legal_entity_country_name text,
        place_of_perform_country_n text,
        place_of_perform_county_co text,
        awarding_office_name text,
        funding_office_name text,
        legal_entity_city_code text,
        legal_entity_foreign_descr text,
        submission_id numeric,
        place_of_perfor_state_code text,
        place_of_performance_zip5 text,
        place_of_perform_zip_last4 text
    )
);