-- FPDS
UPDATE * FROM legal_entity
WHERE is_fpds = TRUE
SET business_categories = compile_fpds_business_categories(
    legal_entity.small_business_competitive,
    legal_entity.for_profit_organization,
    legal_entity.alaskan_native_owned_corpo,
    legal_entity.american_indian_owned_busi,
    legal_entity.asian_pacific_american_own,
    legal_entity.black_american_owned_busin,
    legal_entity.hispanic_american_owned_bu,
    legal_entity.native_american_owned_busi,
    legal_entity.native_hawaiian_owned_busi,
    legal_entity.subcontinent_asian_asian_i,
    legal_entity.tribally_owned_business,
    legal_entity.other_minority_owned_busin,
    legal_entity.minority_owned_business,
    legal_entity.women_owned_small_business,
    legal_entity.economically_disadvantaged,
    legal_entity.joint_venture_women_owned,
    legal_entity.joint_venture_economically,
    legal_entity.woman_owned_business,
    legal_entity.service_disabled_veteran_o,
    legal_entity.veteran_owned_business,
    legal_entity.c8a_program_participant,
    legal_entity.the_ability_one_program,
    legal_entity.dot_certified_disadvantage,
    legal_entity.emerging_small_business,
    legal_entity.federally_funded_research,
    legal_entity.historically_underutilized,
    legal_entity.labor_surplus_area_firm,
    legal_entity.sba_certified_8_a_joint_ve,
    legal_entity.self_certified_small_disad,
    legal_entity.small_agricultural_coopera,
    legal_entity.small_disadvantaged_busine,
    legal_entity.community_developed_corpor,
    legal_entity.domestic_or_foreign_entity text, foreign_owned_and_located,
    legal_entity.foreign_government,
    legal_entity.international_organization,
    legal_entity.foundation,
    legal_entity.community_development_corp,
    legal_entity.nonprofit_organization,
    legal_entity.other_not_for_profit_organ,
    legal_entity.state_controlled_instituti,
    legal_entity.c1862_land_grant_college,
    legal_entity.c1890_land_grant_college,
    legal_entity.c1994_land_grant_college,
    legal_entity.private_university_or_coll,
    legal_entity.minority_institution,
    legal_entity.historically_black_college,
    legal_entity.tribal_college,
    legal_entity.alaskan_native_servicing_i,
    legal_entity.native_hawaiian_servicing,
    legal_entity.hispanic_servicing_institu,
    legal_entity.us_federal_government,
    legal_entity.federal_agency,
    legal_entity.us_government_entity,
    legal_entity.interstate_entity,
    legal_entity.us_state_government,
    legal_entity.council_of_governments,
    legal_entity.city_local_government,
    legal_entity.county_local_government,
    legal_entity.inter_municipal_local_gove,
    legal_entity.municipality_local_governm,
    legal_entity.township_local_government,
    legal_entity.us_local_government,
    legal_entity.local_government_owned,
    legal_entity.school_district_local_gove,
    legal_entity.us_tribal_government,
    legal_entity.indian_tribe_federally_rec,
    legal_entity.housing_authorities_public,
    legal_entity.airport_authority,
    legal_entity.port_authority,
    legal_entity.transit_authority,
    legal_entity.planning_commission
)

-- FABS
UPDATE * FROM legal_entity
WHERE is_fpds = FALSE
SET business_categories = compile_fabs_business_categories(
    legal_entity.business_types
)
