-- Please replace the second conditional to whatever you need to use
-- to limit which rows are updated for performance

-- FPDS
UPDATE legal_entity
SET business_categories = compile_fpds_business_categories(
    legal_entity.small_business,
    legal_entity.for_profit_organization,
    legal_entity.alaskan_native_owned_corporation_or_firm,
    legal_entity.american_indian_owned_business,
    legal_entity.asian_pacific_american_owned_business,
    legal_entity.black_american_owned_business,
    legal_entity.hispanic_american_owned_business,
    legal_entity.native_american_owned_business,
    legal_entity.native_hawaiian_owned_business,
    legal_entity.subcontinent_asian_asian_indian_american_owned_business,
    legal_entity.tribally_owned_business,
    legal_entity.other_minority_owned_business,
    legal_entity.minority_owned_business,
    legal_entity.women_owned_small_business,
    legal_entity.economically_disadvantaged_women_owned_small_business,
    legal_entity.joint_venture_women_owned_small_business,
    legal_entity.joint_venture_economic_disadvantaged_women_owned_small_bus,
    legal_entity.woman_owned_business,
    legal_entity.service_disabled_veteran_owned_business,
    legal_entity.veteran_owned_business,
    legal_entity."8a_program_participant",
    legal_entity.the_ability_one_program,
    legal_entity.dot_certified_disadvantage,
    legal_entity.emerging_small_business,
    legal_entity.federally_funded_research_and_development_corp,
    legal_entity.historically_underutilized_business_zone,
    legal_entity.labor_surplus_area_firm,
    legal_entity.sba_certified_8a_joint_venture,
    legal_entity.self_certified_small_disadvantaged_business,
    legal_entity.small_agricultural_cooperative,
    legal_entity.small_disadvantaged_business,
    legal_entity.community_developed_corporation_owned_firm,
    legal_entity.domestic_or_foreign_entity,
    legal_entity.foreign_owned_and_located,
    legal_entity.foreign_government,
    legal_entity.international_organization,
    legal_entity.foundation,
    legal_entity.community_development_corporation,
    legal_entity.nonprofit_organization,
    legal_entity.other_not_for_profit_organization,
    legal_entity.state_controlled_institution_of_higher_learning,
    legal_entity."1862_land_grant_college",
    legal_entity."1890_land_grant_college",
    legal_entity."1994_land_grant_college",
    legal_entity.private_university_or_college,
    legal_entity.minority_institution,
    legal_entity.historically_black_college,
    legal_entity.tribal_college,
    legal_entity.alaskan_native_servicing_institution,
    legal_entity.native_hawaiian_servicing_institution,
    legal_entity.hispanic_servicing_institution,
    legal_entity.us_federal_government,
    legal_entity.federal_agency,
    legal_entity.us_government_entity,
    legal_entity.interstate_entity,
    legal_entity.us_state_government,
    legal_entity.council_of_governments,
    legal_entity.city_local_government,
    legal_entity.county_local_government,
    legal_entity.inter_municipal_local_government,
    legal_entity.municipality_local_government,
    legal_entity.township_local_government,
    legal_entity.us_local_government,
    legal_entity.local_government_owned,
    legal_entity.school_district_local_government,
    legal_entity.us_tribal_government,
    legal_entity.indian_tribe_federally_recognized,
    legal_entity.housing_authorities_public_tribal,
    legal_entity.airport_authority,
    legal_entity.port_authority,
    legal_entity.transit_authority,
    legal_entity.planning_commission
)
WHERE is_fpds = TRUE and business_categories @> ARRAY['small_business', 'category_business'];

-- FABS
UPDATE legal_entity
SET business_categories = compile_fabs_business_categories(
    legal_entity.business_types
)
WHERE is_fpds = FALSE and business_categories @> ARRAY['small_business', 'category_business'];
