# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateData',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('fips', models.TextField(db_index=True)),
                ('code', models.TextField()),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('year', models.IntegerField(db_index=True)),
                ('population', models.BigIntegerField(blank=True, default=None, null=True)),
                ('pop_source', models.TextField(blank=True, default=None, null=True)),
                ('median_household_income', models.BigIntegerField(blank=True, default=None, null=True)),
                ('mhi_source', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'state_data',
            },
        ),
    ]
