# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-18 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DUNS',
            fields=[
                ('awardee_or_recipient_uniqu', models.TextField(primary_key=True, serialize=False)),
                ('legal_business_name', models.TextField()),
                ('ultimate_parent_unique_ide', models.TextField()),
                ('ultimate_parent_legal_enti', models.TextField()),
                ('broker_duns_id', models.TextField()),
                ('update_date', models.DateField()),
            ],
            options={
                'db_table': 'duns',
            },
        ),
    ]
