# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-18 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0002_duns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duns',
            options={'managed': True},
        ),
    ]
