# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-18 20:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0003_historicparentduns'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_level', models.CharField(max_length=1)),
                ('recipient_hash', models.UUIDField()),
                ('recipient_unique_id', models.TextField()),
                ('legal_business_name', models.TextField()),
                ('recipient_affiliations', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('last_12_months', models.DecimalField(decimal_places=2, max_digits=23)),
            ],
            options={
                'db_table': 'recipient_profile',
                'managed': False,
            },
        ),
    ]
