# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-23 17:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0004_dunsprops'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_level', models.CharField(max_length=1)),
                ('recipient_hash', models.UUIDField(null=True)),
                ('recipient_unique_id', models.TextField(null=True)),
                ('recipient_name', models.TextField(null=True)),
                ('recipient_affiliations', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('last_12_months', models.DecimalField(decimal_places=2, default=0, max_digits=23)),
            ],
            options={
                'db_table': 'recipient_profile',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='recipientprofile',
            unique_together=set([('recipient_level', 'recipient_hash')]),
        ),
    ]
