# Generated by Django 2.2.17 on 2021-05-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0006_auto_20210315_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientAgency',
            fields=[
                ('fiscal_year', models.IntegerField(db_index=True)),
                ('toptier_code', models.TextField(db_index=True)),
                ('recipient_hash', models.UUIDField(primary_key=True, db_index=True)),
                ('recipient_name', models.TextField()),
                ('recipient_amount', models.DecimalField(decimal_places=2, max_digits=23)),
            ],
            options={
                'db_table': 'recipient_agency',
                'managed': True,
            },
        ),
    ]
