# Generated by Django 2.2.17 on 2021-07-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0007_recipientagency'),
    ]

    operations = [
        migrations.AddField(
            model_name='duns',
            name='uei',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duns',
            name='ultimate_parent_uei',
            field=models.TextField(blank=True, null=True),
        ),
    ]
