# Generated by Django 2.2.17 on 2021-09-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0008_auto_20210727_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientprofile',
            name='uei',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
