# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-02 17:48
from __future__ import unicode_literals

from django.db import migrations
import partial_index


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0010_duns_dba_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recipientlookup',
            name='recipient_l_parent__e14231_partial',
        ),
        migrations.AddIndex(
            model_name='recipientlookup',
            index=partial_index.PartialIndex(fields=['parent_duns'], name='recipient_l_parent__efd6d5_partial', unique=False, where=partial_index.PQ(parent_duns__isnull=False)),
        ),
    ]
