# Generated by Django 2.2.27 on 2022-02-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0010_recipientlookup_uei'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recipientprofile',
            index=models.Index(fields=['uei'], name='recipient_p_uei_25c7ff_idx'),
        ),
    ]
