# Generated by Django 2.2.17 on 2022-01-25 17:46

from django.db import migrations, models
import partial_index


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0010_recipientlookup_uei'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recipientlookup',
            name='recipient_l_duns_bb057a_partial',
        ),
        migrations.AlterField(
            model_name='recipientlookup',
            name='duns',
            field=models.TextField(null=True),
        ),
        migrations.AddIndex(
            model_name='recipientlookup',
            index=partial_index.PartialIndex(fields=['duns'], name='recipient_l_duns_a43c07_partial', unique=False, where=partial_index.PQ(duns__isnull=False)),
        ),
        migrations.AddIndex(
            model_name='recipientlookup',
            index=partial_index.PartialIndex(fields=['uei'], name='recipient_l_uei_c6ad5f_partial', unique=False, where=partial_index.PQ(uei__isnull=False)),
        ),
    ]
