# Generated by Django 2.2.17 on 2022-01-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0010_recipientlookup_uei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientlookup',
            name='duns',
            field=models.TextField(null=True),
        ),
    ]
