# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-18 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0011_auto_20180902_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryAwardRecipient',
            fields=[
                ('award_id', models.TextField(primary_key=True, serialize=False)),
                ('action_date', models.DateField(blank=True, db_index=True)),
                ('recipient_hash', models.UUIDField(null=True, db_index=True)),
                ('parent_recipient_unique_id', models.TextField(null=True, db_index=True)),
            ],
            options={
                'db_table': 'summary_award_recipient',
                'managed': True,
            },
        ),
    ]
