# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-19 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0014_auto_20181126_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryawardrecipient',
            name='award_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
