# Generated by Django 2.2.17 on 2022-03-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0014_auto_20220224_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientlookup',
            name='parent_uei',
            field=models.TextField(null=True),
        ),
    ]
