# Generated by Django 2.2.17 on 2022-03-07 19:46

from django.db import migrations
import partial_index


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0015_recipientlookup_parent_uei'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recipientlookup',
            index=partial_index.PartialIndex(fields=['uei'], name='recipient_l_uei_620159_partial', unique=True, where=partial_index.PQ(uei__isnull=False)),
        ),
        migrations.AddIndex(
            model_name='recipientlookup',
            index=partial_index.PartialIndex(fields=['parent_uei'], name='recipient_l_parent__271f5c_partial', unique=False, where=partial_index.PQ(parent_uei__isnull=False)),
        ),
    ]
