# Generated by Django 2.2.17 on 2022-03-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0015_recipientlookup_parent_uei'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE UNIQUE INDEX recipient_l_uei_620159_partial ON recipient_lookup (uei) WHERE uei IS NOT NULL",
            reverse_sql="DROP INDEX recipient_l_uei_620159_partial",
            state_operations=[
                migrations.AddIndex(
                    model_name="recipientlookup",
                    index=models.Index(name="recipient_l_uei_620159_partial", fields=["uei"], condition=models.Q(uei__isnull=False)),
                )
            ]
        ),
        migrations.RunSQL(
            sql="CREATE INDEX recipient_l_parent__271f5c_partial ON recipient_lookup (parent_uei) WHERE parent_uei IS NOT NULL",
            reverse_sql="DROP INDEX recipient_l_parent__271f5c_partial"
        ),
    ]
