# Generated by Django 2.2.17 on 2022-03-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0016_auto_20220307_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientprofile',
            name='parent_uei',
            field=models.TextField(null=True),
        ),
    ]
