# Generated by Django 2.2.17 on 2022-03-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0017_recipientprofile_parent_uei'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summaryawardrecipient',
            name='parent_recipient_unique_id',
        ),
        migrations.AddField(
            model_name='summaryawardrecipient',
            name='parent_uei',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
