# Generated by Django 2.2.17 on 2022-03-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0018_summaryawardrecipient_parent_uei'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summaryawardrecipient',
            name='parent_recipient_unique_id',
        ),
    ]
