# Generated by Django 2.2.28 on 2022-05-13 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0020_auto_20220406_1352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SummaryAwardRecipient',
        ),
    ]
