# Generated by Django 2.2.28 on 2022-05-17 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0021_delete_recipientagency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SummaryAwardRecipient',
        ),
    ]
