# Generated by Django 3.2.13 on 2022-08-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0023_shorter_index_names'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE recipient_lookup DROP CONSTRAINT recipient_lookup_recipient_hash_key",
            reverse_sql="ALTER TABLE recipient_lookup ADD CONSTRAINT recipient_lookup_recipient_hash_key UNIQUE (recipient_hash)"
        ),
    ]
