# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDataLoadDate',
            fields=[
                ('external_data_load_date_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_load_date', models.DateField()),
            ],
            options={
                'db_table': 'external_data_load_date',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExternalDataType',
            fields=[
                ('external_data_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'external_data_type',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='externaldataloaddate',
            name='external_data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='broker.ExternalDataType'),
        ),
        migrations.AlterUniqueTogether(
            name='externaldataloaddate',
            unique_together=set([('last_load_date', 'external_data_type')]),
        ),
    ]
