# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaldataloaddate',
            name='last_load_date',
            field=models.DateTimeField(),
        ),
    ]
