# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-16 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_add_nullable_to_transaction_map'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionassistancenew',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transactioncontractnew',
            options={},
        ),
    ]
