# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-16 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_auto_20170916_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionassistancenew',
            name='published_award_financial_assistance_id',
            field=models.AutoField(primary_key=True),
        ),
        migrations.AlterField(
            model_name='transactioncontractnew',
            name='detached_award_procurement_id',
            field=models.AutoField(primary_key=True),
        ),
    ]
