# Generated by Django 3.2.25 on 2024-03-21 18:57

from django.db import migrations

from usaspending_api.broker.lookups import LoadTrackerStepEnum, LoadTrackerLoadTypeEnum


class Migration(migrations.Migration):

    dependencies = [
        ("broker", "0007_create_load_tracker_view"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                f"INSERT INTO load_tracker_step(name) VALUES('{LoadTrackerStepEnum.SWAP_IN_NEW_TABLE_TRANSACTION_SEARCH_FABS.value}')",
                f"INSERT INTO load_tracker_step(name) VALUES('{LoadTrackerStepEnum.SWAP_IN_NEW_TABLE_TRANSACTION_SEARCH_FPDS.value}')",
                f"INSERT INTO load_tracker_step(name) VALUES('{LoadTrackerStepEnum.SWAP_IN_NEW_TABLE_TRANSACTION_SEARCH.value}')",
            ]
        ),
    ]
