# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                'drop index if exists toptier_agency_toptier_code_8b0eb9cb_like',
            ],
        ),
    ]
