# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_auto_20160920_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefSubtierAgencyOfficeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('agency_name', models.CharField(blank=True, max_length=150, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtier_agencies', to='references.Agency')),
            ],
            options={
                'db_table': 'ref_subtier_agency_office_code',
                'managed': True,
            },
        ),
    ]
