# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_naics'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSC',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
            options={
                'managed': True,
                'db_table': 'psc',
            },
        ),
    ]
