# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_psc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='legalentity',
            unique_together=set([('recipient_unique_id', 'recipient_name', 'location')]),
        ),
    ]
