# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_refsubtieragencyofficecode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RefSubtierAgencyOfficeCode',
            new_name='SubtierAgency',
        ),
    ]
