# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_auto_20160920_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='agency_code_aac',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='agency_code_cgac',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='create_user_id',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='department_parent_id',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='location',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='sub_tier_parent_id',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='update_user_id',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='valid_period_end',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='valid_period_start',
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='RefCgacCode',
        ),
    ]
