# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 17:02
from __future__ import unicode_literals

from django.db import migrations
from usaspending_api.references.models import LegalEntity


def forwards_func(apps, schema_editor):
    legalentities = apps.get_model("references", "LegalEntity")
    for le in legalentities.objects.all():
        LegalEntity.update_business_type_categories(le)
        le.save()


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0006_legalentity_business_categories'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
