# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-09 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0006_auto_20171211_1913'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE object_class SET major_object_class_name = 'Unknown' WHERE major_object_class = '00' ",
            None
        )
    ]
