# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-23 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0007_auto_20180109_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='is_fpds',
            field=models.BooleanField(default='none', verbose_name='Is FPDS'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='transaction_unique_id',
            field=models.TextField(default='none', verbose_name='Transaction Unique ID'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_fpds',
            field=models.BooleanField(default='none', verbose_name='Is FPDS'),
        ),
        migrations.AddField(
            model_name='location',
            name='transaction_unique_id',
            field=models.TextField(default='none', verbose_name='Transaction Unique ID'),
        ),
    ]
