# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0007_auto_20160920_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtieragency',
            name='code',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
