# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0008_auto_20160920_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='refprogramactivity',
            name='allocation_transfer_agency_id',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='refprogramactivity',
            name='main_account_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='refprogramactivity',
            name='responsible_agency_id',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.RemoveField(
            model_name='refprogramactivity',
            name='id',
        ),
        migrations.AddField(
            model_name='refprogramactivity',
            name='ref_program_activity_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='refprogramactivity',
            unique_together=set([('program_activity_code', 'program_activity_name', 'budget_year', 'responsible_agency_id', 'allocation_transfer_agency_id', 'main_account_code')]),
        ),
    ]
