# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0008_auto_20180123_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_country_code',
            field=models.TextField(blank=True, null=True, verbose_name='Location Country Code'),
        ),
    ]
