# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0009_auto_20160921_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='awardee_or_recipient_legal',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='location',
            field=models.ForeignKey(null=True, on_delete=models.deletion.DO_NOTHING, to='references.Location'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='ultimate_parent_legal_entity_id',
            field=models.IntegerField(null=True),
        ),
    ]
