# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0009_auto_20160921_2053'),
        ('references', '0009_auto_20160921_1246'),
    ]

    operations = [
    ]
