# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 15:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0010_merge_20170518_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('filter', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='JSON of Filter')),
                ('hash', models.TextField(unique=True, verbose_name='Hash of JSON Filter')),
            ],
            options={
                'db_table': 'filter_hash',
                'managed': True,
            },
        ),
    ]
