# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0010_merge_20160921_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refprogramactivity',
            name='ref_program_activity_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
