# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0011_auto_20160922_0221'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('location_country_code', 'location_country_name', 'location_state_code', 'location_state_name', 'location_state_text', 'location_city_name', 'location_city_code', 'location_county_name', 'location_county_code', 'location_address_line1', 'location_address_line2', 'location_address_line3', 'location_foreign_location_description', 'location_zip4', 'location_congressional_code', 'location_performance_code', 'location_zip_last4', 'location_zip5', 'location_foreign_postal_code', 'location_foreign_province', 'location_foreign_city_name', 'reporting_period_start', 'reporting_period_end')]),
        ),
    ]
