# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0012_auto_20160923_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='cgac_code',
            new_name='id',
        ),
    ]
