# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-02 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0012_auto_20180222_1504'),
    ]

    operations = [
        migrations.RunSQL(sql="CREATE INDEX legal_entity_recipient_name_idx ON legal_entity (recipient_name)",
                          reverse_sql="DROP INDEX legal_entity_recipient_name_idx")
    ]
