# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-03 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0013_add_pg_trgm_extension'),
        ('references', '0013_frecmap'),
    ]

    operations = [
    ]
