# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0013_auto_20160923_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
