# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0014_merge_20170703_1825'),
        ('references', '0014_add_agency_metadata'),
    ]

    operations = [
    ]
