# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-01 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0015_merge_20170712_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateAbbreviation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abbrev', models.TextField(db_index=True)),
                ('name', models.TextField(db_index=True)),
            ],
        ),
    ]
