# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0016_location_location_zip_4a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='create_user_id',
        ),
        migrations.RemoveField(
            model_name='refcitycountycode',
            name='create_user_id',
        ),
        migrations.RemoveField(
            model_name='refcitycountycode',
            name='update_user_id',
        ),
        migrations.RemoveField(
            model_name='refcountrycode',
            name='create_user_id',
        ),
        migrations.RemoveField(
            model_name='refcountrycode',
            name='update_user_id',
        ),
        migrations.RemoveField(
            model_name='refobjectclasscode',
            name='create_user_id',
        ),
        migrations.RemoveField(
            model_name='refobjectclasscode',
            name='update_user_id',
        ),
        migrations.RemoveField(
            model_name='refprogramactivity',
            name='create_user_id',
        ),
        migrations.RemoveField(
            model_name='refprogramactivity',
            name='update_user_id',
        ),
        migrations.AddField(
            model_name='location',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='refcitycountycode',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='refcitycountycode',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='refcountrycode',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='refcountrycode',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='refobjectclasscode',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='refobjectclasscode',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='refprogramactivity',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='refprogramactivity',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
