# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-14 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0016_create_gtas_total_obligation_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='domestic_or_foreign_entity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='county_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
