# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0019_merge_20160928_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='cgac_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
