# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0020_agency_cgac_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='subtier_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
