# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0020_indices_d1_d2_c'),
        ('references', '0016_stateabbreviation'),
    ]

    operations = [
    ]
