# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-07 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0020_indices_d1_d2_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfda',
            name='program_number',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subtieragency',
            name='name',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Sub-Tier Agency Name'),
        ),
        migrations.AlterField(
            model_name='toptieragency',
            name='name',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Top-Tier Agency Name'),
        ),
    ]
