# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-12 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0020_legalentity_parent_recipient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAICSRaw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.TextField()),
                ('naics_id', models.TextField()),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
