# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0020_agency_cgac_code'),
        ('references', '0020_auto_20161006_1021'),
    ]

    operations = [
    ]
