# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0021_legalentityofficers_duns'),
    ]

    operations = [
        migrations.AddField(
            model_name='naics',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
