# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0022_merge_20161011_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_city_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
