# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 17:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0022_naics_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rosetta',
            fields=[
                ('document_name', models.TextField(primary_key=True, serialize=False)),
                ('document', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'rosetta',
                'managed': True,
            },
        ),
    ]
