# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 19:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0022_naics_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rosetta',
            fields=[
                ('element', models.TextField(primary_key=True, serialize=False, verbose_name='Element')),
                ('definition', models.TextField(verbose_name='Definition')),
                ('fpds_element', models.TextField(verbose_name='FPDS Element')),
                ('file_a_f', models.TextField(verbose_name='File A-F')),
                ('award_file', models.TextField(verbose_name='Award File')),
                ('award_element', models.TextField(verbose_name='Award Element')),
                ('subaward_file', models.TextField(verbose_name='Subaward File')),
                ('subaward_element', models.TextField(verbose_name='Subaward Element')),
                ('account_file', models.TextField(verbose_name='Account File')),
                ('account_element', models.TextField(verbose_name='Account Element')),
                ('legacy_award_element', models.TextField(verbose_name='Legacy Award Element')),
                ('legacy_subaward_element', models.TextField(verbose_name='Legacy Subaward Element')),
                ('full_doc', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'rosetta',
                'managed': True,
            },
        ),
    ]
