# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-22 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0023_rosetta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='legal_entity_id',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
