# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0025_auto_20181126_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='toptieragency',
            name='justification',
            field=models.URLField(blank=True, null=True, verbose_name='Top-Tier Agency Congressional Justification'),
        ),
    ]
