# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-17 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0025_auto_20181126_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentityofficers',
            name='officer_1_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='legalentityofficers',
            name='officer_2_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='legalentityofficers',
            name='officer_3_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='legalentityofficers',
            name='officer_4_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='legalentityofficers',
            name='officer_5_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
