# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0027_auto_20161024_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfdaprogram',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cfdaprogram',
            name='website_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
