# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-10 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0027_drop_legalentityofficers'),
        ('references', '0027_cgac'),
    ]

    operations = [
    ]
