# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0028_auto_20161026_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='certified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='last_modified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='certified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='last_modified_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
