# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-29 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0030_auto_20190823_2139'),
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                migrations.DeleteModel(
                    name='CGAC',
                ),
            ],
        ),
    ]
