# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0030_auto_20161026_1544'),
        ('references', '0028_auto_20161026_1549'),
    ]

    operations = [
    ]
