# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-18 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0031_delete_cgac'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subtieragency',
            options={},
        ),
        migrations.AlterModelOptions(
            name='toptieragency',
            options={},
        ),
        migrations.AlterField(
            model_name='subtieragency',
            name='abbreviation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtieragency',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subtieragency',
            name='name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='subtieragency',
            name='subtier_code',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subtieragency',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='user_selectable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agency',
            name='subtier_agency',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='references.SubtierAgency'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='toptier_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='references.ToptierAgency'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='agency',
            unique_together=set([]),
        ),
        migrations.AlterField(
            model_name='toptieragency',
            name='abbreviation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toptieragency',
            name='cgac_code',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='toptieragency',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='toptieragency',
            name='icon_filename',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toptieragency',
            name='justification',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toptieragency',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toptieragency',
            name='name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='toptieragency',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='toptieragency',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        # This keeps our agency table honest at the database level.  Unique constraints don't work
        # well if one of the columns in the constraint accepts nulls.  The workaround is to place
        # a unique index on the other column but only where the nullable column is null.
        migrations.RunSQL(
            ["""create unique index idx_agency_toptier_agency_id_null_subtier_agency_id_uniq on
                agency (toptier_agency_id) where subtier_agency_id is null"""],
            ["drop index if exists idx_agency_toptier_agency_id_null_subtier_agency_id_uniq"]
        ),
    ]
