# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-07 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0067_auto_20191007_1334'),
        ('accounts', '0007_auto_20191007_1334'),
        ('references', '0032_auto_20190918_0148'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                migrations.RemoveField(
                    model_name='agency',
                    name='subtier_agency',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                migrations.RemoveField(
                    model_name='agency',
                    name='toptier_agency',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                migrations.DeleteModel(
                    name='Agency',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                migrations.DeleteModel(
                    name='SubtierAgency',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                migrations.DeleteModel(
                    name='ToptierAgency',
                ),
            ],
        ),
    ]
