# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-16 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0033_move_cgacs_back'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toptieragency',
            old_name='cgac_code',
            new_name='toptier_code',
        ),
    ]
