# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0033_auto_20161030_2051'),
        ('references', '0033_auto_20161101_1029'),
    ]

    operations = [
    ]
