# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0034_merge_20161101_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfdaprogram',
            name='data_source',
            field=models.CharField(choices=[('USA', 'USAspending'), ('DBR', 'DATA Act Broker')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='data_source',
            field=models.CharField(choices=[('USA', 'USAspending'), ('DBR', 'DATA Act Broker')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='data_source',
            field=models.CharField(choices=[('USA', 'USAspending'), ('DBR', 'DATA Act Broker')], max_length=3, null=True),
        ),
    ]
