# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-06 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0035_remove_legalentity_business_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectclass',
            options={},
        ),
        migrations.AlterField(
            model_name='objectclass',
            name='direct_reimbursable',
            field=models.TextField(blank=True, choices=[(None, None), ('D', 'Direct'), ('R', 'Reimbursable')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='objectclass',
            name='direct_reimbursable_name',
            field=models.TextField(blank=True, choices=[(None, None), ('Direct', 'D'), ('Reimbursable', 'R')], null=True),
        ),
        migrations.AlterField(
            model_name='objectclass',
            name='major_object_class',
            field=models.TextField(choices=[('00', 'Unknown'), ('10', 'Personnel compensation and benefits'), ('20', 'Contractual services and supplies'), ('30', 'Acquisition of assets'), ('40', 'Grants and fixed charges'), ('90', 'Other')], db_index=True),
        ),
        migrations.AlterField(
            model_name='objectclass',
            name='major_object_class_name',
            field=models.TextField(choices=[('Unknown', '00'), ('Personnel compensation and benefits', '10'), ('Contractual services and supplies', '20'), ('Acquisition of assets', '30'), ('Grants and fixed charges', '40'), ('Other', '90')]),
        ),
    ]
