# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0036_auto_20161107_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='airport_authority',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Airport Authority'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='alaskan_native_owned_corporation_or_firm',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Alaskan Native Owned Corporation or Firm'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='alaskan_native_servicing_institution',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Alaskan Native Owned Servicing Institution'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='american_indian_owned_business',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='American Indian Owned Business'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='asian_pacific_american_owned_business',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Asian Pacific American Owned business'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='c1862_land_grant_college',
            field=models.CharField(blank=True, db_column='1862_land_grant_college', max_length=1, null=True, verbose_name='1862 Land Grant College'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='c1890_land_grant_college',
            field=models.CharField(blank=True, db_column='1890_land_grant_college', max_length=1, null=True, verbose_name='1890 Land Grant College'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='c1994_land_grant_college',
            field=models.CharField(blank=True, db_column='1994_land_grant_college', max_length=1, null=True, verbose_name='1894 Land Grant College'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='c8a_program_participant',
            field=models.CharField(blank=True, db_column='8a_program_participant', max_length=1, null=True, verbose_name='8a Program Participant'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Recipient Name'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='recipient_unique_id',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='DUNS Number'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_address_line1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_address_line2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_address_line3',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Address Line 3'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_city_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_congressional_code',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Congressional District Code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_country_code',
            field=models.ForeignKey(blank=True, db_column='location_country_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='references.RefCountryCode', verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_country_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_performance_code',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Primary Place Of Performance Location Code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_state_code',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='State Code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_state_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='State Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_zip4',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ZIP+4'),
        ),
    ]
