# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-27 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0069_auto_20191227_1603'),
        ('references', '0036_auto_20191206_1945'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='legalentity',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='location',
        ),
        migrations.DeleteModel(
            name='LegalEntity',
        ),
    ]
