# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-16 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0070_auto_20200116_1354'),
        ('references', '0037_auto_20191227_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
