# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-03 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0038_auto_20161219_1358'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='legalentity',
            unique_together=set([('recipient_unique_id',)]),
        ),
    ]
