# Generated by Django 2.2.9 on 2020-02-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0039_auto_20200206_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefCityCountyCode',
        ),
    ]
