# Generated by Django 2.2.11 on 2020-03-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0040_auto_20200206_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='frec',
            name='associated_cgac_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
