# Generated by Django 2.2.12 on 2020-04-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0042_popcounty'),
    ]

    operations = [
        migrations.AddField(
            model_name='toptieragency',
            name='about_agency_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
