# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-12 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0042_toptieragency_fpds_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agency',
            unique_together=set([('toptier_agency', 'subtier_agency', 'office_agency')]),
        ),
    ]
