# Generated by Django 2.2.11 on 2020-03-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0042_cgac_is_shared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frec',
            old_name='associated_cgac_code',
            new_name='associated_cgac_code',
        ),
    ]
