# Generated by Django 2.2.9 on 2020-05-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0043_toptieragency_about_agency_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterEmergencyFundCode',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('public_law', models.TextField()),
                ('title', models.TextField(null=True)),
                ('group_name', models.TextField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'disaster_emergency_fund_code',
                'managed': True,
            },
        ),
    ]
