# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-12 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0043_auto_20170112_1939'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='legalentity',
            unique_together=set([('recipient_unique_id',)]),
        ),
    ]
