# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-17 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0044_auto_20170112_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='city_township_government',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='individual',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='small_business',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='special_district_government',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
