# Generated by Django 2.2.10 on 2020-06-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0045_disasteremergencyfundcode_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtastotalobligation',
            name='budget_authority_appropriation_amount_cpe',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gtastotalobligation',
            name='disaster_emergency_fund_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gtastotalobligation',
            name='fiscal_period',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gtastotalobligation',
            name='gross_outlay_amount_by_tas_cpe',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gtastotalobligation',
            name='obligations_incurred_total_cpe',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gtastotalobligation',
            name='other_budgetary_resources_amount_cpe',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gtastotalobligation',
            name='unobligated_balance_cpe',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=23),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='gtastotalobligation',
            unique_together={('fiscal_year', 'fiscal_period', 'disaster_emergency_fund_code')},
        ),
        migrations.RemoveField(
            model_name='gtastotalobligation',
            name='fiscal_quarter',
        ),
        migrations.RemoveField(
            model_name='gtastotalobligation',
            name='total_obligation',
        ),
    ]
