# Generated by Django 2.2.13 on 2020-06-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0045_disasteremergencyfundcode_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DABSSubmissionWindow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reporting_start', models.DateTimeField()),
                ('reporting_end', models.DateTimeField()),
                ('submission_start_date', models.DateTimeField()),
                ('submission_end_date', models.DateTimeField()),
                ('certification_end_date', models.DateTimeField()),
                ('submission_fiscal_year', models.IntegerField()),
                ('submission_fiscal_quarter', models.IntegerField()),
                ('submission_fiscal_period', models.IntegerField()),
                ('is_quarter', models.BooleanField()),
            ],
            options={
                'db_table': 'dabs_submission_window',
                'managed': True,
                'unique_together': {('submission_fiscal_year', 'submission_fiscal_quarter', 'submission_fiscal_period', 'is_quarter')},
            },
        ),
    ]
