# Generated by Django 2.2.10 on 2020-06-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0045_disasteremergencyfundcode_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='GTASSF133Balances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField()),
                ('fiscal_period', models.IntegerField()),
                ('obligations_incurred_total_cpe', models.DecimalField(decimal_places=2, max_digits=23)),
                ('budget_authority_appropriation_amount_cpe', models.DecimalField(decimal_places=2, max_digits=23)),
                ('other_budgetary_resources_amount_cpe', models.DecimalField(decimal_places=2, max_digits=23)),
                ('gross_outlay_amount_by_tas_cpe', models.DecimalField(decimal_places=2, max_digits=23)),
                ('unobligated_balance_cpe', models.DecimalField(decimal_places=2, max_digits=23)),
                ('disaster_emergency_fund_code', models.TextField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gtas_sf133_balances',
                'managed': True,
                'unique_together': {('fiscal_year', 'fiscal_period', 'disaster_emergency_fund_code')},
            },
        ),
    ]
