# Generated by Django 2.2.10 on 2020-06-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0045_disasteremergencyfundcode_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtastotalobligation',
            name='disaster_emergency_fund_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gtastotalobligation',
            name='fiscal_period',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='gtastotalobligation',
            unique_together={('fiscal_year', 'fiscal_period', 'disaster_emergency_fund_code')},
        ),
        migrations.RemoveField(
            model_name='gtastotalobligation',
            name='fiscal_quarter',
        ),
    ]
