# Generated by Django 2.2.10 on 2020-06-25 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_appropriationaccountbalancesquarterly'),
        ('references', '0046_sf_balances_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtassf133balances',
            name='tas_rendering_label',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='gtassf133balances',
            name='treasury_account_identifier',
            field=models.ForeignKey(db_column='treasury_account_identifier', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gtas', to='accounts.TreasuryAppropriationAccount'),
        ),
        migrations.AlterUniqueTogether(
            name='gtassf133balances',
            unique_together={('fiscal_year', 'fiscal_period', 'disaster_emergency_fund_code', 'tas_rendering_label')},
        ),
    ]
