# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-25 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0045_auto_20170117_2126'),
        ('references', '0046_update_location_usage_flags'),
    ]

    operations = [
    ]
