# Generated by Django 2.2.10 on 2020-06-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0047_add_tas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GTASTotalObligation',
        ),
    ]
