# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0048_auto_20170129_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_county_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
