# Generated by Django 2.2.13 on 2020-07-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0049_gtassf133balances_total_budgetary_resources_cpe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='refprogramactivity',
            unique_together=set(),
        ),
        # Special index used to guarantee uniquity on the natural key columns.
        migrations.RunSQL(
            sql=["""
                create unique index if not exists idx_ref_program_activity_natural_key on ref_program_activity (
                    program_activity_code,
                    coalesce(program_activity_name, ''),
                    coalesce(responsible_agency_id, ''),
                    coalesce(allocation_transfer_agency_id, ''),
                    coalesce(main_account_code, ''),
                    coalesce(budget_year, '')
                );
            """],
            reverse_sql=["drop index idx_ref_program_activity_natural_key"]
        ),
    ]
