# Generated by Django 2.2.14 on 2020-12-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0049_auto_20200727_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtassf133balances',
            name='adjustments_to_unobligated_balance_brought_forward_cpe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gtassf133balances',
            name='borrowing_authority_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gtassf133balances',
            name='budget_authority_unobligated_balance_brought_forward_cpe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gtassf133balances',
            name='contract_authority_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gtassf133balances',
            name='deobligations_or_recoveries_or_refunds_from_prior_year_cpe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gtassf133balances',
            name='obligations_incurred',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gtassf133balances',
            name='spending_authority_from_offsetting_collections_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=23),
            preserve_default=False,
        ),
    ]
