# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-07 20:36
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import Case, F, Value, When


def update_legal_entities(apps, schema_editor):
    LegalEntity = apps.get_model("references", "LegalEntity")
    LegalEntity.objects.all().update(business_types_description=(Case(
        When(business_types="A", then=Value("State government")),
        When(business_types="B", then=Value("County Government")),
        When(business_types="C", then=Value("City or township Government")),
        When(business_types="D", then=Value("Special District Government")),
        When(business_types="E", then=Value("Regional Organization")),
        When(business_types="F", then=Value("U.S. Territory or Possession")),
        When(business_types="G", then=Value("Independent School District")),
        When(business_types="H", then=Value("Public/State Controlled Institution of Higher Education")),
        When(business_types="I", then=Value("Indian/Native American Tribal Government (Federally Recognized)")),
        When(business_types="J", then=Value("Indian/Native American Tribal Government (Other than Federally Recognized)")),
        When(business_types="K", then=Value("Indian/Native American Tribal Designated Organization")),
        When(business_types="L", then=Value("Public/Indian Housing Authority")),
        When(business_types="M", then=Value("Nonprofit with 501C3 IRS Status (Other then Institution of Higher Education)")),
        When(business_types="N", then=Value("Nonprofit without 501C3 IRS Status (Other then Institution of Higher Education)")),
        When(business_types="O", then=Value("Private Institution of Higher Education")),
        When(business_types="P", then=Value("Individual")),
        When(business_types="Q", then=Value("For-Profit Organization (Other than Small Business)")),
        When(business_types="R", then=Value("Small Business")),
        When(business_types="S", then=Value("Hispanic-serving Institution")),
        When(business_types="T", then=Value("Historically Black Colleges and Universities (HBCUs)")),
        When(business_types="U", then=Value("Tribally Controlled Colleges and Universities (TCCUs)")),
        When(business_types="V", then=Value("Alaska Native and Native Hawaiian Serving Institutions")),
        When(business_types="W", then=Value("Non-domestic (non-US) Entity")),
        When(business_types="X", then=Value("Other")),
        When(business_types="UN", then=Value("Unknown Business Type")),
        default=Value("Unknown Business Type")
    )))


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0049_auto_20170131_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='business_types_description',
            field=models.CharField(blank=True, default='Unknown Business Type', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='business_types',
            field=models.CharField(blank=True, choices=[('A', 'State government'), ('B', 'County Government'), ('C', 'City or township Government'), ('D', 'Special District Government'), ('E', 'Regional Organization'), ('F', 'U.S. Territory or Possession'), ('G', 'Independent School District'), ('H', 'Public/State Controlled Institution of Higher Education'), ('I', 'Indian/Native American Tribal Government (Federally Recognized)'), ('J', 'Indian/Native American Tribal Government (Other than Federally Recognized)'), ('K', 'Indian/Native American Tribal Designated Organization'), ('L', 'Public/Indian Housing Authority'), ('M', 'Nonprofit with 501C3 IRS Status (Other then Institution of Higher Education)'), ('N', 'Nonprofit without 501C3 IRS Status (Other then Institution of Higher Education)'), ('O', 'Private Institution of Higher Education'), ('P', 'Individual'), ('Q', 'For-Profit Organization (Other than Small Business)'), ('R', 'Small Business'), ('S', 'Hispanic-serving Institution'), ('T', 'Historically Black Colleges and Universities (HBCUs)'), ('U', 'Tribally Controlled Colleges and Universities (TCCUs)'), ('V', 'Alaska Native and Native Hawaiian Serving Institutions'), ('W', 'Non-domestic (non-US) Entity'), ('X', 'Other'), ('UN', 'Unknown Business Type')], default='UN', max_length=3, null=True),
        ),
        migrations.RunPython(update_legal_entities, reverse_code=migrations.RunPython.noop),
    ]
