# Generated by Django 2.2.14 on 2020-12-04 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0049_auto_20200727_1735'),
    ]

    operations = [
        migrations.DeleteModel(name='gtassf133balances'),
    ]
