# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-10 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0050_auto_20170209_1552'),
        ('references', '0050_add_legal_entity_type_descriptions'),
    ]

    operations = [
    ]
