# Generated by Django 2.2.19 on 2021-03-11 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0051_auto_20210223_1404"),
        ("submissions", "0015_submissionattributes_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToptierAgencyPublishedDABSView",
            fields=[],
            options={
                "db_table": "vw_published_dabs_toptier_agency",
                "managed": False,
            },
        ),
        migrations.RunSQL(
            sql=[
                """
                CREATE VIEW vw_published_dabs_toptier_agency AS
                SELECT
                    DISTINCT ON (ta.toptier_code)
                    ta.toptier_code,
                    ta.name,
                    ta.abbreviation,
                    ta.toptier_agency_id,
                    a.id AS agency_id,
                    a.user_selectable
                FROM toptier_agency ta
                INNER JOIN agency a ON (a.toptier_agency_id = ta.toptier_agency_id AND a.toptier_flag = TRUE)
                INNER JOIN submission_attributes sa USING (toptier_code)
                INNER JOIN dabs_submission_window_schedule schedule ON sa.submission_window_id = schedule.id
                WHERE schedule.submission_reveal_date <= now();
                """
            ],
            reverse_sql=["DROP VIEW IF EXISTS vw_published_dabs_toptier_agency;"],
        ),
    ]
