# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-10 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0052_auto_20170210_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='parent_recipient_unique_id',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Parent DUNS Number'),
        ),
    ]
