# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-03 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0053_auto_20170210_1814'),
    ]

    operations = [
        migrations.RunSQL("CREATE INDEX legal_entity_location ON legal_entity (location_id)"),
        migrations.RunSQL("CREATE INDEX agency_toptier_id ON agency (toptier_agency_id)"),
        migrations.RunSQL("CREATE INDEX agency_subtier_id ON agency (subtier_agency_id)"),
        migrations.RunSQL("CREATE INDEX agency_office_id ON agency (office_agency_id)"),
        migrations.RunSQL("CREATE INDEX legal_country_code ON references_location (location_country_code)"),
    ]
