# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-08 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0053_auto_20170210_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtieragency',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Agency Abbreviation'),
        ),
        migrations.AddField(
            model_name='toptieragency',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Agency Abbreviation'),
        ),
    ]
