# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-19 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0054_auto_20170308_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_object_class', models.CharField(db_index=True, max_length=2)),
                ('major_object_class_name', models.CharField(max_length=100)),
                ('object_class', models.CharField(db_index=True, max_length=3)),
                ('object_class_name', models.CharField(max_length=60)),
                ('direct_reimbursable', models.CharField(blank=True, db_index=True, max_length=1, null=True)),
                ('direct_reimbursable_name', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'object_class',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='objectclass',
            unique_together=set([('object_class', 'direct_reimbursable')]),
        ),
    ]
