# Generated by Django 2.2.23 on 2021-10-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0055_auto_20211015_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disasteremergencyfundcode',
            name='code_old',
        ),
        migrations.AlterField(
            model_name='disasteremergencyfundcode',
            name='code',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
