# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-21 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0056_auto_20170318_2052'),
        ('references', '0055_auto_20170320_1455'),
    ]

    operations = [
    ]
