# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-29 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0057_merge_20170321_2024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefObjectClassCode',
        ),
    ]
