# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-29 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0057_merge_20170321_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='refprogramactivity',
            name='id',
            field=models.IntegerField(null=True),
        ),
    ]
