# Generated by Django 3.2.15 on 2022-09-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0058_bureautitlelookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtassf133balances',
            name='adjustment_to_unobligated_balance_brought_forward_oct_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=23),
        ),
    ]
