# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-30 14:26
from __future__ import unicode_literals

from django.db import migrations, models


def copy_ref_program_activity_id_to_id(apps, schema_editor):
    RefProgramActivity = apps.get_model('references.RefProgramActivity')
    RefProgramActivity.objects.update(id=models.F('ref_program_activity_id'))


def copy_id_to_ref_program_activity_id(apps, schema_editor):
    RefProgramActivity = apps.get_model('references.RefProgramActivity')
    RefProgramActivity.objects.all().update(ref_program_activity_id=models.F('id'))


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0058_auto_20170329_2142'),
    ]

    operations = [
        migrations.RunPython(copy_ref_program_activity_id_to_id,
                             reverse_code=copy_id_to_ref_program_activity_id)
    ]
