# Generated by Django 3.2.15 on 2022-09-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0058_bureautitlelookup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gtassf133balances',
            old_name='adjustments_to_unobligated_balance_brought_forward_cpe',
            new_name='adjustments_to_unobligated_balance_cpe',
        ),
    ]
