# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-30 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0058_delete_refobjectclasscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refprogramactivity',
            name='ref_program_activity_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
