# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-30 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0059_auto_20170330_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refprogramactivity',
            name='ref_program_activity_id',
        ),
        migrations.AlterField(
            model_name='refprogramactivity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
