# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-04 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0060_auto_20170402_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refprogramactivity',
            old_name='ref_program_activity_id',
            new_name='id',
        ),
    ]
