# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-07 18:39
from __future__ import unicode_literals

from django.db import migrations



def canonicalize(apps, schema_editor):
    """
    Canonicalizes legacy Location records.
    """
    db_alias = schema_editor.connection.alias

    Location = apps.get_model('references', 'Location')
    # Canonicalization is now built into .save(), so
    Location.objects.all().save()


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0061_auto_20170404_2153'),
    ]

    operations = [
        migrations.RunPython(canonicalize)
    ]
