# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-31 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0061_merge_20170330_1803'),
        ('references', '0059_auto_20170330_2107'),
    ]

    operations = [
    ]
