# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-07 18:39
from __future__ import unicode_literals

from django.db import migrations

from usaspending_api.references.helpers import canonicalize_location_instance


def run_canonicalize(apps, schema_editor):
    """
    Canonicalizes legacy Location records.
    """
    db_alias = schema_editor.connection.alias

    Location = apps.get_model('references', 'Location')

    for loc in Location.objects.all():
        canonicalize_location_instance(loc)
        loc.save()


class Migration(migrations.Migration):

    dependencies = [('references', '0061_auto_20170404_2153'), ]

    operations = [migrations.RunPython(run_canonicalize)]
