# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-07 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0062_auto_20170407_1839'),
        ('references', '0062_auto_20170407_1846'),
    ]

    operations = [
    ]
