# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-03 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0060_auto_20170402_1922'),
        ('references', '0062_merge_20170331_2034'),
    ]

    operations = [
    ]
