# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-03 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0063_merge_20170403_2021'),
    ]

    operations = [
    ]
