# Generated by Django 3.2.23 on 2024-02-08 02:35

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('references', '0064_add_latest_pop_col'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='Office',
            unique_together={('agency_code', 'sub_tier_code', 'office_name', 'office_code')},
        ),
    ]
