# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-10 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0063_merge_20170407_2039'),
        ('references', '0064_auto_20170409_1724'),
    ]

    operations = [
    ]
