# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-13 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0065_merge_20170410_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntityOfficers',
            fields=[
                ('legal_entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='officers', serialize=False, to='references.LegalEntity')),
                ('officer_1_name', models.TextField(blank=True, null=True)),
                ('officer_1_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('officer_2_name', models.TextField(blank=True, null=True)),
                ('officer_2_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('officer_3_name', models.TextField(blank=True, null=True)),
                ('officer_3_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('officer_4_name', models.TextField(blank=True, null=True)),
                ('officer_4_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('officer_5_name', models.TextField(blank=True, null=True)),
                ('officer_5_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('update_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
