# Generated by Django 5.0.4 on 2024-04-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0066_alter_office_unique_index_code_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="office",
            name="office_code",
            field=models.TextField(unique=True),
        ),
    ]
