# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-16 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0067_create_officers'),
        ('references', '0066_auto_20170412_1930'),
    ]

    operations = [
    ]
