# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-25 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0069_auto_20170421_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfdaprogram',
            name='program_number',
            field=models.TextField(max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='airport_authority',
            field=models.TextField(blank=True, null=True, verbose_name='Airport Authority'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='alaskan_native_owned_corporation_or_firm',
            field=models.TextField(blank=True, null=True, verbose_name='Alaskan Native Owned Corporation or Firm'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='alaskan_native_servicing_institution',
            field=models.TextField(blank=True, null=True, verbose_name='Alaskan Native Owned Servicing Institution'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='american_indian_owned_business',
            field=models.TextField(blank=True, null=True, verbose_name='American Indian Owned Business'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='asian_pacific_american_owned_business',
            field=models.TextField(blank=True, null=True, verbose_name='Asian Pacific American Owned business'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='black_american_owned_business',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='business_types',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='business_types_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='c1862_land_grant_college',
            field=models.TextField(blank=True, db_column='1862_land_grant_college', max_length=1, null=True, verbose_name='1862 Land Grant College'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='c1890_land_grant_college',
            field=models.TextField(blank=True, db_column='1890_land_grant_college', max_length=1, null=True, verbose_name='1890 Land Grant College'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='c1994_land_grant_college',
            field=models.TextField(blank=True, db_column='1994_land_grant_college', max_length=1, null=True, verbose_name='1894 Land Grant College'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='c8a_program_participant',
            field=models.TextField(blank=True, db_column='8a_program_participant', max_length=1, null=True, verbose_name='8a Program Participant'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='city_local_government',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='city_township_government',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='community_developed_corporation_owned_firm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='community_development_corporation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='contracts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='corporate_entity_not_tax_exempt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='corporate_entity_tax_exempt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='council_of_governments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='county_local_government',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='division_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='division_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='domestic_or_foreign_entity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='domestic_shelter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='dot_certified_disadvantage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='economically_disadvantaged_women_owned_small_business',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='educational_institution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='emerging_small_business',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='federal_agency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='federally_funded_research_and_development_corp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='for_profit_organization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='foreign_government',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='foreign_owned_and_located',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='foundation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='grants',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='hispanic_american_owned_business',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='hispanic_servicing_institution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='historically_black_college',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='historically_underutilized_business_zone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='hospital_flag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='housing_authorities_public_tribal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='indian_tribe_federally_recognized',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='individual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='inter_municipal_local_government',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='international_organization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='interstate_entity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='joint_venture_economic_disadvantaged_women_owned_small_bus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='joint_venture_women_owned_small_business',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='labor_surplus_area_firm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='limited_liability_corporation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='local_government_owned',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='manufacturer_of_goods',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='minority_institution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='minority_owned_business',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='municipality_local_government',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='native_american_owned_business',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='native_hawaiian_owned_business',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='native_hawaiian_servicing_institution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='nonprofit_organization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='other_minority_owned_business',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='other_not_for_profit_organization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='parent_recipient_unique_id',
            field=models.TextField(blank=True, null=True, verbose_name='Parent DUNS Number'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='partnership_or_limited_liability_partnership',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='planning_commission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='port_authority',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='private_university_or_college',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='receives_contracts_and_grants',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='recipient_name',
            field=models.TextField(blank=True, verbose_name='Recipient Name'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='recipient_unique_id',
            field=models.TextField(blank=True, null=True, verbose_name='DUNS Number'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='sam_exception',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='sba_certified_8a_joint_venture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='school_district_local_government',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='school_of_forestry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='self_certified_small_disadvantaged_business',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='service_disabled_veteran_owned_business',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='small_agricultural_cooperative',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='small_business',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='small_disadvantaged_business',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='sole_proprietorship',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='special_district_government',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='state_controlled_institution_of_higher_learning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='subchapter_scorporation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='subcontinent_asian_asian_indian_american_owned_business',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='the_ability_one_program',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='township_local_government',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='transit_authority',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='tribal_college',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='tribally_owned_business',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='undefinitized_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='us_federal_government',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='us_government_entity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='us_local_government',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='us_state_government',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='us_tribal_government',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='vendor_doing_as_business_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='vendor_fax_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='vendor_phone_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='veteran_owned_business',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='veterinary_college',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='veterinary_hospital',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='woman_owned_business',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='women_owned_small_business',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address_line1',
            field=models.TextField(blank=True, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address_line2',
            field=models.TextField(blank=True, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address_line3',
            field=models.TextField(blank=True, null=True, verbose_name='Address Line 3'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city_name',
            field=models.TextField(blank=True, null=True, verbose_name='City Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='congressional_code',
            field=models.TextField(blank=True, null=True, verbose_name='Congressional District Code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country_name',
            field=models.TextField(blank=True, null=True, verbose_name='Country Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='county_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='county_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='foreign_city_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='foreign_location_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='foreign_postal_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='foreign_province',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='performance_code',
            field=models.TextField(blank=True, null=True, verbose_name='Primary Place Of Performance Location Code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state_code',
            field=models.TextField(blank=True, null=True, verbose_name='State Code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state_description',
            field=models.TextField(blank=True, null=True, verbose_name='State Description'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state_name',
            field=models.TextField(blank=True, null=True, verbose_name='State Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip4',
            field=models.TextField(blank=True, null=True, verbose_name='ZIP+4'),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_4a',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip_last4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objectclass',
            name='direct_reimbursable',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='objectclass',
            name='direct_reimbursable_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='objectclass',
            name='major_object_class',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='objectclass',
            name='major_object_class_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='objectclass',
            name='object_class',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='objectclass',
            name='object_class_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='officeagency',
            name='aac_code',
            field=models.TextField(blank=True, null=True, verbose_name='Office Code'),
        ),
        migrations.AlterField(
            model_name='officeagency',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Office Name'),
        ),
        migrations.AlterField(
            model_name='refcitycountycode',
            name='city_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refcitycountycode',
            name='city_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refcitycountycode',
            name='county_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refcitycountycode',
            name='county_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refcitycountycode',
            name='state_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refcitycountycode',
            name='type_of_area',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refcitycountycode',
            name='valid_code_indicator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refcountrycode',
            name='country_code',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='refcountrycode',
            name='country_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refcountrycode',
            name='valid_code_indicator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refprogramactivity',
            name='allocation_transfer_agency_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refprogramactivity',
            name='budget_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refprogramactivity',
            name='main_account_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refprogramactivity',
            name='program_activity_code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='refprogramactivity',
            name='program_activity_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='refprogramactivity',
            name='responsible_agency_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refprogramactivity',
            name='valid_code_indicator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtieragency',
            name='abbreviation',
            field=models.TextField(blank=True, null=True, verbose_name='Agency Abbreviation'),
        ),
        migrations.AlterField(
            model_name='subtieragency',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Sub-Tier Agency Name'),
        ),
        migrations.AlterField(
            model_name='subtieragency',
            name='subtier_code',
            field=models.TextField(blank=True, null=True, verbose_name='Sub-Tier Agency Code'),
        ),
        migrations.AlterField(
            model_name='toptieragency',
            name='abbreviation',
            field=models.TextField(blank=True, null=True, verbose_name='Agency Abbreviation'),
        ),
        migrations.AlterField(
            model_name='toptieragency',
            name='cgac_code',
            field=models.TextField(blank=True, null=True, verbose_name='Top-Tier Agency Code'),
        ),
        migrations.AlterField(
            model_name='toptieragency',
            name='fpds_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toptieragency',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Top-Tier Agency Name'),
        ),
    ]
