# Generated by Django 4.2.23 on 2025-08-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0069_zipsgrouped"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramActivityPark",
            fields=[
                ("code", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField(db_index=True)),
            ],
            options={
                "db_table": "program_activity_park",
                "managed": True,
            },
        ),
    ]
