# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-03 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0070_auto_20170425_1357'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='legalentity',
            unique_together=set([]),
        ),
    ]
