# Generated by Django 4.2.23 on 2025-09-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0070_programactivitypark"),
    ]

    operations = [
        migrations.AddField(
            model_name="naics",
            name="year_retired",
            field=models.IntegerField(null=True),
        ),
    ]
