# Generated by Django 4.2.23 on 2026-03-10 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("references", "0072_naics_year_retired"),
    ]

    operations = [
        migrations.AddField(
            model_name="gtassf133balances",
            name="bea_category",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gtassf133balances",
            name="budget_object_class",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gtassf133balances",
            name="by_direct_reimbursable_fun",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gtassf133balances",
            name="prior_year_adjustment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gtassf133balances",
            name="program_activity_reporting_key",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="gtas",
                to="references.programactivitypark",
            ),
        ),
    ]
