# Generated by Django 4.2.29 on 2026-06-02 20:08

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0073_gtassf133balances_bea_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfda',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True),
        ),
        migrations.AddField(
            model_name='cfda',
            name='embedding_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='naics',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=256, null=True),
        ),
        migrations.AddField(
            model_name='naics',
            name='embedding_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
