-- So this what we've been building toward.  Add the new subawards built from
-- Broker into the USAspending subaward table.



insert into subaward (
    id,
    subaward_number,
    amount,
    description,
    recovery_model_question1,
    recovery_model_question2,
    action_date,
    award_report_fy_month,
    award_report_fy_year,
    award_id,
    awarding_agency_id,
    cfda_id,
    funding_agency_id,
    award_type,
    broker_award_id,
    internal_id,
    awarding_subtier_agency_abbreviation,
    awarding_subtier_agency_name,
    awarding_toptier_agency_abbreviation,
    awarding_toptier_agency_name,
    cfda_number,
    cfda_title,
    extent_competed,
    fain,
    funding_subtier_agency_abbreviation,
    funding_subtier_agency_name,
    funding_toptier_agency_abbreviation,
    funding_toptier_agency_name,
    last_modified_date,
    latest_transaction_id,
    parent_recipient_unique_id,
    piid,
    pop_city_code,
    pop_congressional_code,
    pop_country_code,
    pop_country_name,
    pop_county_code,
    pop_county_name,
    pop_state_code,
    pop_zip4,
    prime_award_type,
    business_categories,
    prime_recipient_name,
    product_or_service_code,
    product_or_service_description,
    pulled_from,
    recipient_location_congressional_code,
    recipient_location_country_code,
    recipient_location_country_name,
    recipient_location_county_code,
    recipient_location_county_name,
    recipient_location_state_code,
    recipient_location_zip5,
    recipient_name,
    recipient_unique_id,
    type_of_contract_pricing,
    type_set_aside,
    pop_city_name,
    pop_state_name,
    pop_street_address,
    recipient_location_city_code,
    recipient_location_city_name,
    dba_name,
    parent_recipient_name,
    business_type_code,
    business_type_description,
    officer_1_amount,
    officer_1_name,
    officer_2_amount,
    officer_2_name,
    officer_3_amount,
    officer_3_name,
    officer_4_amount,
    officer_4_name,
    officer_5_amount,
    officer_5_name,
    recipient_location_foreign_postal_code,
    recipient_location_state_name,
    recipient_location_street_address,
    recipient_location_zip4,
    updated_at,
    unique_award_key
)

select
    id,
    subaward_number,
    amount,
    description,
    recovery_model_question1,
    recovery_model_question2,
    action_date,
    award_report_fy_month,
    award_report_fy_year,
    award_id,
    awarding_agency_id,
    cfda_id,
    funding_agency_id,
    award_type,
    broker_award_id,
    internal_id,
    awarding_subtier_agency_abbreviation,
    awarding_subtier_agency_name,
    awarding_toptier_agency_abbreviation,
    awarding_toptier_agency_name,
    cfda_number,
    cfda_title,
    extent_competed,
    fain,
    funding_subtier_agency_abbreviation,
    funding_subtier_agency_name,
    funding_toptier_agency_abbreviation,
    funding_toptier_agency_name,
    last_modified_date,
    latest_transaction_id,
    parent_recipient_unique_id,
    piid,
    pop_city_code,
    pop_congressional_code,
    pop_country_code,
    pop_country_name,
    pop_county_code,
    pop_county_name,
    pop_state_code,
    pop_zip4,
    prime_award_type,
    business_categories,
    prime_recipient_name,
    product_or_service_code,
    product_or_service_description,
    pulled_from,
    recipient_location_congressional_code,
    recipient_location_country_code,
    recipient_location_country_name,
    recipient_location_county_code,
    recipient_location_county_name,
    recipient_location_state_code,
    recipient_location_zip5,
    recipient_name,
    recipient_unique_id,
    type_of_contract_pricing,
    type_set_aside,
    pop_city_name,
    pop_state_name,
    pop_street_address,
    recipient_location_city_code,
    recipient_location_city_name,
    dba_name,
    parent_recipient_name,
    business_type_code,
    business_type_description,
    officer_1_amount,
    officer_1_name,
    officer_2_amount,
    officer_2_name,
    officer_3_amount,
    officer_3_name,
    officer_4_amount,
    officer_4_name,
    officer_5_amount,
    officer_5_name,
    recipient_location_foreign_postal_code,
    recipient_location_state_name,
    recipient_location_street_address,
    recipient_location_zip4,
    updated_at,
    unique_award_key

from
    temp_load_subawards_subaward

on conflict (id) do update set
    subaward_number = excluded.subaward_number,
    amount = excluded.amount,
    description = excluded.description,
    recovery_model_question1 = excluded.recovery_model_question1,
    recovery_model_question2 = excluded.recovery_model_question2,
    action_date = excluded.action_date,
    award_report_fy_month = excluded.award_report_fy_month,
    award_report_fy_year = excluded.award_report_fy_year,
    award_id = excluded.award_id,
    awarding_agency_id = excluded.awarding_agency_id,
    cfda_id = excluded.cfda_id,
    funding_agency_id = excluded.funding_agency_id,
    award_type = excluded.award_type,
    broker_award_id = excluded.broker_award_id,
    internal_id = excluded.internal_id,
    awarding_subtier_agency_abbreviation = excluded.awarding_subtier_agency_abbreviation,
    awarding_subtier_agency_name = excluded.awarding_subtier_agency_name,
    awarding_toptier_agency_abbreviation = excluded.awarding_toptier_agency_abbreviation,
    awarding_toptier_agency_name = excluded.awarding_toptier_agency_name,
    cfda_number = excluded.cfda_number,
    cfda_title = excluded.cfda_title,
    extent_competed = excluded.extent_competed,
    fain = excluded.fain,
    funding_subtier_agency_abbreviation = excluded.funding_subtier_agency_abbreviation,
    funding_subtier_agency_name = excluded.funding_subtier_agency_name,
    funding_toptier_agency_abbreviation = excluded.funding_toptier_agency_abbreviation,
    funding_toptier_agency_name = excluded.funding_toptier_agency_name,
    last_modified_date = excluded.last_modified_date,
    latest_transaction_id = excluded.latest_transaction_id,
    parent_recipient_unique_id = excluded.parent_recipient_unique_id,
    piid = excluded.piid,
    pop_city_code = excluded.pop_city_code,
    pop_congressional_code = excluded.pop_congressional_code,
    pop_country_code = excluded.pop_country_code,
    pop_country_name = excluded.pop_country_name,
    pop_county_code = excluded.pop_county_code,
    pop_county_name = excluded.pop_county_name,
    pop_state_code = excluded.pop_state_code,
    pop_zip4 = excluded.pop_zip4,
    prime_award_type = excluded.prime_award_type,
    business_categories = excluded.business_categories,
    prime_recipient_name = excluded.prime_recipient_name,
    product_or_service_code = excluded.product_or_service_code,
    product_or_service_description = excluded.product_or_service_description,
    pulled_from = excluded.pulled_from,
    recipient_location_congressional_code = excluded.recipient_location_congressional_code,
    recipient_location_country_code = excluded.recipient_location_country_code,
    recipient_location_country_name = excluded.recipient_location_country_name,
    recipient_location_county_code = excluded.recipient_location_county_code,
    recipient_location_county_name = excluded.recipient_location_county_name,
    recipient_location_state_code = excluded.recipient_location_state_code,
    recipient_location_zip5 = excluded.recipient_location_zip5,
    recipient_name = excluded.recipient_name,
    recipient_unique_id = excluded.recipient_unique_id,
    type_of_contract_pricing = excluded.type_of_contract_pricing,
    type_set_aside = excluded.type_set_aside,
    pop_city_name = excluded.pop_city_name,
    pop_state_name = excluded.pop_state_name,
    pop_street_address = excluded.pop_street_address,
    recipient_location_city_code = excluded.recipient_location_city_code,
    recipient_location_city_name = excluded.recipient_location_city_name,
    dba_name = excluded.dba_name,
    parent_recipient_name = excluded.parent_recipient_name,
    business_type_code = excluded.business_type_code,
    business_type_description = excluded.business_type_description,
    officer_1_amount = excluded.officer_1_amount,
    officer_1_name = excluded.officer_1_name,
    officer_2_amount = excluded.officer_2_amount,
    officer_2_name = excluded.officer_2_name,
    officer_3_amount = excluded.officer_3_amount,
    officer_3_name = excluded.officer_3_name,
    officer_4_amount = excluded.officer_4_amount,
    officer_4_name = excluded.officer_4_name,
    officer_5_amount = excluded.officer_5_amount,
    officer_5_name = excluded.officer_5_name,
    recipient_location_foreign_postal_code = excluded.recipient_location_foreign_postal_code,
    recipient_location_state_name = excluded.recipient_location_state_name,
    recipient_location_street_address = excluded.recipient_location_street_address,
    recipient_location_zip4 = excluded.recipient_location_zip4,
    updated_at = excluded.updated_at,
    unique_award_key = excluded.unique_award_key;
