name: Cancel Running Workflow

on:
  workflow_call:

jobs:
  Cancel-Running-Workflow:
    name: Cancel Running Workflow
    runs-on: ${{ vars.RUNNER_VERSION }}
    steps:
      - name: Cancel Workflow
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.cancelWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            });

      - name: Waiting for Workflow to Cancel
        uses: actions/github-script@v7
        with:
          script: |
            const delay = ms => new Promise(res => setTimeout(res, ms));
            while (true) {
              core.info('Waiting for workflow to cancel ...');
              await delay(5000);
            }
