name: Pull Request and Review Updates

on:
  pull_request:
    types: [opened]
  pull_request_review:
    types: [submitted]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}-${{ github.actor_id }}
  cancel-in-progress: true

jobs:
  Update-Pull-Request-Assignees:
    name: Update Pull Request Assignees
    runs-on: ${{ vars.RUNNER_VERSION }}
    steps:
      - name: Update Assignee
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [context.actor]
            });
