name: Unit Tests

env:
  BROKER_DB_HOST: usaspending-db
  BROKER_DB_PORT: 5432
  BROKER_DB_USER: admin
  BROKER_DB_PASSWORD: root
  BROKER_DB_NAME: data_broker
  DJANGO_SETTINGS_MODULE: usaspending_api.settings
  ES_SCHEME: http
  ES_HOST: usaspending-es
  ES_PORT: 9200
  IS_LOCAL: true
  MINIO_HOST: minio
  MINIO_PORT: 10001
  MINIO_ACCESS_KEY: usaspending
  MINIO_SECRET_KEY: usaspender
  USASPENDING_DB_HOST: usaspending-db
  USASPENDING_DB_PORT: 5432
  USASPENDING_DB_USER: usaspending
  USASPENDING_DB_PASSWORD: usaspender
  USASPENDING_DB_NAME: data_store_api

on:
  workflow_call:

jobs:
  Run:
    name: Run
    runs-on: ${{ vars.RUNNER_VERSION }}
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          path: usaspending-api

      - name: Validate file structure
        working-directory: ./usaspending-api
        shell: bash
        run: |
          pwd
          ls

      - name: Init Test Environment
        uses: ./usaspending-api/.github/actions/init-test-environment
        with:
          is-integration-test: false
          is-spark-test: false
          working-directory: ./usaspending-api

      - name: Troubleshoot
        working-directory: ./usaspending-api
        shell: bash
        run: |
          pwd
          ls
          docker compose run --rm --entrypoint "pwd" usaspending-test
          docker compose run --rm --entrypoint "ls" usaspending-test
          docker compose run --rm --entrypoint "env" usaspending-test

      - name: Run Test Cases
        id: run-test-cases
        uses: ./usaspending-api/.github/actions/run-pytest
        with:
          cov-report-name: 'unit-tests'
          ignore-glob: '**/tests/integration/*'
          include-glob: 'test_*.py *_test.py'
          marker: '(not signal_handling)'
          working-directory: ./usaspending-api
