name: Spark Integration Tests - test_load_transactions_in_delta_fabs_fpds.py

on:
  workflow_call:
    inputs:
      broker-branch:
        required: true
        type: string

defaults:
  run:
    working-directory: ./usaspending-api

jobs:
  Run:
    name: Run
    runs-on: ${{ vars.RUNNER_VERSION }}
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          path: usaspending-api

      - name: Checkout Broker Backend Repository
        uses: actions/checkout@v4
        with:
          repository: fedspendingtransparency/data-act-broker-backend
          path: data-act-broker-backend
          ref: ${{ inputs.broker-branch }}

      - name: Init Test Environment
        uses: ./usaspending-api/.github/actions/init-test-environment
        with:
          is-integration-test: true
          is-spark-test: true
          working-directory: ./usaspending-api

      - name: Run Test Cases
        uses: ./usaspending-api/.github/actions/run-pytest
        with:
          cov-report-name: 'spark-load-transactions-fabs-fpds-tests'
          include-glob: 'test_*.py *_test.py'
          keyword: 'test_load_transactions_in_delta_fabs_fpds.py'
          marker: 'spark'
          num-processes: 0
          working-directory: ./usaspending-api
