name: Unit Tests

on:
  workflow_call:

defaults:
  run:
    working-directory: usaspending-api

jobs:
  Run:
    name: Run
    runs-on: ${{ vars.RUNNER_VERSION }}
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          path: usaspending-api

      - name: Validate file structure
        shell: bash
        run: |
          pwd
          ls

      - name: Init Test Environment
        uses: ./usaspending-api/.github/actions/init-test-environment
        with:
          is-integration-test: false
          is-spark-test: false
          working-directory: ./usaspending-api

      - name: Run Test Cases
        id: run-test-cases
        uses: ./usaspending-api/.github/actions/run-pytest
        with:
          cov-report-name: 'unit-tests'
          ignore-glob: '**/tests/integration/*'
          include-glob: 'test_*.py *_test.py'
          marker: '(not signal_handling)'
          working-directory: ./usaspending-api
