name: Test Suite

on:
  workflow_call:

env:
  BROKER_DB_USER: admin
  BROKER_DB_PASSWORD: root
  DJANGO_SETTINGS_MODULE: "usaspending_api.settings"
  ES_SCHEME: http
  ES_HOST: localhost
  ES_PORT: 9200
  MINIO_HOST: localhost
  USASPENDING_DB_HOST: localhost
  USASPENDING_DB_PORT: 5432
  USASPENDING_DB_USER: usaspending
  USASPENDING_DB_PASSWORD: usaspender
  USASPENDING_DB_NAME: data_store_api  

jobs:
  Run-Pytest-Test-Suite:
    name: Run Pytest Test Suite
    runs-on: ${{ vars.RUNNER_VERSION }}
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Init Test Environment
        uses: ./.github/actions/init-test-environment

      - name: Run integration test cases
        run: >
          pytest --reuse-db --numprocesses logical --cov=usaspending_api --cov-report term -r=fEs --dist worksteal --verbosity=1 --durations 50
          -m "(spark)" --override-ini=python_files="**/tests/integration/*"
