name: Spark Integration Tests - test_load_transactions_in_delta_lookups.py

env:
  BROKER_DB_HOST: localhost
  BROKER_DB_PORT: 5432
  BROKER_DB_USER: admin
  BROKER_DB_PASSWORD: root
  BROKER_DB_NAME: data_broker
  DJANGO_SETTINGS_MODULE: usaspending_api.settings
  ES_SCHEME: http
  ES_HOST: localhost
  ES_PORT: 9200
  MINIO_HOST: localhost
  USASPENDING_DB_HOST: localhost
  USASPENDING_DB_PORT: 5432
  USASPENDING_DB_USER: usaspending
  USASPENDING_DB_PASSWORD: usaspender
  USASPENDING_DB_NAME: data_store_api  

on:
  workflow_call:

defaults:
  run:
    working-directory: ./usaspending-api

jobs:
  Run-Spark-Integration-Tests:
    name: Run Spark Integration Tests - test_load_transactions_in_delta_lookups.py
    runs-on: ${{ vars.RUNNER_VERSION }}
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          path: usaspending-api
      
      - name: Checkout broker backend repository
        uses: actions/checkout@v4
        with:
          repository: fedspendingtransparency/data-act-broker-backend
          path: data-act-broker-backend

      - name: Init Python Environment
        uses: ./usaspending-api/.github/actions/init-python-environment
        with:
          working_directory: ./usaspending-api

      - name: Init Test Environment
        uses: ./usaspending-api/.github/actions/init-test-environment
        with:
          is_integration_test: true
          is_spark_test: true
          working_directory: ./usaspending-api

      - name: Run test cases
        run: >
          pytest --reuse-db --numprocesses logical --cov=usaspending_api --cov-report term -r=fEs --dist worksteal --verbosity=1 --durations 50
          -m "spark" --override-ini=python_files="test_*.py *_test.py" test_load_transactions_in_delta_lookups.py
