name: Unit Tests

env:
  BROKER_DB_HOST: localhost
  BROKER_DB_PORT: 5432
  BROKER_DB_USER: admin
  BROKER_DB_PASSWORD: root
  BROKER_DB_NAME: data_broker
  DJANGO_SETTINGS_MODULE: usaspending_api.settings
  ES_SCHEME: http
  ES_HOST: localhost
  ES_PORT: 9200
  MINIO_HOST: localhost
  USASPENDING_DB_HOST: localhost
  USASPENDING_DB_PORT: 5432
  USASPENDING_DB_USER: usaspending
  USASPENDING_DB_PASSWORD: usaspender
  USASPENDING_DB_NAME: data_store_api  

on:
  workflow_call:

jobs:
  Run-Tests:
    name: Run Tests
    runs-on: ${{ vars.RUNNER_VERSION }}
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4

      - name: Init Python Environment
        uses: ./.github/actions/init-python-environment

      - name: Init Test Environment
        uses: ./.github/actions/init-test-environment
        with:
          is_integration_test: false
          is_spark_test: false

      - name: Run Test Cases
        run: >
          pytest -x --reuse-db --numprocesses logical --cov=usaspending_api --cov-report term -r=fEs --dist worksteal --verbosity=1 --durations 50
          --override-ini=python_files="test_*.py *_test.py" --ignore-glob="**/tests/integration/*"
