# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # These operations are obsolete and have been squashed.
    ]
