# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_download', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkdownloadjob',
            name='job_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='download.JobStatus'),
        ),
        migrations.DeleteModel(
            name='BulkJobStatus',
        ),
    ]
