    # -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_download', '0002_auto_20171213_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkdownloadjob',
            name='sub_agency',
            field=models.TextField(blank=True, null=True),
        ),
    ]
